### ISSUE TITLE
Sujay follow up with Donny on SPRUCE query for Bioscales and MetaG

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#1]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would like for Sujay to understand Donny's SPRUCE query so he can replicate for other data like Bioscales and metaG

**Describe alternatives you've considered**
N/A

**Acceptance Criteria**
Create a checklist or scenario-based acceptance criteria, from the users perspective, that answers the following: 

Who will use this feature/enhancement? Sujay
When will they use it? As needed
How will they use it? For query other data sets
How will they test it to make sure it's working? ?
Is the request achievable? During one sprint? ?
What is your definition of done for this request? For Sujay to understand how to do this query and to document this and be able to do the query for bioscales and metaG data

**Comment by aclum** [comment]
@sujaypatil96  do you remember what this was about? Is this still needed?
