### ISSUE TITLE
Develop Partnership Tracking Mechanism

### ISSUE THREAD

**Issue by mar-rudolph** [microbiomedata/issues#10]
Current tracking of partners is distributed and inefficient, by creating a centralized place to hold this information we will have a better concept of how to move forward with partners. 

This [spreadsheet](https://docs.google.com/spreadsheets/d/1c5wCVEA_Efh3RdLmPQ97omn_HqTSbaW8MA2UNPdL3hw/edit#gid=0) will make a go to resource to understand who we have interacted with since the beginning of the NMDC 

- [ ] Add all partners for the Partnership Drive into spreadsheet 
- [ ] Work with leadership team to ensure all informal partners are added to the drive

**Comment by ssarrafan** [comment]
Met with @mar-rudolph and @jkelliher-github and moving this to the next sprint and re-assigning to Julia

**Comment by ssarrafan** [comment]
This will be discussed with the squad Tuesday. Will move over so it can be closed after the meeting.

**Comment by ssarrafan** [comment]
@jkelliher-github I believe this was discussed so it would be great if you can close this please. Let me know if I can help.
