### ISSUE TITLE
Study Information: CRediT webpage links

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#101]
Can we add the link to CRediT taxonomy webpage like we have for orcid in the grey text?
https://credit.niso.org/
In the contributor form,” CRediT Information: https://info.orcid.org/credit-for-research-contribution ; CRediT: https://credit.niso.org/” - both URL should be links, ideally

**Comment by mslarae13** [comment]
![Screen Shot 2023-03-02 at 4 31 38 PM](https://user-images.githubusercontent.com/44581429/222601076-d8e9303c-e008-4381-bca2-32f0bc3a39b9.png)

**Comment by mslarae13** [comment]
@pkalita-lbl  can you do this? Should this be @naglepuff ?

**Comment by pkalita-lbl** [comment]
I think we're both capable 😁

**Comment by mslarae13** [comment]
Can we make it 
"Identify all [CRediT roles](https://credit.niso.org/) associated with this contributor. ORCiD and CRediT [Information](https://info.orcid.org/credit-for-research-contribution) "

**Comment by ssarrafan** [comment]
Tested in data-dev site and it looks like the links are there and working
first link goes to https://credit.niso.org/
second link goes to https://info.orcid.org/credit-for-research-contribution/
<img width="958" alt="subportal-contributorlinks" src="https://user-images.githubusercontent.com/79225425/225155695-3d580bad-1467-46a7-95cc-f346147abbce.png">
