### ISSUE TITLE
Study Information: Study description guidance

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#102]
Can we some text to the study description to help people understand what they should be adding here?

Something like 
"Provide a description of your study. This should include some general context of your research goals and study design. For examples, please see existing study landing pages on data.microbiomedata.org"

**Comment by pkalita-lbl** [comment]
Replace this text:
![image](https://user-images.githubusercontent.com/102547565/222838975-fb940a02-2a09-4c04-ae7e-652a838cbbf5.png)

**Comment by ssarrafan** [comment]
Tested on data-dev
Description is updated
Link to data portal works fine

<img width="1079" alt="subportal-studyinfodescription" src="https://user-images.githubusercontent.com/79225425/225156598-f99e809d-6e00-4a64-bd0b-e42468d69a64.png">
