### ISSUE TITLE
Submission Context: Add additional project types

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#104]
Add the following options to the "What kind of project have you been awarded?" radio buttons. Include acronym and full name in radio button list. Link full name if URL is available.

CSP: Community Science Program (link to https://jgi.doe.gov/user-programs/program-info/csp-overview/csp-annual-call/)
BERSS:  Biological and Environmental Research Support Science (link to https://jgi.doe.gov/user-programs/other-programs/)
FICUS: Facilities Integrating Collaborations for User Science (link to https://www.emsl.pnnl.gov/basic/ficus-program/1872)
MONet: Molecular Observation Network (link to https://www.emsl.pnnl.gov/monet)
BRCSs: Bioenergy Research Centers (link to https://jgi.doe.gov/user-programs/other-programs/)

**Comment by mslarae13** [comment]
similar to https://github.com/microbiomedata/issues/issues/105

**Comment by pkalita-lbl** [comment]
Include acronym and full name in radio button list

**Comment by ssarrafan** [comment]
Tested on data-dev and works as described, links work as noted

<img width="880" alt="Screen Shot 2023-03-14 at 3 39 58 PM" src="https://user-images.githubusercontent.com/79225425/225158345-55a454ec-2edf-47fd-ba16-4e9c3e4305b2.png">
<img width="863" alt="Screen Shot 2023-03-14 at 3 39 41 PM" src="https://user-images.githubusercontent.com/79225425/225158353-d8681357-70c4-4e34-95ac-7a70d98489af.png">
