### ISSUE TITLE
Multiomics: Update external data source collection

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#107]
@mslarae13 I couldn't find anything in your notes on this. Can you update description and if it should go to Mike or Patrick?

**Comment by mslarae13** [comment]
When ... 
![Screen Shot 2023-03-02 at 4 43 00 PM](https://user-images.githubusercontent.com/44581429/222602967-91da2dcf-3c8b-4721-8d1f-1eb3f6c81abf.png)


Then

![Screen Shot 2023-03-02 at 4 43 06 PM](https://user-images.githubusercontent.com/44581429/222602989-14674774-1586-4c9c-a173-1941925837dc.png)

From Emiley
 I would rename "Alternative Names" as "Alternative Names / Ids" and put it under GOLD and NCBI Project Accession (I wasn't sure what "Alternative Names" meant until I saw GOLD and NCBI BioProject and I was like "Oh, ok”).


Lost GOLD Study ID First

Then NCBI BioProject Accession ID
Then "Alternative Names/ IDs"

**Comment by ssarrafan** [comment]
done, duplicate issue
