### ISSUE TITLE
Survey NMDC Staff (New & Old) for External Partners 

### ISSUE THREAD

**Issue by mar-rudolph** [microbiomedata/issues#11]
- [ ] Develop survey 
- [ ] Send out to NMDC Team 
- [ ] Ensure responses from majority of team
- [ ] Enter into partnership [spreadsheet](https://docs.google.com/spreadsheets/d/1c5wCVEA_Efh3RdLmPQ97omn_HqTSbaW8MA2UNPdL3hw/edit#gid=0)

**Comment by ssarrafan** [comment]
@jkelliher-github I found the issue.  If you'd like to add any details or attachments to it that would be great. Thanks for doing the survey. I'll close this as discussed.
