### ISSUE TITLE
Metadata: Add collection date format to help

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#114]
I see an example in help.  @mslarae13 were you looking for another way to show the format besides the example?  
<img width="1064" alt="Screen Shot 2023-03-02 at 3 01 20 PM" src="https://user-images.githubusercontent.com/79225425/222579905-6b9e7334-d039-468a-a6d1-99fc2bc81ead.png">

**Comment by mslarae13** [comment]
Add to Guides / coments

"Year-Month-Day"
"YYYY-MM-DD"

**Comment by ssarrafan** [comment]
<img width="926" alt="Screenshot 2024-08-02 at 12 16 46 PM" src="https://github.com/user-attachments/assets/a167a177-a861-4ac6-aaeb-87686d815c79">
Looks like the other examples were added. See screenshot. Closing ticket.
