### ISSUE TITLE
Metadata: RNA Well should only be required when submitting a plate

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#115]
RNA well number should not be required if submitting in a tube

**Comment by mslarae13** [comment]
DNA is right.... RNA (metaT) needs updated to match

![Screen Shot 2023-03-02 at 7 06 47 PM](https://user-images.githubusercontent.com/44581429/222621452-c4cf6c66-a2f8-49c0-99e9-092d49e911c0.png)

![Screen Shot 2023-03-02 at 7 06 54 PM](https://user-images.githubusercontent.com/44581429/222621504-b72cd554-8476-4b6f-b976-ac1fa6a596de.png)

**Comment by ssarrafan** [comment]
@turbomam is this in scope for this two week period?

**Comment by turbomam** [comment]
I don't think so. We can check this with rules in the nmdc-schema, but I don't think rules are generally checked by DataHarmonizer.  @pkalita-lbl do you know where we stand with LinkML rules and DataHarmonizer?

Re-reading @mslarae13's "DNA is right" comment... does that mean that the "well number is only relevant for plate containers" rule is being enforced already? I'll have to check that.

**Comment by pkalita-lbl** [comment]
The LinkML `rules` syntax has not been implemented in DataHarmonizer yet. See https://github.com/cidgoh/DataHarmonizer/issues/370.

**Comment by ssarrafan** [comment]
> The LinkML `rules` syntax has not been implemented in DataHarmonizer yet. See [cidgoh/DataHarmonizer#370](https://github.com/cidgoh/DataHarmonizer/issues/370).
> 
> If that needs to be prioritized, let me know.

I checked with @emileyfadrosh and she said this issue isn't the highest priority so not urgent to do before everything.  @pkalita-lbl

**Comment by turbomam** [comment]
> Even without validation in DH, we can still validate data in files against the submission schema.

Actually, even this is going to be difficult, since the base schema is defined with schemasheets and rules are a little to complex to express in schemasheets at this point. 

I'm going to try grafting something in with @pkalita-lbl's favorite tool, `yq`

**Comment by ssarrafan** [comment]
@turbomam based on the last comment I'm assuming this is still being actively worked on. I'll move to the next sprint.  Let me know if you don't plan to work on it in the next couple of weeks.

**Comment by turbomam** [comment]
Yes, we were just looking though it in the LinkML-developers meeting. I think we found an error in the json schema generator and @pkalita-lbl will be working on it. That will help us validate this rule off-line from DataHarmonizer. Checking it in DH will come later.

**Comment by ssarrafan** [comment]
Doesn't appear to be active.  Removing from sprint. @turbomam

**Comment by mslarae13** [comment]
As an interim fix, can we make RNA plate position recommended instead of required? @pkalita-lbl 
If someone uses the subport for JGI RNA, and has tubes, this won't validate.

**Comment by mslarae13** [comment]
Interim fix has been completed. RNA plate position is optional in dev ... not in prod / sandbox

**Comment by mslarae13** [comment]
We discussed something similar for method columns. See https://github.com/microbiomedata/nmdc-schema/issues/1433 

In short, this is really hard to do.

https://github.com/microbiomedata/nmdc-schema/issues/1433

@pkalita-lbl can you comment on if this is feasible this fiscal year.. or if it's a bigger data harmonizer problem & slot requirement dependency is something we will have to hold on?

**Comment by ssarrafan** [comment]
@mslarae13 @turbomam is this still something that needs to be worked on?

**Comment by mslarae13** [comment]
The initial request for this issue to make RNA plate well recommended has been resolved.

The conditional requirement is much bigger and is in a separate issue linked above. Closing this one.
