### ISSUE TITLE
Metadata: Water geo_loc string needs updates

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#116]
In the water package sheet, "Size-fraction lower threshold" and "Size-fraction upper threshold" columns are on either side of "depth,meters" ?  They probably should be next to each other

<img width="1058" alt="Screen Shot 2023-03-02 at 3 06 06 PM" src="https://user-images.githubusercontent.com/79225425/222581834-5d86fd30-ebc5-41aa-8f96-fdb4035697ca.png">

@mslarae13 is this what this issue is referring to?  Please confirm before assigning

**Comment by mslarae13** [comment]
I think this is 2 issues mushed together on accident... and both were addressed...

https://github.com/microbiomedata/issues/issues/113

https://github.com/microbiomedata/issues/issues/112

**Comment by ssarrafan** [comment]
> I think this is 2 issues mushed together on accident... and both were addressed...
> 
> #113
> 
> #112

oh ok, good to know. I will close this one out.  Thanks.
