### ISSUE TITLE
Metadata: GOLD ecosystem requirement level

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#117]
gold ecosystem information should be recommended, not required since JGI metadata submission doesn’t require this
<img width="1410" alt="Screen Shot 2023-03-02 at 3 09 55 PM" src="https://user-images.githubusercontent.com/79225425/222582961-300ea763-0089-4d84-a775-62f630520e1a.png">

@mslarae13 can you confirm you want all 5 fields to be recommended instead of required

**Comment by mslarae13** [comment]
Confirmed, but we should discuss this with @emileyfadrosh 

@aclum brought this up at our testing session. Discussion to be had before making changes

**Comment by ssarrafan** [comment]
sent a slack message to Emiley and Alicia to see if this discussion has happened or not

**Comment by emileyfadrosh** [comment]
Agree, make recommended, and not required. Thanks!
