### ISSUE TITLE
Outline Potential Metabolomics & Metaproteomics Groups 

### ISSUE THREAD

**Issue by mar-rudolph** [microbiomedata/issues#12]
- [ ] Gather information from NMDC Specialists (Yuri & Paul) 
- [ ] Enter Potential Partners into Spreadsheet [https://docs.google.com/spreadsheets/d/1c5wCVEA_Efh3RdLmPQ97omn_HqTSbaW8MA2UNPdL3hw/edit#gid=0](url)

**Comment by ssarrafan** [comment]
@SamuelPurvine are there any updates on this issue?  I know the team meeting got postponed till next week so I will move this issue to the next sprint but let me know if it should be closed.

**Comment by SamuelPurvine** [comment]
MANA workshop interest group (may be a challenge wrt environmental focuses versus gut microbiome) - https://metabolomicsna.org/
metabolomics workbench (north american repository - NIH) - https://www.metabolomicsworkbench.org/
metabolomics society (international) - https://metabolomicssociety.org/
Metabolites (european repository) - https://www.efsa.europa.eu/en/glossary/metabolite
Metabolon - https://www.metabolon.com/

Look into clinical communities for metabolomics

National High Magnetic Field Laboratory (MagLab)(Alan Marshall) south east coast HUI? WHOI? Carbon based analysis NOM marine focus, with a movement to metabolomics

- Yuri has made progress on setting up an interest group in MANA with Yuri, Montana and two others. Likely to happen if the Board agrees.
- Biofuels ASMS section, maybe working with NREL (colorado folks), present or discuss microbiome biofuel productions, coming in June 2023. 
  Lee Ann doesn't think this will bear fruit, as there's likely no one doing this work. looking to send invites for conversations in January.
-   Need to look for a small group of folks doing environmental metabolomics at various conferences
