### ISSUE TITLE
1000 soils metadata ingest

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#120]
Ingesting the 1000 soils metadata from the submission portal for GSP.

Metadata has been curated on the submission portal, see study "1000-Soils Metadata for GSP" (https://data.microbiomedata.org/submission/a2c2b0e9-ea12-4742-a597-59b3dcc1997f/study ) 

To ingest this metadata into the data portal for GSP
- [x] Map metadata to GOLD data (Montana, https://docs.google.com/spreadsheets/d/1kExreCLFy4NucyvdumHV3j7v1CYa8flNkr5kq8FkpQI/edit?usp=sharing )
- [ ] #121
- [ ] Get Study landing page information from MONet PM (Montana)
- [x] Ingest 1000 soils metadata & GOLD metadata - https://github.com/microbiomedata/nmdc-server/issues/886

**Comment by mslarae13** [comment]
Relates to https://github.com/microbiomedata/issues/issues/85

Will need to ensure 1000 soils metadata from data portal ingest is correctly connected to the GOLD ingest. See the google sheet linked above for which GOLD samples match the sample metadata

**Comment by aclum** [comment]
biosample_set records were submitted by Sujay and James yesterday. I updated the study_set record with the information Montana provided using changesheets.

**Comment by aclum** [comment]
For a human readable name to appear on the portal we need at least a 'name'. I have a changesheet ready to go that was validated and tested on dev to update the 'name' for class biosample. These records don't have 'type' defined so I need to wait for a fix from Donny to push to production.
depends on https://github.com/microbiomedata/issues/issues/175

**Comment by aclum** [comment]
This is fixed in mongo prod, will close if dev data portal ingest looks okay.

**Comment by aclum** [comment]
@mslarae13  okay to close?

**Comment by ssarrafan** [comment]
I see the study on the portal so assuming this can be closed.  @mslarae13 @aclum
