### ISSUE TITLE
create a submission schema repo

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/issues#125]
- [x] create sheets-and-friends PyPI package https://pypi.org/project/sheets-and-friends/
- [x] create https://github.com/microbiomedata/submission-schema
  - separation of concerns 
  - exposes schema help pages via GH pages
  - includes valid and invalid data checks
- [x] remove all submission schema bits from sheets_and_friends repo
- [x] create a repo from which a submission schema DataHarmonizer can be hosted in GH pages

**Comment by ssarrafan** [comment]
@turbomam based on the remaining checkboxes I'm assuming this is still being actively worked on. I'll move to the next sprint.  Let me know if you don't plan to work on it in the next couple of weeks.

**Comment by ssarrafan** [comment]
Doesn't appear to be actively worked on. Removing from sprint as unfinished.

**Comment by turbomam** [comment]
This is very much actively worked on

**Comment by ssarrafan** [comment]
> This is very much actively worked on

Ok I will add this to the current sprint.

**Comment by ssarrafan** [comment]
@turbomam still active?

**Comment by turbomam** [comment]
Yes, this is active and will presumably continue to be active for the next few sprints. Ultimately, @cmungall would to merge the submission schema into the nmdc-schema. If and when that happens, this issue can be closed.
