### ISSUE TITLE
finalize and purchase pamphlets for NMDC engagement

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#126]

**Comment by iockert** [comment]
The second round of pamphlets (corrected proof) have been purchased and are being sent to Emiley.

**Comment by iockert** [comment]
Order must be set up with Sandra by COB Mar. 22 in order to have the pamphlets in time for GSP. Set and Emiley will touch base on Wednesday and decide next step.

**Comment by ssarrafan** [comment]
50 pamphlets were ordered today. Info sent to Sandra.
@iockert we weren't 100% satisfied so only ordered 50 so we can improve for the larger oder.  Closing issue.
