### ISSUE TITLE
Partnership Criteria

### ISSUE THREAD

**Issue by mar-rudolph** [microbiomedata/issues#13]
- [x] Brainstorm Criteria 
- [x] Test criteria against partners in tracking sheet 
- [ ] Apply criteria to partners

**Comment by ssarrafan** [comment]
Moving to the next sprint. @mar-rudolph expects to close or re-assign by Friday.

**Comment by ssarrafan** [comment]
This will be discussed at the squad meeting next week and then closed afterwards.

**Comment by simroux** [comment]
link to "brainstorming criteria" doc (criteria will then be included in the master spreadsheet) - https://docs.google.com/document/d/1koavOMpVByZA-lnSSfbFBpJIduh8Q9M5wmBdmD73MEM/edit

**Comment by ssarrafan** [comment]
@jkelliher-github I believe this was discussed so it would be great if you can close this please. Let me know if I can help.

**Comment by simroux** [comment]
I think the first task "Brainstorm criteria" can be marked as done ? Tasks #2 and #3 are probably still ongoing though
