### ISSUE TITLE
GOLD study identifiers are not displaying on the study pages for grow and bioscales

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#136]
**Is your feature request related to a problem? Please describe.**
The two new studies are missing the pointers to the GOLD study identifier on the study page
https://data-dev.microbiomedata.org/details/study/nmdc:sty-11-5tgfr349
https://data-dev.microbiomedata.org/details/study/nmdc:sty-11-r2h77870

The values for GOLD study identifiers for these two new studies are in gold_study_identifiers in the study_set collection in mongo. 

**Describe the solution you'd like**
I would like to see a GOLD study link from the study page like we do for the other JGI studies (ie https://data-dev.microbiomedata.org/details/study/gold:Gs0103573)

**Describe alternatives you've considered**
n/a
**Acceptance Criteria**
Ex
https://data-dev.microbiomedata.org/details/study/nmdc:sty-11-5tgfr349
under Open in GOLD displays  https://gold.jgi.doe.gov/study?id=Gs0149396

cc @ssarrafan

**Comment by aclum** [comment]
Reopening @naglepuff  whatever changes got applied now GOLD study identifiers are completely missing for these two study pages.

**Comment by naglepuff** [comment]
After merging, re-ingest needed to happen before they would show up. You should be able to see them in dev now. Feel free to close when you confirm.

**Comment by aclum** [comment]
Both GROW and Bioscales have working links to GOLD studies from the NMDC study pages.
