### ISSUE TITLE
Protein files may be corrupted

### ISSUE THREAD

**Issue by scanon** [microbiomedata/issues#137]
**Is your feature request related to a problem? Please describe.**
Protein files are overwriting each other and causing duplicate entries.

**Describe the solution you'd like**
Copy the correct one and remove the extra entries in data_object_set and activity records.

**Describe alternatives you've considered**
Ignore it.

**Acceptance Criteria**

Copy correct file
Fix database

**Comment by aclum** [comment]
This is an issue with new annotation records (GROW and Bioscales) only. The previous data transfer process did copy over the genemark and prodigal *faa files in addition to the _proteins.faa file

**Comment by aclum** [comment]
This should be fixed.

**Comment by aclum** [comment]
spot checking this is still wrong
nmdc:omprc-11-7w7kd053/nmdc:wfmgan-11-wfrwg749.1 
based on file size of the JGI files the proteins.faa file should 514772672 bytes. nmdc_wfmgan-11-wfrwg749.1_proteins.faa has a file size of 450885950, which is the size of the genemark protein file for jgi (Ga0495608_genemark_proteins.faa)
this is a bioscales omics_processing_set record

**Comment by aclum** [comment]
spot checking this looks correct.
GROW
nmdc:wfmgan-11-yp9h1719.1 
Bioscales
nmdc:wfmgan-11-wfrwg749.1
nmdc:wfmgan-11-fkjwh373.1
nmdc:wfmgan-11-wfrwg749.1
