### ISSUE TITLE
Discrepancy in sample count between Bioscales study details page and studies summaries

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/issues#139]
- 318 Bioscales metagenome samples reported in lower right of Data Portal (dev)
- But Bioscales study details page](https://data-dev.microbiomedata.org/details/study/nmdc:sty-11-r2h77870) says 416 samples

Due to 98 unreported metabolome samples?

**Comment by turbomam** [comment]
Metabolome samples just not reported?

**Comment by ssarrafan** [comment]
@aclum is this still an issue that needs to be resolved or can this one be closed?

**Comment by aclum** [comment]
This is the expected behavior, closing.
