### ISSUE TITLE
No image for Bioscales study page in dev

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/issues#140]
https://data-dev.microbiomedata.org/details/study/nmdc:sty-11-r2h77870

Didn't we have a photo of Mitchel Doktycz in the past? I do see it on the prod Data Portal but not the dev Data Portal that @sujaypatil96 has been updating.

https://portal.nersc.gov/project/m3408/profile_images/doktycz_mitchel.jpg

Ideally, we would show an image representative of the study (from `study_image`), not the PI.

**Comment by aclum** [comment]
This is being addressed in https://github.com/microbiomedata/issues/issues/155 along with a few other study issues.
