### ISSUE TITLE
data portal should preferentially display study logo over PI logo when available 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#143]
depends on
- [x] https://github.com/microbiomedata/issues/issues/142
- 
**Is your feature request related to a problem? Please describe.**
For large scale collaborative projects like GROW, BIoscales, EMP Emiley would like the study logo to be displayed instead of the PI logo.
**Describe the solution you'd like**
If study_image is populated in mongo it should display that instead of profile_image_url
**Describe alternatives you've considered**
populate profile_image_url with study logo

**Acceptance Criteria**
GROW logo can be seen on the study page.

cc @ssarrafan @shreddd

**Comment by naglepuff** [comment]
I did some investigation, and it seems like this wouldn't be too difficult to get into dev by the end of the current sprint, as long as image URLs are added to the study documents in mongo.

**Comment by aclum** [comment]
@naglepuff two studies now have images in mongo prod in study_set for you to test with. Study identifiers are 
nmdc:sty-11-34xj1150 and nmdc:sty-11-5tgfr349. Note that the structure of study_image in mongo has a range of ImageValue, not string like profile_image_url
https://microbiomedata.github.io/nmdc-schema/ImageValue/

cc @ssarrafan  @emileyfadrosh
