### ISSUE TITLE
GROW and bioscales missing read filtering data 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#145]
**Is your feature request related to a problem? Please describe.**
Read filtering results is missing for new metagenome records. There are two similarly named collection sets and we need to pick one and migrate the records over, similar to what happened with [#62 Sync up on the class name change for the readbased analysis set](https://github.com/microbiomedata/issues/issues/62)

Example this record  below has a entry in read_qc_analysis_activity_set with an id of nmdc:wfrqc-11-sesm2630.1 but nothing is visible on the data portal. 

Rhizosphere soil microbial communities from poplar common garden site in Clatskanie, Oregon, USA - GW-9591-CL1_34_16 rhizosphere
Study ID:[nmdc:sty-11-r2h77870](https://data-dev.microbiomedata.org/details/study/nmdc:sty-11-r2h77870)Sample Identifiers:[GOLD:Gb0291786](https://identifiers.org/GOLD:Gb0291786)[3300047319](https://identifiers.org/3300047319)

**Describe the solution you'd like**
Consolidate to a single collect name for read qc records, it looks like `read_qc_analysis_activity_set` is what is being used for new records and records from `read_QC_analysis_activity_set` are what would need to get moved over. Then kitware would need to update which mongo collection they ingest from on their end.

**Describe alternatives you've considered**
n/a

**Acceptance Criteria**
Metagenome workflow records contain read qc filtering results for sample Rhizosphere soil microbial communities from poplar common garden site in Clatskanie, Oregon, USA - GW-9591-CL1_34_16 rhizosphere. Filtering results are not lost for older studies (ex Bulk soil microbial communities from the East River watershed near Crested Butte, Colorado, United States - ER_143)

@shreddd

**Comment by scanon** [comment]
@shreddd what do you want to do here.  I can do something quickly copy from one collection to the other.  But I don't know if kitware would want to make a change at this point.

**Comment by aclum** [comment]
kitware has updated to use the lowercase collection and there are no records in the lowercase collection so assigning to Mike to work on.

**Comment by naglepuff** [comment]
The data model on the portal side had `input_read_count`, `input_base_count`, `input_read_bases`, and `output_read_bases` as required, non-nullable fields. The new workflows weren't getting ingested because they have `null`s in these fields. I can update our data model to allow for the `null` values here.
