### ISSUE TITLE
pfam overwritten with supfam

### ISSUE THREAD

**Issue by scanon** [microbiomedata/issues#146]
**Is your feature request related to a problem? Please describe.**
Bug: pfam is actually supfam

**Describe the solution you'd like**
Copy with correct file and fix data objects

**Describe alternatives you've considered**
None

**Acceptance Criteria**
Outputs match

**Comment by mhuntemann** [comment]
Hi Shane,
Is this an issue with the actual annotation pipeline or rather with some post-processing step outside of it?
Thanks,
Marcel

**Comment by aclum** [comment]
@mhuntemann  this is an issue on NMDC's side with creating data objects from the JGI results.

cc @aclum

**Comment by mhuntemann** [comment]
OK, thanks for clarifying, Alicia. Appreciate it.

**Comment by scanon** [comment]
I've cleaned up the errant files.  The next refinement is to copy over and add the actual supfam files.  This will take a little more time.

**Comment by aclum** [comment]
50% fixed

**Comment by aclum** [comment]
Shane still needs to remove redundant data objects, we are still missing supfam

**Comment by scanon** [comment]
I think this is all done now

**Comment by aclum** [comment]
spot check of nmdc:wfmgan-11-8yc5z542.1 looks good for GROW, nmdc_wfmgan-11-wfrwg749 for bioscales looks good.
