### ISSUE TITLE
Ambassador NMDC EDGE training slides & materials

### ISSUE THREAD

**Issue by jkelliher-github** [microbiomedata/issues#150]

**Comment by ssarrafan** [comment]
@frodriguez16 can you update this GH issue with the links to the slides and materials when you're back on Monday.  I'll move this over to the next sprint so we can close it (hopefully) on Monday.  Thanks.

**Comment by frodriguez16** [comment]
https://drive.google.com/drive/folders/1JtnmbuUQgdaEQilhYqNANVnQSQUahEVh
