### ISSUE TITLE
Submission Portal user guide & training video

### ISSUE THREAD

**Issue by jkelliher-github** [microbiomedata/issues#151]

**Comment by emileyfadrosh** [comment]
I just went through and cleaned up the old comments, rearranged some text for the introduction, and took some updated screenshots from dev to be consistent with the latest & greatest. @mslarae13 it would be great if you could take a look and update the sample metadata section (pg 8 onward). 

Would appreciate input from @jkelliher-github @iockert @frodriguez16 for comments, edits, ect - thanks!

And also input and additional text from @cmungall @turbomam @pkalita-lbl for any further details or information that could/should be included.

**Comment by iockert** [comment]
Looked good to me! I added one screenshot, but it looks like a few others are needed.

**Comment by ssarrafan** [comment]
@jkelliher-github @mslarae13 can you please add the link to the user guide/training video in this GH issue. Thanks!

**Comment by turbomam** [comment]
Where can I find the user guide document and the video?

**Comment by ssarrafan** [comment]
https://docs.google.com/document/d/1RLMopTBmNGoxJRWgtePSI-dyKjDN5w7inFXHV36XjqE/edit#heading=h.7r73axau61wj for the user guide (access required)

**Comment by ssarrafan** [comment]
I'm moving this to the next sprint since some screenshots may need to be updated etc.  @emileyfadrosh @mslarae13

**Comment by ssarrafan** [comment]
This is done, closing issue
