### ISSUE TITLE
The DataHarmonizer in the Submission Portal should support loading JSON data and dumping JSON data

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/issues#158]
DataHarmonizer's JSON format is almost totally compatible with the data serialization expected by LinkML tools. See exception below.

The NMDC Submission Portal should support trafficking in JSON so that data developed in the Submission Portal can be included in the submission schema repo and vice versa

Whether that functionality should be exposed to end users or not is a subject for discussion. If we decide not to expose to end users, then either there could be magic URLs or there could be buttons that only appear on an administrator's view.

cc @mslarae13 @naglepuff @jeffbaumes

**Comment by ssarrafan** [comment]
@turbomam @mslarae13 @pkalita-lbl is this still on the table as something that needs to get done?

**Comment by turbomam** [comment]
I think DataHarmonizer is capable of this now but the functionality hasn't been exposed in our Submission Portal. If I'm the only one who wants it, then we can close this.

**Comment by ssarrafan** [comment]
I checked with Montana via Slack and she said this is not a priority for her.  I'm going to close this issue. If it becomes a priority or a request from stakeholders we can create a new ticket or re-open this one.
