### ISSUE TITLE
Ambassador honoraria

### ISSUE THREAD

**Issue by jkelliher-github** [microbiomedata/issues#164]

**Comment by ssarrafan** [comment]
@emileyfadrosh are you actively working on this?

**Comment by emileyfadrosh** [comment]
Sorry, yes, this is in progress and nearly complete (thanks to Wendi, of course!). I will check with Wendi on Monday and then close it out when the Ambassadors have received them. Thanks!

**Comment by ssarrafan** [comment]
Checked with Wendi and she reported the following. I'll close this issue.

From Wendi:  Yes, they are all done (except Candace Hope Bias). After several reminders, I am still waiting for her to e-Fax her paperwork to A/P (she says she has been working on it). The other 12 should start seeing $ deposited in their accounts in the next few days (if not, already).
