### ISSUE TITLE
Blog posts for Ambassador publication

### ISSUE THREAD

**Issue by jkelliher-github** [microbiomedata/issues#166]
- [x] - DOE science highlight
- [x] - Nature blog post
- [x] - Social media releases

**Comment by iockert** [comment]
First draft of the highlight has been written: Emiley and Massie have given feedback. [https://docs.google.com/document/d/11Q5_asueQJWOmHu5RCAnSS5dwMEM1HFP/edit](url)

**Comment by iockert** [comment]
Emiley and Julia have given feedback, but this has increased the FK rating. need to revise it back down to level 13

**Comment by iockert** [comment]
I've finished a highlight at grade 13: https://docs.google.com/document/d/1S6RVnJ3jn07zOgfZ5GroewKjUl3M6Oze/edit?usp=sharing&ouid=117854663729323712737&rtpof=true&sd=true

Additionally, have drafted out a press release: https://docs.google.com/document/d/1kYnw4sYsqzpSfLTWbhHEc3yyh0fRoHxsKiZa8SwV_Es/edit?usp=sharing

**Comment by iockert** [comment]
After talking with Lida Gifford, it was decided that we would not do a press release, but instead we would pitch a feature story to Strat Comms.

The Highlight has been submitted to Ramana.

**Comment by iockert** [comment]
Final Highlight [04122023_NMDC Highlight_Ambassador program_1 .docx](https://github.com/microbiomedata/issues/files/11237565/04122023_NMDC.Highlight_Ambassador.program_1.docx)
