### ISSUE TITLE
metagenome assembly version information file is incorrect name, description, and data_object_type in mongo prod

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#174]
**Is your feature request related to a problem? Please describe.**
Emiley noticed on the data portal that there were two files labeled error corrected reads for an assembly activity. Looking at the data_object_set in mongo one of these files is correct and the other in the *assembly.info file mislabled as Error Corrected Reads.  Example record is 
/global/cfs/cdirs/m3408/ficus/pipeline_products/nmdc:omprc-11-3weevj13/nmdc:wfmgas-11-b025n938.1
The nmdc_wfmgas-11-b025n938.1_assembly.info (data_object_set id nmdc:dobj-11-qer6k715) has the incorrect type.
Filter to find all files from this wf activity in data_object_set
{ "url" : /wfmgas-11-b025n938/ }

**Describe the solution you'd like**
FileTypeEnum should be "Assembly Info File"
Update records such that name, description, and data_object_type are updated in mong prod. 

**Describe alternatives you've considered**
n/a
**Acceptance Criteria**
For each metagenome_assembly_set id (ie wfmgas-11-b025n938.1) the count per unique data_object_type should be equal to one. The data_object_type list should contain the following data_object_type ("Error Corrected Reads","Assembly Info File", "Assembly Contigs","Assembly Coverage Stats","Error Corrected Reads","Assembly Coverage BAM")

cc @shreddd

**Comment by aclum** [comment]
![Screen Shot 2023-03-31 at 5 27 02 AM](https://user-images.githubusercontent.com/8196591/229209805-c1a63e33-be9d-4742-a5ef-6b02218c324f.png)

**Comment by scanon** [comment]
This should be fixed now.

**Comment by aclum** [comment]
confirmed fixed. cc @shreddd
