### ISSUE TITLE
type for Class study not requirement by linkml but required for runtime API endpoint changesheets:validate

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#175]
**Is your feature request related to a problem? Please describe.**
This ticket spans schema and runtime so using the generic issues repo.
The linklm documentation says that type for class Study is optional (https://microbiomedata.github.io/nmdc-schema/Study/)  However, this was missing for 1000 soils and I was unable to use the changesheets endpoint. This was resolved when I minted a new study id with the same information plus ("type":"nmdc:Study")

**Describe the solution you'd like**
json:validate and changesheets:validate and linkml documenation should be consistent. Either changesheets should be allowed for study_set records w/o a type defined or a study_set record w/o type should fail json:validate

**Describe alternatives you've considered**
obscure institutional knowledge 

**Acceptance Criteria**
Pending discussion of how this will be solved. 

id gold:Gs0110119 is the only existing study_set record that does not have 'type' defined so if that is required going forward someone would need to do a direct mongo update on prod.

cc @sujaypatil96 @shreddd

**Comment by dwinston** [comment]
`Study.type` is optional. Fixed error in changesheets:validate via https://github.com/microbiomedata/nmdc-runtime/commit/96cba507f0f84fb06e387ca47601d3e46474672f

**Comment by dwinston** [comment]
note that a sheet modifying `gold:Gs0110119` still does not validate for now, but for a different reason: https://github.com/microbiomedata/nmdc-runtime/issues/243
