### ISSUE TITLE
Available Microbiome Trainings

### ISSUE THREAD

**Issue by jkelliher-github** [microbiomedata/issues#177]
https://docs.google.com/spreadsheets/d/17mEGpZC7jv5AngeQFqKiE7fUiZKjdBNpBnbEsAyEtEc/edit#gid=0

**Comment by ssarrafan** [comment]
@frodriguez16 is this actively being working on?

**Comment by frodriguez16** [comment]
It is, I'm going to chat with Julia about it tomorrow.

**Comment by ssarrafan** [comment]
This issue was marked done back in Sept 2023 so I'm closing it here.
