### ISSUE TITLE
Set up Cloudflare for NMDC

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#179]
Hostname for NMDC currently points to NERSC. Switching to back-up instance will be nicer, more seamless with Cloudflare.   We will move to Cloudflare after GSP.

**Comment by aclum** [comment]
@shreddd  I think you took care of this recently ahead of a nersc maintenance. Please confirm this is okay to close.

**Comment by aclum** [comment]
Closing @shreddd  please reopen if needed.
