### ISSUE TITLE
Missing metagenome_assembly_set data for nmdc:wfmgas-11-tcjh6881.1

### ISSUE THREAD

**Issue by shreddd** [microbiomedata/issues#180]
There is one straggler that I discovered when cross checking the metagenome_assembly_set in Issue #174 

In mongo this entry:
```
db.getCollection("metagenome_assembly_set").find({"id": "nmdc:wfmgas-11-tcjh6881.1"})
```
Returns a record that points to data objects in: 
/global/cfs/cdirs/m3408/ficus/pipeline_products/nmdc:omprc-11-g0vpnz53

These data objects seem to be missing since I am not seeing any wfmgas* workflows here 

Could you take a look to see if the workflow needs to be re-added or cleaned up.

**Comment by aclum** [comment]
Needed deletes on mongo prod 
delete sequencing activity record
```
{
  "delete": "metagenome_sequencing_activity_set",
  "deletes": [{"q": {"id": "nmdc:wfmsa-11-gx00yr18.1"}, "limit": 1}]
}
```
delete data objects 
```
{
  "delete": "data_object_set",
  "deletes": [{"q": {"id": "nmdc:dobj-11-kz89p396"}, "limit": 1},{"q": {"id": "nmdc:dobj-11-zb6r1y22"}, "limit": 1},{"q": {"id": "nmdc:dobj-11-c2ggag17"}, "limit": 1}]
}
```

**Comment by aclum** [comment]
I have permissions to delete permissions via runtime API with the queries:run endpoint. I've deleted the records listed in my comments yesterday.
