### ISSUE TITLE
Add a proxy that includes the portal API and runtime API under a single URL

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/issues#19]
This is a first small step toward API unification based on retreat discussions. @shreddd I believe you said you'd take this one.

@cmungall @shreddd @dwinston @elais @mcovalt

**Comment by jeffbaumes** [comment]
I am realizing this will also need to incorporate/proxy the portal API from the dev instance in addition to the prod API. The dev portal frontend would point to the dev API, and the prod frontend will point to the prod API.

**Comment by shreddd** [comment]
we have a quick and dirty version of a common API
portal API - http://api-dev.nmdc-dev.development.svc.spin.nersc.org/api/summary
runtime API - http://api-dev.nmdc-dev.development.svc.spin.nersc.org/sites
runtime API - docs - http://api-dev.nmdc-dev.development.svc.spin.nersc.org/docs

Next steps:

- [ ] DNS name
- [ ] Cert
- [ ] Add docs for portal API

**Comment by shreddd** [comment]
Unified API is now at https://api-dev.microbiomedata.org/

@mcovalt - Once you've added the docs to /api/docs/ we can close this out
