### ISSUE TITLE
Onboarding/offboarding materials

### ISSUE THREAD

**Issue by iockert** [microbiomedata/issues#194]

**Comment by jkelliher-github** [comment]
Is this new? Francie had started a lot of NMDC content for onboarding

**Comment by iockert** [comment]
This is newish! I created it in case I needed an issue to organize materials for onboarding/offboarding new NMDC team members. (Set and Wendi had organized a meeting about it). In the end, Wendi decided to handle it, so I just removed it. Should I have closed it!
