### ISSUE TITLE
Compare Bioscales metaG to biosample IDs

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#2]
**Is your feature request related to a problem? Please describe.**
This is to address consistency in the bioscales data

**Describe the solution you'd like**
Ability to compare Bioscales metaG metadata to biosample IDs Stan provided in Data Harmonizer

**Describe alternatives you've considered**
N/A

**Acceptance Criteria**
Create a checklist or scenario-based acceptance criteria, from the users perspective, that answers the following: 

Who will use this feature/enhancement? 
When will they use it? When getting data prepared for upload to portal
How will they use it? Use it for checking data consistency and accuracy
How will they test it to make sure it's working? ?
Is the request achievable? During one sprint? ?
What is your definition of done for this request? comparison completed and inconsistencies addressed in bioscales metadata

**Comment by aclum** [comment]
@mslarae13  is this still needed? bioscales was loaded into the data portal for GSP 2023.

**Comment by mslarae13** [comment]
I think this is good to close and no additional changes needed
