### ISSUE TITLE
Update JGI ingest code to handle annotation pipeline version 5.1

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#201]
Per Shane there are GROW projects which span annotation versions 5.0 and 5.1. 
- [ ] The jgi ingest code needs to be updated to handle the newer version. 
- [ ] review if new file enums are needed
- [ ] updates to scripts for submitting metadata to mongo

**Comment by aclum** [comment]
@ssarrafan  not sure if this is going to be the next sprint or the following. @Michal-Babins  is going to refactor the existing ingest code first.

**Comment by ssarrafan** [comment]
I'll leave it in the GROW board. Once it moves to in progress I'll add it to the current sprint.

**Comment by aclum** [comment]
No changes needed, the enums, transfer scripts, and submission scripts work with both versions. NMDC has decided against storing the intermediate files which is where the differences b/w the two versions are.
