### ISSUE TITLE
Latest updates and deploy the backup instance at EMSL

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#202]
NMDC portal has been updated in PROD.  Please grab the latest updates and deploy the backup instance at EMSL.

**Comment by naglepuff** [comment]
Yes, 0.9.1

**Comment by ssarrafan** [comment]
@shreddd @kfox1111 assuming we can close this issue.  Please re-open if necessary.  
Thank you for getting this set up for GSP @kfox1111
