### ISSUE TITLE
Submission Portal Issues Post-GSP

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#203]
**After GSP** 
- [ ] #204
- [x] #205
- [x] #206
- [ ] #118
- [x] #207
- [x] #208
- [ ] microbiomedata/issues#98
- [x] #209
- [x] #210
- [x] #122
- [ ] #114 moving from GSP list 4/7/23
- [ ] #115 moving from GSP list 4/7/23

**Comment by mslarae13** [comment]
Ha! 

Umm,, I'll look at the open issues, sort out their priority, who & when they should be worked on.

**Comment by mslarae13** [comment]
These are all in a post GSP board or submission board. I'm going to close the super issue
