### ISSUE TITLE
Study Information: Remove EMSL and JGI check boxes if "data will NOT be generated at a UF"

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#206]

**Comment by mslarae13** [comment]
This is done. When you select "Data has already been generated" If you do not check "Data generated by a DOE UF" you do not see JGI and EMSL as options in step 4.

You do however still see the "GOLD Study ID" ... should that be removed too? @aclum @emileyfadrosh

**Comment by aclum** [comment]
GOLD supports externally generated data (ie there are GOLD studies for NEON data sequenced external, [EMP500]([Gs0154244](https://gold.jgi.doe.gov/study?id=Gs0154244)), etc) so I suggest leaving it.
