### ISSUE TITLE
Metadata: Make JGI pre-provided fields a different color

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#208]

**Comment by mslarae13** [comment]
They're not editable and will come in via the API.
@pkalita-lbl is it possible to add another color?

**Comment by pkalita-lbl** [comment]
It's not something that DataHarmonizer provides out of the box, but we might be able to hack something together.

**Comment by mslarae13** [comment]
IMO, hacking something together seems unnecessary & this doesn't seem that important to me.
How do we have the purple and yellow for required and recommended?

**Comment by pkalita-lbl** [comment]
It's part of DataHarmonizer's interpretation of a LinkML schema. When a slot is marked with `required: true`, the column header is rendered as yellow; otherwise if it's marked with `recommended: true`, the column header is rendered as purple; otherwise the column header is the default grey.

**Comment by mslarae13** [comment]
I am going to close this as OBE. The JGI fields will be auto populated, you get a "no" cursor when you hover over the fields that are provided & can't be edited.
