### ISSUE TITLE
Shipping info: EMSL experiment goals

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#209]

**Comment by mslarae13** [comment]
The experiment goals box is there... @ssarrafan do you remember what this was for? Was it missing? Does it need more information?

**Comment by ssarrafan** [comment]
> The experiment goals box is there... @ssarrafan do you remember what this was for? Was it missing? Does it need more information?

I think it wasn't there before. I'll go ahead and close this one.  Thanks!
