### ISSUE TITLE
Partnership criteria - Apply criteria to partners

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#21]
Last step from previous partnership criteria work - https://github.com/microbiomedata/issues/issues/13

See more details on criteria at https://docs.google.com/presentation/d/1YohF6Lm_p1nbBUVQyfgSsrrzL1-Noej_nvpxO09dUDY/edit#slide=id.g1885faa4fd2_0_10

@jkelliher-github will work with @simroux on this.

**Comment by ssarrafan** [comment]
Moving to the next sprint, LANL closed on Wednesday so I don't think this one will be closed

**Comment by jkelliher-github** [comment]
@ssarrafan Can this one continue to next sprint? Still need results from other team members

**Comment by ssarrafan** [comment]
Closing per updates from engagement meeting 1/3/23. @jkelliher-github will open a new one to add the publishers to the criteria in the future.
