### ISSUE TITLE
Shane's Items (need to split out)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#212]
- [ ] Design and implement mechanism to manage the life-cycle of data (e.g. draft, release, archive/deprecate)
- [ ] Schema changes to support above

**Comment by ssarrafan** [comment]
@scanon @aclum are these things we still need or can I close this issue?

**Comment by aclum** [comment]
Conceptually all data is released so we don't have a concept of 'draft' right now, deprecation an archive is handled either through a combination of workflow ID versioning (.1, .2,.3) and by [qc_status](https://microbiomedata.github.io/nmdc-schema/qc_status/), [qc_comment](https://microbiomedata.github.io/nmdc-schema/qc_comment/), [qc_failure_what](https://microbiomedata.github.io/nmdc-schema/qc_failure_what/), and [qc_failure_where](https://microbiomedata.github.io/nmdc-schema/qc_failure_where/)
