### ISSUE TITLE
Streamline Mongo->PG ingest pipeline

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#213]

**Comment by aclum** [comment]
Anyone remember specifics about this ticket? Ingest doesn't seem to be a problem currently. @ssarrafan @shreddd

**Comment by ssarrafan** [comment]
> Anyone remember specifics about this ticket? Ingest doesn't seem to be a problem currently. @ssarrafan @shreddd

I looked back on the notes from that week and don't have any more details. I think this was one of the things we wanted to do after GSP last year. DB discussion this week may shed some more light into this?

**Comment by aclum** [comment]
I'm going to close this for now, @marySalvi @naglepuff @jeffbaumes  let's start a new nmdc-server ticket if needed.
