### ISSUE TITLE
rna plate position should be recommended

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#217]
Found another slot usage that I think was lost with the retiring of sheets and friends.
'RNA plate position" should be recommended, like it is for DNA (MG)... not required

See here

![Screen Shot 2023-04-11 at 3 39 21 PM](https://user-images.githubusercontent.com/44581429/231304262-f93bd9c8-2035-4cd1-985d-da03618851b5.png)
![Screen Shot 2023-04-11 at 3 39 38 PM](https://user-images.githubusercontent.com/44581429/231304269-dd572337-5440-4393-866e-a48bfaa388f9.png)

Or recording here:
~ 8min-9:10

Criteria for completion
- [ ] Update the requirement level for rna plate position to recommended
- [ ] Sync change to prod and sandbox

**Comment by pkalita-lbl** [comment]
Schema changes are in. Once we release a new version of `submission-schema` we'll need to bring it into `nmdc-server`.

**Comment by ssarrafan** [comment]
Moving to next sprint per @pkalita-lbl

**Comment by pkalita-lbl** [comment]
This is still paused waiting for a new `submission-schema` release.

**Comment by pkalita-lbl** [comment]
This change is now on https://data-dev.microbiomedata.org/
