### ISSUE TITLE
Create template for MOUs and other governance materials

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#22]
- [ ] Governance policy for workflow updates and db partnerships with User Facilities
- [ ] Develop governance policy for interactions with KBase
- [ ] Develop governance policy for interactions with ESS-DIVE

**Comment by ssarrafan** [comment]
@emileyfadrosh I'm going to move this to the next sprint. Let me know if I can help.

**Comment by emileyfadrosh** [comment]
Started a draft collaborative agreement for JGI & NMDC as a starter [here](https://docs.google.com/document/d/18E1P0JagyGDV2pPtlVuwRsCGc9qdfQq7WgKUMh67bsM/edit#heading=h.81hs5y3yia04)

Will need to get input on level of detail from team, and then route through Nigel and JLT for input/approval. For the other milestones associated with governance policies, will need separate agreements as follows: 

- [ ] Collaborative agreement with EMSL (splitting Milestone 0.4) 
- [ ] Collaborative agreement with KBase (Milestone 0.7)
- [ ] Collaborative agreement with ESS-DIVE (Milestone 0.7)

For all, will need Director-level sign off and DOE Program Manager approval. Deadlines for all are December 31.
