### ISSUE TITLE
EMP 500 MassIVE identifiers 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#222]
We now have a slot, [massive_study_identifiers](https://microbiomedata.github.io/nmdc-schema/massive_study_identifiers/), for class Study and can add the EMP 500 massive records from [the publication](https://www.nature.com/articles/s41564-022-01266-x)
[MSV000083475](https://massive.ucsd.edu/ProteoSAFe/QueryMSV?id=MSV000083475), [MSV000083743](https://massive.ucsd.edu/ProteoSAFe/QueryMSV?id=MSV000083743)

nmdc class Study id `gold:Gs0154244`

**Comment by ssarrafan** [comment]
@aclum @mslarae13 is this still something we need to do?

**Comment by aclum** [comment]
Yes this is still outstanding. It should be fast, I can do it this sprint.

**Comment by aclum** [comment]
The metadata in mongo prod has been updated. It will be on the portal study page after the next weekly ingest.
