### ISSUE TITLE
Bioscales - add additional study level records

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#225]
- [x] JGI genome portal 
https://genome.jgi.doe.gov/portal/BioDefcarcycling/BioDefcarcycling.info.html
depends on https://github.com/microbiomedata/nmdc-schema/issues/868

- [x] GNPS records 
C18-negative: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=4b848c342a4f4abc871bdf8a09a60807
C18-positive: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=f8efbde4cc154db6a4cf269072d42d40
HILIC-negative: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=51cc733a80ed41139ecdd1bedf3c01af
HILIC-positive: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=8062948726c543dba53ec58c0f1ebb25

depends on https://github.com/microbiomedata/nmdc-schema/issues/868

**Comment by ssarrafan** [comment]
@aclum is this still in the backlog?  (see bioscales board)

**Comment by aclum** [comment]
@ssarrafan yes, see blocking issue https://github.com/microbiomedata/nmdc-schema/issues/868. We need a schema release + sync.

**Comment by aclum** [comment]
Blocked on data portal study page revamp squad.

**Comment by aclum** [comment]
These records were added to mongoDB during the Zoe sprint.
