### ISSUE TITLE
JGI data ingest code updates for multiple seq unit projects which should be kept separate 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#228]
JDP API has added information about what what original sequencing files were used for metagenome and metatranscriptome assemblies. We can use this information to confirm what input files where used, this is especially important if there are multiple seq units per JGI sequencing project id (ie GROW).
JDP API return documents now include seq_unit_name at the same level as _id if the file is data_group=Analysis

example
```
   {
          "_id": "61314c5ccf09c80068562bde",
          "_highlight": null,
          "file_path": "/global/dna/dm_archive/rqc/analyses/AUTO-353198",
          "file_status_id": 10,
          "metadata": {
            "proposal": {
              "award_doi": "10.46936/10.25585/60001289",
...
            "seq_unit_name": [
              "52554.1.382511.TTCGATCC-CTATACGG.fastq.gz"
            ],

```
This information can be used to make sure the right raw and filtered data are associated correctly.  This means that for agg_id=1309648 the raw data file is 52554.1.382511.TTCGATCC-CTATACGG.fastq.gz and the filtered data and associate files should have the same prefix (ie 52554.1.382511.TTCGATCC-CTATACGG.*). 

Example JDP API query where there are two seq units 
https://data.jgi.doe.gov/search?q=1280048

**Comment by aclum** [comment]
Mark and I met and discussed this yesterday.

**Comment by ssarrafan** [comment]
> Mark and I met and discussed this yesterday.

assuming this means it's going to be actively worked on, correct @mflynn-lanl @aclum

**Comment by aclum** [comment]
Yes.

**Comment by aclum** [comment]
@mflynn-lanl  did you do a test transfer this week?

**Comment by mflynn-lanl** [comment]
No, I finished refactoring my code and tests. I’ll test today

From: aclum ***@***.***>
Reply-To: microbiomedata/issues ***@***.***>
Date: Thursday, June 1, 2023 at 4:23 PM
To: microbiomedata/issues ***@***.***>
Cc: "Flynn, Mark C" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [microbiomedata/issues] JGI data ingest code updates for multiple seq unit projects which should be kept separate (Issue #228)


@mflynn-lanl<https://urldefense.com/v3/__https:/github.com/mflynn-lanl__;!!Bt8fGhp8LhKGRg!Gz2qqpVGn_IqxAOFrgYdx1lGnEMabfPGuLYn5MhORaSXecuSzXI-KeSX-if3ug-4W3miVLRmAXullg_DtYYeZBfY$> did you do a test transfer this week?

**Comment by ssarrafan** [comment]
I'll move to new sprint so @mflynn-lanl can report on his testing and close the issue next week(?).

**Comment by ssarrafan** [comment]
@mflynn-lanl @aclum What's the status of the testing for this?

**Comment by aclum** [comment]
@mflynn-lanl Do you have test output directories?

**Comment by aclum** [comment]
Do you have test output from a GROW project that has two libraries?

**Comment by ssarrafan** [comment]
This was marked done by Donny in October so I'm closing the issue
