### ISSUE TITLE
Add funding statement input field to submission portal

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#229]
**Is your feature request related to a problem? Please describe.**
GSP workshop feedback, would like to add a statement about funding source. This is available on the data portal study landing page, but we currently don't have anywhere for someone to put one.

**Describe the solution you'd like**
Add a "funding statement" field to the study page on the submission portal. Above description maybe?

**Acceptance Criteria**
Create a checklist or scenario-based acceptance criteria, from the users perspective, that answers the following: 

Who will use this feature/enhancement? submitters
When will they use it? when filling out their study information in the submission portal
Is the request achievable? During one sprint? yes?

**Comment by ssarrafan** [comment]
@JamesTessmer what's the status of this issue?  Are you actively working on this?

**Comment by JamesTessmer** [comment]
@ssarrafan yes I am sorry. It should be done soon, I got a little overconfident in my prediction that it would be done this sprint because I underestimated how much time I would soend moving to a new apt this week.

**Comment by JamesTessmer** [comment]
This issue should be resolved with the PRs below:
https://github.com/microbiomedata/nmdc-runtime/pull/627 Runtime PR
https://github.com/microbiomedata/nmdc-server/pull/1323 Server PR

**Comment by JamesTessmer** [comment]
@mslarae13 I think this issue is pretty much done but I wanted to check one thing with you. Right now the server repo front end isn't set up to take multiple values but the slot is multivalued in the mongo database. Should we update that? The PR on the runtime isn't merged in yet, so that's a small change to that as well if we allow for multiple values in the front end.

**Comment by ssarrafan** [comment]
I'll move over one more sprint for @mslarae13 to review.

**Comment by mslarae13** [comment]
> [@mslarae13](https://github.com/mslarae13) I think this issue is pretty much done but I wanted to check one thing with you. Right now the server repo front end isn't set up to take multiple values but the slot is multivalued in the mongo database. Should we update that? The PR on the runtime isn't merged in yet, so that's a small change to that as well if we allow for multiple values in the front end.

@JamesTessmer can you take a look in mongo or postgres and tell me if the field is a string & if there are any studies that have funding sourced multivalued?
I suspect this one might be: https://data.microbiomedata.org/details/study/nmdc:sty-11-5tgfr349 
But, not 100% sure how it's actually captured.

That said I'd like @pkalita-lbl to chime in from the perspective of the ingest.
Currently it's 1 text box. If they separate funding sources with a ; can you split out the multiple funding sources? Do we care to?
Or, should we have like a + button to add multiple funding sources?

**Comment by pkalita-lbl** [comment]
> can you take a look in mongo or postgres and tell me if the field is a string

In MongoDB it is an array of strings (as `nmdc-schema` [dictates](https://microbiomedata.github.io/nmdc-schema/Study/)). When data is ingested from MongoDB into the data portal's Postgres database, they are still stored as an array of strings.

The changes in https://github.com/microbiomedata/nmdc-server/pull/1323 store a study's funding source (singular) in a _submission_ as a single string. When the submission is brought into MongoDB (the changes in https://github.com/microbiomedata/nmdc-runtime/pull/627) that single string is converted into an array with a single element.

> if there are any studies that have funding sourced multivalued?

Yes, in the prod data portal all of these have multiple funding sources

```
nmdc:sty-11-547rwq94
nmdc:sty-11-t91cwb40
nmdc:sty-11-e4yb9z58
nmdc:sty-11-5tgfr349
nmdc:sty-11-5bgrvr62
nmdc:sty-11-db67n062
nmdc:sty-11-8xdqsn54
nmdc:sty-11-076c9980
```

> Currently it's 1 text box. If they separate funding sources with a ; can you split out the multiple funding sources?

Technically yes, but IMO let's not do that. See below.

> Do we care to?

I think that's what we're asking the product owner to weigh in on 😁 

> should we have like a + button to add multiple funding sources?

If the answer to the "do we care to" question is "yes", then, yeah, we should implement the UI this way.

**Comment by JamesTessmer** [comment]
Yeah, I think if we care to capture multiple values for funding we can refactor the text box to something that will accept multiple values.

**Comment by JamesTessmer** [comment]
Here is the PR for updating the funding source front end https://github.com/microbiomedata/nmdc-server/pull/1345

**Comment by mslarae13** [comment]
Discussed at the infra sync meeting.

Add ability to add another funding request like how contributors works 
- Add a "+ Add Funding Source" button that makes another text box pop up

In the same PR that is being used to add an example link

**Comment by mslarae13** [comment]
Created this issue for how funding source is displayed. 
-  https://github.com/microbiomedata/issues/issues/833 

Will not be part of this work.
