### ISSUE TITLE
add link to submission portal user guide to the submission portal

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#239]
We'd like to add a link to the submission portal user guide to the submission portal.

See below, can we add this link
https://nmdc-documentation.readthedocs.io/en/latest/howto_guides/submit2nmdc.html 

to this spot
![Screen Shot 2023-05-09 at 7 45 06 PM](https://github.com/microbiomedata/issues/assets/44581429/1fbc3821-4638-4f6b-8dd2-bee47b1226f6)

Can we also add it to each sequential page?
![Screen Shot 2023-05-09 at 7 45 24 PM](https://github.com/microbiomedata/issues/assets/44581429/a57249cb-19f1-4adb-889f-7651db8be41a)

**Comment by ssarrafan** [comment]
Appears to be linked to a PR so will move to next sprint.
@naglepuff @mslarae13

**Comment by mslarae13** [comment]
@naglepuff  how is this going?
When this is pushed to prod, can we make sure https://github.com/microbiomedata/nmdc-server/issues/820 is also pushed?

**Comment by naglepuff** [comment]
@mslarae13 this should be in dev soon (if you don't see it now, give it like 5-10 minutes). The linked issue should be fixed by the next push to prod as well. Let me know if the documentation links are satisfactory
