### ISSUE TITLE
Create NMDC Conference Pamphlet

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#24]
This issue is to track the creation of the NMDC conference pamphlet. Originally captured in [this issue]([Create new NMDC conference pamphlet](https://github.com/microbiomedata/NMDC_Planning/issues/256)).

**Comment by iockert** [comment]
working canva design: https://www.canva.com/design/DAFRlCnd1ZA/scBk86TyPV6BixzvA61gHw/edit

**Comment by iockert** [comment]
pamphlet copy https://docs.google.com/document/d/11W5B77cYa8Vm5Aiuc8D2SI1k0TtpNIxz9EO5Bj078zA/edit

**Comment by iockert** [comment]
We have a first draft of the pamphlet. Currently taking comments/edits from the team: 

[NMDC_Pamphlet_112022 (7).pdf](https://github.com/microbiomedata/issues/files/10118174/NMDC_Pamphlet_112022.7.pdf)

**Comment by ssarrafan** [comment]
Great job on the draft of the pamphlet @iockert. I'll close this issue.

**Comment by iockert** [comment]
Great, thank you!
