### ISSUE TITLE
Identify priorities for UR/UT for products and outline broader timeline

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#241]
- [ ] Identify priorities from GSP
- [ ] Identify priorities from surveys
- [ ] Identify..
- [ ]

**Comment by mslarae13** [comment]
@ssarrafan looks like this is last years GSP? Should we consider thie OBE? 
And replaced with other issues?

**Comment by ssarrafan** [comment]
Thanks @mslarae13 I can close this one.  I think this may have been a draft issue when I was meeting with Leah last year.
