### ISSUE TITLE
slot altitude is not relevant for soil. Only elevation

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#242]
Altitude should not be in the soil package (or sediment, or water). We should remove this as to avoid confusion

Criteria for completion

- [ ] Update sheets to ignore or remove altitude.
- [ ] Push update to schema
- [ ] Push update to submission portal
- [ ] Test and confirm submission portal has been updated

**Comment by pkalita-lbl** [comment]
Schema changes are in. Once we release a new version of `submission-schema` we'll need to bring it into `nmdc-server`.

**Comment by ssarrafan** [comment]
Moving to next sprint per @pkalita-lbl

**Comment by pkalita-lbl** [comment]
This is still paused waiting for a new `submission-schema` release.

**Comment by pkalita-lbl** [comment]
This change is now on https://data-dev.microbiomedata.org/
