### ISSUE TITLE
Identify EMSL NEON projects & provide FAIR metadata

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#243]
**Deliverable this task is associated with**
- 4
- See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing 

**RACI**

_Tag people in their roles_
- Responsible: @bmeluch 
- Accountable: @mslarae13 
- Consulted: 
- Informed:

**Describe the the task?**
- [x] Identify EMSL projects with NEON data
- [x] Sort out NMDC relevant data types
- [x] #367
- [x] #370
- [x] #371
- [x] #372
- [x] #373
- [x] #374
- [ ] #375
- [ ] Develop standardized and FAIR metadata

**Criteria for completion**
- NEON data and biosamples have been identified, made FAIR, and are ready for ingest & workflow analysis.

**Estimate people time**
- 1 person, 40 hours

**Completion Date (Goal)**
- June 9th

**Target Sprint Start & End Dates**
- Start: June 5
- End: June 16

**Tag Blocker/Contingent upon isues**
- N/A

**Comment by ssarrafan** [comment]
@bmeluch I'll move this to the new sprint as you just changed the status. Let me know if it would be helpful to break this up into smaller GH issues.

**Comment by bmeluch** [comment]
Projects identified and prioritized (EMSL project codes, searchable here: https://search.emsl.pnnl.gov/)

49247: Some metadata available - difficulty 2/3

50267: Most metadata available - difficulty 2 - high priority

50684: Little metadata available - difficulty 5 - low priority

50718: Most metadata available - difficulty 1 - high priority

51026: Most complex study design - difficulty 5 - low priority

60009: Study not closed - postpone

**Comment by ssarrafan** [comment]
Appears to still be active. Moving to next sprint.

**Comment by ssarrafan** [comment]
@bmeluch @mslarae13 should this one be moved to the next sprint?  Are you still actively working on this?

**Comment by bmeluch** [comment]
Still actively working on this, we will discuss breaking this up into smaller tasks.

**Comment by mslarae13** [comment]
@bmeluch if you do break this into smaller tasks, we can split out the 2 you're working on for ESA, put then in the NEON board. and backlog this one for when we're ready to tackle the rest of the projects.

**Comment by ssarrafan** [comment]
@bmeluch @mslarae13 was this issue broken down into smaller tasks?  Can this one be closed?

**Comment by mslarae13** [comment]
@ssarrafan Bea was working on that before she left. Not sure if it got finished.
I don't think we'll close this one. We'll leave it as the parent issue, and use for tracking the additional projects that aren't ESA priority. so it can come out of the sprint

**Comment by bmeluch** [comment]
Finished creating the sub issues and marked them as either in progress or backlogged for post ESA

**Comment by bmeluch** [comment]
Closing, reopen 
1) if we ever hear back from PIs on the grayed out studies 
2) next year when 60009 is publicly available
