### ISSUE TITLE
Ingest EMSL NEON biosamples & process NOM data

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#244]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 4 & 5

**RACI**

_Tag people in their roles_
- Responsible: @corilo (or @bmeluch ?)
- Accountable: @corilo 
- Consulted:
- Informed: @mslarae13 @aclum 

**Describe the the task?**
- [ ] Create NEON biosamples
- [ ] Process FTICR NOM data via NMDC workflows

**Criteria for completion**
- All NEON NOM data has been processed and is ready for ingest into postgres and MongoDB

**Estimate people time**
- 1 person, 8 hrs?

**Completion Date (Goal)**
- June 30

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon isues**
- #235

**Comment by aclum** [comment]
@mslarae13 @bmeluch Okay to close this?

**Comment by bmeluch** [comment]
We have data for one project that still needs to go through FTICR NOM workflow/biosample creation/ingest

**Comment by aclum** [comment]
Is that blocked on anything?

**Comment by mslarae13** [comment]
I think just time? @bmeluch can we check in with Yuri on this next week

**Comment by aclum** [comment]
@corilo to do this this week or in early January, hopefully will cross train @bmeluch

**Comment by mslarae13** [comment]
@corilo Mid January 2024 goal

**Comment by aclum** [comment]
@lamccue  let us know if this should get moved to the next sprint or backlogged.

**Comment by ssarrafan** [comment]
Moving to the backlog but @lamccue let me know if it should stay active for the next sprint.

**Comment by lamccue** [comment]
let's add this to the next sprint. I actually talked with @corilo about this today, and it is on his list to do by the end of the next sprint. @bmeluch you may want to point Yuri to the metadata again so he doesn't have to dig through his inbox.

**Comment by aclum** [comment]
Moving to the next sprint, this is a target for GSP. cc @mslarae13 
Montana could you include what project this was supposed to be for. NOM datasets were processed for Lybrand and SanClements several months ago

**Comment by bmeluch** [comment]
This is the second half of Lybrand's project, we wanted to get as much as we could in the first round but they had more metadata to track down for the rest of the samples so it's in 2 parts.

**Comment by mslarae13** [comment]
Complete! Good work team!
Data is in production
