### ISSUE TITLE
Provide EMSL link for NEON studies

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#245]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 4, 5, 7

**RACI**

_Tag people in their roles_
- Responsible: @bmeluch 
- Accountable: @mslarae13 
- Consulted:
- Informed:

**Describe the the task?**
- [ ] Provide links to each study from EMSL with NEON data (example: https://www.emsl.pnnl.gov/project/51541)

**Criteria for completion**
- Links have been provided for NEON studies

**Estimate people time**
- 

**Completion Date (Goal)**
- June 23

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon isues**
- #235

**Comment by bmeluch** [comment]
Project links are included in study page information as the study pages go up, and data file links are included in the metadata file sent to Yuri. Do project links need to be provided somewhere else as well?

**Comment by bmeluch** [comment]
EMSL proposal page and award DOI links are included in each study page, this no longer needs to be a separate issue
