### ISSUE TITLE
Define environmental triad for NEON soil samples

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#246]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

1

**RACI**

_Tag people in their roles_
- Responsible: @aclum 
- Accountable: @aclum 
- Consulted: @turbomam , Hugh
- Informed:

**Describe the the task?**
- [x] NEON samples soil need the environmental triad defined

Information will be added to mongo via Sujay's ingest code

**Criteria for completion**
- Environmental triad are defined for  NEON soil biosamples. At a minimum at the site level, plot level is preferable. 

**Estimate people time**
- 

**Completion Date (Goal)**
- June 16

**Target Sprint Start & End Dates**
- Start: conversations are already in progress
- End: June 16

**Tag Blocker/Contingent upon issues**
-

**Comment by aclum** [comment]
Meeting w/Mark, Hugh, Alicia. We are using terrestrial biome for broad scale, soil for environmental medium and will use a mapping by mark from nlcdClass from *sls_soilCoreCollection*csv to envo ontology. This defines terms at a sample level.

**Comment by aclum** [comment]
@turbomam added a mapping file the schema which maps from nlcdClass from sls_soilCoreCollectioncsv to the corresponding envo term
https://github.com/microbiomedata/nmdc-schema/blob/main/assets/neon_mixs_env_triad_mappings/neon-nlcd-local-broad-mappings.tsv

env_broad_scale -> "terrestrial biome" [ENVO:00000446]
env_local_scale -> use neon-nlcd-local-broad-mappings.tsv lookup 
env_medium -> "soil" [ENVO:00001998]
