### ISSUE TITLE
do we have a nmdc-schema, submission-schema, data portal & API synchronized, automated release policy

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/issues#248]
@pkalita-lbl I know you have asked for this to
- be more formal
- and to be run ASAP

Do we have other issues about it yet?

Do you have ideas about automating it?

@sujaypatil96, @aclum and I just added some content to the nmdc-schema

cc @shreddd

**Comment by ssarrafan** [comment]
@shreddd tagging issues related to releases with a release management flag

**Comment by ssarrafan** [comment]
@turbomam @pkalita-lbl can this issue be closed?

**Comment by pkalita-lbl** [comment]
I don't see any specific action items here. Closing.
