### ISSUE TITLE
Website revamp - Landing Page

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#25]
This issue is focused on updating the Landing Page on the NMDC website.  Steps include:

- [x] mock up new landing page
- [x] get feedback on mock ups (from NMDC team, champions, ambassadors?)
- [ ] update landing page in test
- [ ] update based on feedback
- [ ] deploy to production

**Comment by iockert** [comment]
Have talked with CSO about optimizing hero image. Will talk to developer on Friday.

**Comment by pkalita-lbl** [comment]
Update of where we are to date:

* We have mockups for the first round of changes to the home page we'd like to see. They have been reviewed and approved by members of the engagement team.
* @iockert has been working on making any updates allowed by the WordPress Admin interface 
* Other updates require updates to the WordPress theme itself. This is complicated by the fact that the NMDC WordPress site is part of a multi-site instance (along with other sites including https://www.kbase.us/, https://ecopods.lbl.gov/, and others). @shreddd is now an admin at the multi-site level and we have read-only access to the hosting server. However we're still working to understand the right development workflow for making theme changes.
* In the meantime, Yeongshnn Ong (from @shreddd's group) helped in finding a workaround that allows making some of the important homepage changes without underlying theme changes.

Next steps:

* Get feedback on the proposed home page changes currently implemented on a test page. Make changes based on feedback and deploy to main home page.
* Continue to work on understanding how to do development on our WordPress site

**Comment by ssarrafan** [comment]
I'll move this issue to the next sprint to get feedback. @pkalita-lbl @iockert  let me know if you'd prefer a new issue instead.

**Comment by pkalita-lbl** [comment]
Thanks! I think keeping this one open for now is fine

**Comment by pkalita-lbl** [comment]
Just recording the current next steps here:

* @iockert and I will be meeting at 9 AM Pacific on Monday Dec 19 and we'll move the new product links from https://microbiomedata.org/testtesttest/ to https://microbiomedata.org and rearrange the existing sections as needed.
* Creative service is working on preparing a new hero image (the background image under "An open and integrative data science system"). It likely won't be ready until the first week of the new year. I'll be out of the office Jan 5 - 10, but I'll make sure that @iockert is able to do that update in my absence.

**Comment by ssarrafan** [comment]
@iockert said to continue this to the next sprint. Moving to January.

**Comment by iockert** [comment]
We have finished this deliverable! Updated the hero image on Jan 6.
