### ISSUE TITLE
create a Postgres database in SPIN with our relational version of NCBI's biosample_set

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/issues#256]

**Comment by aclum** [comment]
@turbomam  can this be closed? I believe this is complete.

**Comment by turbomam** [comment]
Yes, BBOP's currently maintained dumps of NCBI Biosamples are MongoDB and DuckDB

- https://github.com/microbiomedata/external-metadata-awareness/blob/main/Makefiles/ncbi_metadata.Makefile
- https://portal.nersc.gov/project/m3408/biosamples_duckdb/

```shell
ssh -L27777:mongo-ncbi-loadbalancer.mam.production.svc.spin.nersc.org:27017 \
  -o ServerAliveInterval=60 {YOUR_NERSC_USERNAME}@dtn01.nersc.gov
```

```
mongodb://ncbi_reader:register_manatee_coach78@localhost:27777/?directConnection=true&authMechanism=DEFAULT&authSource=admin
```
