### ISSUE TITLE
keep GH actions components up to date in nmdc-schema and submisson-schema

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/issues#257]
`Build and test nmdc-schema` from `.github/workflows/main.yaml`

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Is this something that I could be taught to do?

**Comment by pkalita-lbl** [comment]
Not sure what repo this is happening in so I might need to pass this one back to you. The error message itself pretty much tells you everything you need to know:

> Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2.

We can't update those 3rd party actions themselves, so the next best thing would be to update our workflow files to specify the latest major version (e.g. `actions/checkout@v3`). If the warning persists after that there's not much we can do until the author of the action fixes it.

**Comment by mslarae13** [comment]
Nearing a year old. Status? Still planned? OBE?
@pkalita-lbl , @turbomam 

Is submission-schema relevant? Or is it really about nmdc-schema?

**Comment by pkalita-lbl** [comment]
This is just routine maintenance that needs to be done in the `nmdc-schema` repo, the `submission-schema` repo, and _all_ of our other repos that use GitHub Actions (which is probably most if not all of them). The standard operating procedure should be that if you're touching a workflow file, go ahead and check to see if it's using any 3rd party actions that need updating.

We could use this issue to do a sweep of the workflows in `nmdc-schema` and `submission-schema`, but in general I don't think we need specific issues for this kind of work. So I also wouldn't object to just closing this one and dealing with the warning as part of the due course of development.

**Comment by mslarae13** [comment]
I agree, long running / routine issues should probably be made and closed as they're accomplished for appropriate tracking.
