### ISSUE TITLE
consider generalizing dna... and rna... specific slots

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/issues#258]
If processes and materials about DNA/metagenomics and RNA/metatranscriptomics are modeled separately, then they can reuse more general slots

cc @aclum @mslarae13 @anastasiyaprymolenna

**Comment by mslarae13** [comment]
I asked @pkalita-lbl about this in another issue. https://github.com/microbiomedata/nmdc-schema/issues/1107#issuecomment-1876161072 

In short, no, because the slots map back to biosamples right now & we'd end up with 2 values for 1 slot.
