### ISSUE TITLE
schema sync v7.7

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#260]
**RACI**

- Responsible: @dwinston @pkalita-lbl @naglepuff @turbomam 
- Accountable: @shreddd 
- Consulted: @aclum 
- Informed: @aclum 

**Describe the task?**
- [x] tagged release version of nmdc-schema (Mark)
- [x] Capture schema changes that need to be reflected in MongoDB (Mark)
- [x] Script to migrate Mongo Collections to reflect Schema Updates (Mark / Donny)
- [x] Test above script in local env (Eric, Donny)
- [x] Run script in Dev (Donny)
- [x] runtime API uses new tagged release version of the schema (Donny)
- [x] Data portal ingest of new data with new schema (Mike)
- [x] Data portal updates to use new tagged release version of the schema (Mike)
- [x] submission-schema updates to released version of nmdc-schema - optional this time (Patrick)
- [ ] nmdc-server use submission-schema version 7.7 (Mike)

**Criteria for completion**
- Changesheets:submit API endpoint can be used to add GNSP and JGI genome portal study identifiers to study_set
- successful data portal dev ingest

**Estimate people time**

**Completion Date (Goal)**
- June 2

**Target Sprint Start & End Dates**
- Start: May 22
- End: June 2

**Tag Blocker/Contingent upon issues**
https://github.com/microbiomedata/nmdc-schema/issues/868

**Comment by aclum** [comment]
@turbomam  let us know how 'capture schema changes that need to be reflected in MongoDB' is coming along

**Comment by ssarrafan** [comment]
Appears to be active so will move to the next sprint. 
Timeline/dates need to be adjusted.

**Comment by ssarrafan** [comment]
@dwinston @naglepuff  should I keep this issue open for next sprint for the outstanding checkboxes?

**Comment by dwinston** [comment]
The new-schema data does indeed need to make it "all the way" to the data portal, so sure, keep open. Perhaps also add @marySalvi on this?

**Comment by aclum** [comment]
@pkalita-lbl are you updating submission-schema to nmdc-schema 7.7 or should we remove this task?

**Comment by pkalita-lbl** [comment]
@turbomam already made a submission-schema release based on nmdc-schema@7.7.1: https://github.com/microbiomedata/submission-schema/releases/tag/v7.7.1. That version still needs to be brought into nmdc-server (although I'm not totally sure if anything between 7.6.5 and 7.7.1 affects anything in the submission portal)

**Comment by ssarrafan** [comment]
@turbomam @dwinston are you planning to complete this by tomorrow?  Or should it be moved to the next sprint?

**Comment by aclum** [comment]
There part is done for this. We are waiting on the data portal ingest code to be updated.

**Comment by naglepuff** [comment]
microbiomedata/nmdc-server#991

Hopefully this is wrapped up early next week

**Comment by aclum** [comment]
postgres dev and data portal dev are up to 7.7 as of today!

**Comment by ssarrafan** [comment]
Closing this issue based on last comment. Assuming 7.7 will in prod with Monday's ingest by @marySalvi
