### ISSUE TITLE
schema sync for NEON

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#261]
RACI

Responsible: @dwinston @pkalita-lbl @naglepuff @turbomam
Accountable: @shreddd
Consulted: @aclum
Informed: @aclum, @Michal-Babins 

Describe the task?
- [ ] tagged release version of nmdc-schema (Mark)
- [ ] runtime API uses new tagged release version of the schema (Donny)
- [ ]  Data portal uses new tagged release version of the schema (Mike)
- [ ] submission-schema updates to released version of nmdc-schema - optional this time? (Patrick)

Criteria for completion

json:submit API endpoint can be used to add NEON json records for a variety of Database types (biosample_set, extraction_set, data_object_set)
successful data portal dev ingest

Estimate people time

Completion Date (Goal)

June 21
Target Sprint Start & End Dates

Start: June 19
End: June 30

Tag Blocker/Contingent upon issues
Contingent upon schema updates for NEON
https://github.com/microbiomedata/nmdc-schema/issues/908
https://github.com/microbiomedata/nmdc-schema/issues/886
https://github.com/microbiomedata/nmdc-schema/issues/908

**Comment by ssarrafan** [comment]
@aclum is this still a backlog item?  Or should it be in the next sprint?
