### ISSUE TITLE
Map NMDC terms to NEON for ingest - soil

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#262]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 1

**RACI**

_Tag people in their roles_
- Responsible: @bmeluch, @aclum 
- Accountable: @sujaypatil96 
- Consulted: @mslarae13, 
- Informed:

**Describe the the task?**
- [x] map NMDC csv fields from the soil chemical and physical properties, periodic (DP1.10086.001) to nmdc schema classes/slots (Bea/Brynn)
- [x] map NMDC csv fields from the soil metagenome sequences to nmdc schema (DP1.10107.001) (Alicia)

**Criteria for completion**
- TSV or TBD file format which Sujay can use for his ingest code

**Estimate people time**
- 

**Completion Date (Goal)**
- June 9

**Target Sprint Start & End Dates**
- Start: May 22
- End: June 16

**Tag Blocker/Contingent upon issues**
- work to map DP1.10107.001 depends on a new released version of nmdc schema for NEON containing the process modeling (subtask of https://github.com/microbiomedata/issues/issues/261)

**Comment by aclum** [comment]
@sujaypatil96  please let us know what format type you need the mapping information in.

**Comment by ssarrafan** [comment]
Appears to be in progress, moving to new sprint

**Comment by bmeluch** [comment]
https://github.com/microbiomedata/nmdc-schema/issues/928

**Comment by ssarrafan** [comment]
@bmeluch let me know if I can help getting this reviewed by the appropriate team members.

**Comment by bmeluch** [comment]
thank you @ssarrafan ! @brynnz22 and I are working with @sujaypatil96 and @turbomam on final bits of formatting so it is well on its way

**Comment by ssarrafan** [comment]
Appears to be active so will move to the next sprint. 
Timeline/dates needs to be updated.

**Comment by aclum** [comment]
This is done, if there is more mapping to be done @sujaypatil96  will add directly based on iterations on his ingest code.
