### ISSUE TITLE
Ingest NEON soil biosamples

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#263]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 1

**RACI**

_Tag people in their roles_
- Responsible: @sujaypatil96 
- Accountable: @turbomam 
- Consulted: @aclum 
- Informed: @aclum 

**Describe the the task?**
- [x] delete existing NEON biosamples that were ingested for GSP. These represent the pooled samples and will be replaced with our new records.
- [x] Ingest new NEON biosamples and metadata for soil metagenomes using [data release version RELEASE-2023](https://data.neonscience.org/data-products/DP1.10107.001/RELEASE-2023) 
- [x] ingest NEON biosamples and metadata for soil metagenome generated from JGI proposal ID 509462/ GOLD study ID Gs0161344

The existing NMDC study page for this should be used, nmdc study id nmdc:sty-11-34xj1150

**Criteria for completion**
- Records exist in prod mongo for ~400 NEON soil biosamples (1-3 biosamples per 1 processed sample)

**Estimate people time**

**Completion Date (Goal)**
-  June 30

**Target Sprint Start & End Dates**
- Start: June 19
- End: June 30 

**Tag Blocker/Contingent upon isues**
https://github.com/microbiomedata/nmdc-runtime/issues/249

**Comment by sujaypatil96** [comment]
Changesheet to delete 493 NEON biosample records ingested for GSP have been deleted.

**Comment by ssarrafan** [comment]
@sujaypatil96 assuming based on your last comment that this issue can be closed?  Can you please confirm?

**Comment by aclum** [comment]
This is not done

**Comment by ssarrafan** [comment]
Doesn't appear to be active. Will remove from sprint and add to backlog.

**Comment by aclum** [comment]
@sujaypatil96 are you working on the JGI NEON data this sprint?

**Comment by aclum** [comment]
@sujaypatil96 is working on the neon/jgi hybrid code this sprint. Feedback on the json shared over slack 8/15
biosample_set
- missing geo_loc_name
- missing [gold_biosample_identifiers](https://microbiomedata.github.io/nmdc-schema/gold_biosample_identifiers/)
- missing [img_identifiers](https://microbiomedata.github.io/nmdc-schema/img_identifiers/)
- missing [biosample_categories](https://microbiomedata.github.io/nmdc-schema/biosample_categories/), enum should be NEON
- missing analysis_type
- depth slot incorrectly labeled as temp
library_preparation_set
-missing library_type
-value for id uses the wrong prefix (Mark)
extraction_set
-missing extraction_target
omics_processing_set
-missing instrument_name
-missing omics_type
-missing gold_sequencing_project_identifiers

**Comment by sujaypatil96** [comment]
@aclum would you mind converting the bullet points in the above comment to checklist items?

**Comment by sujaypatil96** [comment]
* The analysis_type comes from _sequenceAnalysisType_ column in NEON mms_metagenomeDnaExtraction table
* The instrument_name comes from _sequencingMethod_ column in NEON mms_metagenomeSequencing table
* The omics_type comes from _investigation_type_ column in NEON mms_metagenomeSequencing table

We don't have data in any of the above tables since the samples were sequenced at JGI.

**Comment by aclum** [comment]
Correct, you'll need to get this info from GOLD API info like you do for the GOLD only pipeline.

**Comment by sujaypatil96** [comment]
Sure! That makes sense.

So from the GOLD API, we can get:
* analysis_type from sequencingStrategy
* instrument_name from seqMethod
* omics_type from sequencingStrategy

**Comment by ssarrafan** [comment]
@dwinston @mbthornton-lbl can you review this early next week so we can close this issue out.  
See related PR: https://github.com/microbiomedata/nmdc-runtime/pull/251

**Comment by mbthornton-lbl** [comment]
The CC's for this ticket:

_Criteria for completion

    Records exist in prod mongo for ~400 NEON soil biosamples (1-3 biosamples per 1 processed sample)_

Would be satisfied after:

 - running Translator ingestion job from https://github.com/microbiomedata/nmdc-runtime/pull/251
 - spinning dev to prod
 -

**Comment by aclum** [comment]
The records are in mongo prod, we are waiting until Tuesday's NEON meeting to close this out. There is one outstanding item, attaching GOLD metadata to the ~1/3 biosamples that also exist in GOLD, that I will spin out into a separate ticket.

**Comment by aclum** [comment]
@sujaypatil96 there is a bug where biosamples that were sequenced at JGI and are from site TEAK did not get geo_loc_name populated. Would you please take a look? cc @mbthornton-lbl 
below are the biosample_set records
id name
nmdc:bsm-11-rq5m5b31 | TEAK_043-M-8-35.5-20210719
nmdc:bsm-11-6y9njc55 | TEAK_043-M-6.5-2-20210719
nmdc:bsm-11-sst52782 | TEAK_043-M-24.5-34.5-20210719
nmdc:bsm-11-41mb3v03 | TEAK_002-O-9-6-20210720
nmdc:bsm-11-e1a4ak09 | TEAK_003-M-39.5-18.5-20210726
nmdc:bsm-11-vp774955 | TEAK_003-M-37.5-22-20210726
nmdc:bsm-11-ybjxp741 | TEAK_003-M-6.5-5-20210726
nmdc:bsm-11-9dcapv51 | TEAK_025-M-31.5-36.5-20210726
nmdc:bsm-11-agtswv81 | TEAK_025-M-4-27-20210726
nmdc:bsm-11-6xj1cf98 | TEAK_025-M-23.5-6.5-20210726
nmdc:bsm-11-wgm02866 | TEAK_004-M-18.5-32-20210726
nmdc:bsm-11-27za2f92 | TEAK_004-M-28.5-30-20210726
nmdc:bsm-11-zecyq208 | TEAK_004-M-29.5-4.5-20210726
nmdc:bsm-11-35fd3c55 | TEAK_004-O-29.5-4.5-20210726
nmdc:bsm-11-2qcn8345 | TEAK_005-M-7-4.5-20210728
nmdc:bsm-11-fbnqqk80 | TEAK_005-M-32.5-17.5-20210728
nmdc:bsm-11-gw17nt08 | TEAK_005-M-0.5-28-20210728
nmdc:bsm-11-hew13816 | TEAK_005-O-7-4.5-20210728

**Comment by aclum** [comment]
also @sujaypatil96 in some cases the processed sample names are duplicated, we should figure out how to make the names unique. Ie ABBY_001-M-20170607-COMP-DNA1 used for processed_sample_set ids nmdc:procsm-11-dha8mw20 and nmdc:procsm-11-yn6j8q60
