### ISSUE TITLE
Migrate workloads in `nmdc-dev` namespace from `development` to `production` cluster (on Spin)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#267]
Migrate nmdc-dev instance to Spin Production cluster (working with Donny)

---

Workloads migrated so far:

#### The "`nmdc-runtime`-related" workloads:

- [x] `dagster-daemon`
- [x] `dagster-dagit`
- [x] `dagster-postgresql`
- [x] `mongo`
- [x] `runtime-api`

#### The "`nmdc-server`-related" workloads:

- [x] `backend` (nmdc-server/server)
- [x] `data` (nginx)
- [x] `db` (postgres)
- [x] `frontend` (nmdc-server/client)
- [x] `redis` (redis)
- [x] `worker` (nmdc-server/worker)

**Comment by eecavanna** [comment]
We plan to perform the migration during the week of June 19-23.

**Comment by ssarrafan** [comment]
> We plan to perform the migration during the week of June 19-23.

I will move this issue to the next sprint.

**Comment by ssarrafan** [comment]
@eecavanna can this issue be closed?  I believe this is done correct?

**Comment by eecavanna** [comment]
Hi @ssarrafan, 

It's only partially done. We migrated the `nmdc-runtime`-related workloads to the production cluster, but we haven't yet migrated the `nmdc-server`-related workloads to the production cluster (those are still running on the development cluster).

Some paths forward regarding this ticket:

1. I could update the title of this ticket to be about the `nmdc-runtime`-related workloads only, and then close the ticket and create a new ticket for the `nmdc-server`-related workloads, which would be a "todo" for next sprint.

2. Or, I could add a two-item checklist to the description of this ticket (one for `nmdc-runtime`, which would be marked as done; and one for `nmdc-server`, which would not) and then move this ticket (still open) to the next sprint.

Do you have a preference?

**Comment by eecavanna** [comment]
I added a checklist of the workloads to the description of this ticket, which made it so GitHub shows the number of "tasks" completed within the ticket (currently 5 completed out of 11). I'll move the ticket to the next sprint.

I plan to work on migrating the remaining 6 workloads next week (week of July 3).

**Comment by ssarrafan** [comment]
@eecavanna assuming from infra sync meeting today that this issue can be closed. Can you confirm?

**Comment by eecavanna** [comment]
Yes, this Issue can be closed. I'll create smaller Issues for any clean up tasks that arise.

CC: @shreddd
