### ISSUE TITLE
Do we really have MORE than two databases?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/issues#268]
- Kitware/Portal Postgres
- MongoDB
- runtime MongoDB ?
- runtime Terminus ?
- runtime Postgres ?

I'd like to learn moren about that

**Comment by dwinston** [comment]
the runtime has config for a terminus db, but it's unused.

the runtime uses a single mongodb deployment for NMDC schema stuff as well as runtime bookkeeping. there is no separate mongodb deployment.

the runtime dagster deployment has its own internal postgres, managed and used entirely by dagster for its internal bookkeeping.

**Comment by turbomam** [comment]
Unless other people want to weigh in, I can close this as resolved
