### ISSUE TITLE
NEON - map NEON fields to NMDC slots for surface water

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#271]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 2

**RACI**

_Tag people in their roles_
- Responsible: @bmeluch, @brynnz22 
- Accountable: @sujaypatil96 
- Consulted: @mslarae13, 
- Informed:

**Describe the the task?**
- [ ] map NMDC csv fields from the Surface water microbe metagenome sequences (DP1.20281.001) to nmdc schema classes/slots 
see https://github.com/microbiomedata/issues/issues/270 for plan for surface water samples.

**Criteria for completion**
- TSV file format which Sujay can use for his ingest code is in the main branch of nmdc-schema under assets 

**Estimate people time**
- 

**Completion Date (Goal)**
- June 16

**Target Sprint Start & End Dates**
- Start: June 5
- End: June 16

**Tag Blocker/Contingent upon issues**
This should come after the mapping of the soil terms is complete since that is higher priority.

**Comment by ssarrafan** [comment]
Updated to In Progress 2 days ago so will assume it's being actively worked on. Moving to next sprint.
