### ISSUE TITLE
NEON to nmdc term mapping - benthic metagenomes

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#272]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 3

**RACI**

_Tag people in their roles_
- Responsible: @bmeluch @brynnz22 
- Accountable: @sujaypatil96 
- Consulted: @turbomam, @aclum, @mslarae13 
- Informed:

**Describe the the task?**
- [x] map NMDC csv fields from the Benthic microbe metagenome sequences (DP1.20279.001) to nmdc schema classes/slots

Field names have been standardized with Darwin Core terms (http://rs.tdwg.org/dwc/; accessed 12 Au‐
gust 2017), the Global Biodiversity Information Facility vocabularies (http://rs.gbif.org/vocabulary/gbif/;
accessed 12 August 2017), the VegCore data dictionary (https://projects.nceas.ucsb.edu/nceas/projects/
bien/wiki/VegCore; accessed 12 August 2017), where applicable.

[User guide for this product](https://data.neonscience.org/documents/-/document_library_display/kV4WWrbEEM2s/view_file/3272497?_110_INSTANCE_kV4WWrbEEM2s_redirect=https%3A%2F%2Fdata.neonscience.org%2Fdocuments%3Fp_p_id%3D110_INSTANCE_kV4WWrbEEM2s%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_110_INSTANCE_kV4WWrbEEM2s_redirect%3Dhttps%253A%252F%252Fdata.neonscience.org%252Fdocuments%253Fp_p_id%253D110_INSTANCE_kV4WWrbEEM2s%2526p_p_lifecycle%253D0%2526p_p_state%253Dnormal%2526p_p_mode%253Dview%2526p_p_col_id%253Dcolumn-1%2526p_p_col_count%253D1%26_110_INSTANCE_kV4WWrbEEM2s_searchFolderId%3D0%26_110_INSTANCE_kV4WWrbEEM2s_breadcrumbsFolderId%3D11098%26_110_INSTANCE_kV4WWrbEEM2s_keywords%3DNEON_benMicrobeField_userGuide_vC%26_110_INSTANCE_kV4WWrbEEM2s_formDate%3D1686266133768%26_110_INSTANCE_kV4WWrbEEM2s_repositoryId%3D10179%26_110_INSTANCE_kV4WWrbEEM2s_struts_action%3D%252Fdocument_library_display%252Fsearch%26_110_INSTANCE_kV4WWrbEEM2s_folderId%3D11098%26_110_INSTANCE_kV4WWrbEEM2s_searchFolderIds%3D11098)

**Criteria for completion**
- tsv mapping document in assets in the nmdc-schema repo

**Estimate people time**
- 

**Completion Date (Goal)**
- June 23

**Target Sprint Start & End Dates**
- Start: June 19
- End: June 30

**Tag Blocker/Contingent upon issues**
-

**Comment by aclum** [comment]
@brynnz22 @bmeluch is this still in review?

**Comment by brynnz22** [comment]
This is done. I will close it!
