### ISSUE TITLE
Define environmental terms for NEON benthic metagenome samples (DP1.20086.001)

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#274]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 3

**RACI**

_Tag people in their roles_
- Responsible: @aclum, Hugh, @turbomam 
- Accountable:@aclum
- Consulted: @mslarae13 
- Informed: @mslarae13, @sujaypatil96 

**Describe the the task?**
- [x] Determine plan to define environmental terms for benthic metagenome samples 

**Criteria for completion**
- A plan to define the environmental terms for benthic metagenome samples.

**Estimate people time**
- [Hours or days of people time. 1 person, 4 hours]

**Completion Date (Goal)**
- June 30

**Target Sprint Start & End Dates**
- Start: June 5
- End: June 30

**Tag Blocker/Contingent upon issues**
- https://github.com/EnvironmentOntology/envo/issues/1466

**Comment by aclum** [comment]
figure 14 from NEON.DOC.003044.vE, title AOS Protocol and Procedure: AMC – Aquatic Microbial Sampling
![image](https://github.com/microbiomedata/issues/assets/8196591/e75cab6b-7352-4a8e-bc9a-18f99fc3f756)

**Comment by aclum** [comment]
Notes from Hugh
For Broad scale, I believe it would be either “freshwater lake biome” [ENVO:01000252], or “freshwater river biome” [ENVO:01000253]. For surface samples, this would be derived from the “aquaticSiteType” field in the amc_fieldSuperParent table. For benthic samples, the “aquaticSiteType” field of the amb_fieldParent table. The variables of this field are: stream, lake, and river.
For benthic medium scale, the options are pretty clear. The “sampleMaterial” field in the amb_fieldParent table consists of three options: biofilm, sediment, and plant-associated. The corresponding envo terms would be: “biofilm”, [ENVO:00002034], “sediment”, [ENVO:00002007], and “environment associated with a plant part or small plant”, [ENVO:01001057].
For local scale, it is (of course) a little trickier. Benthics have a ‘habitatType’ field, with four variables: pool, riffle, run, and step pool. However, except for ‘riffle’, I could not find any good corresponding envo terms. The aquatic crew suggested “stream bed” [ENVO:00000383] as a catch-all for local scale for benthics (benthic samples are only collected from wadeable streams, so no lakes or big rivers).

**Comment by aclum** [comment]
envo issue to support stream terms https://github.com/EnvironmentOntology/envo/issues/1415 for env_local_scale

if that isn't resolved we'll use the following
##NEON_data_product NEON_table NEON_field NEON_value NMDC_Class NMDC_slot_name NMDC_slot_value
DP1.20279.001 amb_fieldParent aquaticSiteType stream Biosample env_broad_scale "freshwater river biome" [ENVO:01000253]
DP1.20279.001 amb_fieldParent aquaticSiteType stream Biosample env_local_scale “stream bed” [ENVO:00000383]
DP1.20279.001 amb_fieldParent sampleMaterial biofilm Biosample env_medium biofilm [ENVO:00002034]
DP1.20279.001 amb_fieldParent sampleMaterial plant-associated Biosample env_medium environment associated with a plant part or small plant [ENVO:01001057]
DP1.20279.001 amb_fieldParent sampleMaterial sediment Biosample env_medium sediment [ENVO:00002007]

**Comment by sujaypatil96** [comment]
> For Broad scale, I believe it would be either “freshwater lake biome” [ENVO:01000252], or “freshwater river biome” [ENVO:01000253].
The values that the aquaticSiteType column can take are _stream_, _lake_ and _river_. So it's pretty clear that when the values are lake and river the env_broad_scale would be "“freshwater lake biome” [ENVO:01000252]" and "freshwater river biome [ENVO:01000253]" respectively. What term should we use when the column value is _stream_?

CC: @aclum

**Comment by sujaypatil96** [comment]
Could we make a dictionary of term mappings for env_broad_scale, env_local_scale and env_medium?

Like, for env_broad_scale, we would have something like this:

```python
ENV_BROAD_SCALE_MAPPINGS = {
    "lake": {
        "term_id": "ENVO:01000252",
        "name: "freshwater lake biome",
     },
    "river": <fill-in>,
    "stream": <fill-in>
}
```

**Comment by cmungall** [comment]
![image](https://github.com/microbiomedata/issues/assets/50745/3d84c44e-86b5-4499-ae12-66991566aa6e)

It's not clear what it's intended here? Was this sampled from a part of a plant or from a stream?

**Comment by aclum** [comment]
@cmungall  see their sampling protocol linked https://data.neonscience.org/data-products/DP1.20279.001. These samples are microbes living on plants in streams

**Comment by turbomam** [comment]
MAM TODO: suggest an alternative `env_medium` mapping for Neon's "plant-associated" term **ASAP**. NMDC and Neon collaborated on this a while ago, but it doesn't satisfy the MIxS/EnvO guidance of "something that was displaced by sampling"

**Comment by turbomam** [comment]
We would expect to find something useful as a sibling to biofilm, ie a subClassOf [mass of biological material](https://www.ebi.ac.uk/ols4/ontologies/envo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FENVO_01000549?lang=en)

**Comment by turbomam** [comment]
@aclum @cmungall and friends: do you think it is incorrect to say that a [portion of plant tissue](https://www.ebi.ac.uk/ols4/ontologies/po/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPO_0009007?lang=en) was displaced from the environment in the course of collecting Neon "plant-associated" samples?

**Comment by aclum** [comment]
@turbomam It is correct to say that plants are displaced during sampling (see figure 14 above) the samples currently w/ an environmental medium of 'environment associated with a plant part or small plant' [ENVO:01001057] come from NEON aquatic sampling protocol C.6, from the workflow in fig 14 they 'select 1 plant species, clip 5 cm from specimen', samples are then frozen at -80 and sent to a lab for extraction.  Detailed protocol is [NEON.DOC.003044vE](https://data.neonscience.org/documents/-/document_library_display/kV4WWrbEEM2s/view_file/3237660?_110_INSTANCE_kV4WWrbEEM2s_redirect=https%3A%2F%2Fdata.neonscience.org%2Fdocuments%3Fp_p_id%3D110_INSTANCE_kV4WWrbEEM2s%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_110_INSTANCE_kV4WWrbEEM2s_redirect%3Dhttps%253A%252F%252Fdata.neonscience.org%252Fdocuments%253Fp_p_id%253D110_INSTANCE_kV4WWrbEEM2s%2526p_p_lifecycle%253D0%2526p_p_state%253Dnormal%2526p_p_mode%253Dview%2526p_p_col_id%253Dcolumn-1%2526p_p_col_count%253D1%26_110_INSTANCE_kV4WWrbEEM2s_breadcrumbsFolderId%3D11098%26_110_INSTANCE_kV4WWrbEEM2s_keywords%3DNEON.DOC.003044vE%26_110_INSTANCE_kV4WWrbEEM2s_formDate%3D1698777268483%26_110_INSTANCE_kV4WWrbEEM2s_repositoryId%3D10179%26_110_INSTANCE_kV4WWrbEEM2s_struts_action%3D%252Fdocument_library_display%252Fsearch%26_110_INSTANCE_kV4WWrbEEM2s_folderId%3D11098%26_110_INSTANCE_kV4WWrbEEM2s_searchFolderIds%3D11098). Then from the DNA extraction protocol ([BMI_dnaExtractionSOP_v7](https://data.neonscience.org/documents/-/document_library_display/kV4WWrbEEM2s/view_file/3300513?_110_INSTANCE_kV4WWrbEEM2s_redirect=https%3A%2F%2Fdata.neonscience.org%2Fdocuments%3Fp_p_id%3D110_INSTANCE_kV4WWrbEEM2s%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_110_INSTANCE_kV4WWrbEEM2s_redirect%3Dhttps%253A%252F%252Fdata.neonscience.org%252Fdocuments%253Fp_p_id%253D110_INSTANCE_kV4WWrbEEM2s%2526p_p_lifecycle%253D0%2526p_p_state%253Dnormal%2526p_p_mode%253Dview%2526p_p_col_id%253Dcolumn-1%2526p_p_col_count%253D1%26_110_INSTANCE_kV4WWrbEEM2s_breadcrumbsFolderId%3D11098%26_110_INSTANCE_kV4WWrbEEM2s_keywords%3DBMI_dnaExtractionSOP_v7%26_110_INSTANCE_kV4WWrbEEM2s_formDate%3D1698777470933%26_110_INSTANCE_kV4WWrbEEM2s_repositoryId%3D10179%26_110_INSTANCE_kV4WWrbEEM2s_struts_action%3D%252Fdocument_library_display%252Fsearch%26_110_INSTANCE_kV4WWrbEEM2s_folderId%3D11098%26_110_INSTANCE_kV4WWrbEEM2s_searchFolderIds%3D11098)) we have that 'DNA is extracted from the benthic biofilms of sediment samples (sand and silt) and adherent biofilms that are scraped from plant grab samples with sterile spatulas using the PowerBiofilm Kit.

**Comment by aclum** [comment]
The new proposed plan is to make a new class with subclasses to match the NEON terms in envo, see https://github.com/EnvironmentOntology/envo/issues/1466

**Comment by aclum** [comment]
Closing this since the new terms have been added to envo. Updating the env_medium values will be worked on in https://github.com/microbiomedata/issues/issues/571.
