### ISSUE TITLE
Identify existing NEON samples in NMDC 

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#276]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 7

**RACI**

_Tag people in their roles_
- Responsible: Bea
- Accountable: Montana
- Consulted: Lee Ann
- Informed: Alicia

**Describe the the task?**
- [x] Identify which samples exist in mongo that will need the NEON biosample_catagory tag added to them
- [x] Submit change sheet to add this catagory

**Criteria for completion**
- All existing NEON samples will have biosample_catagory

**Estimate people time**
- 1 person, 10 hours

**Completion Date (Goal)**
- June 30

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon isues**
- [Tagg issues]

**Comment by bmeluch** [comment]
NEON samples in 1000 soils project have been identified and change sheet submitted

**Comment by ssarrafan** [comment]
@bmeluch @mslarae13 based on the last comment, can this issue be closed?

**Comment by bmeluch** [comment]
no, sorry, I have more projects than just 1000 soils to look through.

**Comment by ssarrafan** [comment]
Got it. I'll move to the next sprint.

**Comment by bmeluch** [comment]
Samples identified, change sheets in progress

**Comment by ssarrafan** [comment]
@bmeluch will the change sheet be completed by tomorrow?

**Comment by mslarae13** [comment]
@ssarrafan Bea is out until Monday. This is not complete yet

**Comment by bmeluch** [comment]
Completed with help from @aclum, I have to get my permissions fixed but that's a separate issue
