### ISSUE TITLE
Identify biosamples and other data related to a given study

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/issues#277]
Write a Python Notebook people can use to do the following with respect to the "production" MongoDB database:

1. Given the `id` of a study, get all the biosamples that are a part of that study.
2. For each of those biosamples, record its `img_identifiers` value (if it has one), then get all the omics processing (events) that have that biosample as an input.
3. For each of those omics processing (events), record its `id` value, then get all the metagenome annotation activities and read-based taxonomy analysis activities that were informed by that omics processing (event).
4. For each of those metagenome annotation activities, record its `id` value.
5. Similarly, for each of those read-based taxonomy analysis activities, record its `id` value.
6. Display the recorded data in JSON format.

Then, identify some biosamples among those, which meet additional criteria (discussed offline).

**Comment by eecavanna** [comment]
Done on Wednesday, June 14.

**Comment by aclum** [comment]
This code was used to provide updated identifiers for bioscales to IMG.
