### ISSUE TITLE
Metatransciptome omics_processing_set records missing for SPRUCE (gold:Gs0110138)

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#278]
Some of the schema 7.6.7 validation turned up some records that I think are missing a link between biosample_set records and workflow execution activity set records. This seems to be isolated to records associated with study_set id gold:Gs0110138

metatranscriptome_activity_set nmdc:944e7a4a1a3070061bac6414ec994622 part_of [nmdc_mta0dy21] -> nmdc:mta0dy21
metatranscriptome_activity_set nmdc:3b4ae5bffe83e6a104c95360d63954de part_of [nmdc_mta00292] -> nmdc:mta00292
metatranscriptome_activity_set nmdc:84b1d252ae043684f6ea4d1444bffd64 part_of [nmdc_mta07p39] -> nmdc:mta07p39
metatranscriptome_activity_set nmdc:2fd3f7547323a9045aff6fb57a2f09d1 part_of [nmdc_mta0tg76] -> nmdc:mta0tg76
metatranscriptome_activity_set nmdc:0bb611d10d2e0ae7788d98d434d3068f part_of [nmdc_mta0bp43] -> nmdc:mta0bp43
metatranscriptome_activity_set nmdc:628598d00d3931793d9be69a47672642 part_of [nmdc_mta04n39] -> nmdc:mta04n39
metatranscriptome_activity_set nmdc:418a1a5aaa0922e2b9bf476dcdcc2857 part_of [nmdc_mta0y710] -> nmdc:mta0y710
metatranscriptome_activity_set nmdc:1fc013a66057310a031047fbe9562c25 part_of [nmdc_mta06w20] -> nmdc:mta06w20
metatranscriptome_activity_set nmdc:a7f1f19facde372fe54b289878c56550 part_of [nmdc_mta00v17] -> nmdc:mta00v17
metatranscriptome_activity_set nmdc:98cff95ffc921c0c51deec0308e33f2b part_of [nmdc_mta0dx24] -> nmdc:mta0dx24
metatranscriptome_activity_set nmdc:683c4a7adaae08cf5456f7b80bb6f4d3 part_of [nmdc_mta02s25] -> nmdc:mta02s25
metatranscriptome_activity_set nmdc:839560f9650622f232c262d8cf7a9db9 part_of [nmdc_mta0mz25] -> nmdc:mta0mz25
metatranscriptome_activity_set nmdc:17b505f7781a3f0e932e8f39f4190068 part_of [nmdc_mta0jh65] -> nmdc:mta0jh65
metatranscriptome_activity_set nmdc:b502fd974951d11591564592ecff731c part_of [nmdc_mta0a108] -> nmdc:mta0a108
metatranscriptome_activity_set nmdc:897c054089e2c5b6d0584e4871428917 part_of [nmdc_mta0tj70] -> nmdc:mta0tj70
metatranscriptome_activity_set nmdc:6305a511f040e8bef679b8a2e439329e part_of [nmdc_mta0r607] -> nmdc:mta0r607

**Comment by aclum** [comment]
@turbomam  found another issue for this study OmicsProcessing [gold:Gp0208380](http://identifiers.org/gold/Gp0208380) has input  [gold:Gb0150258](http://identifiers.org/gold/Gb0150258), which is undefined in the NMDC metadata

**Comment by aclum** [comment]
The spruce records also do not have biosamples, the workflow records additionally use the same id across collections (ie nmdc:944e7a4a1a3070061bac6414ec994622 is used in annotation, assembly, read qc and metatranscriptome activities

**Comment by aclum** [comment]
@turbomam do you have a query to determine undefined identifiers referenced in the schema?

**Comment by turbomam** [comment]
> @turbomam do you have a query to determine undefined identifiers referenced in the schema?

@aclum we worked on this some last week, right? Do you still need me to write some more queries?

**Comment by aclum** [comment]
@turbomam I don't need any more queries, the ones we worked on last week gave me the full list. There are a number of projects that have the same issue where upstream records are missing.

**Comment by aclum** [comment]
Will be addressed by #527, closing this as a duplicate.
