### ISSUE TITLE
Ambassador Handbook and Playbook updates

### ISSUE THREAD

**Issue by jkelliher-github** [microbiomedata/issues#28]
Ambassador playbook needs to be updated, and Ambassador handbook needs updating before Ambassadors are onboarded

**Comment by ssarrafan** [comment]
@jkelliher-github can this be closed by the end of December or should it be moved to the next sprint?

**Comment by ssarrafan** [comment]
@jkelliher-github I've moved this to the current sprint but please let me know if is not part of the work for this sprint. Also, if it's very large can this be broken down into more steps?

**Comment by ssarrafan** [comment]
Changing this issue to be just focused on the playbook. Will create a new issue for the handbook. This issue can be closed per the ambassador squad meeting today. @jkelliher-github 

Playbook doc at: 
https://docs.google.com/document/d/1kRx4dSg9v4Z1wYTsOXuHIPxpv2RRQHPOY-mMJLYycPg/edit#heading=h.7xrxmlakal5l
