### ISSUE TITLE
Update JGI metadata terms on the submission portal

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#29]
Assigning first to Montana to provide Mark with what needs to be updated.  She will re-assign to Mark.  

This is from the[ task list](https://docs.google.com/spreadsheets/d/1-rnkSNCogXSndbe8bIjy3tVCeqe1PeqUazBIASDiEbM/edit#gid=0) for the subport squad.

**Comment by mslarae13** [comment]
PR: https://github.com/microbiomedata/nmdc-schema/pull/573

**Comment by mslarae13** [comment]
merged and complete
