### ISSUE TITLE
Identifiers mural

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#3]
**Is your feature request related to a problem? Please describe.**
The problem is making sure everyone understands how identifiers are used throughout NMDC metadata flow

**Describe the solution you'd like**
A mural created to show identifiers flow and where they are needed

**Describe alternatives you've considered**
N/A

**Acceptance Criteria**
Create a checklist or scenario-based acceptance criteria, from the users perspective, that answers the following: 

Who will use this feature/enhancement? Entire team
When will they use it? In every meeting when identifiers comes up 
How will they use it? Used in meetings and other ways to make sure team is clear and understands how identifiers work for NMDC overall
How will they test it to make sure it's working? check accuracy with other team members
Is the request achievable? During one sprint?  yes
What is your definition of done for this request? A complete and accurate mural

**Comment by mslarae13** [comment]
https://lucid.app/lucidchart/811029cb-a93e-436a-a997-3faba459497c/edit?viewport_loc=-1787%2C-1210%2C5141%2C2450%2C0_0&invitationId=inv_46ca52cd-6253-4c5d-a913-e8d6df360a42

Mural (Lucid) created for biosample & study. I think we can close this ticket. & re-visit when we're ready to tackle workflow and data IDs.
