### ISSUE TITLE
Determine/design method of 'how to enable multiple data harmonizer sheets'

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#30]
@pkalita-lbl I am putting this one in progress since you're already working on it. If you already have another GH issue for this let me know.  

FYI @mslarae13 
From the [task list ](https://docs.google.com/spreadsheets/d/1-rnkSNCogXSndbe8bIjy3tVCeqe1PeqUazBIASDiEbM/edit#gid=0)for subport squad.

**Comment by mslarae13** [comment]
relates to https://github.com/microbiomedata/NMDC_Planning/issues/199

**Comment by pkalita-lbl** [comment]
Prototype is deployed here for anyone interested: https://pkalita-lbl.github.io/dh-stepper-example/

**Comment by mslarae13** [comment]
Decision finalized today! Complete!
