### ISSUE TITLE
Identify possible "metadata status" values

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#31]
This is from the subport squad [task list](https://docs.google.com/spreadsheets/d/1-rnkSNCogXSndbe8bIjy3tVCeqe1PeqUazBIASDiEbM/edit#gid=0).

**Comment by mslarae13** [comment]
https://docs.google.com/spreadsheets/d/18tN1_KlQFHq1FFaBTT3zzusEn57tkidAfj-3nC5wDfM/edit?usp=sharing

**Comment by mslarae13** [comment]
Would appreciate review.
@emileyfadrosh , @jeffbaumes , @cmungall

**Comment by mslarae13** [comment]
@ssarrafan overdue, please add to January 2023 sprint

**Comment by ssarrafan** [comment]
@mslarae13 Are these still in review status? I will move to the next sprint but let me know if it should go to the backlog instead.

**Comment by ssarrafan** [comment]
Closing #15 and adding link here per Mark M
From Mark:  The pattern for non-corner plate positions (wells) has been applied, and logic tying the state of the container to the values allowed for the well have been added to the schema. That logic just can’t be enforced in DataHarmonizer yet.

**Comment by mslarae13** [comment]
> 

@ssarrafan  I think you have the wrong ticket for this? 
This issue is for the metadata submission status (see https://docs.google.com/spreadsheets/d/18tN1_KlQFHq1FFaBTT3zzusEn57tkidAfj-3nC5wDfM/edit?usp=sharing )

I think this comment is better suited to be captured here: https://github.com/orgs/microbiomedata/projects/46/views/1?pane=issue&itemId=17388351

**Comment by mslarae13** [comment]
Additionally, I think we should backlog this. 
I think this task is basically done, but I didn't want to close it until we started implementation. For now, Mike is focusing on the multiple tabs in the submission portal & once that is complete he'll move onto this. So paused until it's the priority.

**Comment by ssarrafan** [comment]
@mslarae13 I am removing from the sprint and adding the backlog label.

**Comment by mslarae13** [comment]
@naglepuff can you link the issue you start for describing tasks and time for implementing this? Then we can close this issue.
https://docs.google.com/spreadsheets/d/18tN1_KlQFHq1FFaBTT3zzusEn57tkidAfj-3nC5wDfM/edit?usp=sharing

**Comment by naglepuff** [comment]
https://github.com/microbiomedata/nmdc-server/issues/967
