### ISSUE TITLE
Design and describe "multiple submission per study"

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#32]
This is from the subport squad [task list](https://docs.google.com/spreadsheets/d/1-rnkSNCogXSndbe8bIjy3tVCeqe1PeqUazBIASDiEbM/edit#gid=0)

**Comment by mslarae13** [comment]
https://docs.google.com/document/d/1LXvkFe2oA0sxlAWIgTMgONLQCNsnAtrp8260Y2prXbs/edit?usp=sharing

**Comment by mslarae13** [comment]
@ssarrafan continues into January 2023 sprint

**Comment by ssarrafan** [comment]
@mslarae13 moving to the next sprint, let me know if you don't plan to work on it in the next few weeks please

**Comment by ssarrafan** [comment]
@mslarae13 can this be considered done?  Design and describe task.

**Comment by mslarae13** [comment]
@ssarrafan backlog. not a priority for GSP, when we start working on this again is TBD.

**Comment by ssarrafan** [comment]
This looks like it's done so I'm closing the issue.  Marked done Juny 27th.

**Comment by mslarae13** [comment]
Thanks set, yes the design and describe part is doen
