### ISSUE TITLE
NEON `nucleicAcidQuantMethod` - Nucleic acid quantitative method

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/issues#325]

**Comment by aclum** [comment]
We've added a slot for this on Class ProcessedSample, slot is nucleic_acid_concentration which has a range of 
https://microbiomedata.github.io/nmdc-schema/InstrumentValue/, which has an [instrument_name](https://microbiomedata.github.io/nmdc-schema/instrument_name/) slot.

**Comment by brynnz22** [comment]
Okay, I will add this to the mapping tsv. And close this.
