### ISSUE TITLE
Ambassador Handbook updates

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#33]
This issue is to track the updates for the handbook before the Ambassador 2023 launch. 

@jkelliher-github @frodriguez16 please add the link to the document or break down into steps here.

**Comment by frodriguez16** [comment]
https://docs.google.com/document/d/1gNfMs02CU8y1IsGnp47ounagnVTmJlcY_hB3PnOO2V0/edit

**Comment by ssarrafan** [comment]
I see the link so will consider this one done. @frodriguez16 please let me know if it should be reopened. Thanks for adding the link.
