### ISSUE TITLE
Ingest NEON benthic metagenome metadata and biosamples (DP1.20279.001)

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#335]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 3

**RACI**

_Tag people in their roles_
- Responsible: @sujaypatil96 
- Accountable: @turbomam 
- Consulted: @aclum 
- Informed: @aclum 

**Describe the the task?**
- [ ] Ingest new NEON biosamples and metadata for benthic metagenomes using [data release version RELEASE-2023(https://data.neonscience.org/data-products/DP1.20279.001/RELEASE-2023). nmdc study id is nmdc:sty-11-pzmd0x14

**Criteria for completion**
- Records exist in prod mongo for benthic metagenome samples

**Estimate people time**

**Completion Date (Goal)**
-  Sept 8

**Target Sprint Start & End Dates**
- Start: Aug 14
- End: Sept 8

**Tag Blocker/Contingent upon issues**
https://github.com/microbiomedata/nmdc-runtime/issues/249
TDB changes to ingest script make be required to support surface water samples

**Comment by aclum** [comment]
Updated target sprints and end date. This is being worked on this sprint but won't be finished by Friday so adding to sprint 18 board.

**Comment by aclum** [comment]
@sujaypatil96  assuming since we haven't reviewed any json files that this will need to be moved to the next sprint. We now have the updated envo stream terms I'll provide those shortly.

**Comment by aclum** [comment]
we've been iterating over the biosample output and may have run into an issue where there are multiple instrument runs that need to get combined together into a single omics processing set record. For this use case we need to review and maybe make updates to how start and stop dates are modeled.

**Comment by ssarrafan** [comment]
Not updated in the last 2 weeks. Removing from sprint and adding backlog label.

**Comment by aclum** [comment]
This was reviewed at the NEON squad meeting this week. I provided some additional feedback today, moving to the the next sprint.

**Comment by aclum** [comment]
Records were submitted to mongo but we realized part_of was populated incorrectly. Sujay made and submitted a changesheet but there are issues with dagster. Hopefully this will be resolved tomorrow and we can get this closed out. Blocking issue is 
 https://github.com/microbiomedata/nmdc-runtime/issues/349.

**Comment by ssarrafan** [comment]
Moved to new sprint considering it's late Friday afternoon.

**Comment by aclum** [comment]
https://github.com/microbiomedata/nmdc-runtime/issues/349 was resolved last week. @sujaypatil96  was able to submit the changesheet, data in mongo looks good, workflows are running.
