### ISSUE TITLE
Update funding_sources description in nmdc schema

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/issues#339]
Funding statements are inconsistent and varies from a simple statement of BER with a contract number (PNNL or other national lab), to what looks like the funding statement from a manuscript which is quite lengthy and with information out of context in some cases (look at O'Malley gut fungi project). What do we want this to look like?

After discussing what we want the `funding_sources` statement to look like, we can add a detailed `description` to the `funding_sources` slot to specify what this metadata should look like moving forward.

@mslarae13 @turbomam

**Comment by turbomam** [comment]
Yes, a more explicit annotations would be great.

Description is really just for describing what something is. If there are directions we need to provide to users, then that should go in comments, validation patterns (if possible) and/or examples.

**Comment by brynnz22** [comment]
Sounds good, so potentially adding a comment, example, or validation pattern to the schema once we know what we want `funding_sources` to look like.

**Comment by turbomam** [comment]
Yes. `comments` and a valid `examples` will be easiest. I can' think of a good validation `pattern`off the top of my head, and unfortunately we don't have a formal mechanism for giving counter-examples (where an undesired examples is written out)

**Comment by turbomam** [comment]
Here's a report of the current funding sources.[nmdc-study-funding-source-2023-06-29.txt](https://github.com/microbiomedata/issues/files/11906973/nmdc-study-funding-source-2023-06-29.txt)

**Comment by turbomam** [comment]
@mslarae13 @aclum should we institute a general policy of scanning some values in the data for URLs? It's too bad that we don't capture who submitted (?) or updated data in MongoDB. Otherwise we could contact them and work together in routing the URLs/links to other slots in the data object.

**Comment by aclum** [comment]
Yes, I would a way to check that urls resolve.  We do keep track of who submits what data in mongo, the process to get at that info is convoluted but I can forward the info I have from Donny.

**Comment by turbomam** [comment]
oops, the length restriction on funding_sources will technically require a database migration. The value below is 165 characters

> ✗ 'U.S. Department of Energy, Office of Science, Office of Biological and Environmental Research (BER) under contract DE-AC05-00OR22725; Project Number (FWP): 3ERKP730' does not match '^.{1,150}$' in $.study_set[0].funding_sources[0]

What do you think of increasing the limit to 200 characters? Otherwise, can you figure out who created that study and ask them how they want their funding_sources truncated?

**Comment by brynnz22** [comment]
Fixed and increased character count to 200. @turbomam thanks for your help!

**Comment by aclum** [comment]
Is there a ticket yet for the same character limit enforcement in the submission portal ui? @pkalita-lbl @naglepuff

**Comment by pkalita-lbl** [comment]
No issue that I'm aware of

**Comment by mslarae13** [comment]
No need for a character limit issue on subport. We removed the character limit.
