### ISSUE TITLE
Add comment to nmdc schema Study description slot to specify not including any links

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/issues#340]
One of the issues identified in the Study Refresh squad is to keep links out of the "abstract" on the study landing page. According to this [portal-schema mapping doc](https://github.com/microbiomedata/nmdc-server/blob/ingest-data-guide/docs/study_page_annotations.md) the Description portion of the page is being taken from the `description` slot of the Study class. Is the `abstract` slot for the `Study` class being used in the portal or otherwise? According to the `selected_mongodb_contents.yaml` file @turbomam passed along in the Study Refresh slack channel, the `abstract` slot is not used. If it is not being used, can we discuss removing it from the `Study` class  in order to reduce confusion between `description` and `abstract`?

- [ ] To keep links out of this metadata moving forward, I propose adding a `comment` to the `description` slot for the Study class specifying that no links should be included. @mslarae13

**Comment by turbomam** [comment]
Directions like that should generally go in `comments`, `examples` or validation `pattern`s, not `description`. At most, the `description` of `Study`'s `slot_usage` of `description` could be something like
> A brief, link-free summary of a Study

Note that I removed the ..."[that] you're submitted"... portion. Description say what something is, not how to create it or to use it.
 
Comments could include hints about other `Study` slots in which links are allowed or even required (like the proposed `doi` sub-properties!)

**Comment by brynnz22** [comment]
@turbomam @mslarae13 It looks like `abstract` is not being used in the `study_set` collection in MondoDb at all. Only `description` is. Since `Study` is the only class that uses the `abstract` slot, can we remove this slot globally from the schema? Our current descriptions of the two slots are: 

`abstract`: The abstract of manuscript/grant associated with the entity; i.e. a summary of the resource
`description`: a human-readable description of a thing.

And update the description of the `description` slot in the slot usage of `Study` to say something like, "A summary of the study". As well as adding a `comment` in the slot usage to specify not including links.

Does this sound good?

**Comment by mslarae13** [comment]
Description, I believe, populates the information that appears before a sample name in the DP.
Abstract should be what populates the study landing page. 

@brynnz22 @naglepuff @aclum  can you confirm?

**Comment by aclum** [comment]
@mslarae13 abstract is a slot on class study but it has never been used, I believe you are referring to what gets populated with slot 'description' 
slots 'name' and 'description' on class biosample are what populate the sample 
ie
    "id" : "nmdc:bsm-11-3erjkf61",
    "name" : "River sediment microbial communities from Illinois, United States - sangamon_2019_sw_WHONDRS-S19S_0083",
    "description" : "River sediment microbial communities from Illinois, United States"
  https://data.microbiomedata.org/details/sample/nmdc:bsm-11-3erjkf61
  
![Screenshot 2023-07-14 at 2 33 22 PM](https://github.com/microbiomedata/issues/assets/8196591/44fb490d-9866-4e59-8ef2-16b564aa2765)

You are pointing to a stale branch. This is the main branch 
https://github.com/microbiomedata/nmdc-server/blob/main/docs/study_page_annotations.md

**Comment by mslarae13** [comment]
Study.description: description slot of Study class instances  .. according to https://github.com/microbiomedata/nmdc-server/blob/main/docs/study_page_annotations.md 

Is what we're referring to... not biosample description.

**Comment by brynnz22** [comment]
Yes, that's correct; the `description` specifically for the `Study` class. This is what is being used to describe the studies, while `abstract` currently exists in the `Study` class, but we don't use it. Or it doesn't appear that we use it. In Mongo, there are no studies that have the `abstract` slot. So I am wondering if we can remove `abstract` to make the schema more clear and concise and avoid any use of both the `description` and the `abstract` slot to convey the same information in the future.

**Comment by aclum** [comment]
I agree w/Brynn's suggestion to depreciate slot `abstract` for class `Study`. Slot `description` for class `Study` inherits from NamedThing so we have to keep it either way.
