### ISSUE TITLE
Discuss collapsing relevant_protocols slot for the Study Class with protocol_link in the NMDC Schema

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/issues#341]
For the Study Refresh squad, we have discussed separating out websites by data, links, and protocols on the study landing page. We can consider adding the `protocol_link` under `slot usage` for the `Study` class. @mslarae13 @turbomam. This would require some legacy data editing for the Study pages that include protocols like NEON studies.

**Comment by brynnz22** [comment]
closing this. Just saw there is a slot being used in the `Study` class called `relevant_protocols`

**Comment by turbomam** [comment]
Maybe we should collapse `relevant_protocols` and `protocol_link` in the future, if they have compatible ranges.

**Comment by brynnz22** [comment]
I am going to reopen this to discuss collapsing these. `protocol_link` has the range of the `Protocol` class which has the slot `url` with a range of `String`. That seems compatible to `relevant_protocols` whose range is `String`. Although, it sounds like this update is not top priority for the Study pages since `relevant_protocols` can be used for now.

**Comment by mslarae13** [comment]
I think we briefly discussed at study page refresh, and the conclusion was we don't know if splitting out the links is necessary... no user research. Or to what degree of splitting / specification we need to make.

Is that your recollection too @brynnz22 ? If so, we can backlog this?

**Comment by brynnz22** [comment]
Yeah that's right! I think at this point, this ticket is to just to collapse the two protocol slots we are using in the nmdc schema. But its not really necessary for the Study Refresh. Its just to make things tidier. Originally, I created this issue with the protocols in mind, but then saw that we have a slot already for it. And then @turbomam pointed out that we have another slot in the schema for Protocols and it would make sense to collapse them.

**Comment by mslarae13** [comment]
@brynnz22  has the decision been made to no longer address this larger protocol issue in this squad, correcT?

**Comment by brynnz22** [comment]
@mslarae13 yes, I believe that is correct.

**Comment by aclum** [comment]
@brynnz22  can this be closed? Was it addressed in the berkeley refactor?

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by brynnz22** [comment]
Yes, it was.
