### ISSUE TITLE
Benthic related slots to discuss/consider adding/adjusting based on

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/issues#354]
Here is a list of slots in the NEON benthic DP1.20279.001 data package that were not mapped to any NMDC slots that we could potentially discuss adding/editing the nmdc schema to accomodate. Some of the fields that did not map were also part of the soil data package and were listed in issue https://github.com/microbiomedata/issues/issues/279 or the surface water data package and were listed in isssue #343 so I left them out of this issue. @mslarae13 @bmeluch

Biosample:
- [x] #355
- [x] #356
- [x] #357
- [x] #358
- [x] #359

Metagenome Sequencing:
- [x] #360
- [x] #361

**Comment by turbomam** [comment]
I think this is a great issue and would like to see it happen and/or help with it... but I'm not the best judge or priorities. it's been in backlog for a year now.

**Comment by mslarae13** [comment]
I'm not sure the level of priority either. Also, curious if there's any thought from leadership about NMDC creating slots & requesting GSC to also add the slots.
Or NMDC not adding the slots until GSC adds them?

@emileyfadrosh @cmungall @lamccue @ssarrafan

**Comment by ssarrafan** [comment]
> I'm not sure the level of priority either. Also, curious if there's any thought from leadership about NMDC creating slots & requesting GSC to also add the slots. Or NMDC not adding the slots until GSC adds them?
> 
> @emileyfadrosh @cmungall @lamccue @ssarrafan

I've added this ticket to the agenda for next Friday's planning meeting.

**Comment by aclum** [comment]
Not implementing these at this time.

**Comment by mslarae13** [comment]
I'm changing this to closed as not planned.
