### ISSUE TITLE
Study page update - Update identifier requirements

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#365]

**Comment by ssarrafan** [comment]
@mslarae13 any update on this issue. Does Mark have what he needs to work on this?

**Comment by mslarae13** [comment]
pausing until post ESA

**Comment by mslarae13** [comment]
@brynnz22 can you remind me, we decided this was part of re-iding, and isn't for this squad. Right?

**Comment by mslarae13** [comment]
Confirmed at study page meeting. this will be part of the identifiers squad
@aclum

**Comment by aclum** [comment]
@mslarae13  what is needed here? Just to use nmdc identifiers for studies?

**Comment by aclum** [comment]
Closing this as I'm not sure what it was originally for and re-iding is complete. Please reopen and add a description if work is still needed here.
