### ISSUE TITLE
Study page update - Add schema slots for new study landing page fields (ESA: Links)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#366]

**Comment by brynnz22** [comment]
So far, I think the only new slots we will be adding are subslots of `doi` - `award_dois`, `dataset_dois`, and `publication_dois`. See issue https://github.com/microbiomedata/issues/issues/338

**Comment by ssarrafan** [comment]
@mslarae13 do you want to keep this issue open or just track #338 for the updates?

**Comment by mslarae13** [comment]
Since this is ESA specific, we can use #338

**Comment by ssarrafan** [comment]
Closing issue per @mslarae13, see #338
