### ISSUE TITLE
50718 Metadata & data/biosample ingest

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#367]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 4

**RACI**

_Tag people in their roles_
- Responsible: @bmeluch 
- Accountable: @mslarae13 
- Consulted:
- Informed:

**Describe the the task?**
- [x] Identify samples in DMS
- [x] Assemble metadata
- [x] Provide to Yuri for processing
- [x] Samples are processed and in NMDC database
- [x] Create study page

**Criteria for completion**
- Biosamples for 50718 are in NMDC database

**Estimate people time**
- 1 person

**Completion Date (Goal)**
- 21 July 2023

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- [Tag issues]

**Comment by bmeluch** [comment]
Metadata/EMSL data file links provided to Yuri for processing. Study page info pending reply from PI.

**Comment by ssarrafan** [comment]
@mslarae13 @bmeluch this issue isn't assigned to anyone but in this sprint.  I will assign it to Bea but let me know if it should go to the next sprint or backlog instead.

**Comment by ssarrafan** [comment]
@bmeluch any update on this issue?  is it actively being worked on?

**Comment by bmeluch** [comment]
2 final changesheets are ready, one for study page, one to add some missing metadata - holding off on applying them until the next round of data intake (or people get back from conferences and tell me to go ahead) so I'm going to mark this as backlogged

**Comment by ssarrafan** [comment]
@bmeluch I will move to the next sprint since folks should be back next week and you just need to apply them. Does that sound ok?
