### ISSUE TITLE
JGI data for bioscales

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#37]
Ingest JGI sequencing and analysis data

@aclum if any of the template below is relevant please help to fill out.

**Is your feature request related to a problem? Please describe.**
Import JGI metagenomes for Gs0154044.  

**Describe the solution you'd like**
The sequencing project tab of https://docs.google.com/spreadsheets/d/1ijV2j7Z79qvftRT3QerLXtLdGYidBc3a/edit#gid=1063921502 lists which sequencing projects have a status of Complete and their sequencing project ids. These IDs can be used with existing scripts to query jamo directly.  Raw data, filtered data, assembly, annotation, and bins should be ingested.

**Describe alternatives you've considered**
It is possible the JDP API is ready as an alternative to directly querying jamo. We are waiting confirmation from Steve Wilson.
**Acceptance Criteria**
Create a checklist or scenario-based acceptance criteria, from the users perspective, that answers the following: 

Raw reads, filtered data, assembly, annotation, and binning files are available on the NMDC data portal. Sequencing where useable=false or jat records where publish=false should not be ingested.  Files should include readme or info files for filtering, assembly, and annotation.

Depends on 
- [x] https://github.com/microbiomedata/nmdc-runtime/issues/161
- [x] https://github.com/microbiomedata/nmdc-schema/issues/703
- [x] https://github.com/microbiomedata/issues/issues/56 
- [x] https://github.com/microbiomedata/nmdc-server/issues/845
- [x] https://github.com/microbiomedata/issues/issues/60
- [x] https://github.com/microbiomedata/issues/issues/61
- [x] https://github.com/microbiomedata/issues/issues/62
- [x] https://github.com/microbiomedata/nmdc-runtime/issues/212
- [x] https://github.com/microbiomedata/issues/issues/135

**Comment by aclum** [comment]
Some dependencies discussed the workflow automation meeting today. Tickets either exist or will be created in the workflow automation board 
[-minting activity and data object records ](https://github.com/microbiomedata/nmdc-runtime/issues/161)
schema changes to capture new file types
Elimination of json output ingested by the NMDC data portal in favor of aggregating results at the workflow level. Requires changes at the data ingest level and on the NMDC data portal side
workflow automation end to end test Shane is currently working on
Assessment by @mflynn-lanl to see if JDP API can replace direct jamo query. Go/no go date for this decision is in 2 weeks (Feb 14)
@scanon @hubin-keio @Michal-Babins @mflynn-lanl @elais  please add any other dependencies  cc @ssarrafan

**Comment by scanon** [comment]
Reviewing what @Michal-Babins has so far we saw the following
* Change to the NMDC omics ID for the top directory level
* The zip file has the full path, just use the path name
* Add a version/iteration extension for the all the directories

**Comment by Michal-Babins** [comment]
Done.

**Comment by ssarrafan** [comment]
@Michal-Babins @aclum I am assuming that this is not done based on the issues that are dependencies and remain open but if it is done please let me know.  I'll move this to the next sprint.

**Comment by aclum** [comment]
Moving to the next sprint

**Comment by ssarrafan** [comment]
@aclum can we close this one?

**Comment by aclum** [comment]
I would like https://github.com/microbiomedata/issues/issues/135 looked at first to make sure the bins are ok so I'll move this to the next sprint.
