### ISSUE TITLE
50267 Metadata & data/biosample ingest (Part 1)

### ISSUE THREAD

**Issue by bmeluch** [microbiomedata/issues#370]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 4

**RACI**

_Tag people in their roles_
- Responsible: @bmeluch 
- Accountable: @mslarae13 
- Consulted:
- Informed:

**Describe the the task?**
- [x] Identify samples in DMS
- [x] Assemble metadata
- [x] Provide to Yuri for processing
- [x] Samples are processed and in NMDC database
- [x] Create study page

**Criteria for completion**
- Biosamples for 50267 are in NMDC database

**Estimate people time**
- 1 person

**Completion Date (Goal)**
- 21 July 2023

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- [Tag issues]

**Comment by bmeluch** [comment]
First round of samples metadata/EMSL links have been sent to Yuri for analysis. The rest of the samples for this project are missing metadata and will be uploaded once more info is received from the PI.

**Comment by bmeluch** [comment]
Biosamples and study page information are in Mongo

**Comment by ssarrafan** [comment]
@bmeluch does your last comment mean this issue can be closed?

**Comment by ssarrafan** [comment]
Assuming this is done.  Re-open if not the case.

**Comment by bmeluch** [comment]
1 final metadata changesheet is ready - holding off on applying until the next round of data intake (or people get back from conferences and tell me to go ahead) so I'm going to mark this as backlogged
