### ISSUE TITLE
ingest bioscales study

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#38]
Proposed plan is to use the information in nmdc currently for this study to make a new study submission record, modulo using an NMDC study id. The existing study record is https://data.microbiomedata.org/details/study/gold:Gs0154044 

This is more complete than the GOLD study record avaliable via the GOLD API and will reduce manual modifications via change sheets. The current study information
```
(curl -X 'GET' \
  'https://api.microbiomedata.org/studies/gold%3AGs0154044' \
  -H 'accept: application/json')
```

Also include MASSIVE study link 

MASSIVE identifiers were added to the schema in https://github.com/microbiomedata/nmdc-schema/issues/642 
slot is `massive_study_identifiers` the value should be `MASSIVE:MSV000090886`
which resolves to https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?task=83574f41458a4b259621d5c32a4d82f9

**Comment by turbomam** [comment]
This issue does not belong in the nmdc-schema repo because it doe not request changes to the schema. It might make sense to put it in sample-annotator.

**Comment by aclum** [comment]
This study exists in NMDC already so closing this issue.

**Comment by aclum** [comment]
We will create a study for bioscales using the new minter for nmdc ids

**Comment by ssarrafan** [comment]
@aclum based on your comment I am closing this issue.

**Comment by aclum** [comment]
This needs to be open, we need to have a new napa compliant identifier for the study.

**Comment by sujaypatil96** [comment]
The requirements about getting additional information from the `https://api.microbiomedata.org/studies/{GOLD_STUDY_ID}` is very clear.

@aclum: The part that's less clear is how to determine the MASSIVE id for a study.

**Comment by aclum** [comment]
@sujaypatil96  There is no automated way to identify the massive identifier, it is in the ticket description. If there is a different way you'd like this, ie via spreadsheet with slot name, slot value let me know.

**Comment by sujaypatil96** [comment]
Solved it by adding in the MASSIVE identifier information to the current export manually.

**Comment by ssarrafan** [comment]
still in progress
@sujaypatil96 are you waiting for anyone to review this?

**Comment by sujaypatil96** [comment]
Moving this to _done_ since we supplemented some missing information from GOLD with information from the data portal.

**Comment by ssarrafan** [comment]
Closing the issue per Sujay's comment
