### ISSUE TITLE
[BUG] testing from gmail account

### ISSUE THREAD

**Issue by Setstar** [microbiomedata/issues#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Testing the form out from a non-NMDC user account

### Expected Behavior

I'm expecting an issue to be created 
This would be cool then users can use this form

### Steps To Reproduce

1. I sent the[ link ](https://github.com/microbiomedata/issues/issues/new?assignees=&labels=Bug%2CNeeds+Triage&projects=&template=bugform.yml&title=%5BBUG%5D+%3Ctitle%3E)to my gmail account 
2. Clicked on the link and got to this page
3. Will submit this form and see what happens!

### Environment

```markdown
- OS:MacOS Monterey 
- Node:
- npm:
```

### Anything else?

<img width="236" alt="Screen Shot 2023-08-09 at 9 37 19 AM" src="https://github.com/microbiomedata/issues/assets/13546570/ffb60c4d-e4dc-4d92-b5ad-577eb5d1fad2">
Testing attaching an image

**Comment by ssarrafan** [comment]
Hi @Setstar we are reviewing this.  Hang tight.
