### ISSUE TITLE
Flowchart documenting flow of data in NEON experiment/study

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/issues#389]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- This task is associated with deliverable 1.

**RACI**

_Tag people in their roles_
- Responsible: @sujaypatil96 
- Accountable: @sujaypatil96 
- Consulted: @cmungall 
- Informed: @cmungall 

**Describe the the task?**
Document all aspects (temporal, schema objects, etc.) of data flow from an experiment in the NEON study in a flowchart diagram/architecture diagram. Use draw.io/lucidchart or some other accepted UML diagramming tool to make the diagram.

**Estimate people time**
- 1 person, 1 day

**Completion Date (Goal)**
- August 25th

**Target Sprint Start & End Dates**
- Start: August 14th
- End: August 25th

**Comment by aclum** [comment]
can this be closed? Going forward we'll use GOLD to pull in this metadata.
