### ISSUE TITLE
Bioscales -metabolomics only samples metadata ingest

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#39]
Metadata ingest for metabolomics only samples for bioscales. Use the study identifier created from https://github.com/microbiomedata/issues/issues/38

@ssarrafan This is planned for the sprint starting 2/13/23

**Comment by aclum** [comment]
@sujaypatil96  there were no objections in slack to this proposal so we can move forward with the proposed plan.

**Comment by aclum** [comment]
@ssarrafan @sujaypatil96 This has to be done either the sprint the starts Monday or the following one.

**Comment by sujaypatil96** [comment]
I think I might be able to do this in the following sprint. I have to work on some submission portal squad items this sprint.

**Comment by ssarrafan** [comment]
@aclum @sujaypatil96 any update on this?

**Comment by aclum** [comment]
@sujaypatil96 has this ready to submit to mongo.

**Comment by sujaypatil96** [comment]
The data has been prepared here: https://github.com/microbiomedata/nmdc-datasets/blob/main/bioscales/bioscales_metabolomics.json, but still needs to be submitted to Mongo.
