### ISSUE TITLE
Add GOLD metadata to a subset of NEON soil samples 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#397]
**Deliverable this task is associated with**

See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing

**Implementation Sketch**
1. Retrieve GOLD biosample data for study Gs0144570
2. For each: "biosampleName": "Terrestrial soil microbial communities from Disney Wilderness Preserve, Southeast, FL, USA - DSNY_016-M-37-14-20140409-GEN-DNA1",
3. Extract the sample_name part: DSNY_016-M-37-14-20140409-GEN-DNA1
4. Search NMDC data OmicsProcessing.name with sample_name
5. Log if not found
6.  Get BioSample ID from OmicsProcessing.has_input
7. Retrieve NMDC BioSample
8. Compare NMDC and GOLD BioSamples - add ChangeSheet line items for any missing GOLD metadata  

**RACI**

_Tag people in their roles_
- Responsible: @sujaypatil96 
- Accountable: @aclum 
- Consulted:
- Informed:

**Describe the the task?**
- [ ] For NEON soil samples where sequencing data was generate at Battelle/Argonne (DP1.10086.001 and DP1.10107.001) and the project is also in GOLD ex ABBY_062-M-20170606-COMP-DNA1 (n=~492 procsm) we need to add GOLD metadata (img_identifiers, GOLD biosample, GOLD ecosystem pathways) to the NMDC records. We also need the [gold_sequencing_project_identifiers](https://microbiomedata.github.io/nmdc-schema/gold_sequencing_project_identifiers/) for the omics_processing_set record These are the projects comprised of GOLD study https://gold.jgi.doe.gov/study?id=Gs0144570

**Criteria for completion**
-in mongo prod there are ~1700  biosample_set records  with [gold_biosample_identifiers](https://microbiomedata.github.io/nmdc-schema/gold_biosample_identifiers/) populated where part_of equals nmdc:sty-11-34xj1150
studio 3T query `db.getCollection("biosample_set").find({'part_of':'nmdc:sty-11-34xj1150','gold_biosample_identifiers':{$exists:true}})`
There are currently 239 records which correspond to the samples sequenced at the JGI.
Example biosample identifier which should have gold_biosample_identifier populated after these updates nmdc:bsm-11-kyjye260. 
 

**ACs Updated**
- Note: The query `db.getCollection("biosample_set").find({'part_of':'nmdc:sty-11-34xj1150','gold_biosample_identifiers':{$exists:true}})` will find all documents where the gold_biosample_identifiers exists, but may contain 0 elements

*Results against Prod DB:*
- `db.getCollection("biosample_set").find({'part_of':'nmdc:sty-11-34xj1150','gold_biosample_identifiers':{$exists:true}})`
-- 4443 documents
- change query to `'gold_biosample_identifiers':{$size:0}`
-- 4204 documents
- change query to `'gold_biosample_identifiers':{$size:1}`
-- 239 documents 

*Results against Dev - After changesheet applied:*
- gold_biosample_identifiers size = 1
-- 1516 documents
-- 1277 documents updated

*Log*
- Processed 494 GOLD biosamples...
- found 1277 corresponding NMDC biosamples..
- unfindable_count: 48...

**Estimate people time**
- 1 day

**Completion Date (Goal)**
- Sept 8

**Target Sprint Start & End Dates**
- Start: August 28
- End: Sept 8

**Tag Blocker/Contingent upon issues**

**Comment by ssarrafan** [comment]
Moving to next sprint per @mbthornton-lbl

**Comment by ssarrafan** [comment]
@mbthornton-lbl @sujaypatil96 I will move this one more time but would be great to get an update on if it's active or not.  I'll assume it's going in the backlog if it's still open at the end of this sprint.
