### ISSUE TITLE
Napa compliance- Review study and biosample identifiers

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#399]
**Deliverable this task is associated with**

- Determine if legacy identifiers need to be stored

**RACI**

_Tag people in their roles_
- Responsible: @aclum @SamuelPurvine @mslarae13 
- Accountable: @aclum 
- Consulted: @lamccue @shreddd 
- Informed: @emileyfadrosh 

**Describe the the task?**
- [x] Review study and biosample identifiers to determine if the current values are also covered by other existing schema slots

**Criteria for completion**
- Decision on if schema changes are needed or if legacy identifiers are contained within existing schema slots.

**Estimate people time**
- 4 hours

**Completion Date (Goal)**
- Sept 22

**Target Sprint Start & End Dates**
- Start: Sept 11
- End: Sept 11

**Comment by ssarrafan** [comment]
@aclum it looks like the review is done, can we close this issue?

**Comment by aclum** [comment]
@ssarrafan The review is complete but we still haven't addressed the deliverable which is to determine if we need to keep the legacy workflow data and therefore need schema changes to store legacy identifiers or if we can remove it. If this gets discussed tomorrow at the planning meeting and there is a decision then it can be closed.

**Comment by mslarae13** [comment]
Definitely need to dump and store/ archive that's available on request. But what appears on the data portal should be discussed. Emiley wasn't at the Friday morning meeting, so we didn't come to a decision.

**Comment by SamuelPurvine** [comment]
And of course note Mark Miller's discussion of mongo records for data that no longer exists, i.e. we prolly don't need to archive those records. That said, prolly easiest to nuke everything proteomics from the portal and mongo once there are new genome annotations, re-run the proteomics workflow using the new ones, and load the data in cleanly, with a human step in there to make sure we are getting the IDs correct. AND making sure we all agree whether the peptide level data needs to be fed into mongo.

**Comment by ssarrafan** [comment]
Discussed at planning meeting but would like @emileyfadrosh to weigh in so moving to next sprint to get her input.

**Comment by emileyfadrosh** [comment]
After further discussion on slack, I recommend moving forward with taking a snapshot of current data and doing a full refresh with new IDs. @shreddd I reviewed the download logs, and there does not seem to be any indication for active research that would lead to a publication. Pending @jkelliher-github updates from the Champions, I think we are in the clear and once the re-id'ing is completed, we post a message on the data portal that access to old data can be made available. 

@aclum @ssarrafan @mslarae13 - does this sound OK? Thanks!

**Comment by ssarrafan** [comment]
> The review is complete but we still haven't addressed the deliverable which is to determine if we need to keep the legacy workflow data and therefore need schema changes to store legacy identifiers or if we can remove it. If this gets discussed tomorrow at the planning meeting and there is a decision then it can be closed.

Sounds great to me.  Once @aclum confirms Monday we can add this to the decision log.  Should this be run by any of the workflows folks?

**Comment by aclum** [comment]
Yes, let's bring this up at the 2pm sync meeting on Wednesday.

**Comment by aclum** [comment]
We are not going to store legacy identifiers unless there is already an existing slot for them like [gold_biosample_identifiers](https://microbiomedata.github.io/nmdc-schema/gold_biosample_identifiers/)
