### ISSUE TITLE
ingest bioscales biosamples that exist in GOLD

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#40]

**Comment by aclum** [comment]
Capturing the extra soil metadata depends on GOLD ticket https://issues.jgi.doe.gov/browse/GOLD-2048
I've asked Reddy via email to update the envo triad for the root endosphere samples.  After considering using some PO terms, with Montana's approval we went with some existing envo terms.
local environmental context [ENVO_01001057](http://purl.obolibrary.org/obo/ENVO_01001057) 'environment associated with a plant part or small plant'
environmental medium of [ENVO_01000349]](http://purl.obolibrary.org/obo/ENVO_01000349) 'root matter'

GOLD-2048 depends on confirming elevation for Corvallis, waiting to hear back from the PI.

**Comment by ssarrafan** [comment]
@aclum @sujaypatil96 based on Alicia's comments that Sujay is working on this already I am changing the status to in progress.

**Comment by aclum** [comment]
These records are in mongo prod can be seen on the dev data portal.
