### ISSUE TITLE
NEON soil metadata translator refactor

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/issues#402]
Comments recorded for the refactor after code review on https://github.com/microbiomedata/nmdc-runtime/pull/251:

- [x] There are helper methods for creating nested object types in the NMDC schema (like `QuantityValue`, `ControlledIdentifiedTermValue`, etc.) in various _translators_ that we've created (_gold_translator_, _neon_translator_, etc.). Unify all of these helper methods in a common base translator class
- [x] Remove external network connections to raw files on GitHub (or any other file servers). Consider one of two things:
  - [ ] Put the files that the program/pipeline uses in the `nmdc-runtime` repository
  - [ ] Since the files being accessed are mostly in the `nmdc-schema` repository, use `pkgutil` to get it from the downloaded dependency
- [x] Rename `neon_data_translator` to `neon_soil_data_translator` (or something along those lines)
- [x] We have two more data translators coming in - `neon_benthic_data_translator` and the `neon_surface_water_translator` so decide how the file/directory structure keeping the future data translators in mind
- [x] Try to modularize the `neon_soil_data_translator` since the `get_database()` method is pretty large (but low priority)

**Comment by ssarrafan** [comment]
Appears to be in progress. I'll move to next sprint.

**Comment by sujaypatil96** [comment]
Excellent! Thank you @ssarrafan. Yes, it is in progress on https://github.com/microbiomedata/nmdc-runtime/pull/308

**Comment by aclum** [comment]
Incorrectly closed from PR

**Comment by ssarrafan** [comment]
@aclum @sujaypatil96 
removing this so I can close the previous sprint, adding backlog label
please add to current sprint if you're planning to work on it

**Comment by sujaypatil96** [comment]
The NEON ingest infrastructure refactor work was teased out from https://github.com/microbiomedata/nmdc-runtime/pull/308 into the [neon-pipeline-refactor](https://github.com/microbiomedata/nmdc-runtime/tree/neon-pipeline-refactor) branch, but haven't opened a draft/ready for review PR for it yet.

**Comment by sujaypatil96** [comment]
I've opened up https://github.com/microbiomedata/nmdc-runtime/pull/448 for review. Once @pkalita-lbl has had the chance to review/approve it, we can close this PR.
