### ISSUE TITLE
Create new Doi class and Migration Code

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/issues#403]

**Comment by ssarrafan** [comment]
@brynnz22  I'll assume this is in the backlog so will remove from old sprint so I can close the sprint. When you work on it again please add to the current active sprint. Thanks.

**Comment by brynnz22** [comment]
Changing this creating a new doi class:

- [ ] Create `Doi` Class
- [ ] Create applicable slots
- `doi`
- `doi_authority`
- `doi_cateogry`
- [ ] Create associative slot: `associated_dois`
- [ ] Update changelog for upcoming changes
- [ ] Write migration code
- Move the one value for `massive_study_identifier` 
- Move `ess_dive_dataset` values
- Move all other `dois`
- [ ] deprecate the slots:
- `dois`
- `dataset_dois`
- `award_dois`
- `publication_dois`
- `ess_dive_datasets`
- `massive_study_identifiers`

**Comment by brynnz22** [comment]
Questions for Montana and Lee Ann:
- [ ] For `DoiProviderEnum` `permissible_values`, I have:
- emsl
- jgi
- kbase
- osti
- ess_dive
- massive
-Are there any others?
- [ ] Thinking `DoiProviderEnum` should not be required (because of publications). Can we make in a note in the comments (for submission schema puproses) that it is required if `award_doi` or `dataset_doi` are selected? Maybe I can model this with `role`?

**Comment by brynnz22** [comment]
- [ ] Can add conditional logic in schema that says if `doi_category` is `dataset_doi` or `award_doi`, then `doi_provider` is required, otherwise it is not required (for `publication_doi`)
- [ ] Otherwise, if we do want to/need to capture the journal then we need to broaden enums (as Lee Ann mentioned in chat)
- [ ] I don't think we need to broaden `doi_category` - although this could be broadened to something like `resource_type`, although Mark is weird about using "type" in slot and I don't get it. For `doi_provider`, not sure if this need to be extended, could this encompass `biosample_category`?

**Comment by brynnz22** [comment]
These changes have been merged into the nmdc-schema main branch
