### ISSUE TITLE
ess dive doi listed in publication slot for study id gold:Gs0135149

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#406]
In checking some other things I noticed the publications slot on class biosample is populated with a ess dive identifier.  It is already also listed in the ess_dive_datasets slot so no need to add it there.

**Comment by aclum** [comment]
@bmeluch  this would be one to check on.

**Comment by bmeluch** [comment]
From the metadata for study [gold:Gs0135149
](https://api.microbiomedata.org/studies/gold%3AGs0135149)
>   "associated_dois": [
>     {
>       "doi_value": "doi:10.25585/1488224",
>       "doi_category": "dataset_doi",
>       "doi_provider": "jgi"
>     },
>     {
>       "doi_value": "doi:10.46936/fics.proj.2017.49991/60006232",
>       "doi_category": "award_doi",
>       "doi_provider": "emsl"
>     },
>     {
>       "doi_value": "doi:10.21952/WTR/1573029",
>       "doi_category": "dataset_doi",
>       "doi_provider": "ess_dive"
>     },
>     {
>       "doi_value": "doi:10.15485/1577267",
>       "doi_category": "dataset_doi",
>       "doi_provider": "ess_dive"
>     }
>   ]

If I'm reading this right, this study has two ESS-DIVE links, one of which ("doi:10.15485/1577267") has landed in the dataset links at the bottom of the study page, and the other of which ("doi:10.21952/WTR/1573029") has landed in the gray DOI/publications box to the right of the page. 
I'm not sure how the study page is assembled or how that would put two DOIs in different places even though they both have `"doi_provider": "ess_dive"`

**Comment by aclum** [comment]
Thanks for checking this @bmeluch. This appears to have been fixed by the study page refresh squad work so can be closed.
