### ISSUE TITLE
mint NMDC `id`s of class FieldResearchSite for the trees

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#41]
Mint FieldResearchSite IDs for the trees

NMDC slots
name - should be the tree name (ie BESC-905-CL1_32_20)
description - "Tree name. Tree name is a composite of genotype, site, and grid coordinates.  Using BESC-905-CL1_32_20 as an example the components are 'BESC-905' is the genotype designation in the GWAS collection. 'CL1' is the replicate number in one of two plantation location where 'CL' is Clatskanie Oregon plantation and 'Co' is Corvallis Oregon plantation. '32-20' is the grid position in that plantation where the tree is planted, in this case row 32, column 20."

**Comment by aclum** [comment]
@sujaypatil96  I'm reopening this b/c you minted the IDs but I don't see any field_research_site_set records for bioscales in mongo so the collected_from information is currently orphaned

**Comment by aclum** [comment]
There is now a field_research_site collection set populated with the correct number of records for bioscales trees.
