### ISSUE TITLE
NMDC and User Facility collaboration documentation

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#414]
**Deliverable this task is associated with**

_See Deliverables tab here:https://docs.google.com/spreadsheets/d/1z_b6WbuTk4pI0Q-Z-rfCgC-8R3m3F2_JDevYuK8CjYE/edit?usp=sharing _

- 4

**RACI**

_Tag people in their roles_
- Responsible: @simroux 
- Accountable:
- Consulted: @emileyfadrosh 
- Informed:

**Describe the the task?**
- [ ] Develop clear documentation about the NMDC relationship with DOE user facilities
- [ ] Develop clear documentation outlining how a user can leverage NMDC for submission to DOE user facilities
- [ ] Provide clear details on what NMDC supports for DOE user facilities

**Criteria for completion**
- Documentation will be available on https://nmdc-documentation.readthedocs.io/en/latest/overview/nmdc_overview.html# 

**Estimate people time**
- ?

**Completion Date (Goal)**
- Oct 20

**Target Sprint Start & End Dates**
- Start: Sept 11
- End: Oct 20

**Tag Blocker/Contingent upon issues**
- [Tagg issues]

**Comment by mslarae13** [comment]
Part of https://github.com/microbiomedata/issues/issues/444

**Comment by simroux** [comment]
For archiving purposes: the two slides attached are the current documentation of current status and future plans for JGI-NMDC coordination. Slide #1 has current situation, proposed immediate (near-term) change, and proposed long-term development. Slide #2 is a schematic view of the proposed near-term change.


[Draft_UFO_JGI-NMDC_2023-10-27.pdf](https://github.com/microbiomedata/issues/files/13191165/Draft_UFO_JGI-NMDC_2023-10-27.pdf)

**Comment by simroux** [comment]
@mslarae13 : Do you want to put your final slide deck you shared yesterday here, and close this issue? I know this will be stalled while waiting for JGI, but I feel the original goal of having a better documentation for how JGI and NMDC interact was achieved ?

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/issues/issues/444

**Comment by ssarrafan** [comment]
> @mslarae13 : Do you want to put your final slide deck you shared yesterday here, and close this issue? I know this will be stalled while waiting for JGI, but I feel the original goal of having a better documentation for how JGI and NMDC interact was achieved ?

@mslarae13 can this issue be closed?

**Comment by ssarrafan** [comment]
Checked with @mslarae13 and @simroux and we can close this issue.  See final slide deck at https://docs.google.com/presentation/d/1js-90z5x-TKzZcfc3rqxclmgkunraNrPRYUubb6NcQ0/edit#slide=id.p
