### ISSUE TITLE
Metadata ingest for biosamples in GOLD - study Gs0154044

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#42]
- [ ] microbiomedata/issues#38
- [x] microbiomedata/issues#41
- [ ] microbiomedata/issues#40
- [ ] microbiomedata/issues#54
- [x] microbiomedata/issues#55

**Comment by turbomam** [comment]
HI @aclum @ssarrafan @sujaypatil96 

This (and it's sub-issues) are important valid, but they don't belong in the nmdc-schema repo. I have moved all of them to the issues repo.

**Comment by aclum** [comment]
Capturing the extra soil metadata depends on GOLD ticket https://issues.jgi.doe.gov/browse/GOLD-2048
I've asked Reddy via email to update the envo triad for the root endosphere samples.  After considering using some PO terms, with Montana's approval we went with some existing envo terms.
local environmental context [ENVO_01001057](http://purl.obolibrary.org/obo/ENVO_01001057) 'environment associated with a plant part or small plant'
environmental medium of [ENVO_01000349]](http://purl.obolibrary.org/obo/ENVO_01000349) 'root matter'

**Comment by aclum** [comment]
Depends on https://github.com/microbiomedata/sample-annotator/pull/113

**Comment by aclum** [comment]
Asked Reddy for an update on https://issues.jgi.doe.gov/browse/GOLD-2048

**Comment by aclum** [comment]
ETA on [GOLD-2048](https://issues.jgi.doe.gov/browse/GOLD-2048) is Friday or Monday (2/6/23)

**Comment by aclum** [comment]
Depends on schema changes to support tax id for host https://github.com/microbiomedata/nmdc-schema/issues/699

Based on the squad meeting discussion @sujaypatil96 will make the following updates 
- collected_from to be populated with an id of class FieldResearchSite
- parse the suffix after '-' in biosampleName and use that to populate the samp_name slot for the biosamples
- `[Add biogeochemical data for soil samples ](https://github.com/microbiomedata/sample-annotator/issues/115)`

**Comment by sujaypatil96** [comment]
The code in the linked PR is already capable of handling points 1 and 2.

**Comment by aclum** [comment]
The soil measurements do not uniquely map to sample names and this requirement will be dropped for now.

**Comment by ssarrafan** [comment]
This looks like it's still in progress so I'll move to the new sprint.
