### ISSUE TITLE
Back up production MongoDB database and `mongo` container to HPSS

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#425]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1lLQ3wAwJzvxujER6-b4iDnnHx06MYsDbmIBMnu1IOeI/edit#gid=0

- 1

**RACI**

_Tag people in their roles_
- Responsible: @eecavanna @shreddd 
- Accountable: @shreddd 
- Consulted:
- Informed:

**Describe the the task**
- [ ] For the napa compliance squad make a permanent backup of the current mongo prod database.
- [ ] Also backup the container that is running in SPIN for mongo

**Criteria for completion**
- Backup of container to run current mongo and back up all the collections (collections listed in Class Database as well as functional_annotation_agg and metap_gene_function_aggregation

**Estimate people time**
-

**Completion Date (Goal)**
- Nov 17

**Target Sprint Start & End Dates**
- Start:Nov 6
- End: Nov 17

**Tag Blocker/Contingent upon issues**
- [Tag issues]

**Comment by eecavanna** [comment]
### Backing up the database

Regarding this part of the task:

> make a permanent backup of the current mongo prod database.

I think @shreddd already does this on a nightly basis. I will confirm with him.

If not, I think I would disable writes (that would impact workflows) and use [mongodump](https://github.com/microbiomedata/infra-admin/blob/main/mongodb/dump-restore-guide.md#dump-database) to dump the database to my local machine (or some other safe storage place).

### Backing up the container

Regarding this other part of the task:

> Also backup the container that is running in SPIN for mongo

I assume this is referring to backing up the Kubernetes **YAML file** that describes—and can be used to recreate—the container. That YAML file can be downloaded from Rancher's web UI.

The container, itself, is an instance of the [bitnami/mongodb:6.0.4](https://hub.docker.com/layers/bitnami/mongodb/6.0.4/images/sha256-e028520f745bb2a82f10a21243f60c687240571c8b2db9886b1ea8f2212a3009?context=explore) Docker image, an off-the-shelf Docker image hosted on DockerHub.

<img width="440" alt="image" src="https://github.com/microbiomedata/issues/assets/134325062/cbe52681-647b-45dc-9178-4950c1dc022d">

**Comment by aclum** [comment]
We need to make sure that we have a copy of mongo that won't get lifecycled into deletion at some point and confirm that it contains all of the collections we need. @shreddd  was the one that mentioned backup up the container, based on what you've said downloading a copy of the YAML file and storing that on HPSS should be sufficient.

**Comment by eecavanna** [comment]
Ah, OK. Thanks, @aclum. Now I understand why you referred to it as a "permanent" backup in the issue description.

OK, I'll confirm with him what he had in mind regarding "backing up the container."

**Comment by aclum** [comment]
We are backlogging this. We will do the mongo backup right after we lock the production database. Target is November for updates to prod.

**Comment by aclum** [comment]
We used the nightly backups.
