### ISSUE TITLE
archive PNNL NMDC workflow data

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#427]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1lLQ3wAwJzvxujER6-b4iDnnHx06MYsDbmIBMnu1IOeI/edit#gid=0

- 1

**RACI**

_Tag people in their roles_
- Responsible: @kfox1111 
- Accountable: @shreddd @lamccue 
- Consulted:
- Informed:

**Describe the the task**
- [ ] Make sure all NMDC workflow data is backup on EMSL tape resources, especially workflow output using legacy identifiers.

**Criteria for completion**
- Workflow output is on DOE tape resources organized by legacy omics_processing_set identifiers. 

**Estimate people time**
- [Hours or days of people time. 1 person, 4 hours]

**Completion Date (Goal)**
- [GOAL!]

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- [Tag issues]

**Comment by aclum** [comment]
@kfox1111  let us know when you can work on this. We need this done either this or next sprint as a lot of the re-iding and reprocessing work depends on this.

**Comment by aclum** [comment]
@kfox1111 would you please check on this and confirm when the last back of the PNNL NMDC workflow data was?

cc @shreddd @lamccue 

We are planning on re-iding on Monday April 22.

**Comment by lamccue** [comment]
As it happened, @corilo dealt with the backup. And we are not currently using the tape archive for technical reasons. The current backup is on MinIO.  
Yuri will also check connections to the workflow output data on Monday after Napa is pushed to production.

**Comment by ssarrafan** [comment]
Re-IDing postponed to May 1st. Moving this issue to the next sprint.

**Comment by aclum** [comment]
Closing as canceled. This data is not on DOE tape but there are two copies of this data, including on minio. Metabolomics and NOM workflow records are not being re-ided on the file system.
