### ISSUE TITLE
Document missing legacy data objects

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#428]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1lLQ3wAwJzvxujER6-b4iDnnHx06MYsDbmIBMnu1IOeI/edit#gid=0

- 1

**RACI**

_Tag people in their roles_
- Responsible: @turbomam 
- Accountable: @aclum 
- Consulted: workflow leads, @SamuelPurvine 
- Informed:

**Describe the the task**
- [ ] Generate a list of id,name,child of WorkflowExecution activity ID for records in data_object_set where the value for slot url does not resolve with a url checker

**Criteria for completion**
- A list of data objects which were missing pre-reidentification efforts. We'll need a list of what WorkflowExecutionActivites generated those data objects to make sure those workflows are being re-run and not just re-id.

**Estimate people time**
- 1 person, 4 hours

**Completion Date (Goal)**
- [GOAL!]

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- [Tag issues]

**Comment by eecavanna** [comment]
I plan to use the [Lychee](https://github.com/lycheeverse/lychee) link checker tool for this.

**Comment by eecavanna** [comment]
I manually visited one of the URLs in the SPARQL query result verbatim.

It took me to an empty (other than the top menu) page on the data portal.

🔴 URL from SPARQL query result: https://data.microbiomedata.org/1393_65601/ReadbasedAnalysis/1393_65601.json

After adding `data/` to the URL (props to @aclum for noticing it was missing), it took me to a JSON file.

🟢 URL with `data/`: https://data.microbiomedata.org/data/1393_65601/ReadbasedAnalysis/1393_65601.json

So, doing this check of all 30,000+ URLs may require—at some stage (i.e. in database, in SPARQL query, or elsewhere downstream)—adding that `data/` segment to each URL.

**Comment by aclum** [comment]
We found the following issues:
-a subset of data_object_set url slots were malformed. This fell into the category of missing the /data/ or having an underscore instead of a colon in the file path (ie https://data.microbiomedata.org/1393_65601/ReadbasedAnalysis/1393_65601.json should be https://data.microbiomedata.org/data/1393_65601/ReadbasedAnalysis/1393_65601.json or https://data.microbiomedata.org/data/nmdc_mta0y710/qa/filterStats.txt should be https://data.microbiomedata.org/data/nmdc:mta0y710/qa/filterStats.txt)
-data objects associated with the first version of the proteomics workflow. These urls all match https://nmdcdemo.emsl.pnnl.gov/*_1781_*. (ie https://nmdcdemo.emsl.pnnl.gov/proteomics/500088_1781_100336_Peptide_Report.tsv) Detailed list of records is in the napa compliance squad folder. Sam confirmed that these files were removed from the minio server. Per Sam 1781 is a jgi proposal id (jgi.proposal:1781), 500088 refers to a mass spec instrument file at EMSL, 100336  the 100336 is a/the sequencing "ID", most likely drawn from IMG.

**Comment by aclum** [comment]
Just need to make a file w/the legacy id, what workflow they came from and the file name.

**Comment by eecavanna** [comment]
Here's a link to the Gist showing how I checked the URLs:
https://gist.github.com/eecavanna/646b1805227cab4c5c27c5db29c7c2df

**Comment by eecavanna** [comment]
It's not clear to me how I can contribute to finishing this task at this point. I could run link checking on a new SPARQL query result, for example; or format the link-checker result in a certain way so that another script could more readily consume it.

**Comment by ssarrafan** [comment]
@aclum  Not really updated in the last 2 weeks. Removing from sprint and adding backlog label.

**Comment by aclum** [comment]
I used pymongo to dump the documents from the data object set records so we have the legacy identifiers for data objects where the data is actually missing, these are stored in the napa compliance google folder as json can't be attached to github issues. I'd wanted to also list the MetaproteomicsAnalysisActivity identifiers that generated these files as output but based on spot checking those records seem to have already been deleted (ie i couldn't find any of the data object identifiers listed in has_output for documents in the metaproteomics_analysis_activity_set collection.
