### ISSUE TITLE
Summarize GROW EMSL data -NOM

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#43]

**Comment by aclum** [comment]
Water samples have been identified, sediment sample mapping is in progress.

**Comment by aclum** [comment]
@ssarrafan  please move this to the next sprint.

**Comment by mslarae13** [comment]
This should be good to close. Sam completed the mapping: https://docs.google.com/spreadsheets/d/18GnMcz-qmJS9uaeyD5DH4WdPSh0zg3FIRyKJFbUS498/edit?usp=sharing

Next step is Sujay to give Yuri the NMDC IDs for the GOLD matching samples. And then he can process. & will make IDs for the samples that don't have a GOLD match

**Comment by SamuelPurvine** [comment]
The NMDC IDs should be already mapped as well in the file I added to...
