### ISSUE TITLE
Napa compliance - gold:Gs0114663 - metagenomes

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#430]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1lLQ3wAwJzvxujER6-b4iDnnHx06MYsDbmIBMnu1IOeI/edit#gid=0

- 2

**RACI**

_Tag people in their roles_
- Responsible:
- Accountable: @scanon, @hubin-keio 
- Consulted:
- Informed:

**Describe the the task**
- [ ] re-id study_set -> data_object_set records
- [ ] Follow [workflow diagram](https://app.diagrams.net/?mode=google&gfw=1#G1SVBuSWitbp6GyIGTxbU4LqExfNMuncbk) to delete records and re-process from annotation onward

**Criteria for completion**
- 50 metagenomes for project have napa compliant identifiers for study -> data objects. Annotation w/5.2 is run, new binning workflow is run.

**Estimate people time**
- 

**Completion Date (Goal)**
- [GOAL!]

**Target Sprint Start & End Dates**
- Start: Sept 25 
- End: Oct 20

**Tag Blocker/Contingent upon issues**
- [Tag issues]

**Comment by aclum** [comment]
I've re-id the study_set record and the biosample records (for the whole study). I should be able to update the omics_processing_set records tomorrow.
This will go into the next sprint for the work on new workflow execution activities and data objects.

**Comment by ssarrafan** [comment]
Not updated in the last 2 weeks. Removing from sprint and adding backlog label.

**Comment by aclum** [comment]
I plan to update the omics processing set records early next week so moving to the next sprint.

**Comment by Michal-Babins** [comment]
I think me and @mbthornton-lbl are close to having what we want. We can pull down all the records, re-id, do the necessary file operations, and create the updated database_object for them, but we need to do more testing and more clean up. Right now we want to write all the updated objects out to a json. This way we can share it and have more eyes on it. We can also validate against the old records, making sure every 1:1 transformation has occurred. We also need to back propagate the has_input of reads_qc_analysis_activity_set  to the corresponding omics_processing_set. Should be able to share by next weeks meeting. 

Code can be found here:
https://github.com/microbiomedata/nmdc_automation/tree/re_iding/nmdc_automation/re_iding

**Comment by aclum** [comment]
should be moved to the next sprint.

**Comment by aclum** [comment]
We've had a few rounds of reviewing the code to generate the new data objects and workflow exeuction activity records. The last thing to sort out is what to put for git_url and version. Waiting for input from Shane. Moving to the next sprint.

**Comment by Michal-Babins** [comment]
I have pushed the data_objects and activity_sets to the napa mongo instance for Stegen. @mbthornton-lbl will work on creating a changesheet feature to update the changes to the omics_processing_set.

**Comment by aclum** [comment]
Michael applied the changesheets to the omics record this week after Eric set up dagster for napa mongo (required for some API endpoints)
To check on next week:
- [ ] were the old workflow execution activity records 
- [ ] make sure functional_annotation_agg records are deleted based workflow execution activity ID.

moving to the next sprint since this is actively in progress.

**Comment by aclum** [comment]
@Michal-Babins  were new annotation workflow results triggered?

**Comment by Michal-Babins** [comment]
I will take a look. I will set up an instance against the napa api.

**Comment by Michal-Babins** [comment]
Working with @eecavanna and @scanon to set up a scheduler instance against the napa namespace

**Comment by Michal-Babins** [comment]
I have added methods to delete old data objects, activity records, and functional aggregations. I have tested out the endpoint /queries/run for deleting and it works. @aclum I can go ahead and delete all old records for spruce or wait at this point. 

@scanon I am struggling to get the correct job to be made on the nmdc-napa scheduler instance and I am not sure why. I see the branch of the source code on there is from a branch called scanon/features. I'm not sure if that is correct or not. Will need your help to move forward.

**Comment by ssarrafan** [comment]
Appears to be in progress. Will move to the next sprint. @Michal-Babins @aclum let me know if it should be removed.

**Comment by aclum** [comment]
Let's finish getting the stegen project finished. It is more important to have at least a few new annotation records so @picowatt  and @SamuelPurvine  can test the metap code.

**Comment by aclum** [comment]
Perlmutter was down yesterday so it is not expected that these finish before people take off for the holidays. Moving to the first sprint in January.

**Comment by aclum** [comment]
@Michal-Babins  is working on getting cromwell back up to run the test datasets.

**Comment by Michal-Babins** [comment]
I worked with @SamuelPurvine to get records with corresponding proteomics data processing for annotation.

**Comment by aclum** [comment]
Michal was able to generate some annotation results for Cam to test with.
