### ISSUE TITLE
napa  compliance - deal with md5sum duplicate data objects

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#431]
**Deliverable this task is associated with**

https://docs.google.com/spreadsheets/d/1lLQ3wAwJzvxujER6-b4iDnnHx06MYsDbmIBMnu1IOeI/edit#gid=0

- 1

**RACI**

_Tag people in their roles_
- Responsible: @scanon 
- Accountable: @aclum 
- Consulted:
- Informed:

**Describe the the task**
- [ ] review data object names that share a data object ID. This is an edge case from when md5sum was used to populate slot ID and needs to be reviewed as part of the napa compliance squad work.

**Criteria for completion**
- Review data_object_set records which share and id, anything related to mg annotation or mg binning or proteomics will be deleted, records from other workflows need a napa complaint identifier. data_object_set record and the workflow execution activity has_output slot needs to be updated at the same time. 

**Estimate people time**
- 1 person, 8 hours

**Completion Date (Goal)**
- [GOAL!]

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- [Tag issues]

**Comment by aclum** [comment]
Hopefully this is the same as your list @scanon , this is what I got from the rdf version of the nmdc database
These are the duplicate identifier (md5sum) values that are used in has_output slots

count of has_output | data_object_set.id | Database.slot
-- | -- | --
3 | https://w3id.org/nmdc/1dd6f4da00585325ed0e9d779105cdb7 | mags_activity_set
105 | https://w3id.org/nmdc/425873a08e598b0ca2987ff7b9b5da1f | read_based_analysis_activity_set
2 | https://w3id.org/nmdc/427fdb4e0131c092cc98a236d41f4944 | mags_activity_set
2 | https://w3id.org/nmdc/6147d3df37207319ed29ba030d50996d | mags_activity_set
2 | https://w3id.org/nmdc/7d25329b8925dc9195bad30e6f5f9923 | mags_activity_set
2 | https://w3id.org/nmdc/81b950f7d3df977ca5a0a09769470b5b | mags_activity_set
2 | https://w3id.org/nmdc/967df797a098888771ad3ea575eac9bf | mags_activity_set
2 | https://w3id.org/nmdc/a7cfcdc9f9eea0ad501fb527fc5614fa | mags_activity_set
285 | https://w3id.org/nmdc/d41d8cd98f00b204e9800998ecf8427e | mags_activity_set
105 | https://w3id.org/nmdc/dc2e21becda8d6b010a95897cf97ae90 | read_based_analysis_activity_set
2 | https://w3id.org/nmdc/ddaf420fd99f31859dfa05988c414e2d | mags_activity_set
2 | https://w3id.org/nmdc/e4b4bcf168449f645d9eb0329e6c408c | mags_activity_set
2 | https://w3id.org/nmdc/e8bdcd7b113a14b29a3026b73cd18c20 | mags_activity_set

[This](http://3.236.215.220:7200/sparql?name=&infer=true&sameAs=true&query=PREFIX%20nmdc%3A%20%3Chttps%3A%2F%2Fw3id.org%2Fnmdc%2F%3E%0A%0Aselect%20*%20where%20%7B%20%0A%20%20%20%20%7B%3Fs%20%3Fp%20nmdc%3A1dd6f4da00585325ed0e9d779105cdb7%7D%0A%20%20%20%20UNION%0A%20%20%20%20%7B%3Fs%20%3Fp%20nmdc%3A425873a08e598b0ca2987ff7b9b5da1f%7D%0A%20%20%20%20UNION%0A%20%20%20%20%7B%3Fs%20%3Fp%20nmdc%3A427fdb4e0131c092cc98a236d41f4944%7D%0A%20%20%20%20UNION%0A%20%20%20%20%7B%3Fs%20%3Fp%20nmdc%3A6147d3df37207319ed29ba030d50996d%7D%0A%20%20%20%20UNION%0A%20%20%20%20%7B%3Fs%20%3Fp%20nmdc%3A7d25329b8925dc9195bad30e6f5f9923%7D%0A%20%20%20%20UNION%0A%20%20%20%20%7B%3Fs%20%3Fp%20nmdc%3A81b950f7d3df977ca5a0a09769470b5b%7D%0A%20%20%20%20UNION%20%0A%20%20%20%20%7B%3Fs%20%3Fp%20nmdc%3A967df797a098888771ad3ea575eac9bf%7D%0A%20%20%20%20UNION%0A%20%20%20%20%7B%3Fs%20%3Fp%20nmdc%3Aa7cfcdc9f9eea0ad501fb527fc5614fa%7D%0A%20%20%20%20UNION%20%0A%20%20%20%20%7B%3Fs%20%3Fp%20nmdc%3Ad41d8cd98f00b204e9800998ecf8427e%7D%0A%20%20%20%20UNION%0A%20%20%20%20%7B%3Fs%20%3Fp%20nmdc%3Adc2e21becda8d6b010a95897cf97ae90%7D%0A%20%20%20%20UNION%0A%20%20%20%20%7B%3Fs%20%3Fp%20nmdc%3Addaf420fd99f31859dfa05988c414e2d%7D%0A%20%20%20%20UNION%20%0A%20%20%20%20%7B%3Fs%20%3Fp%20nmdc%3Ae4b4bcf168449f645d9eb0329e6c408c%7D%0A%20%20%20%20UNION%0A%20%20%20%20%7B%3Fs%20%3Fp%20nmdc%3Ae8bdcd7b113a14b29a3026b73cd18c20%7D%0A%7D%20limit%201000%20%0A%0A%0A) is an rdf query to get the identifiers of the workflow execution activity records. 
We'll be deleting and reprocessing the MAG results so what needs to be fixed are the records in read_based_analysis_activity_set that have values of `has_output` of `nmdc:425873a08e598b0ca2987ff7b9b5da1f` or `nmdc:dc2e21becda8d6b010a95897cf97ae90` The value of has_output needs to be updated in read_based_analysis_activity_set as well as creating a new records in the data_object_set. Curently there is one data object record per md5sum.

**Comment by scanon** [comment]
That's pretty close to what I was seeing.  Ignoring the mags (since they will be redone), there are two buckets I'm seeing an empty file (that is the dc2e one) and a TSV file that has a common header but no data/rows that both show up in RBA.  I do see more because you queried against the old name I think, but the same in principle.

In thinking about this more, I'm inclined to just generate new data objects and activities entirely because that will be just as easy.  I will make another comment that will outline the process I would use.

**Comment by scanon** [comment]
Actually I will put this in a new issue because it also touches on what we need to do to fix up file locations.

**Comment by turbomam** [comment]
> Actually I will put this in a new issue because it also touches on what we need to do to fix up file locations.

Have you created the new issue yet @scanon ? If so, please link it here.

**Comment by aclum** [comment]
Thinking about moving this to the backlog since it will get resolved concurrently with the re-iding since we are making new data objects. @scanon  let me know if that isn't the case and this needs to be resolved before the re-id.

**Comment by aclum** [comment]
This was resolved with re-iding. All data objects are unique now.
