### ISSUE TITLE
Determine what slots are needed  / updates for pacbio (discuss with Christa)

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#433]
For accurate capture of PacBio, some updates to the schema will be needed

- [ ] Absorbance 260/280* (required for metagenome improved drafts or any PacBio libraries) = [dna_absorb1](https://microbiomedata.github.io/nmdc-schema/dna_absorb1/)
- [ ] Absorbance 260/230* (required for metagenome improved drafts or any PacBio libraries) = [dna_absorb2](https://microbiomedata.github.io/nmdc-schema/dna_absorb2/)

**Comment by mslarae13** [comment]
Part of https://github.com/microbiomedata/issues/issues/444

**Comment by mslarae13** [comment]
My suggestion to do this is add the different types of metaGs to the "JGI" data type selection. For the different JGI metaG or T data types a different interface / tab is avaible in the metadata form..

@pkalita-lbl I want to talk about this at our next meeting to see if it's possible.

@emileyfadrosh curious on your thoughts about the priority level for this.
Specifically, we can collect all the JGI required metadata, but some fields that aren't required for metagenomes are required for the pacbio metagenomes. Should I just check this slot when we get metadata for pacbio? Or do we need to implement a programmatic check & validation NOW?

**Comment by mslarae13** [comment]
Christa confirmed 
"the additional validation that you mentioned is the only difference between those and the standard Illumina MG products. "

**Comment by ssarrafan** [comment]
@mslarae13 who is this assigned to?  Should it be in the current sprint?
