### ISSUE TITLE
Milestone - Enable high bandwidth transfer mechanisms for NMDC data (1.14)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#446]
High-performance Data Transfer
Transferring raw omics data across the wide-area network (Figure 4, H), especially sequencing data that
are often multiple terabytes, can take several days to finish using traditional web protocols. To solve this
problem, we will enable high-bandwidth data transfer mechanisms (Milestone 1.14). We propose using
Globus62, a secured high-performance data transfer service allowing users to transfer large amounts of
data between systems within and across organizations. Globus presents a secure, unified interface to
research data. It can tune performance parameters, maintain security, monitor progress, validate
correctness and resume transfers if there is an interruption. Globus will enable high-performance data
transfer across DOE facilities, as well as between NMDC EDGE, other NMDC resources and external
systems such as KBase. Efficient and automated data transfer will play an important role in streamlining
pre- and post-workflow processing steps across facilities.

Pages 26-27

**Comment by ssarrafan** [comment]
@shreddd is discussing this with the EMSL team. 
FYI @emileyfadrosh  let me know if we should move this to Q2

**Comment by aclum** [comment]
This is in progress, we have a globus endpoint at NERSC @shreddd  is working with @lamccue to get a globus endpoint set up on EMSL
An action item is to advertise the NERSC globus endpoint.

**Comment by ssarrafan** [comment]
Tahoma was down today. the JGI-EMSL coordination meeting was canceled so we don't have an update on this. We can check with the EMSL team once they are done putting out fires.

**Comment by ssarrafan** [comment]
Moving this to Q2

**Comment by ssarrafan** [comment]
Globus endpoint is set up for NMDC at EMSL as of this week as reported by Dave C.

**Comment by ssarrafan** [comment]
Globus endpoint is set up for NMDC at EMSL as of this week as reported by Dave C. 
I'm closing this.  @shreddd if you want to keep it open let me know.

**Comment by shreddd** [comment]
We need to test, productionize and document the solution so there are still some steps left before we can close.

**Comment by ssarrafan** [comment]
@shreddd can this be tested/documented and closed now?

**Comment by aclum** [comment]
@shreddd  what is the update on this?

**Comment by ssarrafan** [comment]
@shreddd can this be closed?

**Comment by shreddd** [comment]
I think the milestone can be closed, but we need to make a ticket to update our docs for this.

**Comment by ssarrafan** [comment]
Closing this per Shreyas. It's already marked done on the milestones spreadsheet.  
I created a new documentation issue for this and assigned it to Shreyas.
https://github.com/microbiomedata/NMDC_documentation/issues/66
