### ISSUE TITLE
Milestone - Assembly support for long-read sequence data (2.13) DUE

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#454]
Support for metagenome assembly of long-read sequence data
Over the past several years, the JGI has increasingly supported metagenome sequencing with the PacBio
platform because library preparation methods have improved and lower inputs of DNA are supported
(19). Long-read sequencing provides vastly improved metagenome assemblies, moving closer to
reconstruction of complete, closed genomes from microbiome samples. The NMDC will coordinate with
the JGI for a PacBio assembly workflow, and develop a new WDL workflow that will be standardized to
work with downstream workflows, such as metagenome annotation. In addition, we will identify existing
projects with PacBio data for benchmarking purposes (Milestone 2.13).

Page 32

**Comment by ssarrafan** [comment]
@aclum any update on this? Any concerns about this getting done by the end of March 2024?

**Comment by mslarae13** [comment]
UFO squad is working on this.
@pkalita-lbl this is the long read metaG work. For the submission portal, how are you feeling about this deadline? We said 'due in dev by feb 23rd' for UFO.

IDK who is working on the workflow?

**Comment by pkalita-lbl** [comment]
It won't be on dev by Feb 23rd. I think the portal work can be done by the end of March.

**Comment by aclum** [comment]
@kaijli  is working on this and we should be on track to finish this by the end of March.

**Comment by kaijli** [comment]
Updated the [longreads branch](https://github.com/microbiomedata/metaAssembly/tree/longreads) to include `makeinfo task` and Chien-Chi fixed the error for SAMTOOLS statistics reading. Uploaded output file to Perlmutter at `/global/homes/k/kli/metaAssembly/testResults03132024` and notified @aclum to look them over. 

The `makeinfo task` is written on the `metaflye.wdl` file in the GitLab submodule that I have pulled, so the changes can't be seen on the GitHub repo. I have all the edits (adding version calls for different tools in various files) committed to a local branch. Looking for guidance on how to implement changes with JGI.

**Comment by aclum** [comment]
We should coordinate this with Robert.

**Comment by ssarrafan** [comment]
Marked as complete on DOE quarterly report today! Woot!

**Comment by aclum** [comment]
@kaijli  We need a task to make the nmdc ids. The short read workflow has call-finish_asm but I dont see this task in your example data.

**Comment by aclum** [comment]
Discussed over slack last week but we are also missing the tool name in the info file, nmdc_xxxxxxx_metaAsm.info

**Comment by aclum** [comment]
JGI stores the following files:
assembly.contigs.fa  corresponds to final_contigs
contigs.sam corresponds to final_sam
contigs.sorted.bam.cov corresponds to final_pileup_out
JGI stores a PDF and txt version of a readme whereas we generate the info file

**Comment by kaijli** [comment]
> @kaijli We need a task to make the nmdc ids. The short read workflow has call-finish_asm but I dont see this task in your example data.
 
Is this a task to be written in choose_assembly.wdl or in metaflye.wdl? Is it JGI or NMDC specific?


> Discussed over slack last week but we are also missing the tool name in the info file, nmdc_xxxxxxx_metaAsm.info

I add the tool name to nmdc_xxxxxxx_metaAsm.info to the new test output directory in `/global/homes/k/kli/metaAssembly/testResults03292024` (though I might have neglected to chmod it). 


> JGI stores the following files: assembly.contigs.fa corresponds to final_contigs contigs.sam corresponds to final_sam contigs.sorted.bam.cov corresponds to final_pileup_out JGI stores a PDF and txt version of a readme whereas we generate the info file

Is this how the output should be formatted through finish_asm? A little confused on what this comment is for. 

@aclum

**Comment by aclum** [comment]
those comments are just to make sure the correct files are getting the NMDC identifiers.

For other workflows the finalizing tasks are in the NMDC wdls so you could put this in choose_assembly.wdl. The short read workflow has this in jgi_assembly.wdl
