### ISSUE TITLE
Milestone - Metaproteomics workflow updated to remove matched metagenome requirement (2.14.2) DUE

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#455]
Expanding the metaproteomics workflow
There are two limitations of the current metaproteomics workflow that limit its utility for the community,
(i) peptide sequence identification currently requires a matched metagenome for streamlined query, and
(ii) all data sets are treated independently which precludes sample comparisons by relative quantitation.
To provide an alternative workflow that removes the requirement for a metagenome, the
metaproteomics workflow will use an EMSL developed tool75 that uses a machine learning model to
identify peptide sequences de novo, and then uses these sequences to predict taxonomy and derive a
pseudo-metagenome for use as the input database (Milestone 2.14).

Page 32

**Comment by ssarrafan** [comment]
Rescheduled for Q4 of this year per the milestones spreadsheet.  

Also renamed:  (MODIFIED) Modify reference metagenome-independent metaproteomics workflow; retrain the peptide-spectrum ML model, and redesign protein sequence database generation

**Comment by aclum** [comment]
per checkin meeting @picowatt thinks we are on track for this quarter. cc @SamuelPurvine

**Comment by ssarrafan** [comment]
> per checkin meeting @picowatt thinks we are on track for this quarter. cc @SamuelPurvine

@picowatt @SamuelPurvine @aclum is this done?  Can you please send me an update here and/or add some accomplishments to the DOE quarterly report at https://docs.google.com/document/d/14fpK-YA352WB6Ucm8XNpMfBaGFDz_HH5VRfyjROpZ4c/edit

**Comment by lamccue** [comment]
Marked as complete in FY24 Q4 DOE report with comment:
The de novo peptide-spectrum ML model has been updated to a transformer model and retrained using annotated spectra from an expanded biodiversity dataset. Methods to generate the protein sequence database from UniProt have been implemented.
