### ISSUE TITLE
GROW - Ingest GOLD study Gs0149396

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#46]
We can fetch basic information from the GOLD API study 
```
curl -X 'GET' \
  'https://gold-ws.jgi.doe.gov/api/v1/studies?studyGoldId=Gs0149396' \
  -H 'accept: */*'
```

slots to be populated via ingest scripts or change sheets post ingest

ess_dive_datasets
https://data.ess-dive.lbl.gov/view/doi:10.15485/1603775
https://data.ess-dive.lbl.gov/view/doi:10.15485/1729719

@cmungall  @SamuelPurvine @emileyfadrosh  are there other ESS-DIVE identifiers besides the ones I've listed? 

doi 
https://doi.org/10.46936/10.25585/60001289

websites
https://www.pnnl.gov/projects/WHONDRS
https://narrative.kbase.us/#org/grow
https://orcid.org/0000-0003-0434-4217
https://microbialecosystemslab.com/

funding_sources
“This study used data from the Worldwide Hydrobiogeochemistry Observation Network for Dynamic River Systems (WHONDRS) under the Perturbation Response Traits project at the Pacific Northwest National Laboratory (PNNL). This research was supported by the U.S. Department of Energy (DOE) Early Career Research Program. A portion of this work was performed at the U.S. Department of Energy Environmental Molecular Science Laboratory User Facility. PNNL is operated by Battelle Memorial Institute for the U.S. Department of Energy under Contract No. DE-AC05-76RL01830."
"This study used data from the Worldwide Hydrobiogeochemistry Observation Network for Dynamic River Systems (WHONDRS) under the River Corridor Science Focus Area (SFA) at the Pacific Northwest National Laboratory (PNNL). This research was supported by the U.S. Department of Energy (DOE), Office of Biological and Environmental Research (BER), Environmental System Science (ESS) Program. A portion of this work was performed at the U.S. Department of Energy Environmental Molecular Science Laboratory User Facility. PNNL is operated by Battelle Memorial Institute for the U.S. Department of Energy under Contract No. DE-AC05-76RL01830.”
"The work (proposal: https://doi.org/10.46936/10.25585/60001289) conducted by the U.S. Department of Energy Joint Genome Institute (https://ror.org/04xm1d337), a DOE Office of Science User Facility, is supported by the Office of Science of the U.S. Department of Energy operated under Contract No. DE-AC02-05CH11231.”

**Comment by sujaypatil96** [comment]
The latest JSON export from the pipeline contains this additional information manually added to it.

**Comment by ssarrafan** [comment]
@aclum is this still "in review" and who needs to review it?  
I'll move to the next sprint to update

**Comment by aclum** [comment]
This was completed this week as part of sprint 6, it apparently wasn't associated with a pull request like some of the other tickets so closing manually.
