### ISSUE TITLE
Determine feasibility of sharing MAG data with SeqCode for novel taxonomy nomenclature additions (2.22) DUE

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#462]
Reference database augmentation
Easy to access and well curated reference databases empower open-source research and help scale the
impact of microbiome research. NMDC will partner with the SeqCode Initiative (see Letter of Support) to
expand the current list of bacterial and archaeal taxa by incorporating data inferred by genome sequences
and providing new taxonomic names to microbes that have yet to be cultured but whose genomes have
been interrogated. To provide more taxonomic context for microbiomes under study, and to support
broad community adoption of the SeqCode taxonomy and nomenclature system, the NMDC will work
directly with the SeqCode development team to outline a plan to update our sequence-based reference
genome and taxonomy databases (Milestone 2.21). Together with the proposed new viral workflow
above, this effort will enable NMDC metagenomes and metatranscriptomes to be annotated with the
current SeqCode and ICTV taxonomies, and aligns with development activities to update the Pilot
metagenome workflow to the current JGI-production version (see An updated metagenome annotation
workflow). Our development teams will explore the feasibility of sharing metagenome bin data which
passes SeqCode criteria for taxonomic registration76, to directly support and expand the SeqCode
taxonomy with new data that will be processed and hosted in the NMDC Data Portal (Milestone 2.22).

Page 34

**Comment by aclum** [comment]
@ssarrafan  can this be closed? There appear to be two duplicate tickets already which are closed.

**Comment by ssarrafan** [comment]
> @ssarrafan can this be closed? There appear to be two duplicate tickets already which are closed.

It's still marked as not completed on the milestones doc.  @emileyfadrosh can we mark this as done? 
This was a repeating milestone which is why there are a few different GitHub issues for it.

**Comment by emileyfadrosh** [comment]
Yes, done! @ssarrafan I'll let you close, thank you.

**Comment by ssarrafan** [comment]
It has been determined that sharing data with SeqCode directly is not feasible due to manual processes and limited support from the current SeqCode staff. The SeqCode Registry & Nomenclature Working Group continues to meet quarterly, although no dedicated funding exists for the SeqCode. The registry has a basic portal here:[ https://disc-genomics.uibk.ac.at/seqcode](https://disc-genomics.uibk.ac.at/seqcode) and code here:[ https://github.com/seq-code/registry](https://github.com/seq-code/registry). While there is a basic API, documentation is not available. It was confirmed that GTDB is able to sync with the SeqCode registry and any updates to GTDB would include the latest taxonomy. Since JGI uses GTDB for taxonomic assignments for MAGs, we can keep aligned with the updated taxonomy through updates with the binning pipeline. SeqCode staff can use the NMDC API to collect MAGs for nomenclature additions.
 
We will stay involved in the WG to see whether they are able to secure stable funding, and reassess our strategy if there is a future path to connect directly.
