### ISSUE TITLE
GROW- ingest biosamples in GOLD for GOLD study Gs0149396

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#47]

**Comment by aclum** [comment]
We identified samples in GOLD which do not have mixs env_broad_scale, env_local_scale, env_medium and asked the collaborators how they'd like it populated for the river sediment samples. Makayla's suggestion was 
envoBroadScale id: freshwater river biome ENVO_01000253
envoLocalScale id: river ENVO_00000022
envoMedium id: sediment ENVO:00002007

I've emailed Reddy to ask him to update these and to update the one river surface biosample, Gb0260961, that was missing this information.

**Comment by sujaypatil96** [comment]
Completed.

**Comment by ssarrafan** [comment]
I'm closing this one based on @sujaypatil96 comment. Yay!
