### ISSUE TITLE
Milestone - Perform user research to refine the Data Portal user experience (4.1) FY24 Q2/FY25 Q2

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#476]
Community Engagement, Outreach & Sustainable Partnerships
During the Pilot, we have seen a steady growth in our online community engagement, as indicated by
metrics on our social media account, the Data Portal, NMDC website, and NMDC EDGE (Appendix 16). To
continue this engagement, we developed the NMDC Pilot Engagement Strategy (Appendix 13) in July 2021
to articulate goals, activities and tasks aligned with infrastructure deliverables (Task 4.1). This strategy has
two focus areas: establishing long-term relationships with key stakeholders within the DOE complex and
supporting the long-term vision and sustainability of the NMDC program (Task 4.4 and Task 4.6). The 12-
month Pilot Extension (Appendix 2) included progress towards integration with ESS-DIVE and KBase, along
with developing a partnership with NSF’s NEON (Task 5.1 and Task 5.2). Since the DOE Review in August
2020, engagement and outreach activities have focused on deepening collaborations with the ASM and
MCC and responding to engagement recommendations from our SAB. These recommendations led to the
launch of the NMDC Community Conversations webinar series32, partnering on an intensive multi-omics
summer training program33, and focusing on creating comprehensive documentation and training across
the NMDC resources (Task 4.5). Highlights of our work are included in Appendix 17.
Page 10

See #477  #478  #479

**Comment by ssarrafan** [comment]
A framework and schedule was created for user research and usability testing; Submission Portal and EDGE user research rounds completed and a new round of Data Portal user testing will be done in 2024.

**Comment by aclum** [comment]
Rescheduled to Q2, Leah and I met about this last week.

**Comment by ssarrafan** [comment]
@aclum @ljohnson09 any update on this milestone? Will this be done by the end of March 2024?

**Comment by ljohnson09** [comment]
@ssarrafan This will be completed by end of March 2024! Actually implementing the action items will be a separate squad, depending on how @aclum would like to handle it and the effort of the items (e.g., one UR action items squad, building in action items into other related squads, some might need their own squad...).

**Comment by shreddd** [comment]
This should be open until we complete the work

**Comment by ssarrafan** [comment]
@ljohnson09 @shreddd @aclum I believe the user research is done for this round. I'm moving this milestone GH issue to 2025 Q2 for the next round.  Updates from DOE quarterly:

A framework and schedule was created for user research and usability testing, and has been successfully implemented for the Submission Portal and NMDC EDGE. User research was performed on the Data Portal in FY24 Q2. From user interviews, 136 insights were compiled into 42 action items. Action items include feature updates to the data summary visualizations, improvements to the bulk data download, and improving accessibility of metadata within the Data Portal.

**Comment by aclum** [comment]
@ssarrafan can you check the roadmap, we have two tickets for this, one says FY25 Q2 and the other says FY25 Q3. We only need ticket since this should happen once per year.

**Comment by ssarrafan** [comment]
> @ssarrafan can you check the roadmap, we have two tickets for this, one says FY25 Q2 and the other says FY25 Q3. We only need ticket since this should happen once per year.

This ticket is for FY25Q2.

**Comment by aclum** [comment]
I am closing this since the roadmap has the user research for FY25 as in Q3 and there is already a ticket for that.
