### ISSUE TITLE
Bioscales metabolomics

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#48]
Link existing metabolomics data in MASSIVE to the NMDC study page
MASSIVE record 
https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?task=83574f41458a4b259621d5c32a4d82f9

**Comment by aclum** [comment]
https://github.com/microbiomedata/nmdc-schema/issues/642 has been resolved.
massive_study_identifiers is part of external_identifiers.yaml in schema v7.4.1

**Comment by aclum** [comment]
duplicated by https://github.com/microbiomedata/issues/issues/38
