### ISSUE TITLE
GROW - Metadata ingest for NOM only samples

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#49]
This issue is to ingest biosample metadata into NMDC for samples that are not in GOLD. 
Depends on 
- [x] https://github.com/microbiomedata/issues/issues/43

Requires defining mixs environmental triad

**Comment by ssarrafan** [comment]
Moving to next sprint per @aclum

**Comment by ssarrafan** [comment]
Done per @corilo, closing issue

**Comment by aclum** [comment]
Per Yuri adding to this sprint.

**Comment by ssarrafan** [comment]
@aclum @corilo removing from sprint, adding backlog label

**Comment by aclum** [comment]
New estimate is next week per Yuri's email. Current metadata is missing lat lon inforamtion

**Comment by aclum** [comment]
New records are in mongo prod
