### ISSUE TITLE
GROW - Ingest JGI sequencing and analysis data records for metagenomes

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#50]
GOLD study Gs0149396
There are 291 metagenomes.

**Comment by aclum** [comment]
@ssarrafan  this should go in the sprint that starts Monday.

**Comment by ssarrafan** [comment]
@aclum @mflynn-lanl @shreddd I believe this is actively being worked on so I'll move to the next sprint but let me know if that's not the case

**Comment by aclum** [comment]
60 sequencing projects have multiple APs, those will likely not get processed before GSP
4 sequencing projects had issues with visibly on the JGI side which JGI staff resolved quickly
3 sequencing projects are not displaying the filtered data in jgi's data portal because of incorrect analysis project metadata

Other challenges include API errors, Alex P. increased the timeout, limits on the API restore requests to 10 TB of data at a time, and slow/variable data transfer speeds with globus likely related to NERSC filesystem problems.

**Comment by ssarrafan** [comment]
I heard from @aclum that this is still in progress so I'll move it to the next sprint.  @mflynn-lanl let me know if you have an update.

**Comment by ssarrafan** [comment]
@mflynn-lanl I think this is also done so I'll close.  Let me know if it should not be closed. @aclum FYI
