### ISSUE TITLE
Milestone - Sample Jupyter and RStudio notebooks available that highlight NMDC data and metadata (2.26)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#512]
The NMDC will add capabilities to enable advanced custom data exploration in an interactive form. Our
intent is not to develop a new platform, instead we will focus on deepening relationships with key
stakeholders by connecting NMDC data with notebooks launched on existing Jupyter / RStudio services
offered by DOE or cloud providers (e.g., NERSC JupyterHub, Google Colab, Binder). The goal of these
notebooks is to provide users with the ability to combine interactive live code execution with inline
documentation and visualizations (Milestone 2.26). These notebooks can be automatically generated
from data and analyses of interest, and spun up in real-time on users’ personal computers or existing
computing infrastructure. There is a compelling training and education component to this approach, since
live notebooks are ideally suited to providing hands-on examples showing users how to interact with and
analyze NMDC data. This approach will also serve as a model for how users can access data and run NMDC
workflows in KBase (see Integration with DOE KBase).

Page 38

**Comment by kheal** [comment]
FYI, this work is being tracked by the notebook squad here: https://github.com/orgs/microbiomedata/projects/131 .

**Comment by ssarrafan** [comment]
@kheal @cmungall @shreddd what's the possibility of this being completed by September? This milestone is due in September, this quarter.

**Comment by kheal** [comment]
We're in good shape for two new notebooks by the end of September to explore NOM data.  We've already added one new one here: https://github.com/microbiomedata/nmdc_notebooks/pull/42 .

**Comment by kheal** [comment]
Notebook squad (@samobermiller @brynnz22 @bmeluch and myself) has completed this milestone with https://github.com/microbiomedata/nmdc_notebooks/pull/68 and https://github.com/microbiomedata/nmdc_notebooks/pull/69 .  

FYI @aclum @ssarrafan @cmungall @shreddd

**Comment by ssarrafan** [comment]
@emileyfadrosh this is listed as a recurring milestone. Are you expecting anything else to be done for milestone 2.26 by September?

**Comment by samobermiller** [comment]
@ssarrafan the PRs closing this out in September FY24 were for the NOM notebook. In Q2-3 FY25 we made a multi omic analysis notebook, a proteomic aggregation notebook and a protein enrichment notebook....so if this is recurring I think this could still be considered completed?
