### ISSUE TITLE
Milestone - Deploy a fully functional public API to support programmatic data access and exploration (4.10)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#516]
Programmatic access to NMDC data for broad community use
Web APIs enable programmatic access to data and computation in a scalable, automated fashion. This
allows users to orchestrate data access into scriptable tools, and is key to enabling complex, repeatable
interactions with the data. They also enable integrations with other web services. We will enable a public
web API for the NMDC to allow broad access to our data for programmatic and automated access (Data
Portal, Milestone 4.7 & 4.10). The

Pages 35-36

**Comment by aclum** [comment]
I'd like the goal for this quarter to be to have an endpoint that traverses collections. This should line up with squad work already in progress.

**Comment by ssarrafan** [comment]
> I'd like the goal for this quarter to be to have an endpoint that traverses collections. This should line up with squad work already in progress.

@shreddd will this be possible to complete by September?

**Comment by aclum** [comment]
This is the ticket we are going to use to say this milestone is complete for this quarter 
https://github.com/microbiomedata/nmdc-runtime/issues/401

**Comment by aclum** [comment]
Backend changes were made this quarter to make traversing collections to return data objects for a study robust to future schema changes (alldocs). Additionally, indexing was added to eliminate timeouts for large studies.  In June we also released a new endpoint that returns information on identifiers, specifically if the identifier exists and what collection it exists in.
