### ISSUE TITLE
Milestone - CI/CD (1.15)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#517]
**Update Dec 11, 2023**
Workflow Automation - CI:
- Unit Tests
-- Unit tests running successfully with GH Actions
   https://github.com/microbiomedata/nmdc_automation/tree/Refactor_fgi_file_staging_unit_tests

**Test Suites that still need to be defined:**
- Integration Tests
- Schema Compatibility Testing
- End to End Testing

**Comment by ssarrafan** [comment]
Automation for improved workflow deployment to production sites
We will support automated workflow execution and testing through techniques like continuous
integration and continuous deployment (CI/CD) (Milestone 1.15). With a CI/CD solution, workflow
updates and new workflow releases will trigger rigorous testing at different stages. This testing includes
unit tests (the test of a single isolated workflow task), as well as integration, and data schema compatibility
tests, along with whole workflow execution tests using predefined data sets, ensuring the latest workflow
from the code repository generates expected results without manual tuning.
page 24

**Comment by aclum** [comment]
@mbthornton-lbl is working on some CI for the nmdc-automation repository.

**Comment by mbthornton-lbl** [comment]
Automatic running of unit tests via GitHub actions is working in this branch:
https://github.com/microbiomedata/nmdc_automation/tree/Refactor_fgi_file_staging_unit_tests

**Comment by ssarrafan** [comment]
Moving to Q4 2024. 
FYI @aclum @mbthornton-lbl @shreddd @emileyfadrosh

**Comment by ssarrafan** [comment]
@aclum what would need to be done for this milestone to be complete?  MS#8 to close? Anything else?

**Comment by aclum** [comment]
We can close this as we've made significant progress towards CI/CD across the project. Within the last year we've:
 - expanded tests the number of CI tests run in nmdc-schema which many team members contributed to
 - added github actions for continuous deployment for the majority the workflow repositories 
 - added github actions for continuous integration which test WDL syntax for workflow repositories 
 - added github actions for continuous integration in nmdc_automation repository
 - added github actions for continuous integration for some notebooks in nmdc_notebooks
