### ISSUE TITLE
Milestone - Lipidomics workflow (2.17)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#519]

**Comment by ssarrafan** [comment]
Update from quarterly report:
The workflow has been scoped and designed with active development. An in-silico mass spectra database of microbial lipids has been collated and deposited into a workflow-accessible database which is essential for the identification steps of the workflow.

@kheal this was a milestone from 2023. We're in the process of rescheduling, re-organizing.  Would you be able to put a new timeline on when this workflow would be done? I can then move it to the appropriate quarter. Thnks.

**Comment by kheal** [comment]
@ssarrafan This should be done by the end of Q2 2024.

**Comment by ssarrafan** [comment]
Rechecking on this milestone. Any concerns about this completing by the end of March 2024?  @kheal @lamccue

**Comment by kheal** [comment]
We're making good progress on the workflow in our local dev environment.  Basic functionality is completed and we are working on the design and structure of the data outputs for reusability/interpretability. 

Regarding timing: We will likely need beyond March 2024 to deploy the workflow to a prod environment and of course there will always be maintenance with work like this, so I'm not sure when the workflow will be considered 'complete' but the dev version will functional by end of March 2024.

**Comment by ssarrafan** [comment]
Marked complete in DOE report sent April 2024
