### ISSUE TITLE
Milestone - Define the outline and deliverables of a partnership with ICTV for implementing viral taxonomy into a robust, reproducible, and machine-readable framework (2.20)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#520]

**Comment by ssarrafan** [comment]
Because of the large diversity of viral genome types, complexity, and recombination/mutation rates across
the virosphere, different taxonomic classification methods and criteria are used across different taxa and
ranks, including gene(s) phylogeny, shared gene content, or genome-wide sequence similarity. These
different criteria are still being refined and/or established for many taxa, and are currently stored as part
of taxonomic proposals (“TaxoProp”), technical reports available on the ICTV website
(https://talk.ictvonline.org/taxonomy/). To help standardize virus taxonomy analyses, particularly for
metagenomic data, we propose to partner with ICTV, where NMDC would provide expertise in
standardized data analysis and bioinformatic workflow management to translate the current and future
demarcation criteria described in several dozens of ICTV TaxoProps into a single computational and
actionable workflow (Milestone 2.20). By following the best practices established for NMDC workflow
development, ICTV will ensure that taxonomic classification of new viruses can be achieved through
portable and reproducible pipelines. This would in turn enable standard metagenomic analyses to not
only include virus sequence detection, but also taxonomic classification following the latest ICTV
guidelines.
Page 35

**Comment by ssarrafan** [comment]
Update from quarterly report:
Discussions were started with the ICTV Bioinformatics Study group about the needs of the viral taxonomy community and the support provided by the NMDC. The exact scope and deliverables still need to be determined in upcoming meetings, and should be finalized by the end of FY24 Q2.

**Comment by ssarrafan** [comment]
@emileyfadrosh any update on this milestone? Any blockers to this getting done by the end of March 2024?

**Comment by simroux** [comment]
I think last time we chatted with Emiley, we said we could consider this as done, but to be confirmed by @emileyfadrosh

**Comment by ssarrafan** [comment]
Updated from DOE QUarterly:
Discussions were conducted with the ICTV Bioinformatics Study group about the needs of the viral taxonomy community and the support provided by the NMDC. The NMDC will share high-quality viral genomes identified via the NMDC metagenome annotation pipeline, for potential integration as new species exemplar in the ICTV taxonomy (to be evaluated by ICTV Study groups). In addition, the NMDC will work with the ICTV Bioinformatics Study group to provide documentation and tools for researchers to include metadata from the GSC MIUViG checklist with their viral MAG submission, as recommended by the ICTV (doi: 10.1038/s41587-023-01844-2).
