### ISSUE TITLE
Milestone - Sample Jupyter and RStudio notebooks available that highlight NMDC data and metadata (2.26)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#521]
The NMDC will add capabilities to enable advanced custom data exploration in an interactive form. Our
intent is not to develop a new platform, instead we will focus on deepening relationships with key
stakeholders by connecting NMDC data with notebooks launched on existing Jupyter / RStudio services
offered by DOE or cloud providers (e.g., NERSC JupyterHub, Google Colab, Binder). The goal of these
notebooks is to provide users with the ability to combine interactive live code execution with inline
documentation and visualizations (Milestone 2.26). These notebooks can be automatically generated
from data and analyses of interest, and spun up in real-time on users’ personal computers or existing
computing infrastructure. There is a compelling training and education component to this approach, since
live notebooks are ideally suited to providing hands-on examples showing users how to interact with and
analyze NMDC data. This approach will also serve as a model for how users can access data and run NMDC
workflows in KBase (see Integration with DOE KBase).
Page 38

see also #512

**Comment by brynnz22** [comment]
@shreddd @cmungall. @kheal, @scanon and I are continuing to work on this from the hackathon. I am adding this to the sprint!

**Comment by brynnz22** [comment]
Here is the link to the repo: https://github.com/microbiomedata/notebook_hackathons

**Comment by brynnz22** [comment]
Next steps:

- [ ] Add python and R analyses for: How does the taxonomic distribution of contigs differ by soil layer (mineral vs organic)?
- [ ] What other analyses?

**Comment by brynnz22** [comment]
I think the first notebook exploring NEON soil metadata is complete. Halfway through a bioscales notebook. And wrote the long mongodb query for the contig/soil layer question. Moving to next sprint to keep working on this. Would love feedback from anyone who has a minute to take a look!

**Comment by brynnz22** [comment]
Bioscales and NEON notebooks complete. Working on the tricking soil/contig/taxonomy question. Hoepfully can complete by end of next spring.

**Comment by ssarrafan** [comment]
@brynnz22 any update on this one? Can we close this?

**Comment by brynnz22** [comment]
Almost done! I will finish it this week!

**Comment by ssarrafan** [comment]
This milestone is done
