### ISSUE TITLE
Re-ID NOM and Metabolomics OmicsProcessing, DataObjects, AnalysisActivies

### ISSUE THREAD

**Issue by corilo** [microbiomedata/issues#524]
- [x] Implement Logic for re-id legacy mongo records for NOM and Metab  AnalysisActivities.
- [x] Implement Logic for re-id legacy DataObjects (raw data and results) for NOM and metab and create entries for missing raw data data objects
- [x] Decide what to do with Lipdomics records
- [x] test on napa mongo
- [x] remove or update was_generated_by for the metabolomics and nom records

**Comment by ssarrafan** [comment]
@corilo will move this to the next sprint since it appears new. If it makes it easier I can create three different issues for the subtasks of this ticket.  Let me know.

**Comment by aclum** [comment]
Yuri is planning to test with gold:Gs0114663

**Comment by aclum** [comment]
I met with Yuri earlier in the week b/c he was having some connection issues from perlmutter to the napa mongo instance which  I couldn't replicate. Moving to the next sprint as this is still in progress.

**Comment by aclum** [comment]
The decision on lipidomics was to remove them from mongo for now. There is a list of exist records in the squad folder (20231109.lipidomics_nmdc.json) which as these records.  Yuri needs to add logic which creates a new data object record if one does not exist to update.

**Comment by ssarrafan** [comment]
Last day of sprint. Removing from sprint, adding backlog label. Please update or add to next sprint if still active.

**Comment by aclum** [comment]
Alicia and Yuri to meet Jan 8th about this.

**Comment by aclum** [comment]
Yuri and I met today, I will update Study,Biosample, and OmicsProcessing records for studies that have legacy nom OmicsProcessing records so Yuri doesn't have to further modify his code. Once that code is tested, Yuri will write the metabolomics code which should be highly similar. Moving to the next sprint.

**Comment by aclum** [comment]
Study through omics records that Yuri needed were updated on Jan 18.

**Comment by ssarrafan** [comment]
checked with Alicia and moving to next sprint.

**Comment by aclum** [comment]
This was worked on last week. Many NOM activities were deleted since they couldn't be connected to upstream records. Yuri is checking with @mslarae13 to see if upstream records can be correctly associated for metabolomics activities.  I've provided feedback to Yuri on the records that were re-id and those need to be addressed before we could apply this on prod.

**Comment by aclum** [comment]
Still actively in progress. Yuri is working on fixing the data object connections. Moving the next sprint.

**Comment by aclum** [comment]
Testing is complete in napa, nom and metabolomics collections pass linkml-validation.

**Comment by aclum** [comment]
Michael deleted the lipidomics records and the downstream data objects

- [ ] There are 79 records NOM records where has_output does not exist. We need data objects for these. Spot checking these existed in prod so appear to have been not migrated/inadvertently deleted.
- [ ] There are  1529 data_object_set records that still have an emsl prefix. Need to know if these can be deleted.

**Comment by aclum** [comment]
The 79 omics_processing_set records without data objects will be deleted by Yuri this week. The remaining orphaned legacy data_object_set records will be deleted by logic implemented in https://github.com/microbiomedata/nmdc_automation/issues/79

**Comment by aclum** [comment]
@corilo  there are still issues with was_generated_by and has_calibration. see comments and code in https://github.com/microbiomedata/nmdc-schema/issues/1865

**Comment by ssarrafan** [comment]
Although all the checkboxes are checked, based on the last comment from Yuri, I'll move this to the next sprint.  FYI @aclum @corilo

**Comment by aclum** [comment]
Considering this closed, will re-open if Michael's testing today turns up any new issues.
