### ISSUE TITLE
Need missing biosample_set or biosample_set and omics processing_set records for a collection of SPRUCE (gold:Gs0110138) samples

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#527]
This work is needed as part of the napa compliance squad to address referential integrity issues. @turbomam  and I found a number of projects which had workflow execution activity records but that were missing upstream records. SPRUCE (gold:Gs0110138) is one of the studies we'd like to fix instead of delete.

**RACI**

_Tag people in their roles_
- Responsible: @sujaypatil96 
- Accountable: @turbomam 
- Consulted: @aclum 
- Informed: napa squad

**Describe the the task**
- [ ] We need omics_processing_set records for the following gold projects. They should use Napa style IDs for the biosample_set and omics_processing_set slot id but should be be populated with part_of:nmdc:sty-11-33fbta56, this is the new ID I'm using in the napa instance of mongo for SPRUCE which previously had an ID gold:Gs0110138. The missing biosample records should be added first b/c the missing gold projects use those reference the missing biosample IDs

gold_project 
-- 
Gp0208343
Gp0208344
Gp0208345
Gp0208346
Gp0208347
Gp0208348
Gp0208349
Gp0208350
Gp0208351
Gp0208352
Gp0208353
Gp0208354
Gp0208355
Gp0208356
Gp0208357
Gp0208358

- [ ] biosample_set records for 24 SPRUCE projects. Omics_processing_set records exist for these already.  New biosample ids can be minted for these, we can use the gold_biosample_identifiers slot to repair the omics_records.

gold_biosample
--
Gb0150237
Gb0150238
Gb0150239
Gb0150240
Gb0150241
Gb0150242
Gb0150243
Gb0150244
Gb0150245
Gb0150246
Gb0150247
Gb0150248
Gb0150249
Gb0150250
Gb0150251
Gb0150252
Gb0150253
Gb0150254
Gb0150255
Gb0150256
Gb0150257
Gb0150258
Gb0150259
Gb0150260

**Criteria for completion**
- biosample_set and omics_processing set records for 16 SPURCE records and biosample_set records only for 24 additional SPRUCE projects in napa prod

**Estimate people time**
- 1 person, 4 hours

**Completion Date (Goal)**
- Jan 26

**Target Sprint Start & End Dates**
- Start: Jan 15
- End: Jan 26

**Comment by sujaypatil96** [comment]
Starting work on this from today 11/1. Will post updates.

**Comment by aclum** [comment]
@sujaypatil96  was the gold ingest pipeline updated to use lowercase for the gold curie prefix? I know we talked about it before but I lost track of if that was addressed or if there was a ticket. If not, that will have to be addressed first.

**Comment by sujaypatil96** [comment]
@aclum no, it wasn't. It's a fairly trivial fix though. I'm happy to make that change.

**Comment by sujaypatil96** [comment]
Will have this done in the next day or two.

**Comment by sujaypatil96** [comment]
JSON file with missing biosample and omics processing records:
[spruce_missing_records.json](https://github.com/microbiomedata/issues/files/13290686/spruce_missing_records.json)

**Comment by aclum** [comment]
In reviewing the submission we were in some cases missing a specific location in geo_loc_name, I asked GOLD to fix this. They did but in doing some they changed some of the biosample ids since they realized some of the projects were paired. Sujay will do a fresh pull from GOLD. Activity in progress so moving to the next sprint.

**Comment by ssarrafan** [comment]
@aclum @sujaypatil96 is this one still active?

**Comment by ssarrafan** [comment]
Moving to next sprint for final submission by Sujay per Slack message.

**Comment by aclum** [comment]
Updated completion criteria to be to submit this to napa mongo. Applying to mongo prod before we've updated the study id will break data portal ingest so I will make a separate linked ticket for that.

**Comment by ssarrafan** [comment]
Last day of sprint. Will remove from sprint and add to backlog. @aclum let me know if this is still active.

**Comment by aclum** [comment]
This is blocked on https://github.com/microbiomedata/nmdc-runtime/issues/442

**Comment by sujaypatil96** [comment]
@aclum I see you've updated some of the GOLD biosample/project ids that we need to fix in the original ticket message.

Based on the corrected ids, I've created a new JSON file for the missing biosample/omics processing set records:
[spruce_missing_records.json](https://github.com/microbiomedata/issues/files/14057747/spruce_missing_records.json)

**Comment by sujaypatil96** [comment]
Linking new JSON file after a couple more modifications - dropped field_research_site_set and updated part_of to use `nmdc:sty-11-33fbta56` as study id.

[spruce_missing_records.json](https://github.com/microbiomedata/issues/files/14058906/spruce_missing_records.json)

**Comment by ssarrafan** [comment]
Appears to be active (and will hopefully be unblocked soon?) so moving to next sprint.  Feel free to put in backlog instead if more appropriate.

**Comment by aclum** [comment]
These records were added to napa mongo but the omics_processing_set records don't have the correct part_of. This needs to be updated and can't b/c done w/changesheets API b/c of other issues with the record. I'll updated these directly w/pymongo next week. While doing that I'll also remove the designated_class slot since that didn't exist in schema 8.0.0 which is what we are using for linkml-validate testing, also b/c it this slot will go away with the updates to type that Mark M. made in the Berkeley schema.

**Comment by aclum** [comment]
[20240129.spruce_mt_fixes.json](https://github.com/microbiomedata/issues/files/14088657/20240129.spruce_mt_fixes.json)
 The json we should use when we update prod is attached. I used pymongo to directly update part_of and pymongo with unset to remove designated_class from the records in napa so there are no validation issues with schema 8.0.0.
