### ISSUE TITLE
napa compliance - delete WorkflowExecutionActivity records and related data object records that do not have an upstream omics record

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#528]
**Deliverable this task is associated with**

_See Deliverables tab here: _

- [Add the Deliverable #]

**RACI**

_Tag people in their roles_
- Responsible: @aclum 
- Accountable: @aclum 
- Consulted: @turbomam 
- Informed:

**Describe the the task**
- [x] delete workflow execution activity records and their data objects, aside from those derived from Class Study id gold:Gs0110138 (SPRUCE), from mongo prod as part of the napa compliance squad work.
- [x] delete dangling bioscales records from read_based_taxonomy_analysis_activity_set
- [x]  deleted functional agg results with
 ```
{"delete": "functional_annotation_agg", "deletes": [{"q": {"metagenome_annotation_id": "nmdc:73b7ba35a832f4e18f885bcbb88b967d"}, "limit": 0}]}

```
or something similar
**Criteria for completion**
- After completion with a sparql query there should be only be 16 records remaining that are of part type MetagenomeAssembly with a relationship of was_informed_by which do not have a parent. If Sujay has addressed [Need missing biosample_set or biosample_set and omics processing_set records for a collection of SPRUCE (gold:Gs0110138) samples#527](https://github.com/microbiomedata/issues/issues/527) this number should be zero. A sparql query of records that are of part type ReadBasedTaxonomyAnalysisActivity with a relationship of was_informed_by which do not have a parent is 0.

**Estimate people time**
-  1 person, 2 hours

**Completion Date (Goal)**
- Dec 1

**Target Sprint Start & End Dates**
- Start: Oct 23
- End: Dec 1

**Tag Blocker/Contingent upon issues**
- to apply this in prod is blocked on [Re-ID NOM and Metabolomics OmicsProcessing, DataObjects, AnalysisActivies#524](https://github.com/microbiomedata/issues/issues/524) and [Napa compliance - gold:Gs0114663 - metagenomes#430](https://github.com/microbiomedata/issues/issues/430) and testing the rest of the studies in the napa mongo instance (no ticket yet)

**Comment by aclum** [comment]
@turbomam  if you have time to set up a graph db instance based on the napa mongo we could confirm that the code I've written and tested against napa mongo works.

**Comment by mbthornton-lbl** [comment]
We have 2 delete queries that accomplish this:
- delete_bioscales_data_objects.js
- delete_omics_processing_has_output_ref_integrity_exceptions.js

**Comment by aclum** [comment]
This ticket is different and pertains to records which do not have omicsprocessing  issues, it requires a list of gold projects.
I've done this in dev and production for the workflow execution activity collections and data object_set collections.
I ran into issues cleaning up the functional_annotation_agg collection with the API, see https://github.com/microbiomedata/nmdc-runtime/issues/509

Napa was down but when it is back up ill do it there too.

**Comment by aclum** [comment]
summary of records deleted in prod 
|count| collection|
|----|------|
|237 |read_qc_analysis_activity_set|
|153 |read_based_taxonomy_analysis_activity_set|
|237 |metagenome_annotation_activity_set|
|1 |metagenome_annotation_activity_set|
|1|mags_activity_set|
|3294 |data_object_set|

**Comment by aclum** [comment]
record of deleted objects stored in the napa squad folder as 20240424.issues_528.deleted_record_identifiers.tsv

**Comment by aclum** [comment]
functional_annotation_agg deletion happened on april 29 using queries:run and deleted 4057 records.
