### ISSUE TITLE
NEON add ncbi biosample and project records to NEON nmdc soil study and biosample records

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#529]
**Deliverable this task is associated with**

_See Deliverables tab here: _

- [Add the Deliverable #]

**RACI**

_Tag people in their roles_
- Responsible:
- Accountable:
- Consulted:
- Informed:

**Describe the the task**
- [ ] Update NEON records from JGI to include NCBI identifiers. These records already exist so use changesheets to get these records updated. The biosamples registered w/NCBI map to nmdc's processed samples that are output from Class extraction. also associate PRJNA1029061, the NCBI Umbrella Bioproject Accession with nmdc study nmdc:sty-11-34xj1150. We should be able to pull this in via the GOLD API.

**Implementation Sketch**
1. Retrieve Gold Study Identifiers for study "nmdc:sty-11-34xj1150"
2. For gold:Gs0161344 retrieve the GoldProjects from the GOLD projects endpoint
3. For each GoldProject retrieve NCBI BioSampleAccession and BioProjectAccession
a. Find NMDC biosample via GoldProject.biosampleGoldId => biosample.gold_biosample_identifiers
b.  Write changesheet line item adding NCBI BioSampleAccession to biosample.insdc_biosample_identifiers
4.  For each GoldProject
a. Retrieve OmicsProcessing record by gold_sequencing_project_identifiers
b. Write changesheet line item adding NCBI BioProjectAccession to insdc_experiment_identifiers

**Criteria for completion**
- NEON soil samples that were processed at JGI have ncbi biosample and sra identifiers associated with Class Biosample and OmicsProcesing respectively.  Records should be updated in mongo prod.

**Estimate people time**
- [Hours or days of people time. 1 person, 4 hours]

**Completion Date (Goal)**
- [GOAL!]

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- [Tag issues]

**Comment by aclum** [comment]
@mbthornton-lbl A good use case for the runtime code you wrote for generalized changesheet needs.

**Comment by aclum** [comment]
We'll need an update to runtime API to use bioproject identifiers for class OmicsProcessing

**Comment by mbthornton-lbl** [comment]
Applied changesheet to api-dev successfully
Changesheet:
https://drive.google.com/file/d/11sLKcPOSKIxNureYndbPSn3qQiQF1Uc6/view?usp=drive_link
