### ISSUE TITLE
NMDC GSP 2023 QA

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#53]
data portal
- [x] https://github.com/microbiomedata/issues/issues/136
- [x] https://github.com/microbiomedata/issues/issues/143
- [x] https://github.com/microbiomedata/issues/issues/145
- [x] https://github.com/microbiomedata/issues/issues/167
- [x] https://github.com/microbiomedata/nmdc-server/issues/918
- [x] https://github.com/microbiomedata/nmdc-server/issues/919
- [x] https://github.com/microbiomedata/issues/issues/174
- [x] https://github.com/microbiomedata/nmdc-server/issues/926

workflows
- [x] https://github.com/microbiomedata/issues/issues/134
- [x] https://github.com/microbiomedata/issues/issues/135
- [x] https://github.com/microbiomedata/issues/issues/137
- [x]  https://github.com/microbiomedata/issues/issues/146
- [x] https://github.com/microbiomedata/issues/issues/180

study/biosample changesheets
- [x] https://github.com/microbiomedata/issues/issues/142
- [x] https://github.com/microbiomedata/issues/issues/144
- [x] https://github.com/microbiomedata/issues/issues/155
- [x] https://github.com/microbiomedata/issues/issues/161
- [x] https://github.com/microbiomedata/nmdc-server/issues/648
- [x] https://github.com/microbiomedata/nmdc-server/issues/886
- [x] microbiomedata/issues#171
- [x] microbiomedata/issues#172
- [x] https://github.com/microbiomedata/issues/issues/176
- [x] https://github.com/microbiomedata/nmdc-datasets/pull/10
- [x] https://github.com/microbiomedata/issues/issues/120

**Comment by aclum** [comment]
Removed issue #153 and #141 since they aren't critical for GSP

**Comment by mslarae13** [comment]
Would like to add https://github.com/microbiomedata/issues/issues/162

**Comment by mslarae13** [comment]
Suggest adding this as well : https://github.com/microbiomedata/nmdc-server/issues/648

**Comment by aclum** [comment]
Removing tickets that won't be done by GSP 2023.

**Comment by ssarrafan** [comment]
Everything looks like its checked off but not all closed so I'll carry this one over to close next week. @aclum
