### ISSUE TITLE
run NEON benthic samples through NMDC workflows

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#530]
**Deliverable this task is associated with**

_See Deliverables tab here:  https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit#gid=417989680

- 3

**RACI**

_Tag people in their roles_
- Responsible: @Michal-Babins @mbthornton-lbl 
- Accountable: @hubin-keio, @aclum 
- Consulted: @aclum , @scanon 
- Informed: @aclum 

**Describe the the task**
- [ ] run end to end metagenome workflow on NEON benthic samples (study id is nmdc:sty-11-pzmd0x14). For this study all data comes directly from NEON, data objects are listed as has_output in the omics_processing_set records. Total samples to process: 560

**Criteria for completion**
- Data objects that are output of workflow activity records are in mong prod for NEON benthic samples

**Estimate people time**
- 2 person, 20 hours

**Completion Date (Goal)**
- Dec 1

**Target Sprint Start & End Dates**
- Start: Nov 6
- End: Dec 1

**Tag Blocker/Contingent upon issues**
https://github.com/microbiomedata/issues/issues/335 - biosample_set through omics_procesing_set ingest should happen shortly.

**Comment by ssarrafan** [comment]
@aclum is this active?

**Comment by aclum** [comment]
Yes, these have been running and should be largely complete. @Michal-Babins  should be able to summarize the status when he is back next week. 
Moving to the next sprint.

**Comment by aclum** [comment]
Michal updated via slack last week. 400 Benthic samples done, had to reset the rest due to connection error and perlmutter outages.

**Comment by Michal-Babins** [comment]
Submitted all benthic samples, and resubmitted after outage. Will scrape any errors and report them for review.

**Comment by ssarrafan** [comment]
Appears to be active. Moving to next sprint.

**Comment by aclum** [comment]
still active but won't be done this sprint. Moving to January sprint.

**Comment by aclum** [comment]
Moving this to the next sprint b/c this won't be worked on until we can add qc info to the workflow records which won't be available until the 1/29/24 runtime update.

**Comment by ssarrafan** [comment]
@aclum should this one go in the backlog?  doesn't appear to be active.

**Comment by Michal-Babins** [comment]
This one is done!

**Comment by ssarrafan** [comment]
Closing per last comment from @Michal-Babins
