### ISSUE TITLE
process NEON surface water samples through NMDC workflow

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#531]
**Deliverable this task is associated with**

_See Deliverables tab here:  https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit#gid=417989680

- 2

**RACI**

_Tag people in their roles_
- Responsible: @vlilanl, @kaijli 
- Accountable: @hubin-keio, @aclum 
- Consulted: @aclum , @scanon 
- Informed: @aclum 

**Describe the the task**
- [ ] run end to end metagenome workflow on NEON surface water samples (study id is nmdc:sty-11-hht5sb92). For this study all data comes directly from NEON, data objects are listed as has_output in the omics_processing_set records.

**Criteria for completion**
- Data objects that are output of workflow activity records are in mong prod for NEON surface water samples

**Estimate people time**
- 2 person, 20 hours

**Completion Date (Goal)**
- April 19

**Target Sprint Start & End Dates**
- Start: April 8
- End: April 19

**Tag Blocker/Contingent upon issues**
https://github.com/microbiomedata/issues/issues/334 - resolved

**Comment by aclum** [comment]
Biosample and omics processing metadata records have been added to mongo prod. There are 147 omics_processing set records. Scheduling to start this next sprint since TRiP is running this sprint.

**Comment by aclum** [comment]
I provided the list of omics records for this project in the neon slack channel. Shane was going to try to start these today.

**Comment by ssarrafan** [comment]
@scanon any update on this issue?  Are you still working on it?  I can move it to the next sprint if still active.  Let me know. Thanks!

**Comment by ssarrafan** [comment]
moving to next sprint per @vlilanl 
@kaijli and @scanon let me know if you won't be working on this issue

**Comment by aclum** [comment]
@scanon We are missing assemblies and annotations for these three omics records
nmdc:omprc-12-6a2d5s20
nmdc:omprc-12-qz44bj76
nmdc:omprc-12-pdkr6t69

**Comment by aclum** [comment]
Note binning will run after eukcc component is added.

**Comment by aclum** [comment]
Paired with Kaitlyn to mark the data as failed for nmdc:omprc-12-6a2d5s20 since there is not enough data. Shane will resubmit the other two shortly, NERSC maintenance was yesterday. Chien-chi released the binning workflow updates so moving this to the next sprint, we should be able to get binning run then.

**Comment by aclum** [comment]
nmdc:omprc-12-6a2d5s20 - memory errors
  0:00:00.667    11M / 25M   INFO    General                 (kmer_splitter.hpp         : 101)   Using cell size of 16384
mimalloc: warning: unable to allocate from region: size 4194304

nmdc:omprc-12-qz44bj76 - completed 
nmdc:omprc-12-pdkr6t69- completed.

**Comment by aclum** [comment]
Slacked Shane to see if the workflow automation can submit to larger nodes. Moving to the current sprint but this will likely be backlogged until the binning is ready to run.

**Comment by ssarrafan** [comment]
Sprint over, removing from sprint.

**Comment by aclum** [comment]
@kaijli  did you updating those two filtering records with a qc status of failed?

**Comment by kaijli** [comment]
I submitted changesheets, but not sure where to check to see if changes went through @aclum 

> did you updating those two filtering records with a qc status of failed?

**Comment by aclum** [comment]
Yes, the omics record and read qc records have a qc_status of fail.
