### ISSUE TITLE
prod mongo re-id master tasklist

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#532]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1lLQ3wAwJzvxujER6-b4iDnnHx06MYsDbmIBMnu1IOeI/edit#gid=0

- 1-10

**RACI**

_Tag people in their roles_
- Responsible:  @mbthornton-lbl @eecavanna 
- Accountable: @aclum @scanon  @corilo Paul
- Consulted: @shreddd napa squad
- Informed: napa squad, leadership

**Describe the task**

- [x] **Prepare the production environment** (Eric)
  1. Take production Runtime (and friends) offline
     1. On Rancher, in the `nmdc` namespace, scale the following workloads down to 0 replicas:
        - `aggregations` (1 → 0)
        - `scheduler` (1 → 0)
        - `dagster-daemon` (1 → 0)
        - `runtime-api` (3 → 0)
  2. Limit production Mongo access
     1. At a `mongosh` shell, use the `root` user to connect to the production Mongo server and [temporarily modify roles](https://www.mongodb.com/docs/manual/reference/method/db.revokeRolesFromRole/#mongodb-method-db.revokeRolesFromRole):
        > You can get the `root` Mongo user's password from Rancher.
        ```js
        use admin;
        
        // Revoke "read" access from team members and the aggregator (they already lack write access).
        db.getRole("nmdc_reader");
        db.updateRole("nmdc_reader", { privileges: [], roles: [] });
        
        // Revoke "read" and "write" access from the scheduler (normally, it can write to the `jobs` collection).
        db.getRole("nmdc_scheduler");
        db.updateRole("nmdc_scheduler", { privileges: [], roles: [] });
        ```
- [x] **Back up the production Mongo databases** (Eric)
  1. Back up the production Mongo databases
     1. On Rancher, go to "Workloads" > "CronJobs", and — in the `nmdc` namespace — locate the CronJob named `backup-mongo`
     2. Click the 3-dot menu on that row and select `Run Now`
  2. Confirm the databases were backed up
     1. On `dtn01.nersc.gov`, confirm the backup exists
        ```sh
        # List the 5 most recent dumps.
        cd /global/cfs/cdirs/m3408/nmdc-mongodumps/
        ls -ltr | tail -5
        ```
- [x] **Prepare the Napa environment** (Eric)
  1. Take Napa Runtime (and friends) offline
     1. On Rancher, in the `nmdc-napa` namespace, scale the following workloads down to 0 replicas:
        - `scheduler` (1 → 0)
        - `dagster-daemon` (1 → 0)
        - `runtime-api` (3 → 0)
  2. Limit Napa Mongo access
     1. At a `mongosh` shell, use the `root` user to connect to the Napa Mongo server and [temporarily modify roles](https://www.mongodb.com/docs/manual/reference/method/db.revokeRolesFromRole/#mongodb-method-db.revokeRolesFromRole):
        > You can get the `root` Mongo user's password from Rancher.
        ```js
        use admin;

        // Revoke "write" access from re-ID squad members.
        // Note: We keep their "read" access so they can help "spot check" the re-ID-ing.
        // Note: Squad members _actively_ performing the re-ID-ing will be given
        //       "write" access via a different role later.
        db.getRole("nmdc_reader_writer");
        db.updateRole("nmdc_reader_writer", { privileges: [], roles: [
          { db: "nmdc", role: "read" },
          { db: "nmdc_updated", role: "read" },
          { db: "nmdc_deleted", role: "read" },
          { db: "nmdc_changesheet_submission_results", role: "read" }
        ]});

        // Revoke "read" and "write" access from the scheduler (normally, it can write to the `jobs` collection).
        db.getRole("nmdc_scheduler");
        db.updateRole("nmdc_scheduler", { privileges: [], roles: [] });
        ```
  2. Back up the Napa databases
     1. On Rancher, go to "Workloads" > "CronJobs", and — in the `nmdc-napa` namespace — locate the CronJob named `backup-mongo`
     2. Click the 3-dot menu on that row and select `Run Now`
  3. Confirm the databases were backed up
     1. On `dtn01.nersc.gov`, confirm the backup exists
        ```sh
        # List the 5 most recent dumps.
        cd /global/cfs/cdirs/m3408/nmdc-mongodumps/
        ls -ltr | tail -5
        ```
  4. Drop the Napa databases
     1. On `dtn01.nersc.gov`, use `mongosh` to connect to the Napa Mongo server and [drop the databases](https://www.mongodb.com/docs/manual/reference/method/db.dropDatabase/):
        ```sh
        cd /global/cfs/projectdirs/m3408/nmdc-mongodumps

        ./bin/mongosh \
          --host="mongo-loadbalancer.nmdc-napa.production.svc.spin.nersc.org" \
          --username "root" \
          --eval 'use nmdc'                                --eval 'db.dropDatabase()' \
          --eval 'use nmdc_test'                           --eval 'db.dropDatabase()' \
          --eval 'use nmdc_updated'                        --eval 'db.dropDatabase()' \
          --eval 'use nmdc_deleted'                        --eval 'db.dropDatabase()' \
          --eval 'use nmdc_changesheet_submission_results' --eval 'db.dropDatabase()'
        ```
  5. Restore the production dump to the Napa Mongo server
     1. On `dtn01.nersc.gov`, use `mongorestore` to restore the production dump you created earlier, into the Napa Mongo server.
        > Replace the `{__TIMESTAMP__}` placeholder below with the real ending of the dump's directory name.
        ```sh
        cd /global/cfs/projectdirs/m3408/nmdc-mongodumps
        
        ./bin/mongorestore \
          --host="mongo-loadbalancer.nmdc-napa.production.svc.spin.nersc.org" \
          --username="root" \
          --verbose --stopOnError --drop --preserveUUID \
          --nsInclude 'nmdc.*' \
          --nsInclude 'nmdc_deleted.*' \
          --nsInclude 'nmdc_updated.*' \
          --nsInclude 'nmdc_changesheet_submission_results.*' \
          --dir="./dump_nmdc-prod_{__TIMESTAMP__}"
        ```
        > This typically takes 7-8 minutes.
  6. Grant read/write access to the team members actively performing re-ID-ing (i.e. Michael and Alicia)
     1. At a `mongosh` shell, use the `root` user to connect to the Napa Mongo server and [temporarily assign roles](https://www.mongodb.com/docs/manual/reference/method/db.revokeRolesFromRole/#mongodb-method-db.revokeRolesFromRole):
        ```js
        use admin;
        
        // Temporarily assign them the "nmdc_runtime" role, which has "read/write" access to all "nmdc*" collections.
        db.grantRolesToUser('alicia.clum-napa', ['nmdc_runtime']);
        db.grantRolesToUser('michael.thornton-napa', ['nmdc_runtime']);        
        ```
  7. Bring the Napa Runtime (and friends) back online
     1. On Rancher, in the `nmdc-napa` namespace, scale the following workloads up:
        - `runtime-api` (0 → 3)
        - `dagster-daemon` (0 → 1)
        - `scheduler` (0 → 1)

~Add SPRUCE records (20240129.spruce_mt_fixes.json) to fix referential integrity issue with API json:submit,see https://github.com/microbiomedata/issues/issues/527 md5sum for input file is 39c6232c370e5765756f93e7b72f76da (Alicia/Micheal)~

- [x]  microbiomedata/nmdc_automation#172 re-id study_set,biosample_set,and omics_processing_set records (Micheal)

~Add proteomics data objects for SPRUCE and STEGEN/Riverbed sediment  with API json:submit endpoint, update omics_processing_set records `has_output`  via API changesheets:submit (Alicia) - files for stegen are attached or linked to https://github.com/microbiomedata/nmdc_automation/issues/111 files for spruce are attached or linked to https://github.com/microbiomedata/nmdc_automation/issues/109~

- [x] microbiomedata/nmdc_automation#172 re-id/replace/delete workflow execution activity, data object and kegg aggregation collections (Micheal)

~metaproteomics use https://github.com/microbiomedata/nmdc-schema/blob/napa_compliance/nmdc_schema/metap_records_delete.py~

- [x] run pure-export and validate copy with linkml-validate, make-rdf (Alicia/Michael)
make-rdf failed because of remaining legacy IDs
- [x] run script to validate that all id slots are napa complaint based on structured pattern.syntax for that Class as well as all references to nmdc identifiers (part_of, was_informed_by, has_input, has_output, was_generated_by, metagenome_annotation_id, metaproteomic_analysis_id) (Alicia/Michael)
No unexpected errors
- [x] **Dump Napa Mongo and restore to production Mongo server** (Eric)
  1. Revoke Napa Mongo write access from the team members actively performing re-ID-ing (i.e. Michael and Alicia)
     1. At a `mongosh` shell, use the `root` user to connect to the Napa Mongo server and [modify roles](https://www.mongodb.com/docs/manual/reference/method/db.revokeRolesFromRole/#mongodb-method-db.revokeRolesFromRole):
        ```js
        use admin;
        
        // Revoke their "write" access to all "nmdc*" collections.
        // Note: They'll still have "read" access because they'll still have the `nmdc_reader_writer` role,
        //       which currently (since we constrained it earlier) provides only "read" access.
        db.revokeRolesFromUser('alicia.clum-napa', ['nmdc_runtime']);
        db.revokeRolesFromUser('michael.thornton-napa', ['nmdc_runtime']);
        ```
  2. Take the Napa Runtime (and friends) offline
     1. On Rancher, in the nmdc-napa namespace, scale the following workloads down:
        - `scheduler` (1 → 0)
        - `dagster-daemon` (1 → 0)
        - `runtime-api` (3 → 0)
  3. Back up the Napa databases (these contained the re-ID-ed data)
     1. On Rancher, go to "Workloads" > "CronJobs", and — in the `nmdc-napa` namespace — locate the CronJob named `backup-mongo`
     2. Click the 3-dot menu on that row and select `Run Now`
  4. Confirm the databases were backed up
     1. On `dtn01.nersc.gov`, confirm the backup exists
        ```sh
        # List the 5 most recent dumps.
        cd /global/cfs/cdirs/m3408/nmdc-mongodumps/
        ls -ltr | tail -5
        ```
  5. Drop the production databases
     1. On `dtn01.nersc.gov`, use `mongosh` to connect to the production Mongo server and [drop the databases](https://www.mongodb.com/docs/manual/reference/method/db.dropDatabase/):
        ```sh
        cd /global/cfs/projectdirs/m3408/nmdc-mongodumps

        ./bin/mongosh \
          --host="mongo-loadbalancer.nmdc.production.svc.spin.nersc.org" \
          --username "root" \
          --eval 'use nmdc'                                --eval 'db.dropDatabase()' \
          --eval 'use nmdc_test'                           --eval 'db.dropDatabase()' \
          --eval 'use nmdc_updated'                        --eval 'db.dropDatabase()' \
          --eval 'use nmdc_deleted'                        --eval 'db.dropDatabase()' \
          --eval 'use nmdc_changesheet_submission_results' --eval 'db.dropDatabase()'
        ```
  6. Restore the Napa dump (containing the re-ID-ed data) to the production Mongo server
     1. On `dtn01.nersc.gov`, use `mongorestore` to restore the Napa dump you created most recently, into the production Mongo server.
        > Replace the `{__TIMESTAMP__}` placeholder below with the real ending of the dump's directory name.
        ```sh
        cd /global/cfs/projectdirs/m3408/nmdc-mongodumps
        
        ./bin/mongorestore \
          --host="mongo-loadbalancer.nmdc.production.svc.spin.nersc.org" \
          --username="root" \
          --verbose --stopOnError --drop --preserveUUID \
          --nsInclude 'nmdc.*' \
          --nsInclude 'nmdc_deleted.*' \
          --nsInclude 'nmdc_updated.*' \
          --nsInclude 'nmdc_changesheet_submission_results.*' \
          --dir="./dump_nmdc-napa_{__TIMESTAMP__}"
        ```
        > This typically takes 7-8 minutes.
- [x] **Restore the production environment and access to it** (Eric)
  1. Restore production Mongo access
     1. At a `mongosh` shell, use the `root` user to connect to the production Mongo server and restore roles to their original definitions
        ```js
        use admin;

        // Allow team members and the aggregator to once again "read" from the `nmdc*` databases.
        // Note: The aggregator may actually require some "write" access; but that is out of scope for this task.
        //       This is the original definition of the "nmdc_reader" role.
        db.getRole("nmdc_reader");
        db.updateRole("nmdc_reader", { privileges: [], roles: [
          { db: "nmdc", role: "read" },
          { db: "nmdc_updated", role: "read" },
          { db: "nmdc_deleted", role: "read" },
          { db: "nmdc_changesheet_submission_results", role: "read" }
        ]});
        
        // Allow the scheduler to once again "read" from all `nmdc*` databases and "write" access to the `jobs` collection.
        db.getRole("nmdc_scheduler");
        db.updateRole("nmdc_scheduler", {
          privileges: [
            { resource: { db: "nmdc", collection: "jobs" }, actions: ["find", "insert", "update", "remove"] }
          ],
          roles: [
            { db: "nmdc", role: "read" },
          ]        
        });
        ```
  2. Bring the production Runtime (and friends) back online
     1. On Rancher, in the `nmdc` namespace, scale the following workloads up:
        - `runtime-api` (0 → 3)
        - `dagster-daemon` (0 → 1)
        - `scheduler` (0 → 1)
        - `aggregations` (0 → 1)
- [x] ingest from mongo prod -> local portal instance  (done by Mary 5/17)
- [x] ingest from mong prod -> data portal prod (Eric, manual after monthly release update on 5/21)
- [x] review of data portal (Alicia) - 6/8 studies have nmdc identifiers and have the correct number of samples and omics records per type.

**Criteria for completion**
- All nmdc identifiers (slot id for Classes Biosample, ProcessedSample, classes that inherit from WorkflowExecutionActivity, DataObject; slot metagenome_annotation_id for FunctionalAnnotationAggMember; slot metaproteomic_analysis_id for metap_gene_function_aggregation)

**Estimate people time**
- 3 person, 8 hours

**Completion Date (Goal)**
- May 7

**Target Sprint Start & End Dates**
- Start: May 6 
- End: May 17

**Tag Blocker/Contingent upon issues**
microbiomedata/issues#430 
microbiomedata/issues#524 
https://github.com/microbiomedata/nmdc_automation/issues/89

**Comment by eecavanna** [comment]
This comment is a reference for @eecavanna.

#### MongoDB: Granting and revoking write access

```js
use admin;
db.getUsers();

// Get all the distinct roles that are assigned to at least one user.
db.getCollection("system.users").distinct("roles.role");

// Get all the user-defined roles that exist.
db.getRoles({ showBuiltinRoles: false });

// Check which users have the `readWrite` role on any database.
db.getCollection("system.users").find({ "roles.role": "readWrite" });

// REVOKE the `readWrite` role from a user, on the "nmdc" database.
// Reference: https://www.mongodb.com/docs/manual/reference/method/db.revokeRolesFromUser/
db.revokeRolesFromUser("{username}", [{ role: "readWrite", db: "nmdc" }]);

// GRANT the `readWrite` role to a user, on the "nmdc" database.
// Reference: https://www.mongodb.com/docs/manual/reference/method/db.grantRolesToUser/
db.grantRolesToUser("{username}", [{ role: "readWrite", db: "nmdc" }]);


```

**Comment by aclum** [comment]
new target is next week.

**Comment by aclum** [comment]
Target for prod re-id is May 15

**Comment by aclum** [comment]
We did this for 6/8 studies. moving to the next sprint to completed the final two studies.

**Comment by aclum** [comment]
Closing this ticket, will make a new one to do the last two studies, target of next week.

**Comment by eecavanna** [comment]
Here's a link to the aforementioned new ticket: https://github.com/microbiomedata/issues/issues/712
