### ISSUE TITLE
Update SPRUCE records during prod mongo re-id

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#545]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1lLQ3wAwJzvxujER6-b4iDnnHx06MYsDbmIBMnu1IOeI/edit#gid=417989680

- 6

**RACI**

_Tag people in their roles_
- Responsible: @aclum 
- Accountable: @aclum 
- Consulted: @eecavanna 
- Informed:

**Describe the the task**
- [ ] Fix SPRUCE (gold:Gs0110138) referential integrity issues based on the json @sujaypatil96  made in https://github.com/microbiomedata/issues/issues/527. This should be done during the migration on mongo prod, doing it beforehand will break data portal ingest since the study has not been re-id yet. 

[20240129.spruce_mt_fixes.json](https://github.com/microbiomedata/issues/files/15113116/20240129.spruce_mt_fixes.json)

**Criteria for completion**
- Based on rdf query there are no referential integrity issues between classes OmicsProcessing, Biosample, and WorkflowExecutionActivity subclasses. 
**Estimate people time**
- 10 min

**Completion Date (Goal)**
- December 22

**Target Sprint Start & End Dates**
- Start: Dec 18
- End: Dec 22

**Tag Blocker/Contingent upon issues**
Must be done at the same time as #532

**Comment by ssarrafan** [comment]
@aclum who is working on this? It's not assigned yet.

**Comment by eecavanna** [comment]
Based on [this Slack message](https://nmdc-group.slack.com/archives/C05RNEJAV38/p1715557198484599), I think the people that will be doing the re-ID-ing in production (this Wednesday) have taken this task into account. 

I don't know where it fits in in the order of things (I assume it's somewhere between when the protection database gets dumped and when the re-ID-ed database gets restored into the production environment).

**Comment by aclum** [comment]
This has to happen before update-study is run on SPRUCE.

**Comment by ssarrafan** [comment]
Sprint over, removing from sprint.
