### ISSUE TITLE
Add Lake Mendota biosample metadata to existing records

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#556]
There is additional metadata in EDI that was sent via spreadsheet to Emiley, forwarded to Alicia on Dec 22, 2023

to do: add metadata to Lake Mendota biosample records. Alternative would be to link to the EDI records. 

NMDC study id nmdc:sty-11-5bgrvr62

**Comment by bmeluch** [comment]
Changesheets with additional metadata have been applied in dev and prod

**Comment by mslarae13** [comment]
@aclum what's left to do here with @bmeluch 's change sheet?

**Comment by aclum** [comment]
Nothing left to do here. Thanks @bmeluch
