### ISSUE TITLE
Test API submission to NCBI

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#559]
**Deliverable this task is associated with**

 FY24Q1 milestone

**RACI**

_Tag people in their roles_
- Responsible:
- Accountable: @shreddd 
- Consulted:
- Informed:

**Describe the the task**
- [ ] Test email instructions from Trow, Jonathan on how to submit to NCBI using their API
part of https://github.com/microbiomedata/issues/issues/445

**Criteria for completion**
- Success response code from NCBI for a biosample registration

**Estimate people time**
- [Hours or days of people time. 1 person, 4 hours]

**Completion Date (Goal)**
- [GOAL!]

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- depends on https://github.com/microbiomedata/issues/issues/669

cc @ssarrafan

**Comment by aclum** [comment]
@chienchi  Would you please comment on the status of this? We at least have done some testing because I've been getting confirmation emails, the last one I believe was successful.

**Comment by chienchi** [comment]
We have successfully tested the API submission to NCBI  test environmen using NEON samples. Sujay generated the submission.xml with the biosample <Action> blocks and the SRA <Action> blocks were mocked along with simulated fastq.gz files.
