### ISSUE TITLE
Method to generate functional search aggregation

### ISSUE THREAD

**Issue by scanon** [microbiomedata/issues#56]
The current functional search relies on some very large mongo collections.

This causes various problems and the data from JGI/IMG will not have the inputs.  I propose that we directly populate a mongo collection for the aggregations and then import that directly to postgres.

I'll add more comments here.

I'm tagging @shreedd so he can help track this.

**Comment by scanon** [comment]
I have a prototype script that will generate the aggregated counts and store them in mongo.

https://github.com/scanon/nmdc_automation/blob/main/src/generate_functional_agg.py

This generates mongo documents that look like...

```json
{
  "metagenome_annotation_id": "nmdc:8253bcdcd0387177ff895c38a047c719",
  "gene_function_id": "KEGG.ORTHOLOGY:K00627",
  "count": 120
}
```

**Comment by ssarrafan** [comment]
@scanon @shreddd 
Shane mentioned that this is ready to be handed off to Kitware.  
@jeffbaumes

**Comment by ssarrafan** [comment]
Hi @naglepuff is this on your radar?  Do you have time to work on this in the next couple of weeks?

**Comment by ssarrafan** [comment]
Note from Shreyas:
there are 2 follow ups 1. 
@elais  needs to implement in runtime and 2. 
@naglepuff  needs to look at this during the database ingest phase

**Comment by naglepuff** [comment]
@scanon We also keep an aggregation  called `metap_gene_function_aggregation`. You can see how the table is constructed with [this](https://github.com/microbiomedata/nmdc-server/blob/dcceec44b31512c8a9a2a891020a1a18abe4b017/nmdc_server/models.py#L737-L762) SQL. It also depends on the `mga_gene_function` table, and a couple of other tables that we build during ingest: `metaproteomic_peptide` and `peptide_mga_gene_function` ([link](https://github.com/microbiomedata/nmdc-server/blob/875f541a8d089795b3c2fdea4ac06fe2166140b1/nmdc_server/ingest/pipeline.py#L85)). I believe we only need these tables to build `metap_gene_function_aggregation`.

Is there a plan to create this aggregation on the mongo side? If not, we'd still need the `mga_gene_function` table to construct it on the ingest side.

**Comment by ssarrafan** [comment]
This is still being discussed. There was a meeting this morning. Will move to new sprint.

**Comment by ssarrafan** [comment]
I think this is done.  Ingest only takes 15 mins in dev now. Woot! Closing issue.
