### ISSUE TITLE
Implement welcome screen

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/issues#562]
1. [x] Add a welcome route which shows the welcome message, tutorial button, login button, and continue without login button. From the mockups to illustrate the content, not necessarily the exact styling needed (i.e. this screen probably shouldn't have the sidebar menu icon):

![Image](https://github.com/microbiomedata/issues/assets/102547565/b00ad9c4-ab29-4f5e-81ca-e7538b3128f9)

2. [ ] Add a tutorial route. I assume this should display a set of maybe 3 - 5 slides highlighting app features and/or best practices in the field? The exact content can come later, but for the purposes of this task let's just add the route a few placeholder slides. Ionic recommends using the Swiper.js library and has a tutorial here: https://ionicframework.com/docs/react/slides.

**Comment by ssarrafan** [comment]
Adding backlog label per @eecavanna

**Comment by eecavanna** [comment]
I am going to rename this issue to narrow its scope to only be about the welcome screen. 

I have created a new issue about the tutorial screens: https://github.com/microbiomedata/nmdc-field-notes/issues/48

**Comment by eecavanna** [comment]
The welcome screen has been implemented (albeit, with some "no op" buttons for now).
