### ISSUE TITLE
Design and implement offline-tolerant request and caching system

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/issues#563]
In order to be tolerant of working offline we need to design and implement a request manager that handles making API requests and maintaining a cache of the results. It also needs to use the cache to hold pending updates if objects are modified while the device is offline. Here is roughly how I imagine it working:

```mermaid
sequenceDiagram
    participant SYS as System
    participant USR as User
    participant STOR as Request Manager
    participant API

    USR->>+STOR: Get Submission
        opt network active
    STOR->>+API: GET Request
    end
    STOR->>-USR: Cached Data
    opt network active
        API-->>-STOR: Latest Data
        STOR-->>USR: Latest  Data
    end

    USR->>STOR: Save Submission
    opt network active
        STOR->>+API: POST/PATCH Request
        API-->>-STOR: Updated Data
    end

    SYS->>STOR: Network Reconnect Event
    loop Each submission with unsynced changes
        STOR->>+API: POST/PATCH Request
        API-->>-STOR: Updated Data
    end
```

My gut says that this is probably a pretty common use case so we should see what kind of 3rd party tools are already available that might implement some of this for us.

**Comment by eecavanna** [comment]
I read this article over lunch and found it helpful in ramping up on this topic.

https://ionic.io/blog/best-practices-for-building-offline-apps

P.S. I haven't yet viewed the sequence diagram in the issue description yet (doesn't show up in the GitHub mobile app, but I'll view it on desktop later).

**Comment by pkalita-lbl** [comment]
I _think_ a lot of this can be handled by using https://tanstack.com/query/latest/docs/react/overview. I've used it (or previous versions anyway) in prior projects mainly for its short-term caching features. I didn't use the mutations feature, but it looks promising. I'm going to start experimenting with it and see how it goes.

**Comment by pkalita-lbl** [comment]
Still actively being worked on. Moving to next sprint.
