### ISSUE TITLE
add ess-dive links for nmdc study gold:Gs0135149

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#564]
from https://github.com/microbiomedata/nmdc-server/issues/371
SESAR (per sample) and ESS DIVE links (per dataset) for the Brodie dataset 

See [spreadsheet](https://docs.google.com/spreadsheets/d/1HyWhwsOWD6np8MrEl9gzD3jpLmyd_oTNtbmTw28O0tM/edit#gid=652587412) copied from the previous ticket

**Comment by bmeluch** [comment]
Running into this same bug due to the study having a legacy id https://github.com/microbiomedata/nmdc-runtime/issues/416

This issue may be fixed by the re-IDing effort, since the current biosample IDs are IGSN identifiers and will be moved to the `igsn_biosample_identifiers` slot anyway.

**Comment by bmeluch** [comment]
ESS-DIVE dataset links are visible on the study page, IGSN identifiers are now present on biosamples. Hooray for re-IDing! 
Closing this, @aclum let me know if anything more needs to be done
