### ISSUE TITLE
metaT pipeline work

### ISSUE THREAD

**Issue by kaijli** [microbiomedata/issues#565]
Edit: 
MetaT Assembly and MetaG Annotation will be connected by NMDC Automation repo via the output `File final_contigs = create_agp.outcontigs` and input `String input_file`. Work will instead be performed on modularization of other workflow portions for connection. 

___
___
Modify output of [MetaT Assembly](https://github.com/microbiomedata/metaT_Assembly) to fit input for [MetaG Annotation](https://github.com/microbiomedata/mg_annotation/tree/master).

MetaT Assembly
```
output {
        File final_tar_bam = tar_bams.outtarbam
        File final_contigs = create_agp.outcontigs
        File final_scaffolds = create_agp.outscaffolds
        File final_log = assy.log
	File final_readlen = readstats_raw.outreadlen
        File final_sam = finalize_bams.outsam
        File final_bam = finalize_bams.outbam
    }
```

MetaG Annotation
- inputs.json.example
```
{
  "annotation.input_file": "/path/to/example/Ga0587029_contigs.fna",
  "annotation.imgap_project_id": "Ga0587029",
  "annotation.proj": "Ga0587029",
  "annotation.resource": "NERSC - CORI",
  "annotation.informed_by": "None"
}
```
- annotation_full.wdl
```
input {
  String  proj
  String  input_file
  String  imgap_project_id
  String  database_location="/refdata/img/"
  String  imgap_project_type="metagenome"
  String?  gm_license="/refdata/licenses/.gmhmmp2_key"
  Int     additional_threads=16
  String  container="microbiomedata/img-omics@sha256:d5f4306bf36a97d55a3710280b940b89d7d4aca76a343e75b0e250734bc82b71"

  # structural annotation
  Boolean sa_execute=true

  # functional annotation
  Boolean fa_execute=true
}
```

**Comment by kaijli** [comment]
Modified metaG ReadsQC [short reads workflow](https://github.com/microbiomedata/ReadsQC/tree/longReads) for [metaT version](https://github.com/microbiomedata/metaT_readsqc.git) to match JGI's QC, unpacked script from Donying's perlmutter folder and (reshuffled)[https://github.com/microbiomedata/metaT_read_counting.git]. MetaT ReadsQC successfully runs through test, but read counting is still in testing.

**Comment by kaijli** [comment]
All portions of workflow can be successfully run to completion. Ready for next steps of implementation.

**Comment by ssarrafan** [comment]
> All portions of workflow can be successfully run to completion. Ready for next steps of implementation.

Can this issue be closed? And open a new ticket for the next steps?

**Comment by ssarrafan** [comment]
I'm going to close this issue, @kaijli @aclum can you open a new issue for any additional next steps?
