### ISSUE TITLE
Bioscales - drop existing study, biosample and omics processing records for Bioscales in NMDC schema

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#57]
The existing study record in NMDC is https://data.microbiomedata.org/details/study/gold:Gs0154044 and is associated with 217 NMDC biosamples, 206 metagenome analysis activity sets. Relates to [ingest bioscales study#38](https://github.com/microbiomedata/issues/issues/38) as I've proposed capturing the existing study information modulo using the old identifier.

**Comment by aclum** [comment]
@ssarrafan  for the sprint starting 2/13/23

**Comment by aclum** [comment]
@sujaypatil96 @ssarrafan  this has to be done the sprint that starts on Monday or the following sprint.

**Comment by sujaypatil96** [comment]
Can we move this to the next sprint? I have other squad items to complete this sprint.

**Comment by aclum** [comment]
Yes, no problem.

**Comment by ssarrafan** [comment]
@aclum @sujaypatil96 any update on this?

**Comment by aclum** [comment]
@sujaypatil96  is going to work on this Monday so we need to move to the next sprint.

**Comment by sujaypatil96** [comment]
All changesheets are in this workbook: https://docs.google.com/spreadsheets/d/1swZfJP4V-_vWybWLuT0jm8Xbyvw4peFm5jn2_7qKo3c/edit?usp=sharing

**Comment by sujaypatil96** [comment]
This has been completed.
