### ISSUE TITLE
NEON - update benthic env_medium slots

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#571]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit#gid=417989680

- 3

**RACI**

_Tag people in their roles_
- Responsible: @sujaypatil96 
- Accountable: @turbomam 
- Consulted: @aclum 
- Informed: @aclum @cmungall 

**Describe the the task**
- [x] Mark made new ENVO terms for benthic samples, NMDC study id nmdc:sty-11-pzmd0x14, and we now need to use changesheets to update the biosample_set records to use these new terms for slot env_medium. The replacement values should come from the `*amb_fieldParent*csv`, field `aquMicrobeType`. Previously we were using field `sampleMaterial` from that same table. 
New mappings are below.  These terms are in envo in the owl.edit file but not in OLS search yet (pending envo release).
amb_fieldParent.aquMicrobeType,NMDC.env_medium
"epilithon", "epilithon" [ENVO:03605001]
"epipelon", "epipelon" [ENVO:03605002]
"epiphyton", "epiphyton" [ENVO:03605003]
"epipsammon", "epipsammon" [ENVO:03605004]
"epixylon", "epixylon" [ENVO:03605005]

**Criteria for completion**
- biosample_set documents in mongo prod which are `part_of` `nmdc:sty-11-pzmd0x14` have `env_medium` values only from the above list. 

**Estimate people time**
- [Hours or days of people time. 1 person, 2 hours]

**Completion Date (Goal)**
- January 26, 2024

**Target Sprint Start & End Dates**
- Start: Jan 15, 2024
- End: January 26, 2024

**Tag Blocker/Contingent upon issues**

**Comment by sujaypatil96** [comment]
Will have the changesheet for this ready/done by tomorrow, 2/9.

**Comment by sujaypatil96** [comment]
@aclum the changesheet that completes this task has been sent on Slack because GitHub does not allow us to upload/share tsv files.

**Comment by sujaypatil96** [comment]
Changesheet reviewed and applied to both dev and prod Mongo. This issue can be moved to done and closed.
