### ISSUE TITLE
Add proteomics data_object_set records for SPRUCE (gold:Gs0110138)

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#585]
We need this for referential integrity and so the proteomics workflow has all needed information in mongo.  Sam has already started working. 
- [x] Make data object json (Sam)
- [ ] submit to mongo napa and prod during re-iding (Alicia)

This was done recently for the gold:Gs0114663

**Comment by SamuelPurvine** [comment]
@aclum  This should work :) Please let me know if it does not!
[nmdc.data_objects_set.spruce.metap.SOP01.json](https://github.com/microbiomedata/issues/files/14068319/nmdc.data_objects_set.spruce.metap.SOP01.json)

**Comment by aclum** [comment]
Fixed some small issues new json is attached, these have been added to mongo and I used changesheets to update the corresponding omics_processing_set has_output values. TSVs can't be attached but the changsheet is in the napa compliance squad directory on google docs, file name "spruce metap data records"

[nmdc.data_objects_set.spruce.metap.SOP01.FIXED.json](https://github.com/microbiomedata/issues/files/14070501/nmdc.data_objects_set.spruce.metap.SOP01.FIXED.json)

**Comment by aclum** [comment]
Putting this as blocked until the it is time for the production update.

**Comment by aclum** [comment]
Closing this to avoid confusion b/c there are other tickets that have more updated data files to use for the production updates. Files for stegen are attached or linked to https://github.com/microbiomedata/nmdc_automation/issues/111 files for spruce are attached or linked to https://github.com/microbiomedata/nmdc_automation/issues/109
