### ISSUE TITLE
identifier slot for img ids

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#6]
Make an alternative identifiers slot for IMG IDs

@turbomam can you add more details here when the time comes to work on this please

**Comment by turbomam** [comment]
@ssarrafan can you answer any of these questions, or tell me who can?

- What action is required?
- What class should bear an IMG ID attribute?
- What kind of thing should the IMG ID point to?

**Comment by ssarrafan** [comment]
> @ssarrafan can you answer any of these questions, or tell me who can?
> 
> * What action is required?
> * What class should bear an IMG ID attribute?
> * What kind of thing should the IMG ID point to?

Here are some answers from @pvangay:
What action is required? — not sure I understand this question
What class should bear an IMG ID attribute? — I would think BioSample?
What kind of thing should the IMG ID point to? — there are some redirects that take place here. based on a changesheet i helped with recently, the ID is provided in the slot but it’s ultimately used (by kitware I believe) in this url: [identifiers.org/id](http://identifiers.org/id) — which then gets redirected to the proper IMG URL.  
Thank you @pvangay for your help!

**Comment by sujaypatil96** [comment]
Linked issue: https://github.com/linkml/linkml/issues/938

**Comment by turbomam** [comment]
@mslarae13 said probably links to IMG biosmaple identifiers

The point here is that IMG identifiers shouldn't go in a catch-all slot, but rather a qualified/attributes slot.

See https://data.dev.microbiomedata.org/details/sample/gold:Gb0126432

which links to https://img.jgi.doe.gov/cgi-bin/w/main.cgi?section=TaxonDetail&taxon_oid=3300042765

It looks like that IMG page is about the results of assembling and taxon-calling

There's an NMDC link! 

NMDC ID | nmdc:mga0jx8k09

What patterns does GOLD use for linking biosmaples to results?

**Comment by ssarrafan** [comment]
@turbomam Any update on this issue? Can this issue be closed today or by Tuesday?

**Comment by ssarrafan** [comment]
Discussed at squad meeting and moving to the backlog.

**Comment by turbomam** [comment]
@mslarae13 I have created a multivalued but otherwise under-specified `img_identifiers` slot for class `Biosample` . I am also migrating `alternative_identifiers`  with prefixes of 'img.taxon' into the `img_identifiers` slot in https://github.com/microbiomedata/nmdc-schema/blob/issue-486-data-to-7-0/util/migrate_7.py

@ssarrafan what can you and I do to ensure that the right level of detail is provided by the requesting party at the time of issue creation?
