### ISSUE TITLE
`MassSpectrometry` Changesheets and mapping slots to DMS

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/issues#601]
As part of the Berekeley refactoring, the new MassSpectrometry class will require a migration from `DataGeneration`/`OmicsProcessing` to `MassSpectrometry`. This will require both a migration and an ingest for the new fields introduced in the class. We need to map the slots to where they exist in DMS to prepare for an ingest. 

- [x] #748
- [x] #750
- [x] #751
- [ ] #773
- [x] #749
- [x] #803

**Comment by ssarrafan** [comment]
@SamuelPurvine @brynnz22 I'll move this to the current sprint but please let me know if you are not actively working on it.

**Comment by brynnz22** [comment]
Yes, we are working on it. Sorry for missing this!

**Comment by brynnz22** [comment]
Update - most slots mapped. We possibly need to adjust some of the mappings. Some notes from @kheal:
- Agilent_GC_MS should not be direct infusion for the `eluent_introduction`, it should be chromotographics separation process
- `ionization_source` should not be `electrospray_ionization`, it should be `electron_ionization`: see issue to add enum to schema here: https://github.com/microbiomedata/nmdc-schema/issues/1777
- for VOrbiETD04 `mass_spectrum_collection_mode` should be `profile` not `centroid` (not sure if its reduced or full)
- All of the mappings need the `eluent_introduction` details mapped, which is a nested class. Can we create these mappings in JSON instead of a spreadsheet? 
- How can we connect to the protocols and utilize the `protocol_link` slot? 

Other things: 

- Do we need to include the qc metadata slots (e.g. `qc_status`, `qc_comment`, and `has_failure_categorization`, and if so, how do these map?

**Comment by kheal** [comment]
Regarding the note above re: VOrbiETD04 mapping `mass_spectrum_collection_mode` as `profile` is not a generalizable assumption. The specific DMS datasets that were collected on the VOrbiETD04 are profile mode but that's not necessarily true for all data collected on this instrument.  I know this only because I am working directly with the data.

**Comment by kheal** [comment]
@SamuelPurvine @brynnz22 

Additional note - some of these data are collected with multiple types of mass analyzers (Orbitrap for ms1 and some ms2; ion_trap for some ms2).  Right now the `mass_analyzer` slot in the `MassSpectrometry` class only accepts one value.  We could be more explicit in the slot definition to indicate that this is the primary mass_analyzer (or alternate language), or allow for multiple types.

**Comment by ssarrafan** [comment]
Doesn't appear to be an active issue?  @brynnz22 @kheal 
I'm removing this from the sprint and adding backlog label.

**Comment by brynnz22** [comment]
@ssarrafan apologies I thought I moved everything to  the next sprint before I left office last week. This is actively being work on. I will move it to the new sprint. Sorry for the mix up!

**Comment by brynnz22** [comment]
Backlogging this for now since our work if overlapping with the metabolomics squads work, and since the `MassSpectrometry` class will be changing a bit, we will wait to finish up the mapping to the final schema changes. Most of the mapping work is done.

**Comment by ssarrafan** [comment]
@brynnz22 @SamuelPurvine are you planning to work on this issue next sprint?

**Comment by SamuelPurvine** [comment]
Pretty sure yes :)

**Comment by brynnz22** [comment]
Sorry @ssarrafan . I am going to break this into smaller tasks so it doesn't span multiple sprints.

**Comment by brynnz22** [comment]
Removing from sprint and replacing with smaller issues.

**Comment by brynnz22** [comment]
Everything is added to prod, with the exception of the Chemical Entities which I believe @kheal  is working on. Closing out this issue.
