### ISSUE TITLE
2024.3 release

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#602]
Release 2024.3 is schedule to be released to production on Monday March 25, 2024.

The version of nmdc-schema to be used in this release should be stable by Wednesday March 13, 2024.

Feature freeze for nmdc-server and nmdc-runtime is end-of-day Tuesday, March 19, 2024. After that point only critical bug fixes should go into dev.

Focused testing on dev should begin by Wednesday March 20, 2024.

Please use this issue to record any deployment work that needs to happen outside of the standard deployment procedure.

cc @pkalita-lbl

**Comment by pkalita-lbl** [comment]
Done.

* New `nmdc-runtime` version is 1.4.2
* New `nmdc-server` version is 0.19.0
* Schema version used by both is 10.1.4
* Ingest into prod data portal succeeded
* Copy of Mongo data from prod to dev succeeded
