### ISSUE TITLE
1000 soils- Process NOM data

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#604]
1000 soils have NOM data. The DMS IDs are similar enough to the biosample names that mapping will be easy.

- [x] Provide mapping file to Yuri
- [ ] Process NOM data
- [ ] Ingest to dev for testing
- [ ] Ingest to prod

**Comment by bmeluch** [comment]
Working on matching NMDC biosamples to DMS data files, have reached out to EMSL team with questions (why are there so many data files per sample?) Once that is sorted out I will be able to make the mapping file for Yuri.

**Comment by ssarrafan** [comment]
@mslarae13 @bmeluch is this an active issue?  I'm going to remove this from this sprint and add to the backlog but if it's active please add to a future sprint.

**Comment by bmeluch** [comment]
EMSL team got back to us with helpful information, sample mapping file was provided on 29 Feb

**Comment by ssarrafan** [comment]
Email from @bmeluch:

Here are the biosample to fastq mappings.

https://portal.nersc.gov/project/m3408/submission_data/e8f724a2-9cbc-48e5-a35b-1abd5a182fee/ this submission includes md5 checksums, I put the filename in the md5 column
https://portal.nersc.gov/project/m3408/submission_data/fdd683e8-374a-43a7-9619-628eb0a37869/ this submission includes “raw” and “filtered” files, both are in the file, I can remove one or the other if you like
Thank you for working on this!

**Comment by bmeluch** [comment]
Hi Set, that email attachment was regarding the metagenome file mappings, not the NOM files - different issue

**Comment by ssarrafan** [comment]
> Hi Set, that email attachment was regarding the metagenome file mappings, not the NOM files - different issue

ah! ok. I'll remove from this issue.  Thanks.

**Comment by bmeluch** [comment]
Currently with Yuri to process the NOM data, it is still active, he's just had a crazy two weeks

**Comment by ssarrafan** [comment]
ok it's been moved to the next sprint
@aclum fyi

**Comment by bmeluch** [comment]
NOM data is in production Mongo! Hooray for @corilo
