### ISSUE TITLE
NMDC website updates for GSP/ECR 2024

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#605]
These requests are in order of priority to be done by March 11, 2024 in preparation for GSP/ECR. More details at https://docs.google.com/document/d/1cELSdx7d-LMffokFT-2uIEjJqCJRjvHUU1dXrzgZCQI/edit 

- [x] #606
- [x] #607
- [x] #609
- [x] #608

**Comment by eecavanna** [comment]
FYI @pkalita-lbl: I am starting to work on making the above changes to the NMDC website. No action needed on your part — just a heads up that some website updates are in the works, some of which may involve uploading a new version of the WordPress theme (I'll contact you directly if that's the case).

**Comment by eecavanna** [comment]
Note for sprint planning: There's a chance this will be done Friday afternoon, but I think it's more likely that it will spill over into the next sprint.

**Comment by eecavanna** [comment]
> Update the Code of Conduct on the website to reflect the updated one on GitHub

I don't know which updated one on GitHub this is referring to. Do you have a URL to it?

**Comment by ssarrafan** [comment]
> > Update the Code of Conduct on the website to reflect the updated one on GitHub
> 
> I don't know which updated one on GitHub this is referring to. Do you have a URL to it?

The is the CoC on GitHub but I don't think it has the latest updates from @shreddd yet: https://github.com/microbiomedata/nmdc-schema/blob/main/CODE_OF_CONDUCT.md

**Comment by eecavanna** [comment]
Here is the current status of each of the tasks listed in the issue description (as of the end of the day on Friday):

![image](https://github.com/microbiomedata/issues/assets/134325062/1d0ea33f-1981-4479-a82f-09374871af09)

**Comment by eecavanna** [comment]
Hi @ssarrafan, are you OK with me moving the CoC item into a separate ticket?

> Update the Code of Conduct on the website to reflect the updated one on GitHub

That will allow me to close this one when the other sub-tasks of this one are done.

**Comment by ssarrafan** [comment]
> Hi @ssarrafan, are you OK with me moving the CoC item into a separate ticket?
> 
> > Update the Code of Conduct on the website to reflect the updated one on GitHub
> 
> That will allow me to close this one when the other sub-tasks of this one are done.

Absolutely. @shreddd and I are going to get together (soon I hope) to update the CoC in GitHub so this can be a new issue that I can create for the future.

**Comment by eecavanna** [comment]
Thanks, @ssarrafan. For future reference, here's a link to that issue: #626
