### ISSUE TITLE
GSP/ECR 2024 Website updates - Team, Advisory Board, Champions, Ambassadors pages updates

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#607]
- [x] Remove blue bar and blue tint to all headshots for Team, Advisory, Ambassador and Champions pages
- [x] Move names and affiliations to below the photo so it is not cutting into the photo
- [x] Remove the grey box if possible and have the title of the page but just not in the grey box
- [x] Create ticket #624

**Comment by eecavanna** [comment]
Before I make any changes, here's are some screenshots showing the current state of things:

Example from https://microbiomedata.org/team/:

<img width="400" alt="image" src="https://github.com/microbiomedata/issues/assets/134325062/04f0823c-d1e3-47a2-ae3d-694634fc2fdd">

Example from https://microbiomedata.org/advisory/:

<img width="400" alt="image" src="https://github.com/microbiomedata/issues/assets/134325062/85f90bb9-759d-4cbe-abbc-351b7b51da0e">

Example from https://microbiomedata.org/ambassadors/:

<img width="400" alt="image" src="https://github.com/microbiomedata/issues/assets/134325062/da8a1ffe-9025-401a-88c9-903de07bbe94">

Example from https://microbiomedata.org/community/championsprogram/:

<img width="400" alt="image" src="https://github.com/microbiomedata/issues/assets/134325062/4c8059ca-ea35-46cb-97d7-02b2f58672e4">

**Comment by eecavanna** [comment]
Here's a screenshot from my development instance of the website, where I have implemented the changes described by the first two of the four checkboxes in the PR description.

<img src="https://github.com/microbiomedata/issues/assets/134325062/4f323fd0-5357-4e37-8be3-96a968487121" width="400">

**Comment by eecavanna** [comment]
> Remove the grey box if possible and **have the title of the page but just not in the grey box**

The second half of that can be done by adding a "block" (of type "Hero") to the page, dragging that block _above_ the existing "Team" block, and then configuring the block as follows:

- Title: `NMDC Team Members`
- Subtitle: (Optional)
- Background: (Click "Add Image" and choose a background image)

<img width="600" alt="image" src="https://github.com/microbiomedata/issues/assets/134325062/2484786b-29c3-4592-8cc4-a93f1d9a0889">

The result will look like this:

<img width="600" alt="image" src="https://github.com/microbiomedata/issues/assets/134325062/c049db2d-342e-456a-a483-3a59cf2c32dc">

**Comment by eecavanna** [comment]
> **Remove the grey box if possible** and have the title of the page but just not in the grey box

The first part of that can be done by emptying out the "Title" field within the "Team" block.

<img width="600" alt="image" src="https://github.com/microbiomedata/issues/assets/134325062/4c12d9c3-53fd-4fd7-8d0d-80ffadcb6e7e">

The result looks like this (with the "hero" image in place—see previous comment):

<img width="600" alt="image" src="https://github.com/microbiomedata/issues/assets/134325062/868f9b5e-2f88-4420-94d3-606472ae6716">

**Comment by emileyfadrosh** [comment]
Thanks @eecavanna! I just made updates to the team and SAB page to remove the gray box and add the hero banner. Looks great :)

**Comment by eecavanna** [comment]
Reopening issue because, although the code changes for items 1-2 have been implemented, they have not yet deployed to the production website. I'll close the issue once they have been deployed to the production website. Then, I'll open an independent issue for item 4 (updating the bio content).

**Comment by ssarrafan** [comment]
> Reopening issue because, although the code changes for items 1-2 have been implemented, they have not yet deployed to the production website. I'll close the issue once they have been deployed to the production website. Then, I'll open an independent issue for item 4 (updating the bio content).

I'll add to next sprint under "in review".  Should we add a column for "ready for prod" or "waiting for prod release" or something?

**Comment by eecavanna** [comment]
> Should we add a column for "ready for prod" or "waiting for prod release" or something?

I like that idea. The column could be between `in review` and `done`.

In past projects, I have used a **label** called `awaiting-release` for that.

**Comment by eecavanna** [comment]
I created a separate ticket for item 4. That ticket is here: https://github.com/microbiomedata/issues/issues/624

**Comment by eecavanna** [comment]
Now that items 3-4 are live in production and item 4 is represented by a separate ticket, I will close this one.
