### ISSUE TITLE
GSP/ECR 2024 Website updates - IDEA page - rename IDEA "Strategic Plan" to Action Plan with the same URL

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#608]
- [x] Rename IDEA "Strategic Plan" to Action Plan
- [x] Would like to have a URL with the words action plan instead of strategic plan but would like the old URL to resolve to the new one. Current URL:  https://microbiomedata.org/idea-strategic-plan/

**Comment by eecavanna** [comment]
Before I make any changes, here's what it looks like today:

<img width="876" alt="image" src="https://github.com/microbiomedata/issues/assets/134325062/93153a4f-9b04-4942-a518-bb4e834ee229">

**Comment by eecavanna** [comment]
> Would like to have a URL with the words action plan instead of strategic plan but would like the old URL to resolve to the new one.

My plan for this is to:

1. Update the page title from `IDEA Strategic Plan` to `IDEA Action Plan`
2. Update the page slug from `idea-strategic-plan` to `idea-action-plan`
3. Use the "Redirections" plugin (which happens to be installed—see heavily-redacted screenshot below) to redirect people that visit `idea-strategic-plan` so they end up at `idea-action-plan`

![image](https://github.com/microbiomedata/issues/assets/134325062/ed082c4a-eb9d-4cec-ba93-4c864f70aeb1)

**Comment by eecavanna** [comment]
This is done.

Now, when people visit https://microbiomedata.org/idea-strategic-plan, their web browsers will automatically go to https://microbiomedata.org/idea-action-plan instead.

<img width="454" alt="image" src="https://github.com/microbiomedata/issues/assets/134325062/78a4ee16-5d8d-4c3c-b535-0d55ae0c6309">
