### ISSUE TITLE
JGI API assessment

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#61]
Assessment by @mflynn-lanl to see if JDP API can replace direct jamo query. 
Go/no go date for this decision is 2/14/23

**Comment by ssarrafan** [comment]
I'll move to the new sprint since the go/no go date is 2/14
Asked @mflynn-lanl for status via Slack

**Comment by ssarrafan** [comment]
@mflynn-lanl @aclum what's the status of this issue?

**Comment by aclum** [comment]
I think this can be closed. @mflynn-lanl  been using the API to fetch and stage the data.

**Comment by ssarrafan** [comment]
Closing per Alicia's last comment. Thanks!
