### ISSUE TITLE
Enable integrated authentication and authorization across NMDC products and infrastructure using ORCiD (6.2)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#614]
To streamline the user experience across the 3 NMDC products, we are working towards integrated authentication using ORCiD. Towards this effort, we have completed ORCID membership requirements and deployed ORCID member credentials on the Data Portal along with access to the NMDC API. A design for authentication for the Submission Portal and NMDC EDGE has been completed with anticipated completion by FY24 Q3. 

From DOE Quarterly Update 2024 Q1 report

**Comment by aclum** [comment]
@shreddd  please close if compelte.

**Comment by ssarrafan** [comment]
I think we reported this as done so I'm closing.  @shreddd if you want to add more details here that would be great.
