### ISSUE TITLE
Align existing metadata with NMDC identifiers (6.8)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#615]
The NMDC launched new persistent identifiers last year and work to update existing data has been underway. Code has been successfully developed for re-iding and reprocessing data records using a separate instance of mongo, runtime, and the workflow scheduler. We anticipate this work to be completed by FY24 Q3. 

From DOE Quarterly Update 2024 Q1 report

**Comment by aclum** [comment]
This work has been in progress for several months. See [napa compliance board ](https://github.com/orgs/microbiomedata/projects/81)

**Comment by ssarrafan** [comment]
Related to issue created by @mbthornton-lbl https://github.com/microbiomedata/nmdc-schema/issues/1807

**Comment by ssarrafan** [comment]
@aclum  just a heads up that we need to report on this and close it by June for the next DOE report.

**Comment by aclum** [comment]
We expect this work to be completed in April.

**Comment by aclum** [comment]
All records now use NMDC persistent identifiers. There were some issues introduced with workflow version identifiers that are being addressed in separate tickets (
https://github.com/microbiomedata/nmdc_automation/issues/201 and https://github.com/microbiomedata/nmdc_automation/issues/198)
