### ISSUE TITLE
Sync up on the class name change for the readbased analysis set

### ISSUE THREAD

**Issue by scanon** [microbiomedata/issues#62]
The read based analysis set name was changed back in August in the Schema but since the runtime and portal were still using the old schema, this change didn't have any impact.  The old name was read_based_analysis_activity_set and the new name is read_based_taxonomy_analysis_activity_set.

See commit: https://github.com/microbiomedata/nmdc-schema/commit/7600327ec0a583477e3596e5cedc93510b996934

When we migrate everything to the new schema, this should handle moving data from the old collection name to the new one in mongo.  I'm both assuming and/or asserting this.  But this hasn't been done yet and I'm not clear if this is planned for GSP.  Since the runtime is using the new schema, then currently that means new data is going into the new collection.  Also the portal will need to be updated so it does the ingest from the correct collection.

So for GSP I see two options...

1) Go ahead and migrate this collection over prior to GSP so everything is in the new collection name.

2) Force the runtime to use the old collection name for any new data and then plan to fix this during the eventual migration operation.

**Comment by scanon** [comment]
It sounds like the decision is to move to the name.

So the steps would be...

* Change the name of the existing collection in mongo (this may require a dump/restore of that collection)
* Fix the name in the ingest side of the portal

**Comment by aclum** [comment]
@scanon  is there an update on this?

**Comment by aclum** [comment]
912 documents with old name (read_based_analysis_activity_set) - this sounds right
7 documents with the new name (read_based_taxonomy_analysis_activity_set) - this sounds wrong, related to recovery from issues with spin filling up.

**Comment by scanon** [comment]
I've now copied all the old one (912) into the new collection.

The current count for `read_based_taxonomy_analysis_activity_set` is 1095

**Comment by naglepuff** [comment]
Just to be clear, @scanon @aclum, are we deprecating the collection called `reads_based_analysis_activity_set` in favor of the new collection called `reads_based_taxonomy_analysis_activity_set`? Should I (i.e. the ingest script) treat `reads_based_analysis_activity_set` like it won't exist in the future?

I want to make sure that ingest is still pulling in from the right collection/collections.

**Comment by aclum** [comment]
@naglepuff  Yes, reads_based_analysis_activity_set no longer exists in the schema is 7.4.12
https://microbiomedata.github.io/nmdc-schema/Database. The ingest script should use `reads_based_taxonomy_analysis_activity_set`

**Comment by ssarrafan** [comment]
@shreddd @scanon @aclum assuming I can close this issue? Please confirm (or close).

**Comment by ssarrafan** [comment]
I'm closing this. @scanon @shreddd let me know if there are still loose ends and this needs to be re-opened.
