### ISSUE TITLE
Add information to the data portal about re-iding

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#620]
**Deliverable this task is associated with**

_See Deliverables tab here: _

- [Add the Deliverable #]

**RACI**

_Tag people in their roles_
- Responsible: @aclum 
- Accountable:
- Consulted: leadership team
- Informed: leadership team

**Describe the the task**
- [x] determine language to post on the NMDC data portal about re-iding
- [x] [get this updated as a banner on the nmdc data portal](https://github.com/microbiomedata/nmdc-server/issues/1211)

**Criteria for completion**
- prod data portal has information about re-iding

**Estimate people time**
- [Hours or days of people time. 1 person, 4 hours]

**Completion Date (Goal)**
- April 17, 2024

**Target Sprint Start & End Dates**
- Start: April 8
- End: April 19

**Tag Blocker/Contingent upon issues**

**Comment by ssarrafan** [comment]
@aclum I'm going to assume this will be done in the next sprint?

**Comment by aclum** [comment]
yes, please this should move to the next sprint.

**Comment by aclum** [comment]
Remove from the current sprint b/c this is now an after gsp activity.

**Comment by aclum** [comment]
Draft text sent to leadership, [PR](https://github.com/microbiomedata/nmdc-schema/pull/1924) on schema documentation.

**Comment by aclum** [comment]
An announcement banner is now posted on data portal prod.
