### ISSUE TITLE
Determine FMA to UBERON mapping for TRiP project

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#625]
In reviewing environmental context terms several weeks ago it was determined that we should preferentially use UBERON over FMA per Chris' recommendation. We need to update terms for study id nmdc:sty-11-hdd4bf83.

**RACI**

_Tag people in their roles_
- Responsible: @turbomam @cmungall 
- Accountable: @cmungall 
- Consulted:
- Informed:

**Describe the the task**
- [x] Determine what UBERON terms should replace existing FMA term FMA:14541
- [x] Update records in mongo via changesheets such that has_raw_value, term.id, term.name use an UBERON term for env_local_scale and env_medium

**Criteria for completion**
- [What does success look like for this task to be considered complete?]
- FMA is not a prefix used for any studies for env_local_scale, env_medium, and env_broad_scale

**Estimate people time**
- [Hours or days of people time. 1 person, 4 hours]

**Completion Date (Goal)**
- March 22

**Target Sprint Start & End Dates**
- Start: March 11
- End: March 22

**Tag Blocker/Contingent upon issues**
- [Tagg issues]

**Comment by cmungall** [comment]
caecum http://purl.obolibrary.org/obo/UBERON_0001153

(it's already mapped)

**Comment by ssarrafan** [comment]
> caecum http://purl.obolibrary.org/obo/UBERON_0001153
> 
> (it's already mapped)

Does this mean we can close this issue @aclum ?

**Comment by aclum** [comment]
not yet, someone needs to update the metadata in mongo.

**Comment by turbomam** [comment]
This is Study [nmdc:sty-11-hdd4bf83](https://w3id.org/nmdc/sty-11-hdd4bf83)

@cmungall and I started a [discussion about this in the GSC Slack workspace](https://gsc-vpc4453.slack.com/archives/C023NM0C85S/p1709913373300259)

I recommend sticking with `env_broad_scale` of animal-associated environment (ENVO:01001002), but nobody besides @cmungall and I have formally signed on to that yet. We might have a different perspective in the future.

I recommend

**Comment by aclum** [comment]
@turbomam  please issue the changesheets to that effect.

**Comment by ssarrafan** [comment]
Based on comments last week assuming this is active.  @aclum @turbomam let me know if this should go in the backlog instead.  Moving to next sprint.

**Comment by turbomam** [comment]
I still haven't applied these changes. Was nervous about doing it before GSP/ECR Thanks for the reminder.

**Comment by ssarrafan** [comment]
@aclum is this still a priority?

**Comment by ssarrafan** [comment]
Moving to next sprint. @turbomam will remove from sprint if it's no longer a priority.

**Comment by turbomam** [comment]
I'll be on vacation through Wednesday but will apply change sheets for the FMA and meadow ecosystem annotations before the end of the week

**Comment by ssarrafan** [comment]
@mslarae13 should this be moved to the next sprint?  backlog?

**Comment by ssarrafan** [comment]
@turbomam is almost done. Needs @aclum to sign off to complete. Moving to next sprint.

**Comment by aclum** [comment]
Confirming prod records have been updated.
