### ISSUE TITLE
Update the Code of Conduct on the website to reflect the updated one on GitHub

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#626]
Update Code of Conduct in GitHub so that it can be pulled into the website.

**Comment by eecavanna** [comment]
Hi @ssarrafan, I will put that new CoC content on the website tomorrow, Friday, 3/22.

I'll post a follow-up message here when that has been done.

FYI: @jkelliher-github, @emileyfadrosh

**Comment by eecavanna** [comment]
Done. I put the new Code of Conduct [on the website](https://microbiomedata.org/nmdc-code-of-conduct/).
