### ISSUE TITLE
Create "Events" page on website

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/issues#627]
The website navigation menu described in https://github.com/microbiomedata/issues/issues/606 includes a `Partner with Us` > `Events` menu item.

In [this comment](https://github.com/microbiomedata/issues/issues/606#issuecomment-1962261264) on that issue, @emileyfadrosh said she thought someone had suggested that the page it points to be a page containing a calendar of upcoming events.

This ticket represents the task of creating such a page. Once the page exists, someone (e.g. @eecavanna) can create the `Partner with Us` > `Events` menu item that points to it.

**Comment by eecavanna** [comment]
**Caution:** There is already a page whose "slug" is `events`.

![image](https://github.com/microbiomedata/issues/assets/134325062/7e3aa534-c319-4f90-86ad-2b1ad750b125)

The page can created with an arbitrary slug and then—before adding it to the menu–we can work together to map the right slugs to the right pages.

**Comment by ssarrafan** [comment]
@emileyfadrosh @eecavanna will this be done by Friday?

**Comment by eecavanna** [comment]
I expect the creation of the menu item to take me 5 minutes.

I am waiting until the page exists before I create the next item.

I'm OK deferring this to the next sprint. I consider website updates to be an "asynchronous" thing, not accounted for in our monthly product release process.

**Comment by emileyfadrosh** [comment]
Hi @eecavanna: Let's not create a new "Events" page right now. 

However, I would like to go back to https://github.com/microbiomedata/issues/issues/606 for the **News & Impact > Newsletters**. It looks like the page exists (https://microbiomedata.org/newsletters/) but does not appear in the navigation menu. Can that be added since you are making updates for the Field Notes?

**Comment by eecavanna** [comment]
Whoops! Thanks for bringing that to my attention.

I will add a menu item for it now (in the 2nd position from the top, as shown in #606):

![image](https://github.com/microbiomedata/issues/assets/134325062/d3c06f20-7b71-46e5-a97e-5866b5992b9a)

**Comment by eecavanna** [comment]
>Let's not create a new "Events" page right now.

OK, that works for me.

**Comment by eecavanna** [comment]
It's in the website menu now.

![image](https://github.com/microbiomedata/issues/assets/134325062/1e2db9c6-cce6-439b-8b4d-d65a03b84a59)

I'll add it to the Data Portal's menu also... at least, in the code/repository. I don't know when we will be deploying to the production Data Portal next (I put that topic on the agenda for tomorrow's infrastructure meeting).

**Comment by emileyfadrosh** [comment]
Perfect, thanks!!!

**Comment by ssarrafan** [comment]
I'm going to remove this from the sprint and add the backlog label since @emileyfadrosh decided to hold of on the events page.

**Comment by emileyfadrosh** [comment]
I believe all this has been sorted out for the website. Thanks @eecavanna for the great work on updates! I will close this issue so it's not sitting in the backlog gathering dust :)
