### ISSUE TITLE
Add "Newsletters" page to website menu

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/issues#628]
An outstanding subtask of https://github.com/microbiomedata/issues/issues/606 is to add a menu item at `News & Impact` > `Newsletters` that points to the "Newsletters" page. 

This task is to—once the "Newsletters" page has been finalized—create that menu item.

**Time estimate:** less than 5 minutes (less than 1 minute if I'm already working on the website).

**Comment by ssarrafan** [comment]
checked with @eecavanna and moving to next sprint

**Comment by eecavanna** [comment]
I did this tonight.
