### ISSUE TITLE
Migrate to new data object ID scheme

### ISSUE THREAD

**Issue by scanon** [microbiomedata/issues#63]
Up until now the data object IDs have been based on the MD5 sum of the file.  However, the plan is to have these follow the Napa protocol.

The pattern can be seen here...

https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/nmdc.yaml#L224

The pattern is...  "{id_nmdc_prefix}:dobj-{id_shoulder}-{id_blade}{id_version}{id_locus}"

Note this allows for a version and a locus but I don't know if we want to try to track versions and the locus doesn't apply here.

At a minimum we will need to mint new IDs for the existing data.

Additionally, we will have to make some changes in the workflow automation since the workflow wouldn't know the IDs for any inputs and would need to call the minting service to generate new IDs.

I propose that adopt issue #59 so that we don't need the workflows to be making API calls (which I think is a `#BadIdea`).

**Comment by aclum** [comment]
Closing this out, Shane marked this Done on the workflow automation board in March 2023.
