### ISSUE TITLE
Determine and populate in Berkeley schema NMDC MaterialProcessing metadata fields for small molecule workflows

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#640]
**Deliverable this task is associated with**

This task is the deliverable, please add issues as needed to break up work

**RACI**

_Tag people in their roles_
- Responsible:  @anastasiyaprymolenna 
- Accountable: @corilo 
- Consulted: @brynnz22 , @kheal , @mslarae13 
- Informed: Schema refactoring team

**Describe the the task**
- [ ] Add tasks to convert to issues

**Criteria for completion**
- Evaluation of the existing MaterialProcessing sub-classes and slots for the applicability towards small molecule analyses (metab, lipido, NOM)
- Any additional classes or slots needed for these sample types at this step in the metadata process should be added
- Include example data as needed for schema changes

**Estimate people time**
- 

**Completion Date (Goal)**
- May 1

**Target Sprint Start & End Dates**
- Start: March 25
- End: May 3

**Tag Blocker/Contingent upon issues**
- [Tagg issues]

**Comment by kheal** [comment]
Closing this - its done!
