### ISSUE TITLE
Study Page testing and updates

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#645]
- [x] NEON Parent is missing the logo
  - @brynnz22 can you put in a change sheet

- [x] Some PI photos are a bit weird, not on center. We should adjust this
  - Colonization resistance against Candida
  - River Corridor SFA

- [x] Grow (nmdc:sty-11-5tgfr349) still has an image of the Grow logo, should be an image of Kelly Wrighton

- [x] For consortia, the team is missing from the NEON parent and WHONDRS
  - https://www.pnnl.gov/projects/WHONDRS/team

- [x] Remove NEON parent from Geochemical controls on soil resiliency to carbon loss following permafrost thaw in Alaska soils (nmdc:sty-11-db67n062)
  - NEON isn't a parent for this study. They used NEON samples but no parent-child relationship

**Comment by brynnz22** [comment]
NEON parent `study_image` logo added

NEON  team also added.

**Comment by brynnz22** [comment]
Waiting for discussions to be resolved to address the remaining issues

**Comment by mslarae13** [comment]
@marySalvi you fixed the centering of the photos for the 2nd check box, yes?

**Comment by mslarae13** [comment]
NEON parent study team has been added
