### ISSUE TITLE
Test 2-7-23

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#66]
- [x] #67
- [x] #68
- [x] #70
- [x] #69

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Acceptance Criteria**
Create a checklist or scenario-based acceptance criteria, from the users perspective, that answers the following: 

Who will use this feature/enhancement?
When will they use it?
How will they use it?
How will they test it to make sure it's working?
Is the request achievable? During one sprint? 
What is your definition of done for this request?

**Comment by mslarae13** [comment]
@ssarrafan should your test issues be closed?

**Comment by ssarrafan** [comment]
> @ssarrafan should your test issues be closed?

This one is closed already.
