### ISSUE TITLE
NMDC Submission: e3b3be26-7da9-417d-b3a6-4fc747a1d586 (Blanchard)

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#663]
**Submitter Name and ORCiD**
[Jeffrey Blanchard](https://orcid.org/0000-0002-7310-9678)

**Submission ID**
e3b3be26-7da9-417d-b3a6-4fc747a1d586

**Have data already been generated for your study?**
yes (Award DOI: 10.46936)

**PI Name and ORCiD**
[Jeffrey Blanchard](https://orcid.org/0000-0002-7310-9678)

**Status**
In Progress

**EMSL ID**
49483

**JGI ID**
503125

**GOLD Study ID**
Gs0130354

**NCBI BioProject**
Add if appropriate

**Alternative Names/IDs**
Add if appropriate

**Data Types**

- [ ] Metagenome (DOE)
- [ ] Metatranscriptome (DOE)
- [ ] Metaproteome (DOE)
- [ ] Metabolome (DOE)
- [ ] NOM (DOE)

**Sample Type**
soil

**Number of Samples**
42

**Notes**

**Comment by aclum** [comment]
just a note that jeff also has lipidomics data when we are ready for that.

**Comment by mslarae13** [comment]
@aclum I updated the metadata to include the units.
But, now the env triad is invalid. I'm not sure why. I've asked Mark

**Comment by aclum** [comment]
@mslarae13  are the env triad issues sorted out.

**Comment by mslarae13** [comment]
Yup! It's a valid submission! I can hit submit if Jeff has nothing else to add. That will trigger an issue to get created about the submission.  So I'll close this one (they'll be redundant)

**Comment by aclum** [comment]
Let's move forward with what we have. Thanks!

**Comment by mslarae13** [comment]
Submitted, see new issue: https://github.com/microbiomedata/issues/issues/888

**Comment by mslarae13** [comment]
Updates were made, https://github.com/microbiomedata/issues/issues/921
