### ISSUE TITLE
1000 soils missing omics_processing_set record for Gp0623680

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#665]
**Deliverable this task is associated with**

_See Deliverables tab here: _

- [Add the Deliverable #]

**RACI**

_Tag people in their roles_
- Responsible: @sujaypatil96 
- Accountable: @turbomam 
- Consulted:
- Informed: @mslarae13 

**Describe the the task**
Two gold projects were associated with a single omics record for 1000 soils b/c they had the same source sample. They used two different extraction methods (as denoted by _Z and _Q). 
- [x] We need issue a changesheet so nmdc:omprc-12-nct8f131 is only associated with gold:Gp0623674, remove association with gold:Gp0623680
- [x] new NMDC omics_processing_set record for gold:Gp0623680

**Criteria for completion**
- Two omics records which has_input nmdc:bsm-11-6p6mhh86

**Estimate people time**
- 1 person, 2 hours

**Completion Date (Goal)**
- April 19

**Target Sprint Start & End Dates**
- Start: April 8
- End: April 19

**Tag Blocker/Contingent upon issues**
- [Tagg issues]

**Comment by aclum** [comment]
related to #120

**Comment by sujaypatil96** [comment]
@aclum gold:Gp0623674 is the project id that would have the name "Soil microbial communities from grassland in Ellensburg, Washington, USA - 1000S_FTA5_BTM_Z" and gold:Gp0623680 is the one that would have the name "Soil microbial communities from grassland in Ellensburg, Washington, USA - 1000S_FTA5_BTM_Q".

So for `nmdc:omprc-12-nct8f131` I think we can remove `gold:Gp0623680` from _gold_project_identifiers_ and create a new OmicsProcessing instance for `gold:Gp0623680` right?

**Comment by sujaypatil96** [comment]
Here is the new OmicsProcessing record that I am creating:

```json
    {
      "add_date": "2022-04-22",
      "designated_class": "nmdc:OmicsProcessing",
      "gold_sequencing_project_identifiers": [
        "gold:Gp0623680"
      ],
      "has_input": [
        "nmdc:bsm-11-6p6mhh86"
      ],
      "id": "nmdc:omprc-12-p633ka78",
      "instrument_name": "Illumina NovaSeq S4",
      "mod_date": "2024-01-07",
      "name": "Soil microbial communities from grassland in Ellensburg, Washington, USA - 1000S_FTA5_BTM_Q",
      "ncbi_project_name": "Soil microbial communities from grassland in Ellensburg, Washington, USA - 1000S_FTA5_BTM_Q",
      "omics_type": {
        "has_raw_value": "Metagenome"
      },
      "part_of": [
        "nmdc:sty-12-0tajxq27"
      ],
      "principal_investigator": {
        "email": "nancy.hess@pnnl.gov",
        "has_raw_value": "Nancy Hess",
        "name": "Nancy Hess"
      },
      "processing_institution": "JGI",
      "type": "nmdc:OmicsProcessing"
    },
```

**Comment by sujaypatil96** [comment]
@aclum can you verify that both omics processing records: `nmdc:omprc-12-nct8f131` and `nmdc:omprc-12-p633ka78` are correct? This issue is ready to be closed.
