### ISSUE TITLE
test that proteomics aggregation works on napa data

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#666]
Use runtime dev to test that proteomics workflow results properly propagate metap_gene_function_aggregation by adding the 7 projects with metagenome annotation and proteomics records to runtime dev.

**Comment by aclum** [comment]
@picowatt  do you have the json files for the workflow results?

**Comment by picowatt** [comment]
@aclum Yeah, I will upload them in a minute.

**Comment by aclum** [comment]
Unlikely to be done tomorrow so moving the next sprint.

**Comment by aclum** [comment]
I updated the metaprotomics activity records and the input and output data objects. We can check the runtime dev tomorrow to see if this triggered the metap aggregation.

**Comment by aclum** [comment]
The aggregation jobs ran but did not add any information to the aggregation collection so we need to debug this. Moving to the next sprint.

**Comment by aclum** [comment]
@scanon  @picowatt this is an example of a record that should have produced a kegg hit. 
activity record id nmdc:wfmp-11-09dewq75.1 the first record in has_peptide_quantifications has a best_protein
 hit of nmdc:wfmgas-11-txcpae82.1_3048_c1_1743_2237 
 when I took for that in /global/cfs/cdirs/m3408/ficus/pipeline_products/nmdc:omprc-11-0g415160/nmdc:wfmgan-11-6vp45x09.1/nmdc_wfmgan-11-6vp45x09.1_functional_annotation.gff the hit is to KO:K02358

**Comment by aclum** [comment]
This code is in the infra-admin repo.

**Comment by aclum** [comment]
Shreyas and I checked the logs and the annotation execution activities are needed as well.

**Comment by aclum** [comment]
I've uploaded these to the dev instance

**Comment by aclum** [comment]
There were some issues with the code which Shane fixed. Eric merged in the pull request and moved the code to a different repo https://github.com/microbiomedata/nmdc-aggregator

Eric will build and push this container and update the container in spin for the dev instance. If that works he'll update prod.

**Comment by aclum** [comment]
I checked on this this morning and the agg collection on dev had not been updated.

**Comment by aclum** [comment]
@eecavanna  and I debugged the issue this morning, there was a type issue, dict when it should have been a list. The code has been updated in nmdc-aggregator and deployed to production and dev. We confirmed that the aggregation collection is being properly updated in dev now, production has been updated but no new records are expected until after re-iding.

**Comment by aclum** [comment]
see https://github.com/microbiomedata/nmdc-aggregator/issues/4
