### ISSUE TITLE
write lock mongo prod (Eric)

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/issues#670]
This will involve:
- Add notification to submission portal
- Notify workflow 
- Pause all workflows

**Comment by mbthornton-lbl** [comment]
This will involve:
- Add notification to submission portal
- Notify workflow 
- Pause all workflows

**Comment by eecavanna** [comment]
I don't know how to pause workflows (is it just a matter of scaling down the scheduler?).

Is this task still outstanding?

**Comment by aclum** [comment]
Closing b/c we are done with re-iding.
