### ISSUE TITLE
Add "GOLD" definition to Data Portal left panel search bar

### ISSUE THREAD

**Issue by ljohnson09** [microbiomedata/issues#682]
**Deliverable this task is associated with**

_See Deliverables tab here: _

- [Add the Deliverable #]
4.1 Perform user research to refine the Data Portal user experience

**RACI**

_Tag people in their roles_
- Responsible: @turbomam @jeffbaumes @marySalvi @naglepuff 
- Accountable: Alicia
- Consulted:
- Informed:

**Describe the the task**
- [ ] Identify which schema field should be used for GOLD definition. GOLD is not defined explicitly in the schema; maybe use "GOLD path field" definition? @turbomam 
- [ ] Once definition is settled, pull from schema @jeffbaumes @marySalvi @naglepuff  
<img width="820" alt="Screenshot 2024-04-22 at 7 02 39 AM" src="https://github.com/microbiomedata/issues/assets/126267639/34b56505-648a-4546-a72f-c391dc9610ab">

**Criteria for completion**
- GOLD definition added to DP search panel 

**Estimate people time**
- [Hours or days of people time. 1 person, 4 hours]

**Completion Date (Goal)**
- [GOAL!]

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- [Tagg issues]

**Comment by aclum** [comment]
Making a separate ticket for the nmdc server work.
