### ISSUE TITLE
NEON soil - ingest JGI data for nmdc:omprc-11-ycnhgw23

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#691]
**Deliverable this task is associated with**

_See Deliverables tab here: _

- [Add the Deliverable #]

**RACI**

_Tag people in their roles_
- Responsible: @mflynn-lanl 
- Accountable:
- Consulted:
- Informed:

**Describe the the task**
- [x] Ingest JGI readqc and annotation for nmdc:omprc-11-ycnhgw23, all other datasets were ingested in https://github.com/microbiomedata/issues/issues/264

**Criteria for completion**
- records in mongo for read_qc_analysis_activity_set and metagenome_assembly_set that were_informed_by nmdc:omprc-11-ycnhgw23

**Estimate people time**
- [Hours or days of people time. 1 person, 4 hours]

**Completion Date (Goal)**
- [GOAL!]

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- [Tagg issues]

**Comment by aclum** [comment]
@mflynn-lanl where was the JGI NEON data staged to? GOLD analysis identifier is Ga0597026

**Comment by mflynn-lanl** [comment]
The data was staged to:
/global/cfs/projectdirs/m3408/aim2/dev/bioscales_mapping/neon_analysis_projects/Ga0597026/
________________________________
From: aclum ***@***.***>
Sent: Tuesday, May 7, 2024 2:31 PM
To: microbiomedata/issues ***@***.***>
Cc: Flynn, Mark C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microbiomedata/issues] NEON soil - ingest JGI data for nmdc:omprc-11-ycnhgw23 (Issue #691)


@mflynn-lanl<https://urldefense.com/v3/__https://github.com/mflynn-lanl__;!!Bt8fGhp8LhKGRg!GuM9CIubUWp9T1ZHjlpa4muI20pRCuaJnuktX8_o7tiVE85ZWx1e5UEyJDA8U54mN1elW1mFb6wECKq0echlkHVr$> where was the JGI NEON data staged to? GOLD analysis identifier is Ga0597026

**Comment by aclum** [comment]
This is blocked on https://github.com/microbiomedata/nmdc_automation/issues/239

**Comment by mbthornton-lbl** [comment]
Ran `import-projects` on dev, then on prod:

Prod Log:
```
INFO:__main__:Importing nmdc:omprc-11-ycnhgw23 from /global/cfs/projectdirs/m3408/aim2/dev/bioscales_mapping/neon_analysis_projects/Ga0597026: 72 files
INFO:__main__:Mapping sequencing data
INFO:__main__:Mapping single data files
INFO:__main__:Mapping multiple data files
INFO:__main__:Mapping workflow executions
INFO:root:Processing Reads QC
INFO:root:Processing Metagenome Assembly
INFO:__main__:Validating imported data
INFO:__main__:Validation Passed
INFO:__main__:Applying update to sequencing data generation
INFO:__main__:Posting data to the API
``` 


Results from `https://api.microbiomedata.org/nmdcschema/workflow_execution_set?filter=%7B%22was_informed_by%22%3A%20%22nmdc%3Aomprc-11-ycnhgw23%22%7D&max_page_size=20`
```
{
  "resources": [
    {
      "id": "nmdc:wfrqc-11-7bqn0498.1",
      "type": "nmdc:ReadQcAnalysis",
      "name": "Read QC for nmdc:wfrqc-11-7bqn0498.1",
      "has_input": [
        "nmdc:dobj-11-btk4vq32"
      ],
      "has_output": [
        "nmdc:dobj-11-68zjpy38",
        "nmdc:dobj-11-wahdbp07"
      ],
      "execution_resource": "JGI",
      "git_url": "https://github.com/microbiomedata/ReadsQC",
      "started_at_time": "2024-11-27T18:53:24.889499+00:00",
      "was_informed_by": "nmdc:omprc-11-ycnhgw23",
      "ended_at_time": "2024-11-27T18:53:24.889517+00:00",
      "version": "v1.0.13"
    },
    {
      "id": "nmdc:wfmgas-11-8ny3yq87.1",
      "type": "nmdc:MetagenomeAssembly",
      "name": "Metagenome Assembly for nmdc:wfmgas-11-8ny3yq87.1",
      "has_input": [
        "nmdc:dobj-11-68zjpy38"
      ],
      "has_output": [
        "nmdc:dobj-11-e3r78b71",
        "nmdc:dobj-11-eyc2ec41",
        "nmdc:dobj-11-e4b3e814",
        "nmdc:dobj-11-gpzr1786"
      ],
      "execution_resource": "JGI",
      "git_url": "https://github.com/microbiomedata/metaAssembly",
      "started_at_time": "2024-11-27T18:53:25.959757+00:00",
      "was_informed_by": "nmdc:omprc-11-ycnhgw23",
      "ended_at_time": "2024-11-27T18:53:25.959773+00:00",
      "version": "v1.0.7"
    }
  ]
}
```

**Comment by aclum** [comment]
Looks correct!
