### ISSUE TITLE
ETL for converting submission portal metadata for user facilities

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#71]
Implement ETL for converting submission portal metadata to:

- [ ] EMSL template
- [ ] JGI template

**Comment by ssarrafan** [comment]
Based on SubPort board changing this to in-progress and moving to the next sprint
@sujaypatil96 @mslarae13

**Comment by ssarrafan** [comment]
@aclum I put it in the sprint assuming it was in progress from the submission portal squad.  @mslarae13 is this on hold?

**Comment by mslarae13** [comment]
The ETL script I believe is done. We can confirm with Sujay. I looked over the documentation and that's good.
We need a different issue for the automation, but that's a big task and required Elais too.

**Comment by ssarrafan** [comment]
> The ETL script I believe is done. We can confirm with Sujay. I looked over the documentation and that's good. We need a different issue for the automation, but that's a big task and required Elais too.

oh great, @sujaypatil96 I will close this per Montana's last comment. Can you please add the link to the documentation here?
