### ISSUE TITLE
issue with neon input data

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#710]
Ticket to track issues with neon raw data, a subset of neon raw data across soil, benthic, and surface water samples appears to not be formatted correctly in such a way that interleaving produces the correct results.  

example issue
The data for example for ARIK.20140902.AMC.SESTON.1-DNA1 read 1 and read 2 are from different lanes based on fastq naming conventions 
zcat BMI_HVKLYBGX5_Tube97_R1.fastq.gz | head -1
@NB551228:18:HVKLYBGX5:1:11101:23907:1086 1:N:0:GAGATTCC+NAAGATTA
 zcat BMI_HVKLYBGX5_Tube97_R2.fastq.gz | head -2
@NB551228:18:HVKLYBGX5:3:11401:6460:1022 2:N:0:GAGATTCC+TAAGATTA
the number after the flowcell (HVKLYBGX5) is the lane number. Here read 1 is from lane 1 and read 2 is from lane 3.

Link to header nomenclature https://help.basespace.illumina.com/files-used-by-basespace/fastq-files

We need to review the existing NEON results and fail workflow results that have this issue and their dependent workflow results.

**Comment by aclum** [comment]
soil problem institute_flowcell

  69 2023 BMI_HFWLLBGX7_mms_R1
  69 2023 BMI_HFWLLBGX7_mms_R2
  15 2023 BMI_HFWLVBGX7_mms_R1
  15 2023 BMI_HFWLVBGX7_mms_R2
  13 2023 BMI_HFWM2BGX7_mms_R1
  13 2023 BMI_HFWM2BGX7_mms_R2
  34 2023 BMI_HFWM5BGX7_mms_R1
  34 2023 BMI_HFWM5BGX7_mms_R2
  38 2023 BMI_HL77TBGX7_mms_R1
  38 2023 BMI_HL77TBGX7_mms_R2
  37 2023 BMI_HL7C5BGX7_mms_R1
  37 2023 BMI_HL7C5BGX7_mms_R2
  35 2023 BMI_HLN2HBGX7_mms_R1
  35 2023 BMI_HLN2HBGX7_mms_R2
  37 2023 BMI_HLN2JBGX7_mms_R1
  37 2023 BMI_HLN2JBGX7_mms_R2
  37 2023 BMI_HM2FCBGX7_mms_R1
  37 2023 BMI_HM2FCBGX7_mms_R2
  37 2023 BMI_HVC57BGX5_mms_R1
  37 2023 BMI_HVC57BGX5_mms_R2
  34 2023 BMI_HVFYCBGX5_mms_R1
  34 2023 BMI_HVFYCBGX5_mms_R2
  27 2023 BMI_HVKLYBGX5_mms_R1
  27 2023 BMI_HVKLYBGX5_mms_R2
  52 2023 BMI_HWTKKBGX7_mms_R1
  52 2023 BMI_HWTKKBGX7_mms_R2
  18 2023 BMI_HWTY2BGX7_mms_R1
  18 2023 BMI_HWTY2BGX7_mms_R2
   4 2023 BMI_HWVCLBGX7_mms_R1
   4 2023 BMI_HWVCLBGX7_mms_R2
  58 2023 BMI_HWVCMBGX7_mms_R1
  58 2023 BMI_HWVCMBGX7_mms_R2
  43 2023 BMI_HWVWKBGX7_mms_R1
  43 2023 BMI_HWVWKBGX7_mms_R2
  70 2023 BMI_HWVWMBGX7_mms_R1
  60 2023 BMI_HWVWMBGX7_mms_R2
  57 2023 BMI_HWWGYBGX7_mms_R1
  57 2023 BMI_HWWGYBGX7_mms_R2

**Comment by aclum** [comment]
377 impacted benthic OmicsProcessing records (nmdc:sty-11-pzmd0x14)
97 impacted surface water OmicsProccessing records (nmdc:sty-11-hht5sb92)
628 impacted soil OmicsProcessing records (nmdc:sty-11-34xj1150)

to do:
pass list to IMG
check for records where filtering failed.

**Comment by aclum** [comment]
Provided a list to Amy on Friday.

**Comment by aclum** [comment]
Still in progress, moving to the next sprint. Submitted filtering jobs that had failed previously to jaws to see which of those files interleave properly or not. Jeff provided ORCiD IDs for for people that have downloaded NEON data and we are trying track down corresponding emails.

**Comment by aclum** [comment]
21 incorrectly paired files, 2 where R2 file is truncated, 6 were memory errors that I'm resubmitting.

**Comment by aclum** [comment]
Issues with benthic data (bad pairs) that failed filtering. These need to be retracted.
nmdc:omprc-12-25fzry10
nmdc:omprc-12-mgvgdj16
nmdc:omprc-12-5kjw9208
nmdc:omprc-12-c8hdqa92
nmdc:omprc-12-aya9kb44
nmdc:omprc-12-qa8vhm48

There were no neon surface water samples that failed filtering.

**Comment by aclum** [comment]
Deleted with queries:run the data_object_set and omics_procesing_set records for neon soil datasets where filtering had failed.

**Comment by aclum** [comment]
All that is left is to sort out a communication plan

**Comment by aclum** [comment]
Emiley will check in on this with Kate during ASM which is this weekend so moving to the next sprint.

**Comment by ssarrafan** [comment]
@emileyfadrosh any update on this issue after meeting with Kate at ASM?  
@aclum

**Comment by ssarrafan** [comment]
Emiley said NEON is still working on this.  There is a call on Monday and we'll hopefully get an update. I'll move this to the next sprint.
@aclum @emileyfadrosh

**Comment by aclum** [comment]
NEON will post a data notification this week. NMDC will link in the quarterly newsletter to NEON's data notification. cc @jkelliher-github Kate said she wanted to review our newsletter text before it was distributed.

**Comment by aclum** [comment]
Per July the newsletters is scheduled for July 24th. Will close this and work off the draft newsletter.
