### ISSUE TITLE
2024.6 Release

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/issues#711]
The 2024.6 Release is scheduled to take place on: **June 24, 2024**

Upstream events:
- Freeze the version of `nmdc-schema` that will be used in this release, by: **June 17, 2024**
- Begin focused testing of the to-be-released versions of everything, in the development environment, by: **June 19, 2024**

Use this issue to document any tasks that you want to be part of the release process for this release, that aren't already part of the standard release process.

**Comment by aclum** [comment]
The plan is also to fix the workflow identifiers at the same time. @JamesTessmer  will write the migrator for NOM, Michael will write to code for Metagenome components.

**Comment by pkalita-lbl** [comment]
Re migrator for NOM: https://github.com/microbiomedata/nmdc-schema/pull/2059

**Comment by aclum** [comment]
NOM ticket https://github.com/microbiomedata/issues/issues/707
Metagenome Activity issues https://github.com/microbiomedata/nmdc_automation/issues/186

**Comment by eecavanna** [comment]
> For both of these activities, we should try to wrap up the development work by the end of this week (Friday, June 14) so that we can test them on dev starting next week (Monday, June 17) and assess any ingest impact.

Running this migrator will "require" (not technically, but this is how we've been doing it) a Python notebook that walks through the process of backing up the original database, loading it into a transformation database, running the migrators, validating the results, etc. I don't think I'll have time to do that on Friday, but I can have it done by the end of Monday.

**Comment by eecavanna** [comment]
On "release day", I'm planning to carry out the migration portion of the release (and so I'm planning on copiloting the release in general).

**Comment by aclum** [comment]
@eecavanna  can you update runtime dev to nmdc-schema to v10.5.4 including running the migrator on mongo dev today? The prod release is scheduled for next Monday and tomorrow is a holiday.

**Comment by eecavanna** [comment]
Hi @aclum, yes, I'll do that today and post an announcement on Slack (in the #general channel) once it's done.

**Comment by pkalita-lbl** [comment]
Thanks @eecavanna. I can take care of the submission-schema and nmdc-server upgrades (hopefully today).

**Comment by pkalita-lbl** [comment]
Release 2024.6 has been deployed to production.
