### ISSUE TITLE
nmdc:omprc-12-kryfs935 fail existing assembly and annotation records and rerun

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#716]
There was an issue with the copy from scratch to cfs for the filtered fastq file so a single read had a mismatch b/w quality score and read length but the file was also truncated. I re-copied the file from scratch but we need to fail the exist assembly and annotation an rerun.
nmdc:wfmgas-11-yqz05476.1
nmdc:wfmgan-11-cy9mdb57.1

**Comment by kaijli** [comment]
Tried validating changesheet with both:
`{
  "detail": "('Cannot find ID', 'nmdc:wfmgan-11-cy9mdb57.1', 'in any collection')"
}`

changesheet:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/kli/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/kli/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">



</head>

<body link="#467886" vlink="#96607D">


id | action | attribute | value
-- | -- | -- | --
nmdc:wfmgas-11-yqz05476.1 | update | qc_status | fail
nmdc:wfmgan-11-cy9mdb57.1 | update | qc_status | fail



</body>

</html>

**Comment by aclum** [comment]
You are correct, there were results on the filesystem that did not make it into mongo.

**Comment by kaijli** [comment]
Updated `nmdc:wfmgas-11-yqz05476.1`
