### ISSUE TITLE
Squad next steps: Add Sam O. and Natalie to Squad, discuss with engagement team

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/issues#722]
Add Sam O. and Natalie to Notebooks Squad.

- [ ] Sam to write new Python notebook

- [ ] Natalie to discuss using PNNL's suite of visualization tools for processed data analysis.

- [ ] Consult engagement team to discuss potential next notebook topics that community would want to see.

**Comment by kheal** [comment]
Sam has been added, decided to keep Natalie off of squad for now.  Decided to move forward with a NOM example notebook for next steps and will re-engage with the engagement team after we've drafted the notebooks.
