### ISSUE TITLE
Make `DataGeneration` and `DataObject` records for fixed NEON raw data

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#735]
**Deliverable this task is associated with**

This is a super issue tracking for tracking the creation of new DataGeneration and DataObject records for 3 NEON studies -- surface water, benthic and soil.

- [Add the Deliverable #]

**RACI**

_Tag people in their roles_
- Responsible: @sujaypatil96 
- Accountable: @turbomam 
- Consulted: @aclum 
- Informed: @aclum 

**Describe the the task**
- [x] Hugh has provided a spreadsheet with fastq data that is properly paired. For records where we deleted the DataObjects and OmicsProcessing records because the data was not paired correctly we need to make new OmicsProcessing and Data Object records.
- [x] https://github.com/microbiomedata/issues/issues/933
- [x] https://github.com/microbiomedata/issues/issues/934
- [x] https://github.com/microbiomedata/issues/issues/935

**Criteria for completion**
- New OmicsProcessing and DataObject set records 

**Estimate people time**
- 1 person ,3 days? likely requires ad hoc code

**Completion Date (Goal)**
- July 12
**Target Sprint Start & End Dates**
- Start: July 1
- End: July 12

**Tag Blocker/Contingent upon issues**
- [Tagg issues]

**Comment by aclum** [comment]
@sujaypatil96 how is this going?

**Comment by aclum** [comment]
ETA to start work on this is next week.

**Comment by ssarrafan** [comment]
It's relatively new comment so I'll move to new sprint.  @sujaypatil96 let me know if you're not working on this.

**Comment by ssarrafan** [comment]
No updates for 2+ weeks. Removing from sprint.

**Comment by aclum** [comment]
This is high priority after ecofab and berkeley schema rollout work.

**Comment by sujaypatil96** [comment]
Can someone point me to the new spreadsheet that Hugh provided us with?

**Comment by ssarrafan** [comment]
> Can someone point me to the new spreadsheet that Hugh provided us with?

I added you to the NEON-NMDC Slack channel.  
Did you look at the NEON collaboration folder on Google drive?  https://drive.google.com/drive/folders/1K32ZfuJjZMlailRTwjmTAcI_CPxCs9OQ

**Comment by sujaypatil96** [comment]
Awesome, thank you @ssarrafan. I've pinged Hugh on the slack channel.

**Comment by sujaypatil96** [comment]
Current status: Generated a JSON file with corrected OmicsProcessing/DataObject records for the NEON benthic water study, and is being reviewed.

**Comment by ssarrafan** [comment]
@sujaypatil96 who needs to review?
I'll move to the next sprint
FYI @aclum

**Comment by aclum** [comment]
This has been reviewed and changes are needed. Let's backlog until berkeley changes are finished.

**Comment by aclum** [comment]
Per slack @sujaypatil96  has started working on this again now that berkeley changes are finished so adding to this sprint. This is expected to span into next sprint.

**Comment by ssarrafan** [comment]
Appears to be active.  @sujaypatil96 I'll move to the next sprint. If you're not going to work on this let me know.  Thanks!

**Comment by aclum** [comment]
This is high priority for the renewal. Sujay is working an an endpoint to facilitate finding out which projects have a biosample record but not a NucleotideSequencing record.

**Comment by ssarrafan** [comment]
Appears to be active. Moving to the next sprint.  FYI @sujaypatil96 @aclum

**Comment by aclum** [comment]
Benthic and surface water samples were loaded into mongo dev and look good, okay to proceed with prod. Sujay is working on the soil samples, there are 4 samples which are missing from the fastq. We expected a few dropouts from truncated fastq files and will confirm that the sample identifiers for these match up.

**Comment by aclum** [comment]
@sujaypatil96 we are ready to load these 3 json files into prod mongo. Thanks!

**Comment by sujaypatil96** [comment]
Thanks @aclum. I just finished submitting all 3 files to prod Mongo.

Logs:

```bash
➜  ~ curl -X 'POST' \
  'https://api.microbiomedata.org/metadata/json:submit' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyOnNwYXRpbCIsImV4cCI6MTczMjM5MzIzOH0.ZNzmgbHJCvNAF1UD5Za69gJEWJzI-1jv4KE7OMohung' \
  -H 'Content-Type: application/json' \
  -d @/Users/sujaypatil/Desktop/nmdc-runtime/neon_surface_water_repaired_records.json 
{"type":"success","detail":{"run_id":"nmdc:sys00p4vmx36"}}%
```

```bash
➜  ~ curl -X 'POST' \
  'https://api.microbiomedata.org/metadata/json:submit' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyOnNwYXRpbCIsImV4cCI6MTczMjM5MzIzOH0.ZNzmgbHJCvNAF1UD5Za69gJEWJzI-1jv4KE7OMohung' \
  -H 'Content-Type: application/json' \
  -d @/Users/sujaypatil/Desktop/nmdc-runtime/neon_benthic_repaired_records.json      
{"type":"success","detail":{"run_id":"nmdc:sys00ana4697"}}%
```

```bash
➜  ~ curl -X 'POST' \
  'https://api.microbiomedata.org/metadata/json:submit' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyOnNwYXRpbCIsImV4cCI6MTczMjM5MzIzOH0.ZNzmgbHJCvNAF1UD5Za69gJEWJzI-1jv4KE7OMohung' \
  -H 'Content-Type: application/json' \
  -d @/Users/sujaypatil/Desktop/nmdc-runtime/neon_soil_repaired_records.json   
{"type":"success","detail":{"run_id":"nmdc:sys0npwehh08"}}
```

**Comment by sujaypatil96** [comment]
This issue is ready to be closed @aclum.
