### ISSUE TITLE
BUG - Submission validates but the submit goes away

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

See https://data-dev.microbiomedata.org/submission/e4f340e0-3a3f-4784-ae33-9bad94d5cdd3/samples

As far as I can tell, that submission is valid. 
I get the green check mark, but when I change between soil and JGI or just seconds after submitting I get the yellow ! and the submission button goes away but I can't see anything wrong or invalid.

It's slow.

### Expected Behavior

Show the validation error or let me submit.

### Steps To Reproduce

1. Got to https://data-dev.microbiomedata.org/submission/e4f340e0-3a3f-4784-ae33-9bad94d5cdd3/samples
2. In soil, click validate
3. go to JGI, click validate
4. Switch back to soil
5. Wait a but if it takes it a while.

### Environment

```markdown
- https://data-dev.microbiomedata.org
```

**Comment by pkalita-lbl** [comment]
This should be fixed on dev now
