### ISSUE TITLE
Archive Google Analytics (Universal Analytics) data before July 1

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/issues#741]
There's an alert at the top of the Google Analytics page that says:

> If you haven't completed migration, finish setting up your Google Analytics 4 property before your connected Universal Analytics property is permanently deleted on Jul 1, 2024. To maintain access to data from this property, you should download your data now.

We have set up Google Analytics 4 property, but it doesn't include all of our oldest data.

Here's a screenshot of a similar alert that appears elsewhere on Google Analytics:

![image](https://github.com/microbiomedata/issues/assets/134325062/f11f8f9d-41c9-4bf6-8234-2e2863efe2a6)

---

The task here is to export data that only exists in the UA property (at a monthly granularity is OK). We don't have a specific need for it, but don't want to lose it. It may come in handy for future metrics analysis.

**Comment by eecavanna** [comment]
I'll work on this either Friday PM or Sunday early PM. In terms of sprint management, I'm OK with it being removed from the current sprint. I have it on my personal calendar already.

**Comment by ssarrafan** [comment]
Thank you for taking care of this @eecavanna 
I'll move it to the next sprint so you can have the first closed ticket in July ;)

**Comment by eecavanna** [comment]
This is done, for both of our "UA" Google Analytics properties (one of which is for the Data Portal and one of which is for the Website):

### Here are the Google Analytics screens I exported data from (and the names of the corresponding Google Sheets document that was exported from it):

1. Audience > Overview: `visitors-overview`
2. Audience > Technology > Browser and OS: `visitors-browser`
3. Acquisition > Overview: `trafficsources-overview`
4. Acquisition > All Traffic > Source/Medium (Show rows = 5000): `trafficsources-all-traffic`
5. Behavior > Overview: `content-overview`
6. Behavior > Site Content > All Pages (Show rows = 5000): `content-pages`

### I also took a screenshot of:

1. Audience > Users Flow: `audience-users-flow.png`

Those files currently reside in my Google Drive. I will relocate them to the NMDC Shared Drive shortly.

**Comment by eecavanna** [comment]
Looks like I don't have permission to create a folder at the top level of the NMDC Shared Drive. Since I don't know where "deeper in the drive" these files would fit well, I'll keep them in my individual Google Drive for future reference (and possibly future transfer to a different Google Drive).

**Comment by eecavanna** [comment]
I found a "deeper in the drive" folder that I think they'd fit well in, but I don't have permission to move them there.



![Image](https://github.com/microbiomedata/issues/assets/134325062/346c198e-859c-41bc-98e2-46a88d372237)

**Comment by eecavanna** [comment]
For my own future reference, the names of the Google Drive folders containing the above "exported" files are:

- `NMDC Data Portal - Google Analytics - Universal Analytics Data`
- `NMDC Website - Google Analytics - Universal Analytics Data`
