### ISSUE TITLE
Transfer `refscan` repository into `microbiomedata` organization on GitHub

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/issues#746]
This is something the Referential Integrity squad discussed. I wanted to create a GitHub Issue for it and add it to the sprint so I don't lose track of it as a task. Although it takes < 1 minute to create a GitHub repository and another < 1 minute to put the code into it (or the same could be effectively accomplished via GitHub's "Transfer repository" function), I want to do a final review of the `refscan` repo before transferring it in. I plan to do this after this week's squad meeting.

**Comment by ssarrafan** [comment]
@eecavanna are you planning to do this today? Or can it be moved to the next sprint?

**Comment by ssarrafan** [comment]
Moving to the next sprint. @eecavanna don't work on this till Monday.

**Comment by eecavanna** [comment]
This is done now. 

Old repo URL: https://github.com/eecavanna/refscan

New repo URL: https://github.com/microbiomedata/refscan
