### ISSUE TITLE
Create `MassSpectrometryConfiguration` instances and upload to Mongo

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/issues#748]
The initial spreadsheet of the `MassSpectrometryConfiguration` instances has been created. What is left to do is:

- [x] Provide a `name` and `description` for each instance
- [x] Mint ids for each instance
- [x] @kheal reviews and give thumbs up for upload
- [ ] @brynnz22 Convert to json and upload to Berkeley Mongo.

~Potential blocker: Berkeley version of Runtime. Won't be able to mint ids and submit to Berkeley Mongo until the Berkeley runtime is up and running.~

**Comment by ssarrafan** [comment]
@kheal @brynnz22 is this one still actively being worked on?

**Comment by ssarrafan** [comment]
It's the last remaining issue in the sprint so I'll move it to the new sprint. Let me know if it should be in the backlog instead. Thanks!

**Comment by brynnz22** [comment]
Converted to json, but blocked for now until Berkeley becomes production since Berkeley mongo is not replacing production Mongo.

**Comment by brynnz22** [comment]
Adding the final json here so its easy to find for everyone: [mass_spec_config.json](https://github.com/user-attachments/files/17103063/mass_spec_config.json)

**Comment by bmeluch** [comment]
JSON submitted through /metadata/json:submit in dev and prod

**Comment by brynnz22** [comment]
Thanks @bmeluch
