### ISSUE TITLE
Ingest study and biosamples for GOLD study Gs0118397 (AGFMA)

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#75]
We need to ingest the study and biosample data from GOLD for Gs0118397 similar to what we did for bioscales and grow. We only want a subset of the metatranscriptome projects. GOLD has populated the environmental terms.

There are two options to handle selecting only a subset of the projects. This first is manual, use the [spreadsheet](https://docs.google.com/spreadsheets/d/1kp3bQmdkOCFaKyAoDOHyXI3dfkNFP8datfgPlgfMtM8/edit#gid=1398928692) where I've prefiltered the data, use the "GOLD biosamples include" and "GOLD bioprojects include". The second is the values of "itsSequencingProductName" to filter the results. Reddy says this information is in the NMDC endpoint. For this project we only want projects that match 'Metagenome Standard Draft' or 'Eukaryote Community Metatranscriptome'. There should be 95 biosamples.
Example of a metatranscriptome project to include Gb0237200
Example of a metatranscriptome project to exclude Gp0401539

Note all the projects are host-associated so should have a host tax id and host tax name similar to some of the Bioscales samples.

**Comment by aclum** [comment]
@ssarrafan if @sujaypatil96  Emiley wanted this for GSP. Let Set know if you have time in the next sprint cycle to work on this.

**Comment by ssarrafan** [comment]
Adding to the next sprint. Lower priority than bioscales and GROW.

**Comment by aclum** [comment]
@sujaypatil96  this is the list of GOLD projects to include
<google-sheets-html-origin><style type="text/css"></style>

projectGoldId
--
Gp0213379
Gp0213380
Gp0213381
Gp0213382
Gp0213383
Gp0213384
Gp0213385
Gp0213386
Gp0213387
Gp0213388
Gp0213389
Gp0213390
Gp0213391
Gp0213392
Gp0213393
Gp0213394
Gp0213395
Gp0213396
Gp0242239
Gp0242240
Gp0242241
Gp0242242
Gp0242243
Gp0242244
Gp0242245
Gp0242246
Gp0242247
Gp0242248
Gp0242249
Gp0242250
Gp0242251
Gp0242252
Gp0242253
Gp0242254
Gp0242255
Gp0242256
Gp0242257
Gp0242258
Gp0242259
Gp0242260
Gp0242261
Gp0242262
Gp0256559
Gp0306429
Gp0306430
Gp0306431
Gp0321434
Gp0321435
Gp0321436
Gp0321437
Gp0321438
Gp0321439
Gp0321440
Gp0321441
Gp0321442
Gp0321443
Gp0321444
Gp0321445
Gp0321446
Gp0321448
Gp0321449
Gp0321451
Gp0321452
Gp0321453
Gp0434145
Gp0434146
Gp0434147
Gp0434148
Gp0434149
Gp0434150
Gp0434151
Gp0434152
Gp0434153
Gp0434154
Gp0434155
Gp0434156
Gp0434157
Gp0434158
Gp0434159
Gp0434160
Gp0434161
Gp0434162
Gp0434163
Gp0434164
Gp0434165
Gp0434166
Gp0434167
Gp0434168
Gp0434169
Gp0434170
Gp0434171
Gp0434172
Gp0434173
Gp0434174
Gp0434175

**Comment by sujaypatil96** [comment]
Started working on this. Will post updates soon.

**Comment by ssarrafan** [comment]
@sujaypatil96 @aclum  based on the last comment I'm assuming this is still being actively worked on. I'll move to the next sprint.  Let me know if you don't plan to work on it in the next couple of weeks.
