### ISSUE TITLE
"Download XLSX" button doesn't work without clicking through each tab

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#76]
(currently in -dev)

You cannot download the template until you've clicked through each of the tabs. (EMSL, JGI MG, JGI MT). If you've only been on the biosample tab (soil), the template won't download

Criteria for completion
- The .xlsx file will download without clicking through tabs or adding samples. Just a empty template will be available.

**Comment by pkalita-lbl** [comment]
Reopening this because there are a few edge cases not caught by the initial fix.
