### ISSUE TITLE
Check depth values for NEON surface water samples (nmdc:sty-11-hht5sb92)

### ISSUE THREAD

**Issue by bmeluch** [microbiomedata/issues#762]
While working on https://github.com/microbiomedata/issues/issues/612 I noticed that some depth values for this project are suspiciously high, considering that our units are meters. Are the values actually in centimeters?

- [ ] Share sample names with Hugh/NEON to double check with sampling team
- [ ] Submit changesheet converting to m if necessary

id | name | part_of | Max depth | Min depth
-- | -- | -- | -- | --
nmdc:bsm-12-r7axcm81 | CRAM.C2.20170801 | nmdc:sty-11-hht5sb92 | 14 | 10
nmdc:bsm-12-v8mpfq03 | CRAM.C2.20180807 | nmdc:sty-11-hht5sb92 | 15.2 | 10.4
nmdc:bsm-12-wht50360 | CRAM.C2.20190806 | nmdc:sty-11-hht5sb92 | 13 | 9.7
nmdc:bsm-12-63shyh13 | CRAM.C2.20200804 | nmdc:sty-11-hht5sb92 | 12.1 | 9.4
nmdc:bsm-12-wb2wss52 | CRAM.C2.20210809 | nmdc:sty-11-hht5sb92 | 14.2 | 10.4
nmdc:bsm-12-9bm38c35 | TOOK.C2.20160727 | nmdc:sty-11-hht5sb92 | 15.3 | 10.8
nmdc:bsm-12-wsvcpw44 | TOOK.C2.20170801 | nmdc:sty-11-hht5sb92 | 17.5 | 8.5
nmdc:bsm-12-m4k0ba86 | TOOK.C2.20190709 | nmdc:sty-11-hht5sb92 | 17.2 | 11.4
nmdc:bsm-12-8496kx05 | TOOK.C2.20200707 | nmdc:sty-11-hht5sb92 | 15.2 | 11.1
nmdc:bsm-12-y3xbg509 | TOOK.C2.20210706 | nmdc:sty-11-hht5sb92 | 18.3 | 11.8

**Comment by mslarae13** [comment]
Contacted Hugh

**Comment by hughcross** [comment]
Those are all lake samples, and the **C2** designation means they are from deeper in the water column, so those measurements make sense. I checked the original measures for many of these samples and they are correct. I confirmed with the aquatic team that they are in meters, not centimeters. So, they are all fine. 

Hugh (Microbial Ecologist at NEON)

**Comment by bmeluch** [comment]
Thank you @hughcross !
