### ISSUE TITLE
Check depth values for GROW samples (nmdc:sty-11-5tgfr349)

### ISSUE THREAD

**Issue by bmeluch** [microbiomedata/issues#763]
While working on https://github.com/microbiomedata/issues/issues/612 I noticed that some depth values for this project are suspiciously high, considering that our units are meters. Are the values actually in centimeters?

- [ ]  Check with source data/PI
- [ ] Submit changesheet converting to m if necessary

id | samp_name | part_of | depth.has_numeric_value
-- | -- | -- | --
nmdc:bsm-11-fws0s186 | Yojoa_01_2020_B_hypo | nmdc:sty-11-5tgfr349 | 18
nmdc:bsm-11-mfm7cw16 | Yojoa_01_2020_E_hypo | nmdc:sty-11-5tgfr349 | 18
nmdc:bsm-11-we20cb04 | Yojoa_01_2020_R_hypo | nmdc:sty-11-5tgfr349 | 18
nmdc:bsm-11-avfq6w73 | Yojoa_06_2019_Q_hypo | nmdc:sty-11-5tgfr349 | 16
nmdc:bsm-11-0kawe915 | Yojoa_01_2020_E_meta | nmdc:sty-11-5tgfr349 | 12
nmdc:bsm-11-4269ar54 | Yojoa_01_2020_B_meta | nmdc:sty-11-5tgfr349 | 12
nmdc:bsm-11-n3qamv22 | Yojoa_01_2020_R_meta | nmdc:sty-11-5tgfr349 | 12

**Comment by mslarae13** [comment]
@bmeluch for got about this. Status?

**Comment by bmeluch** [comment]
Emailed PI to double check, pending response

**Comment by bmeluch** [comment]
Sent a follow up email 08 Oct 2024

**Comment by bmeluch** [comment]
Have not heard back about these specific samples, PI and google maps confirm that this is in a lake so 18 meters is possible. Unless we hear otherwise, I'm going to close this issue and leave the data as is
