### ISSUE TITLE
-sandbox submission portal not working

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#77]
Depending on the person, the https://data-sandbox.microbiomedata.org/submission/home site isn't working.

An error is popping up, or the "Create New Submission" button does nothing

Criteria for completion
- Diagnose the errors. Why can some people (Montana) make a submission and some can't?
- Fix this error so all users can create a submission in sandbox

**Comment by mslarae13** [comment]
Lee Ann discovered this issue initially, then @simroux , then @shreddd . During the discussion, I was able to make a submission.. but now, see attached, the screen is stuck on "Loading Items" and I can no longer make a submission in -sandbox.

prod is working as normal.

**Comment by pkalita-lbl** [comment]
Clicking on the Create New Submission button sends a `POST /api/metadata_submission` request that's being rejected with:

```json
{
    "detail": [
        {
            "loc": [
                "body",
                "metadata_submission",
                "template"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        },
        {
            "loc": [
                "body",
                "metadata_submission",
                "multiOmicsForm",
                "datasetDoi"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        },
        {
            "loc": [
                "body",
                "metadata_submission",
                "multiOmicsForm",
                "NCBIBioProjectName"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        },
        {
            "loc": [
                "body",
                "metadata_submission",
                "sampleData"
            ],
            "msg": "value is not a valid list",
            "type": "type_error.list"
        }
    ]
}
```

Based on that it seems like the front-end and back-end on `data-sandbox` are out of sync. The front-end is sending data in the new format (e.g. `sampleData` as an object), but the backend is expecting the old format (e.g. `sampleData` as a list).

**Comment by ssarrafan** [comment]
I believe this issue was resolved by making sure the versions of sandbox and prod were the same. Anything else you want to add before we close this issue @shreddd ?

**Comment by ssarrafan** [comment]
Closing this issue as the sandbox is working now
