### ISSUE TITLE
reprocessing post re-id proteomics nmdc:sty-11-33fbta56

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#771]
**Deliverable this task is associated with**

_See Deliverables tab here: _

- [Add the Deliverable #]

**RACI**

_Tag people in their roles_
- Responsible: @picowatt 
- Accountable: @SamuelPurvine 
- Consulted: @aclum 
- Informed: napa squad

**Describe the the task**
- [ ] Run proteomics workflow on 19 proteomics datasets. All annotations have completed.

**Criteria for completion**
- 19 [MetaproteomicsAnalysisActivity](https://microbiomedata.github.io/nmdc-schema/MetaproteomicsAnalysisActivity/) records that join with OmicsProcessing records on part_of nmdc:sty-11-33fbta56

**Estimate people time**
- 1 person, 8 hours

**Completion Date (Goal)**
-  Aug 9

**Target Sprint Start & End Dates**
- Start: July 15
- End: Aug 9

**Tag Blocker/Contingent upon issues**

**Comment by aclum** [comment]
Issues with site credentials, Cam created new ones today.

**Comment by picowatt** [comment]
Submitted DOs for MSGF+ param file, MASIC param file, and contam file with IDs nmdc:dobj-11-h9637w90, nmdc:dobj-11-hfx93f93, and nmdc:dobj-11-sprrem27 respectively.

**Comment by ssarrafan** [comment]
@picowatt @aclum this issue was just opened 4 days ago so I am assuming this won't be done today. If it's completed please let me know @picowatt or close the issue. Thanks!

**Comment by aclum** [comment]
These have been run and Cam will upload the results to mongo.

**Comment by picowatt** [comment]
Submitted JSON. Tested some URLs, all tested appear to resolve to our workflow outputs.

**Comment by aclum** [comment]
two more datasets to process.

**Comment by picowatt** [comment]
Submitted the last two, nmdc:wfmp-11-fz8k5p27.1 and nmdc:wfmp-11-z44t9n42.1
