### ISSUE TITLE
define multi-valued slot vs compound value 

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#78]
In the submission portal, some slots have compound values (agrochem_addition, roundup;5 milligram per liter;2018-06-21).

Other slots are multi valued (analysis_type, metabolome; proteome)

Clear documentation of how they're different should be provided and clear validation and parsing.

Criteria for completion
- Define and document multi-valued vs compound value vs compound value pattern + multi-valued
- Parsing and storing of these values

**Comment by ssarrafan** [comment]
Is this definition happening as part of the Berkeley schema work?  Can this issue be closed?  @mslarae13

**Comment by mslarae13** [comment]
Not part of berk schema. No work was done on documentation or biosample.

There is still work to do here. There's a similar issue with GSC
- https://github.com/GenomicsStandardsConsortium/mixs/issues/465

And for NMDC
- https://github.com/microbiomedata/submission-schema/issues/23 
- https://github.com/microbiomedata/nmdc-schema/issues/1464
- https://github.com/microbiomedata/nmdc-ontology/issues/67
- https://github.com/microbiomedata/nmdc-metadata/issues/419

I think we have enough other multivalued issues that we can close this one.
