### ISSUE TITLE
reprocessing post re-id proteomics nmdc:sty-11-aygzgv51

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#782]
There are 33 projects which need proteomics, all annotations for this study have completed.

**Comment by ssarrafan** [comment]
@picowatt @aclum this issue was just opened 2 days ago so I am assuming this won't be done today. I'll move this to the next sprint.

**Comment by aclum** [comment]
Cam should be able to run these this week.

**Comment by picowatt** [comment]
Processing completed, submitted metadata for 33 runs of metaP

**Comment by aclum** [comment]
Confirmed these records are in mongo prod.
