### ISSUE TITLE
Submit EcoFAB data to NCBI

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#795]
**Deliverable this task is associated with**

_See Deliverables tab here: _

- [Add the Deliverable #]

**RACI**

_Tag people in their roles_
- Responsible: @sujaypatil96, @chienchi 
- Accountable: @turbomam 
- Consulted: @aclum, @chienchi  
- Informed: @mslarae13 

**Describe the the task**
- [ ] Generate biosample and SRA submission xml for EcoFab submission from Vlastimil Novak

**Criteria for completion**
- ncbi biosample and SRA identifiers 

**Estimate people time**
- 2, 20 hours

**Completion Date (Goal)**
- Aug 16

**Target Sprint Start & End Dates**
- Start: July 29
- End: Aug 22

**Tag Blocker/Contingent upon issues**
- blocked on submission portal to mongo ingest @mslarae13  please add the ticket for that once it exists.

cc @ssarrafan

**Comment by aclum** [comment]
For the SRA block use
library_strategy = AMPLICON
library_source = METAGENOMIC
library_selection = PCR
library_layout = paired
platform = ILLUMINA
instrument_model = Illumina MiSeq

**Comment by ssarrafan** [comment]
Blocked by https://github.com/microbiomedata/issues/issues/776
Montana is reviewing Mongo ingest today

**Comment by aclum** [comment]
This data is in mongo prod now see https://github.com/microbiomedata/issues/issues/812 
Study ID is nmdc:sty-11-ev70y104
The data to make the sra records is here /global/cfs/cdirs/m3408/gsharing/ecofab/ecofab_data

@sujaypatil96  this is ready to start work on.

**Comment by sujaypatil96** [comment]
Starting work on this today, 9/7.

**Comment by sujaypatil96** [comment]
This needs to be moved to the next sprint.

**Comment by sujaypatil96** [comment]
Status update:

* Currently (as of this message) we do not have an existing BioProject record/id for the EcoFAB study on NCBI yet, so we will need to create one. In my pipeline I am using a placeholder BioProject id (`PRJNA123456`) so if you see that id in the XML know that it will be replaced with the correct NCBI BioProject id once we’ve created it
* Organization name we are using is “Lawrence Berkeley National Laboratory” and “broker name” is “National Microbiome Data Collaborative”. Please let me know if either of those needs to be corrected/changed to something else
In the SRA `<Action>` blocks:
  * We have nested `<Identifier> `tags. For the NEON studies we were populating that field with information from `LibraryPreparation.protocol_link.name` but unfortunately we can’t do that for records in this study, so I am simply populating it with `Biosample.name` == `Biosample.samp_name` == “sample name” from [spreadsheet](https://docs.google.com/spreadsheets/d/1rEffhm79Alryzi4pPLtmnh4644QwEcwX/edit?gid=1187542875#gid=1187542875)
* We are also missing Library attribute information for `library_construction_protocol` in this [comment](https://github.com/microbiomedata/issues/issues/795#issuecomment-2251145709)
* We were using env_package to infer the value for `<Package>` in the BioSample `<Action> `blocks which makes it look like this: `<Package>MIMS.me.miscellaneous natural or artificial environment.6.0</Package>`
Ideally, we would want to use a standard NCBI package name from here: https://www.ncbi.nlm.nih.gov/biosample/docs/packages/
* We can see 140 `<Action>` blocks for BioSample records and 90 blocks for SRA records which are both the expected number of blocks

Refer to the squad slack channel for a preview of the XML export file.

ETA: ideally, end of the week/sprint.

**Comment by aclum** [comment]
Actively in progress but we are still iterating over the code that generates the xml for this new package so moving the next sprint.

**Comment by aclum** [comment]
We tried to submit this as a test but are having trouble with the bioproject IDs.

**Comment by ssarrafan** [comment]
> We tried to submit this as a test but are having trouble with the bioproject IDs.

@sujaypatil96 any update on the bioproject IDs issue?

**Comment by chienchi** [comment]
The test submission successfully and will submit to production. Move to next sprint and hope it will be done early next week.

**Comment by chienchi** [comment]
The submission to NCBI went through. 
![image_720](https://github.com/user-attachments/assets/01bfafa9-f2ac-4abe-bb54-8195506781bb)
