### ISSUE TITLE
SPRUCE missing data products

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#8]
For EMSL Summer school, we discocered 3 SPRUCE samples that were on the data portal, but we couldn't fin the data products from the NMDC workflows. Samples do exist on NERSC. 

June2016WEW_10_10 (June2016WEW_Plot10_D2) : https://data.microbiomedata.org/details/sample/gold:Gb0153621

June2016WEW_13_40 (June2016WEW_Plot13_D5): https://data.microbiomedata.org/details/sample/gold:Gb0153630

June2016WEW_17_40 (June2016WEW_Plot17_D5): https://data.microbiomedata.org/details/sample/gold:Gb0153638

Completion Criteria
- [ ] SPRUCE missing data is located and ingested
- [ ] Mechanism for checking orphan data sets in the portal where we have sample metadata but no data products

**Comment by aclum** [comment]
There is metagenomic data and metaproteomic data for June2016WEW_10_10 and June2016WEW_17_40 and metagenomic data for June2016WEW_13_40 which matches the number of omics processing records in mongo prod. @mslarae13  would you confirm if these samples meet your expectations now?
