### ISSUE TITLE
Create `MassSpectrometry` change sheets with updated `has_chromatography_configuration` values.

### ISSUE THREAD

**Issue by kheal** [microbiomedata/issues#803]
- [x] #749 
    _must be closed before we can start on this_
- [x]  Add ChromatographyConfiguration ids to all applicable MassSpec instances
- [x] Format change sheets to work with API endpoint submission
- [x] Submit change sheets to Berkeley Mongo.

**Comment by brynnz22** [comment]
Closing. These are added to prod.
