### ISSUE TITLE
Draft an ADR for using sheets-and-friends to make slot usage updates

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#81]
This issue is to create an ADR and therefore a process for how to make slot usage updates.

**Comment by ssarrafan** [comment]
@turbomam @mslarae13 any update on this?  Should this one go in the backlog?  I know how busy you both are.

**Comment by mslarae13** [comment]
Back log please. I won't get to this till after I return.

**Comment by aclum** [comment]
I believe sheets and friends no longer exists. Can this be closed @mslarae13?

**Comment by turbomam** [comment]
https://github.com/microbiomedata/sheets_and_friends still exists, is still used in the submission-schema and nmdc-schema build processes, and may become more important in the monterey-schema.

https://github.com/linkml/linkml-transformer may be a better choice in the long run

@pkalita-lbl can you share you thought about using the following for making derivatives of schemas?

- https://github.com/microbiomedata/sheets_and_friends
- https://github.com/linkml/linkml-transformer
- https://github.com/mikefarah/yq

**Comment by pkalita-lbl** [comment]
linkml-transformer is designed to transform _data_ adhering to one schema into equivalent data adhering to another schema. It's not totally clear to me how that would be be useful in creating derived schemas. 

qy commands, while powerful, always feel a bit opaque to me. I like it for one-off commands in a shell, but once you have 50 lines of it in a Makefile it makes me think, why not just write a Python script that could be properly commented, debugged, etc.

The sheets_and_friends model (that is, configuration TSV files and Python code that reads them and produces a derived schema accordingly) makes the most sense to me. I'm sure there's plenty we could do to document and improve the format of those configuration files (possibly even adding new ones if needed).

**Comment by mslarae13** [comment]
@pkalita-lbl ... I know you've worked with @bmeluch on how to update pieces of sheets and friends for the submission schema is this something she can help with? Or get started??

**Comment by pkalita-lbl** [comment]
I'm not sure I can give a good answer to that question. This issue doesn't really have a lot of context to it. Is the task to write an ARD (if so what's the decision that needs making?) or to implement something in sheets and friends (if so what exactly? is there a concrete use case?)

**Comment by mslarae13** [comment]
ADR describing how slot usage is accomplished in the submission schema for the different interfaces... because it isn't done the same way it is in the NMDC schema.. there's a table you have to update, right? 

I haven't done it, but Bea kinda showed me what you two had talked about a couple weeks ago..

@pkalita-lbl

**Comment by pkalita-lbl** [comment]
Yeah understood. I think this would probably be better addressed through documentation in both the `sheets_and_friends` project and the `submission-schema` project. Unless I'm missing something I don't think we're _deciding_ anything new, so an ADR probably isn't warranted.

**Comment by mslarae13** [comment]
Documentation is good for me!!

**Comment by mslarae13** [comment]
@pkalita-lbl  I assume this documentation hasn't been done? Maybe something @bmeluch can work on?

**Comment by ssarrafan** [comment]
I'm closing this issue since it sounds like an ADR isn't needed.  
@bmeluch let me know if you have an issue to work on the documentation or if you need help creating one.  
FYI @mslarae13
