### ISSUE TITLE
Replicate records for NOM processed data objects and upstream objects

### ISSUE THREAD

**Issue by kheal** [microbiomedata/issues#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are repeating records in Mongo that correspond to the same object/url.  

Screenshot below shows how they show up on the data portal:
![image](https://github.com/user-attachments/assets/c2ab477d-d1ea-416a-9740-df73a24e443d)

When you download these objects, they are identical (even the url you download them from is identical).  In essence, they represent replicated `DataObject` instances that are in mongo.

Because of the way the metadata were generated from the processed NOM data objects, this resulted in several 'upstream' repeated records as well.

Attached is a csv of the repeated records we have found (each row represents the full 'chain' of replicated records, so we need to remove two of these chains to maintain referential integrity).
[nom_replicates.csv](https://github.com/user-attachments/files/16460346/nom_replicates.csv)

### Steps to fix this issue and consider it closed

Below is the summary of records we should delete from mongo:
_Note that these correspond to the bottom two "chains" described above_
1. From `data_object_set` [2 processed data objects, 2 raw data objects]
    1. nmdc:dobj-11-4t2x0y18
    2. nmdc:dobj-11-dxhdyz52
    3. nmdc:dobj-11-xfwcqf33
    4. nmdc:dobj-11-xkm3y166
2. From `nom_analysis_set`
    1.  nmdc:wfnom-11-t68q3s78.1
    2. nmdc:wfnom-11-3fczdt63.1
3.  From `omics_processing_set`
    1. nmdc:omprc-11-xv5ny564
    2. nmdc:omprc-11-k1wgzp49
4.  From `biosample_set`
    1. nmdc:bsm-11-eg7txt85
    2. nmdc:bsm-11-jwzaea31 

@samobermiller, can you please double/triple check the IDs and collections/sets to be removed?  

See discussion here that revealed these replicates: https://github.com/microbiomedata/nmdc_notebooks/discussions/58#discussioncomment-10078445

**Comment by samobermiller** [comment]
Yes these IDs show up as having the same md5 checksum!

**Comment by kheal** [comment]
@aclum - here are the jsons for these deletions.  I used this script's make_deletes method with the collections and records above. https://github.com/microbiomedata/nmdc-schema/blob/main/nmdc_schema/identify_workflow_duplicates_emp500.py

[biosample_set_request_body.json](https://github.com/user-attachments/files/16606542/biosample_set_request_body.json)
[omics_processing_set_request_body.json](https://github.com/user-attachments/files/16606543/omics_processing_set_request_body.json)
[data_object_set_request_body.json](https://github.com/user-attachments/files/16606544/data_object_set_request_body.json)
[nom_analysis_set_request_body.json](https://github.com/user-attachments/files/16606545/nom_analysis_set_request_body.json)

**Comment by aclum** [comment]
@kheal tested this with runtime dev, there was a minor typo in the nom activity collection name which i fixed and then applied to prod. Please confirm expected records are deleted on mongo prod and we can close this out.
