### ISSUE TITLE
Ingest and process data for EcoFab `nmdc:sty-11-ev70y104`

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#812]
Study, metadata, and biosamples submitted via NMDC submission portal 

- [x] Ingest into mongo dev & test (#776 )
- [x] Ingest into mongo prod (#776 )
- [ ] Ingest data to run workflows
  - [ ] metagenomics

**Comment by pkalita-lbl** [comment]
The study and sample records are now in prod MongoDB. Study ID: `nmdc:sty-11-ev70y104`

**Comment by aclum** [comment]
Closing this as there is only itag data, no metagenomics.
