### ISSUE TITLE
Link to “Minimum Information about any (x) Sequence” is broken on `https://microbiomedata.org/metadata/overview/ `

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#817]
On https://microbiomedata.org/metadata/overview/   “Minimum Information about any (x) Sequence” points to https://www.gensc.org/mixs/ which is not a valid link anymore 
I believe https://www.gensc.org/pages/projects/mixs-gsc-project.html is what we want. Montana to confirm.

**Comment by eecavanna** [comment]
I transferred this issue to the `issues` repo.

I'll close it now, since it's fixed.

**Comment by aclum** [comment]
thanks!
