### ISSUE TITLE
NEON JGI soil reannotation stragglers

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#818]
These 2 JGI generated projects for NEON soil are still missing new annotations (v1.1.0)

nmdc:omprc-11-bhx9bh23 - this one I can see it tried but failed. i can't see any non-zero exit codes. /pscratch/sd/n/nmdcda/cromwell-executions/annotation/9cbcf206-07ed-43f1-a743-2b9fffea9898> find -name 'rc' | xargs cat | sort | uniq
0

 nmdc:omprc-11-dmfp3f27 - similar situation.

I'd like the full set before we have Marcel ingest the new records.

**Comment by kaijli** [comment]
from cq metadata:
```
"message": "Unable to determine that 219760 is alive, and /pscratch/sd/n/nmdcda/cromwell-executions/annotation/9cbcf206-07ed-43f1-a743-2b9fffea9898/call-s_annotate/shard-3/sa.s_annotate/e72272ee-1201-4500-89c1-ce03b7028fe6/call-gff_merge/execution/rc does not exist."
```
though, the rc file does exit, so could it be a time-out error from workers inactive? @scanon is this just a resubmit?

**Comment by ssarrafan** [comment]
@scanon @kaijli any update on this? Today is the last day of this sprint.  Is this still an active issue?

**Comment by aclum** [comment]
will add this to the agenda for the workflows meeting, i dont think anything was done for this this sprint.

**Comment by scanon** [comment]
I've reset the failed count and it is getting resubmitted.  I'm guessing there was some transient error on Perlmutter that this tripped over.

**Comment by ssarrafan** [comment]
> I've reset the failed count and it is getting resubmitted. I'm guessing there was some transient error on Perlmutter that this tripped over.

@scanon any update on this?

**Comment by ssarrafan** [comment]
Moving to next sprint. @scanon let me know if you're not working on this.

**Comment by ssarrafan** [comment]
No updates for 2+ weeks
Removing from sprint
@aclum @scanon @kaijli

**Comment by aclum** [comment]
These were completed in Aug, we have annotation version 1.1.0 records for both nmdc:omprc-11-bhx9bh23 and nmdc:omprc-11-dmfp3f27.
