### ISSUE TITLE
Determine policies for env_local_scale

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#840]
https://github.com/microbiomedata/issues/discussions/835

Criteria for completion
- Determine NMDC policy for env_local_scale
- Determine NMDC policy/ method for env_local_scale in SOIL
- Draft ADR for environment trial methods / policies

Not part of this issue:
- The ADR will change once #844 & #845 are complete.
-  Finalized policy will be recorded & ADR will be updated with tasks #846 
- How many env_local_scale values are not a children of material entity? (from what's in NMDC mongo or postgres or NCBI) (see other issue)
- - @sierra-moxon can review, issue coming

Policy for env_local_scale outside of the limitation of any environment is doable. 
- ANY local scale (material entities - biomes - env systems that are shadow of biome - environmental materials). 
- Local scale should not be quantifiable, it's countable.
- This is still a large list with this narrowing.
- From here, we have to figure out how to do it for each environment.

**Comment by sierra-moxon** [comment]
for sierra:

- [ ] spin up https://github.com/microbiomedata/external-metadata-awareness development environment and run tests
- [ ] review oak usage

**Comment by turbomam** [comment]
[Using ENVO with MIxS](https://github.com/EnvironmentOntology/envo/wiki/Using-ENVO-with-MIxS)


> In this field, report the entity or  entities which are in your sample or specimen’s local vicinity and which  you believe have significant causal influences on your sample or  specimen.
> 
> Please use terms that are present in ENVO and which are of smaller spatial grain than your entry for env_broad_scale


Less helpful than the `env_broad_scale` and `env_medium` guidance, but we should still keep it in mind

**Comment by mslarae13** [comment]
Using dynamic enumeration for submisson portal. Separate syntax. OR, decide, do we use dynamic enums in LinkML or populate enums with pre-determined static enum.

Using a dynamic enum & refreshing it, you get all new and different content according to source ontology

Evaluate Pros & Cons

What about old data? What if a term is removed? Dynamic enums is concerning when users are selecting these terms. 
- In general, what will be NMDC's policy if ENVO changes, removes something, and a user can't find it?

For GOLD, we do not evaluate data in Mongo for still valid pathway, on monthly basis, the enum is re-generated to match GOLD as part of the release cycle. 
- Does GOLD update its DB?
