### ISSUE TITLE
1000 soils- link Gold Biosamples for Gs0156736 to existing NMDC biosamples

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#85]
@JamesTessmer  ingested 1000 soils data from the NMDC submission portal. This ticket's purpose now is 
- [x] to update the biosample records that are also in gold using the `gold_biosample_identifiers` slot for class biosample. [This spreadsheet](https://docs.google.com/spreadsheets/d/1kExreCLFy4NucyvdumHV3j7v1CYa8flNkr5kq8FkpQI/edit#gid=0) has the mapping based on [emsl_biosample_identifiers](https://microbiomedata.github.io/nmdc-schema/emsl_biosample_identifiers/)
- [x] synchronize with GOLD biosample metadata (esp ecosystem pathway terms)
- [x] create omics_processing_set records

**Comment by aclum** [comment]
Thanks to work from the EMSL team we now have environmental terms from the development instance of the submission portal (https://data-dev.microbiomedata.org/submission/3d433048-67f2-4335-b34d-698f14095a0c/samples). I have also dumped this into our spreadsheet. We would like to ingest at least the biosamples from GOLD that map 1:1 which what is in the NMDC submission portal. In some cases submission portal rows map 1:2 JGI GOLD record because biological samples were extracted with 2 different DNA kits (corresponding to *_Q or *_Z) for the GOLD identifier.  Below is the list of what biological samples have what count of GOLD biosample records (NMDC would call these analytical samples) 
   1 UUID:FTA3-CB-B-6c80279c-0ca3-4835-bfea-501e43fdc1a6
   1 UUID:FTA3-CB-T-4116d3f6-5dfe-45c0-9989-6a6489238fbf
   1 UUID:FTA5-CB-T-6930cad4-38f4-4eab-8b53-45805fbcc40d
   1 UUID:OKPF-CB-B-d7417aa2-8ef2-4dfe-a655-4c535ec5a5b3
   1 UUID:OKPF-CB-T-08bb4fcb-2668-4d6f-a7eb-8f76a862abaf
   1 UUID:PETF-CB-B-9196012d-042a-47b4-986a-21ead1040e31
   1 UUID:PETF-CB-T-cef6133d-59d9-44f6-8c22-29664736616d
   1 UUID:PSR1-CB-B-60b61105-073e-4d04-b3dc-452479bbae4b
   1 UUID:PSR1-CB-T-b15f1f00-c26a-47d1-969f-91faf5944d58
   1 UUID:PSR2-CB-B-a9123b93-226f-4ac9-86f6-da9030cb4603
   1 UUID:PSR2-CB-T-177b015d-e006-4aca-977d-c9c118f6ec69
   1 UUID:WSU1-CB-B-19e2cefa-49f2-499b-841d-33cc7ed8e6a7
   1 UUID:WSU1-CB-T-90f166a5-20ce-4c9b-b4a4-4a587395ffae
   1 UUID:WSU2-CA-B-6ad1d2a3-0949-423a-a549-c801913e1d63
   1 UUID:WSU2-CB-T-f0728f3d-65c8-4075-9d17-47ce2e1de63c
   1 UUID:WSU3-CB-B-c248f426-b677-44df-919e-a9bd18e6fa7b
   1 UUID:WSU3-CB-T-4aaf3e2e-30af-4cb3-bfb3-e4cbeae25f62
   2 UUID:FTA5-CB-B-f450aea0-e6fb-4596-9f8b-56dba4635a8b
   2 UUID:WSU1-CB-B-19e2cefa-49f2-499b-841d-33cc7ed8e6a7
   2 UUID:WSU1-CB-T-90f166a5-20ce-4c9b-b4a4-4a587395ffae
   2 UUID:WSU2-CA-B-6ad1d2a3-0949-423a-a549-c801913e1d63
   2 UUID:WSU2-CB-T-f0728f3d-65c8-4075-9d17-47ce2e1de63c
   2 UUID:WSU3-CB-B-c248f426-b677-44df-919e-a9bd18e6fa7b

At a minimum ingest the samples were there is a 1:1 relationship b/w NMDC submission portal and GOLD using the MIxS environmental terms from the submission portal. There is other useful metadata in the submission portal if that is easy to pull in based on work you've done for other studies. 
[This spreadsheet ](https://docs.google.com/spreadsheets/d/1kExreCLFy4NucyvdumHV3j7v1CYa8flNkr5kq8FkpQI/edit#gid=0)has a few useful tabs
The 'GOLD' tab has a dump of the GOLD public biosample API and a mapping to NMDC submission portal sample name, global unique identifiers, and the MIxS environmental terms based on vlookup. 
The 'GOLD-SubPort Map' tab is the mapping key b/w GOLD sample name and NMDC sample name.
The '20230306 NMDC submission portal' tab is a dump of the NMDC submission portal sample metadata. This is a static version of what can be found in the [NMDC dev submission portal for this study](https://data-dev.microbiomedata.org/submission/3d433048-67f2-4335-b34d-698f14095a0c/samples).

**Comment by aclum** [comment]
@sujaypatil96  please let me know if you have questions on what needs to happen.  This is the highest study/biosample ingest priority after you are done with GROW and Bioscales.

**Comment by mslarae13** [comment]
The submission with the terms is : https://data.microbiomedata.org/submission/a2c2b0e9-ea12-4742-a597-59b3dcc1997f/study 

"1000-Soils Metadata for GSP"

**Comment by aclum** [comment]
This is still outstanding. I see you have moved it to this sprint.

**Comment by aclum** [comment]
@bmeluch  possible ticket for this week

**Comment by aclum** [comment]
Thanks @bmeluch  let's leave this ticket open since we still need to pull in the GOLD metadata now that we have the mapping information in our biosample records.

**Comment by mslarae13** [comment]
@aclum is there any GOLD biosample metadata that isn't already captured?

**Comment by aclum** [comment]
@mslarae13 the gold ecosystem fields don't all match what is in GOLD. For example for Gb0315283 nmdc has Unclassified fro specific_ecosystem and ecosystem_subtype, in GOLD these are 'Bulk soil' and 'Grasslands', GOLD also has the ncbi taxonomy ID and name which are not currently populated in our records. The sample collection date is different in our system and GOLD so those should be synchronized (I'm guessing we'd consider nmdc the source b/c you worked closely with the PI on this one). At a minimum we should use make sure the GOLD ecosystem pathway slots match what is in GOLD.

**Comment by aclum** [comment]
Based on the GOLD biosample IDs we also need to make OmicsProcessing records.

**Comment by mslarae13** [comment]
@aclum @bmeluch is going to grab the GOLD metadata and we'll look at the differences I agree, we should pull the GOLD metadata and update the GOLD paths to what GOLD has. For the collection date, yes I think what we have is right, but I'd like to look at it and confirm with the 1000 soils team, cuz that's weird.

For the OmicsProcessing records, yes we should pull what GOLD has but there's a LOT more metagenome data to be processed. Can we also look into getting the genewiz data and processing it?

**Comment by aclum** [comment]
Yes, we can do what we did with the TRiP data where we'd need a table that says what data goes with what.

**Comment by turbomam** [comment]
@aclum which of the three check-boxes form your original post are still pending? Which were you thinking @sujaypatil96 would help with

**Comment by turbomam** [comment]
Would it be helpful to split hem out into separate issue and have a separate assignee for each?

**Comment by aclum** [comment]
Bea has added the GOLD biosample identifiers to the ndmc biosample records. I need help from @sujaypatil96  for the second two issues. That is, to make sure the gold pathways match what is in gold for these biosamples and to make omics records so that we can ingest the JGI processed data. If think separate tickets feel free to make them.

**Comment by bmeluch** [comment]
I made a spreadsheet today comparing metadata between NMDC and GOLD which I can share wherever would be best to have that. Once I look at the collection dates with @mslarae13 I think I can do this with changesheets, unless someone else is already working on it.

In summary - 

**Missing in NMDC; pull from GOLD**
- description
- habitat
- ncbi_taxonomy_name
- sample_collection_site

**Discrepancy; pull from GOLD**
- ecosystem_subtype
- specific_ecosystem

**Discrepancy; NMDC values are more specific, I assume we keep them?**
- depth
- elev
- geo_loc_name

**??? collection date mystery ???**
- collection_date

**Comment by sujaypatil96** [comment]
Thanks for the analysis between NMDC and GOLD @bmeluch. I will pull in the right ecosystem pathway terms (eocosystem_subtype, specific_ecosystem) from GOLD for each biosample to address the second checkbox in this issue.

**Comment by sujaypatil96** [comment]
> make omics records so that we can ingest the JGI processed data

@aclum where can I find a reference to what FASTQ files are to be associated to the data objects that will be the output of the omics processing records that we are creating?

**Comment by sujaypatil96** [comment]
@ssarrafan needs to be moved to next sprint, will not be complete by 2/23.

**Comment by sujaypatil96** [comment]
@aclum here is the changesheet to address the second checkbox in this issue: https://docs.google.com/spreadsheets/d/15gB7bxCl4WkyrGDkAMTrAINqHMOpGwRIMT3vrD58kGc/edit?usp=sharing

**Comment by mslarae13** [comment]
Review GOLD metadata vs Submission portal metadata
- [ ] Dates match, use GOLD ecosystem classification for subtype and specific. 
Gb0317111	FTA5_CoreB_BTM
Gb0317117	FTA5_CoreB_BTM
Gb0316253	FTA5_CoreB_TOP

- [ ] Use NMDC collection date. Push update to GOLD. use GOLD ecosystem classification for subtype and specific. 
Gb0315293	PETF_CoreB_BTM
Gb0315292	PETF_CoreB_TOP

- [ ] Not sure why these biosamples were missed on NMDC ingest. But they are in the submission portal. @pkalita-lbl can you take a look?
Gb0315291	OKPF_CoreB_BTM
Gb0315290	OKPF_CoreB_TOP

- [ ] Typo in NMDC submission, GOLD date is correct. Change sheet to NMDC to correct to 2022 collection date
Gb0315295	PRS1_CoreB_BTM
Gb0315294	PRS1_CoreB_TOP
Gb0315297	PRS2_CoreB_BTM
Gb0315296	PRS2_CoreB_TOP

- [ ] Still investigation [in progress]
Gb0317112	WSU1_CoreB_TOP
Gb0317113	WSU2_CoreB_TOP
Gb0315288	WSU3_CoreB_TOP

**Comment by ssarrafan** [comment]
Per @sujaypatil96 request moving to the next sprint and also to the next sprint column on the ECR/GSP board.  @aclum @mslarae13

**Comment by mslarae13** [comment]
OK. WSU1,2,3 were have a collection site of USA: Oregon, Warm Springs. 

OKPF_CoreB_BTM & OKPF_CoreB_TOP were missed because the core # was wrong. Need to create these biosamples in NMDC. We can pull in the GOLD biosample, and submit a change sheet to correct the metadata.

[Uploading nmdc_sample_export (22).xlsx…]()t @sujaypatil96 I color coded it. Does it make sense to you? If you need, I can update your change sheet. Just lmk.

**Comment by bmeluch** [comment]
[nmdc_sample_export.22.xlsx](https://github.com/microbiomedata/issues/files/14381077/nmdc_sample_export.22.xlsx)
Thank you Montana! I made some small edits. @sujaypatil96 we tried to make it not too chaotic but please let me know if you want help looking through it!
The OKPF metadata that NMDC has looks correct, apart from the GOLD pathway.

**Comment by turbomam** [comment]
@bmeluch and team: can you please briefly describe how you got the necessary GOLD data, compared it to something else (NMDC Biosamples?) and then added the missing parts? 

This is very valuable work and I would like to capture the flow so that it can be automated and generalized

**Comment by bmeluch** [comment]
Ooh boy. Well, we took the GOLD metadata and NMDC metadata and compared the slots that map to each other. We tried to 1) find places where the data doesn't match, which is easy, and 2) find places where the data doesn't make sense, which is harder (eg. latlon and geo_loc_name are formatted correctly but don't refer to the same place when you check the map, collection_date is formatted correctly but wayyyyy outside the time span of the other samples)
Sometimes, the mismatches are easy to correct (eg. GOLD had all zeros or blanks for depth but NMDC had actual ranges), but in several cases it required going through old emails and contacting team members to figure out what the correct values were. I would love to have this automated, but it required judgement calls and sleuthing and institutional knowledge, so maybe we should just automatically check for agreement between corresponding slots and review from there?

**Comment by turbomam** [comment]
Thanks. Yes, it will be hard to automate all of this. Job security! But there's a lot of potential for at least automated detection of discrepancies.

Where/how did you get the GOLD and NMDC metadata that you considered in-scope?

**Comment by sujaypatil96** [comment]
The new OKPF biosamples have the following ids if you want to look them up through the API: https://api.microbiomedata.org/docs#/find/find_biosample_by_id_biosamples__sample_id__get — `nmdc:bsm-11-my88da58` and `nmdc:bsm-11-yqhjes36`.

**Comment by sujaypatil96** [comment]
Changesheet applied to dev/prod to capture the changes requested by @mslarae13 in this [comment](https://github.com/microbiomedata/issues/issues/85#issuecomment-1960052896).

**Comment by ssarrafan** [comment]
@mslarae13 can this issue be closed?  I know you'll be off to vacation soon so let me know.

**Comment by sujaypatil96** [comment]
@ssarrafan not yet. The `OmicsProcessing` records for the 1000 soils study need to be created still. Once that's done, this issue can be closed I think? Apologies, this is more like a super issue which has small subissues within it.

**Comment by sujaypatil96** [comment]
I see this issue being completed in the first few days of the next sprint, so this issue will need to be moved to the next sprint @ssarrafan.

**Comment by sujaypatil96** [comment]
@JamesTessmer and I finished addressing check box 3 from this original issue description.

The omics processing and data object records for the 1000 soils study have been submitted to both dev and prod Mongo. This issue is ready to be closed @ssarrafan.

CC: @aclum
