### ISSUE TITLE
Lake Mendota - ingest GOLD study and biosamples for Gs0136121

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#86]
Similar to GROW and Bioscales we need to ingest this study and biosamples from GOLD. Environmental terms are in GOLD.
GOLD study Gs0136121

There is a large combined assembly which I don't think NMDC can handle yet so ignore Ga0590176, this has an analysis project type of 'Combined Assembly'

**Comment by ssarrafan** [comment]
@aclum @sujaypatil96 is this in scope for this sprint?

**Comment by aclum** [comment]
Yes, this project should be straightforward to import from GOLD so we hope to have it in for GSP but is lower priority than 1000 soils and NEON.

**Comment by ssarrafan** [comment]
@aclum @sujaypatil96  I'm assuming this is still being actively worked on. I'll move to the next sprint.  Let me know if you don't plan to work on it in the next couple of weeks. Also let me know if it should be re-assigned to Patrick.
