### ISSUE TITLE
Milestone - Scale current search to support eight orders of magnitude more elements (e.g. functional terms) (1.12)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#868]
Scaling Search Capabilities 
There are a large number of metadata entries generated from the functional annotation workflow. There  are currently 397M raw annotations which we aggregate into 3.3M queryable records. In order to support  the ability to query across all multi-omics samples by functional element in a performant manner, the  NMDC team constructed indexes accessed by the Data Portal that can be efficiently joined with other  metadata search terms. We are confident variations of this approach can be used to improve performance  as more data is ingested in the system. Options include index optimization, scaling available memory,  database partitioning, and sharding. Together, these approaches could scale functional annotation search  up to eight orders of magnitude beyond what is currently in the system (Figure 4, F; Milestone 1.12).  While scaling these search capabilities, we will work closely with our users to understand search priorities  for the community to increase interest in Portal usage.  

@emileyfadrosh @aclum

**Comment by aclum** [comment]
This seems like an infrastructure milestone so reassigning to @shreddd. @jeffbaumes @naglepuff can you comment on this?Did the aggregation tables on the mongo side take care of this or is more work here needed. Adding COG and Pfam will approximately triple the number of records in the functional aggregation table.

**Comment by aclum** [comment]
There are currently 27.6 million records in functional_annotation_agg which is 8.18x the 3.3 million described in the milestone so marking this milestone complete. @naglepuff @shreddd @jeffbaumes  please comment here if you disagree.
