### ISSUE TITLE
Initialize step-by-step instructions for Berkeley Schema "Switch Over" Day

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/issues#873]
Initialize a document (e.g. Google Doc, GitHub Issue, `README.md`) that team members (specifically, Berkeley Schema Roll Out squad members) can use to document—in a single, common place—what they will be doing as part of the Berkeley Schema Roll Out Day (i.e. the day when we "flip the switch" from the legacy schema to the Berkeley schema).

I think doing this in a GitHub Issue description will be too chaotic and collision-prone; so I do not plan on pursuing that option. A Google Doc may be easier for non-developers to edit; while a GitHub `README.md` will—in my opinion—have better support for embedded code snippets. Maybe we can start with a Google Doc to get the skeleton of the document (without the code snippets); then I can migrate that to a `README.md`, and the people that will be running commands/code can edit the `README.md`.

**Comment by eecavanna** [comment]
I have created a Google Doc for this. I am still adding my own steps to it. There's a link to it in the Google Doc named `Berkeley-Schema-Refactor-RollOutNotes` (search for "`Berkeley Schema Switch-over Day: Plan`"). I will post a link to the document on Slack once I've finished adding my own steps to it (I expect those to be useful anchor points for people).

**Comment by ssarrafan** [comment]
Moving to next sprint @eecavanna

**Comment by eecavanna** [comment]
Thanks, @ssarrafan

**Comment by eecavanna** [comment]
I finished initializing this document.

**Comment by ssarrafan** [comment]
> I finished initializing this document.

Hi @eecavanna who do you want to review this?  Or can we close this issue since the document has been initialized?

**Comment by eecavanna** [comment]
Thanks, @ssarrafan. This is done. I just now updated the issue title to emphasize the "initialize" aspect.
