### ISSUE TITLE
Determine policies for env_broad_scale

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#877]
Criteria for completion
- [ ] Determine NMDC policy for env_broad_scale
- [ ] Determine NMDC policy for env_broad_scale in SOIL
- [ ] Draft ADR for environment trial methods / policies

Not part of this issue:
- The ADR will change once https://github.com/microbiomedata/issues/issues/844 & https://github.com/microbiomedata/issues/issues/845 are complete.
- Finalized policy will be recorded & ADR will be updated with tasks https://github.com/microbiomedata/issues/issues/846

@sierra-moxon can review
@sierra-moxon could help & review with this
Policy for env_broad_scale parent class recommended is biome.

Using OAK, structurally do these searches for subclasses & use axiomatic (rules/ children queries that leave out specific strings / text.)

**Comment by mslarae13** [comment]
biome is the policy for top level.

Keep in mind exceptions for some host extensions.

If a term is missing for an extension, request a new term, don't use something outside of biome.

Starting at biome means we will not include ecosystem.
- For most terms, if a term is in ecosystem and we need it in biome, we've requested a biome. 
- yes, leave out ecosystem
- Suggestion: provide the list of un-included terms, the part of the query the eliminated, and a space for notes.
  - getting the query piece to export might be hard/manual. Might need to be a reverse engineering solution
  - why did we eliminate everything that's not biome justification. Why you don't see the pieces you would've expected. Why we excluded some pieces in biome

Still allow overwrite with own term?
- yes, with scrutiney.
- need user research

**Comment by mslarae13** [comment]
for soil, biome - aquatic biome ... human review.

Split leaf nodes & non-leaf nodes.
Review these lead and non-leaf nodes for elimination. 
Expect leaf nodes to be removed.

**Comment by turbomam** [comment]
- try base ontology
- share excludeds
- include classes with NLCD aliases
- share the spreadsheet 
- legacy allowed list vs presented pick list
- 218 biomes, 392 ecosystems
- Yeah there are some addition non-biome ecosystem terms like “ecotone”
- biomes are all subclasses of ecosystem

**Comment by turbomam** [comment]
- check for intersection of "soil" text search and subclasses of soil
- would we ever need stemming?
