### ISSUE TITLE
Metadata: Remove "Menus:" from the DH help box.

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#88]
@pkalita-lbl  @turbomam 
Not sure if this is a Data harmonizer thing? 
But can we remove Menus?

![Screen Shot 2023-02-27 at 8 29 31 PM](https://user-images.githubusercontent.com/44581429/221754160-814ebe5d-8b4c-4f17-8ab6-e7277eeb15ef.png)

**Comment by pkalita-lbl** [comment]
@ssarrafan I'm not sure where it says "Menue". Do you have a screenshot or any other pointers?

**Comment by pkalita-lbl** [comment]
This behavior comes from DataHarmonizer. I'm sure Damion won't be interested in removing it altogether, but I'll try to work with him to find a way to make it configurable.
