### ISSUE TITLE
Release 2024.10 (the Berkeley Schema release)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/issues#891]
Release 2024.10 is scheduled to be deployed to production on: `Tuesday, October 15, 2024`

Upstream events (subject to change, given that this is the Berkeley Schema release):

- Freeze the version of `nmdc-schema` that will be used in this release, by: `Friday, October 4, 2024`
- Begin focused testing of the to-be-released versions of everything, in the development environment, by: `Wednesday, October 9, 2024`
- Additional events TBD

Use this issue to document any tasks that you want to be part of the release process for this release, that aren't already part of the standard release process.

**Comment by ssarrafan** [comment]
@shreddd this issue hasn't been closed so maybe you can add the hotfix info here?
