### ISSUE TITLE
Several sequencing workflows are missing stats json file needed by nmdc_automation

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#898]
In several cases in the workflow repository we are not outputting the stats file needed in order for the nmdc_automation code populate mongo records with workflow specific fields (ie contig_bp for nmdc:MetagenomeAssembly). Some of this is from the re-working of workflows to add long read support from rewriting wdl tasks or changing variable names. We need to review all WDLs and make sure the files that contain the fields specified by the schema are part of the workflow level outputs (the nmdc_automation code checks outputs block of the metadata.json file from cromwell).

Please prioritize the short read workflows as automation is not set for the long read workflow. If there are needed changes to the variable names those should be pull requests on the nmdc_automation repository.  I suggest PRs from [this branch ](https://github.com/microbiomedata/nmdc_automation/tree/252-workflow-automation-berkley-rc1)if this is being worked on before 10/15/24 when we are rolling out large changes to accommodate schema changes (berkeley).

Here are two subtickets that I made for individual repos:
https://github.com/microbiomedata/ReadsQC/issues/39
https://github.com/microbiomedata/metaAssembly/issues/21
https://github.com/microbiomedata/metaAssembly/issues/22

cc @mbthornton-lbl @scanon

**Comment by ssarrafan** [comment]
Is anyone actively working on this issue for this sprint @chienchi @kaijli @vlilanl?

**Comment by aclum** [comment]
@vlilanl is working this.

**Comment by ssarrafan** [comment]
I'm adding the backlog label and removing from sprint.
@vlilanl @aclum
