### ISSUE TITLE
Develop roadmap for NMDC website harmonization

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/issues#9]
We are currently in the very early stages of thinking about how to make the various NMDC product (data portal, EDGE) and documentation websites feel more cohesive and unified. The overarching goal is improved user experience in navigating, using, and understanding the various NMDC products. This issue is to organize the initial planning of those efforts.

**Acceptance Criteria**
1. [ ] Assess current situation (what websites exist, how they are linked, how they are built and managed, etc) and come up with ideas for improvement with relevant stakeholders
2. [ ] Based on initial assessment, create new GitHub issues for implementation tasks. It would be good to distinguish between short term tasks ("low hanging fruit") and longer term plans. 

Is the request achievable? During one sprint? Yes
What is your definition of done for this request? Complete acceptance criteria items

**Comment by pkalita-lbl** [comment]
The first item (assessment of current situation) is underway. Notes and decisions are being tracked in this document: https://docs.google.com/document/d/1eYjY4gJKzPmzfH3LBmOpFIiB2EhBu1vvqz-4bFLJ4JU/edit

**Comment by pvangay** [comment]
Updates from squad meeting 9/22/22 are added to the current [document](https://docs.google.com/document/d/1eYjY4gJKzPmzfH3LBmOpFIiB2EhBu1vvqz-4bFLJ4JU/edit). 
Next steps:
- Patrick will flesh out “WordPress queries nmdc-server API” a bit more
- Shreyas will start thread with Emiley / leadership team to discuss ideas and get road map started
-

**Comment by pkalita-lbl** [comment]
I'm going to close this issue because I think we've reached an acceptable stopping point on this work for now. The document linked above details ideas that are technically feasible along with effort levels and associated risks. I'll be discussing those ideas with Shreyas, Chris, Emiley, and Julia on Oct 24, and we'll try to lay out the next steps there.
