### ISSUE TITLE
`berkeley` referential integrity data qc

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#901]
**Deliverable this task is associated with**

**RACI**

_Tag people in their roles_
- Responsible: @aclum 
- Accountable:
- Consulted:
- Informed:

**Describe the the task**
- [ ] look at output of refscan for berkeley schema

**Criteria for completion**
- number of referential integrity issues should be ~33 which is what we had in mongo prod at the end of re-iding efforts.

**Estimate people time**
- [Hours or days of people time. 1 person, 4 hours]

**Completion Date (Goal)**
- 10/14/24

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- [Tagg issues]

**Comment by aclum** [comment]
cc @eecavanna

**Comment by eecavanna** [comment]
Here is the violation report that I [posted on Slack](https://nmdc-group.slack.com/archives/CFVH4DYGH/p1728560235834079?thread_ts=1728518467.865379&cid=CFVH4DYGH), but converted to CSV format (GitHub wouldn't allow me to attach a TSV file): [violations.schema-v11.0.1_nmdc-dev_with-misplaced.tsv.csv](https://github.com/user-attachments/files/17331712/violations.schema-v11.0.1_nmdc-dev_with-misplaced.tsv.csv)

Note: This is the variant of the report that was generated when the `--locate-misplaces-documents` flag was passed to refscan, which resulted in refscan populating the `name_of_collection_containing_target` column of the report.

Most of the violations involve a reference where the referenced `id` is the word "`False`" or "`FALSE`".

**Comment by aclum** [comment]
we get the 33 expected has_input issues, has_calibration issues are okay, a 'string' is allowed, the was_generated_by reported records are b/c of issues with the range being specified as any_of w/o a common parent for the default range.
