### ISSUE TITLE
ingest Gs0053073

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#908]
This project has plant associated metagenomes + JGI metabolomics.
 

Blocked on 
- [x] [GOLD-2773](https://issues.jgi.doe.gov/browse/GOLD-2773) to fill out env broad scale for the rest of the samples. RESOLVED
- [x] https://github.com/microbiomedata/nmdc-runtime/issues/789

MSV000093248
MSV000093257

acceptance criteria:
80 data_generation_set records with analyte_category=metagenome
9 data_generation_set records with analyte_category=metatranscriptome

**Comment by aclum** [comment]
Check on env terms and bring in via GOLD.

**Comment by aclum** [comment]
blocked on https://github.com/microbiomedata/nmdc-runtime/issues/789

**Comment by cmungall** [comment]
Looking at the JSON @sujaypatil96 has produced:

- I think the `samp_collection_site` values are wrong ("unplanted soil" is not a site, nor is "arabidopsis")
- it would be good to better represent case vs control

**Comment by aclum** [comment]
Created an internal GOLD ticket because some of the projects are typed incorrectly as metagenome when they should be Targeted Gene Survey. Supratim is working on fixing this.

**Comment by aclum** [comment]
Regarding incorrectly typed projects we could write an optional workaround would be to exclude those with a project status of permanent draft but I'd prefer to see if GOLD can resolve this.

I agree with Chris that we should remove field research site from for this study as it doesn't make sense/there is not enough information to determine.

**Comment by aclum** [comment]
@sujaypatil96 once you remove the field research site please mark this as blocked for the next sprint so I can remember to check in with the GOLD status on this next sprint.

**Comment by aclum** [comment]
GOLD categorization issues are resolved.

**Comment by sujaypatil96** [comment]
I made modifications to the GOLD translator (will push up a PR for it soon) so that it ignores the field research sites. Here is the JSON file that the pipeline produces: [Gs0053073.json](https://github.com/user-attachments/files/18103748/Gs0053073.json)


If it looks good, we can submit it to dev Mongo.

**Comment by aclum** [comment]
There were more issues with the GOLD categorization, i reopened that ticket and it was resolved yesterday so ready for work again.

**Comment by sujaypatil96** [comment]
Latest JSON file generated after fixes in GOLD study: [Gs0053073.json](https://github.com/user-attachments/files/18131294/Gs0053073.json)

**Comment by aclum** [comment]
GOLD has a mix of format for geographic location. I've asked them to fix this. Moving this to the next sprint as blocked as GOLD has been pretty quick to make updates for us.

**Comment by aclum** [comment]
@sujaypatil96  GOLD has fixed the locations, this is ready to run.

**Comment by aclum** [comment]
there are projects that have an incomplete status that look like itags. I will file a ticket with GOLD.

**Comment by sujaypatil96** [comment]
Fixed by: https://github.com/microbiomedata/nmdc-runtime/pull/853

**Comment by sujaypatil96** [comment]
Here is the JSON file we submitted to both dev and prod Mongo: [Gs0053073.json](https://github.com/user-attachments/files/18215099/Gs0053073.json)

**Comment by sujaypatil96** [comment]
Once we've looked at how this data looks in the dev and prod data portals after ingest on 12/23, we can close out this issue.

**Comment by aclum** [comment]
This is on prod & looks good. I used changesheets to add dois, Jeff's orcid, and the jgi portal identifier.

**Comment by sujaypatil96** [comment]
Here are the links to this study's data on the dev and prod data portals:
* https://data-dev.microbiomedata.org/details/study/nmdc:sty-11-prtb4s28
* https://data.microbiomedata.org/details/study/nmdc:sty-11-prtb4s28

The study page looks good with dois, orcid and jgi portal identifier. This issue is ready to be closed.
