### ISSUE TITLE
Submission portal - source material identifier on JGI MG tab

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#919]
This field isn't editable but the guidance indicates is.

env: dev

**Comment by mslarae13** [comment]
That's because you complete the source_mat_id field in the "soil" or "environment" tab and it auto populates in the JGI tab.

**Comment by aclum** [comment]
Can the help menu be updated here? The other fields have comments about how this information should not be populated but this one doesn't in the JGI tab.

**Comment by mslarae13** [comment]
If we update the help menu it's gonna update it for the whole interface. I don't think we can add a "This field is locked because you can only edit it on the soil tab" comment to just the JGI tab view.
@pkalita-lbl can you confirm
