### ISSUE TITLE
Make `DataGeneration` and `DataObject` records for fixed NEON surface water data (`nmdc:sty-11-hht5sb92`)

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/issues#933]
**Deliverable this task is associated with**

This is a sub-issue to track the completion of work in https://github.com/microbiomedata/issues/issues/735

**RACI**

_Tag people in their roles_
- Responsible: @sujaypatil96 
- Accountable: @sujaypatil96 
- Consulted: @aclum 
- Informed: @aclum 

**Describe the the task**
- Work in that issue requires regeneration of DataGeneration and DataObject for 3 NEON studies. This sub-issue is for tracking the progress on the first study -- NEON surface water (`nmdc:sty-11-hht5sb92`).

**Criteria for completion**
- A JSON file with a total of 97 DataGeneration records and 194 DataObject records.

**Estimate people time**
- 1 person, 2 days

**Completion Date (Goal)**
- Nov 15

**Target Sprint Start & End Dates**
- Start: Nov 4
- End: Nov 15

**Tag Blocker/Contingent upon issues**
- [Tagg issues]

**Comment by sujaypatil96** [comment]
JSON file with new DataGeneration and DataObject records for NEON surface water study: 
[neon_surface_water_repaired_records.json](https://github.com/user-attachments/files/17748537/neon_surface_water_repaired_records.json)

**Comment by ssarrafan** [comment]
@sujaypatil96 who needs to review this?
@aclum @cmungall

**Comment by aclum** [comment]
This is ready to submit to mongo dev.

**Comment by sujaypatil96** [comment]
Submitted JSON file to dev Mongo.

**Comment by sujaypatil96** [comment]
Data submitted to prod Mongo.

```bash
➜  ~ curl -X 'POST' \
  'https://api.microbiomedata.org/metadata/json:submit' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyOnNwYXRpbCIsImV4cCI6MTczMjM5MzIzOH0.ZNzmgbHJCvNAF1UD5Za69gJEWJzI-1jv4KE7OMohung' \
  -H 'Content-Type: application/json' \
  -d @/Users/sujaypatil/Desktop/nmdc-runtime/neon_surface_water_repaired_records.json 
{"type":"success","detail":{"run_id":"nmdc:sys00p4vmx36"}}%
```
