### ISSUE TITLE
submit test lipidomics records to mongo dev

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#944]
To make sure bar chart, upset plot, study page summaries, and workflow results show up in the data portal and are downloadable please make a test record and submit it to mongo dev which contains:
data_generation_set record which has_input a biosample which already exists
worklow_execution_set record
data_object_set record which includes raw and processed data objects.

**Comment by aclum** [comment]
@kheal do you have time to do this this sprint.

cc @marySalvi @naglepuff

**Comment by kheal** [comment]
I've submitted some records to mongo-dev.  Note that the urls should resolve but they point to pretty random places (other data objects).

Here's the json I submitted for reference so you can more easily find the ids of objects etc. 
[example_lipid_metadata.json](https://github.com/user-attachments/files/17838489/example_lipid_metadata.json)

**Comment by kheal** [comment]
Thanks @bmeluch for the assist on this.
