### ISSUE TITLE
sample mapping for lipidomics for nmdc:sty-11-8ws97026 (PI Blanchard)

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#955]
**Deliverable this task is associated with**

_See Deliverables tab here: _

- [Add the Deliverable #]

**RACI**

_Tag people in their roles_
- Responsible: @corilo 
- Accountable: @SamuelPurvine 
- Consulted: @mslarae13 
- Informed: @kheal 

**Describe the the task**
- [ ] Jeff indicated there was lipidiomics for this project but there wasn't an option to mark this in the submission portal. 
award DOI [10.46936/fics.proj.2016.49483/60006003](https://www.osti.gov/award-doi-service/biblio/10.46936/fics.proj.2016.49483/60006003)

**Criteria for completion**
- Determine if there is lipidomics data for this project and provide mapping for workflows if there is.

**Estimate people time**
- [Hours or days of people time. 1 person, 4 hours]

**Completion Date (Goal)**
- [GOAL!]

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- [Tagg issues]

**Comment by kheal** [comment]
Related to https://github.com/microbiomedata/issues/issues/954 .  This mapping is probably more efficiently done by someone more familiar with the process. 

I should be informed so I know when the data are mapped for processing.

FYI @lamccue

**Comment by SamuelPurvine** [comment]
I've done the initial mapping for these and handed it over to Alicia for an initial look. There are 28 NMDC non-incubated biosamples for this study (https://api.microbiomedata.org/docs#/find/find_biosamples_biosamples_get enter associated_studies:nmdc:sty-11-8ws97026 into the filter box) of which 23 have what appear to be matching DMS biosamples using plot number, horizon, and treatment. There are an additional 4 biosamples in DMS that do not have a match to what is in NMDC, one of which (2B) is currently part of an ongoing discussion (with pictures of actual sample tubes) to see if we can at least figure it where it should live. Carrie Nicora is my contact for this and is out until Dec 2, so it will be a bit before we get this fully resolved.

I've mapped the proteomics, lipidomics, metabolomics and three sets of NOM analyses for all of the DMS biosamples, and the datafile names are in the file I gave over to Alicia so we can easily grab them along with their associated metadata for processing.

I've added this verbiage to the metabolomics issue :)

**Comment by kheal** [comment]
FYI @bmeluch - once Sam has these mapped from DMS dataset to nmdc biosample id, I'm hoping we can pull these into the additional metadata mapping.

**Comment by SamuelPurvine** [comment]
Here is the mapping I have wrought 
[EMSL_49483_Blanchard_DataMapping_2024-11-27.xlsx](https://github.com/user-attachments/files/17940040/EMSL_49483_Blanchard_DataMapping_2024-11-27.xlsx)

**Comment by aclum** [comment]
This is done, @kheal  will use existing tickets for further mapping and data processing

**Comment by kheal** [comment]
Subsequent ticket here: https://github.com/microbiomedata/issues/issues/963
