### ISSUE TITLE
Curate metadata mapping for lipidomics data for nmdc:sty-11-aygzgv51,  nmdc:sty-11-dcqce727, and nmdc:sty-11-8ws97026

### ISSUE THREAD

**Issue by kheal** [microbiomedata/issues#957]
**Deliverable this task is associated with**

Completed metadata .csvs - see here for example (https://code.emsl.pnl.gov/mass-spectrometry/metams/-/blob/lipid_dev/metaMS/nmdc_lipidomics_metadata_generation/example_metadata_file.csv?ref_type=heads).  

Mapping to biosamples is complete, we just need to map to configurations and `MassSpectrometry` metadata.  

Mappings to biosamples and emsl IDs are here for the first two: https://drive.google.com/file/d/17-bmINtMmYdq-9XfnxJf0ia26LH4nAzy/view?usp=drive_link

Mappings for biosamples and DMS dataset names for nmdc:sty-11-8ws97026 are linked in this ticket: https://github.com/microbiomedata/issues/issues/955

**RACI**

_Tag people in their roles_
- Responsible: @bmeluch 
- Accountable: @lamccue 
- Consulted: @kheal 
- Informed: @aclum 

**Describe the the task**
- [x] Complete metadata mapping for lipidomics datasets for nmdc:sty-11-aygzgv51
- [x] Complete metadata mapping for lipidomics datasets for nmdc:sty-11-dcqce727
- [x] Complete metadata mapping for lipidomics datasets for nmdc:sty-11-8ws97026

**Criteria for completion**
- Mapping files should be reviewed and OK'd by @kheal and be functional with the lipidomics metadata generation scripts (here: https://code.emsl.pnl.gov/mass-spectrometry/metams/-/blob/lipid_dev/metaMS/nmdc_lipidomics_metadata_generation/main.py?ref_type=heads).

**Estimate people time**
- 1 person, 8 hours

**Completion Date (Goal)**
- Dec 13

**Target Sprint Start & End Dates**
- Start: Dec 2
- End: Dec 13

**Contingent upon issues**
- #939
- #938

**Comment by bmeluch** [comment]
Done! @kheal is there somewhere I should upload these?

**Comment by kheal** [comment]
@bmeluch  - good question.  I don't think there's a place right now that makes sense.  I have them in a safe place locally (including your script, thank you!).  Wouldn't hurt to drop them in this issue for extra safe keeping.

**Comment by bmeluch** [comment]
[nmdc_sty-11-dcqce727.csv](https://github.com/user-attachments/files/18116328/nmdc_sty-11-dcqce727.csv)
[nmdc_sty-11-aygzgv51.csv](https://github.com/user-attachments/files/18116330/nmdc_sty-11-aygzgv51.csv)
[nmdc_sty-11-8ws97026.csv](https://github.com/user-attachments/files/18116335/nmdc_sty-11-8ws97026.csv)
[lipidomics_metadata_Dec2024_R.txt](https://github.com/user-attachments/files/18116341/lipidomics_metadata_Dec2024_R.txt)
