### ISSUE TITLE
invalid url for calibration data object

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#960]
Calibration records were added in https://github.com/microbiomedata/issues/issues/750
the url for nmdc:dobj-14-1e9qeq49, 
https://admin.nmdcdemo.emsl.pnl.gov/minio/nom/reference_calibration_files/Hawkes_neg.ref, does not resolve

**Comment by brynnz22** [comment]
It looks like the NMDC Minio is not resolving in general. I messaged Cam (I don't know his github handle) to see what's going on.

**Comment by brynnz22** [comment]
I had the admin url. I fixed it for the negative reference calibration file and fixed for the positive reference calibration file. Thanks for catching @aclum
