### ISSUE TITLE
Update FAIR documentation for renewal

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#983]
https://nmdc-documentation.readthedocs.io/en/latest/explanation/fair_data.html

- [ ] Update to no longer refer to the pilot
- [ ] Add FAIRness evaluation? 

https://github.com/microbiomedata/docs/blob/main/content/nmdc/src/explanation/fair_data.md

**Comment by cmungall** [comment]
I am working on a modified FAIR evaluation we can link to:

https://docs.google.com/spreadsheets/d/1ck9YzSQchadygA_JZJmgrEQtE0tD_7FllD1CcPWINWE/edit?gid=127295437#gid=127295437
