### ISSUE TITLE
Study Information: Show JGI and EMSL templates based on Data generated Yes/No, Submitting sample to EMSL UF, and checked boxes

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#99]
When to show template components.

Data already generated?- YES
Data completed by UF?- YES
Multiomics tab should still show JGI and EMSL options 
Dataharmonizer should NOT show EMSL and JGI templates

Data already generated?- Yes 
Data completed by UF? -No
Multiomics tab should NOT show JGI and EMLS options
Data harmonizer should not show EMSL and JGI templates

Data already generated?- No
Are you submitting metadata for samples that will be sent to a DOE user facility?- JGI yes, emsl yes (or any combination of yes/no)
Multiomics tab should show JGI and EMSL options
Data haromizer should show EMSL and JGI templates.

Generale rule.
JGI and EMSL templates ONLY show when "Has data already been generated? = NO" & "JGI and EMSL" are checked for submitting metadata for samples that will be sent to a DOE UF. Which templates can be determined based on the multiomics selections to be made (EMSL, metagenomics, metatranscriptomics) 

![Screen Shot 2023-02-27 at 8 52 08 PM](https://user-images.githubusercontent.com/44581429/221757407-24b8bea4-3e90-40c9-b87a-d3f6aa9c790b.png)
![Screen Shot 2023-02-27 at 8 52 20 PM](https://user-images.githubusercontent.com/44581429/221757410-690fea80-a96e-41db-a2e9-03e3d7f67246.png)
![Screen Shot 2023-02-27 at 8 52 29 PM](https://user-images.githubusercontent.com/44581429/221757411-a499a907-8f4d-4e64-b267-996ff7dc6d25.png)

JGI and EMSL multiomics options should appear if "Has data already been generated? = Yes" and "DOE user facility" is checked. But should NOT have the data harmonizer templates.

![Screen Shot 2023-02-27 at 8 53 27 PM](https://user-images.githubusercontent.com/44581429/221757524-321ed916-8cb3-44b1-af99-cb67ed906d07.png)

![Screen Shot 2023-02-27 at 8 52 20 PM](https://user-images.githubusercontent.com/44581429/221757410-690fea80-a96e-41db-a2e9-03e3d7f67246.png)

![Screen Shot 2023-02-27 at 8 54 01 PM](https://user-images.githubusercontent.com/44581429/221757603-cd6767bc-1d23-4e3c-9a7c-0c475c955865.png)

**Comment by ssarrafan** [comment]
Tested on data-dev and it works as described above.
