### ISSUE TITLE
Website contains 3 broken links

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/issues#994]
I found a link checker that is "recursive" (unlike [lychee](https://github.com/lycheeverse/lychee/issues/78#issuecomment-1674487994), which is not) and used it to check the links on our website. The link checker  is called [linkcheck](https://github.com/filiph/linkcheck) and the command I used to run it is:

```shell
docker run --rm tennox/linkcheck https://microbiomedata.org/
```

Out of the 9,998 links it found across all pages of our website, it reported that only 3 of them were broken. Those are:
- [x] 1. On https://microbiomedata.org/2020/04/29/nature-reviews-microbiology-comment/, the words "two strategic priorities" link to https://microbiomedata.org/roadmap/, which does not exist.
- [x] 2. On that same page, the word "engagement" links to https://microbiomedata.org/engagement/, which does not exist.
- [x] 3. On https://microbiomedata.org/2024/10/13/2024-nmdc-summer-conference-season/, the word "website" links to https://microbiomedata.org/events/https://microbiomedata.org/events/, which does not exist (in this case, I think the author accidentally pasted the URL twice).

CC: @jkelliher-github

**Comment by emileyfadrosh** [comment]
Fixed, thanks SO much @eecavanna !!
